import { LOCALES, ROUTES } from "./types";

export { LOCALES, ROUTES };

export const CONTROLLED_FAILURE_TARGET_LESSON_ID = "intro-m1-l4-ai-can-cannot";
export const CONTROLLED_FAILURE_TARGET_LOCALE = "en" as const;
export const CONTROLLED_FAILURE_TARGET_CELL_ID = `${CONTROLLED_FAILURE_TARGET_LESSON_ID}__${CONTROLLED_FAILURE_TARGET_LOCALE}`;

export const PILOT_INSTRUCTIONAL_LESSON_ID = "intro-m1-l4-ai-can-cannot";
export const PILOT_MASAARAT_LESSON_ID = "builder-m7-l1-tables-columns";
export const PILOT_AUTHORIZED_EXTERNAL_LESSON_ID = "builder-m6-l3-first-prompt-to-lovable";

export const FULL_400_CONFIRM_TOKEN = "RUN_AUTHORIZED_400";

/** After CR-VIS-PILOT-MANIFEST-RECLASSIFICATION-20260725-01: pilot screenshot lessons → INSTRUCTIONAL_COMPOSITION. */
export const EXPECTED_COUNTS = {
  MASAARAT_SCREENSHOT: 6,
  AUTHORIZED_EXTERNAL_SCREENSHOT: 2,
  INSTRUCTIONAL_COMPOSITION: 92,
} as const;

export const EXPECTED_TOTAL_LESSONS = 100;
export const EXPECTED_TOTAL_CELLS = EXPECTED_TOTAL_LESSONS * LOCALES.length;

export const CANVAS_WIDTH = 1280;
export const CANVAS_HEIGHT = 720;

export const CLASSIFICATION_SOURCE_SHA256 =
  "19401FA59DA7A592C9BD81D74C59CF501D6CE182D7B71A9CA10801D166FE093B";
export const ACCEPTED_CLASSIFICATION_BASELINE_SHA = "a9b31c53aee45a9498f89f1301987f684ff1bae9";
export const RECONCILED_ORIGIN_MAIN_SHA = "aca5ad018b7d47238959bc0ee91a195d142cd348";
