export type RouteVisibility = "public" | "private" | "utility";

export type RouteCatalogEntry = {
  source: string;
  pattern: string;
  visibility: RouteVisibility;
  sitemap: boolean;
  robotsPath?: string;
};

export const ROUTE_CATALOG = [
  { source: "index.tsx", pattern: "/", visibility: "public", sitemap: true },
  { source: "contact.tsx", pattern: "/contact", visibility: "public", sitemap: true },
  { source: "curriculum.tsx", pattern: "/curriculum", visibility: "public", sitemap: true },
  { source: "kids.tsx", pattern: "/kids", visibility: "public", sitemap: false },
  { source: "kids.index.tsx", pattern: "/kids", visibility: "public", sitemap: true },
  { source: "kids.privacy.tsx", pattern: "/kids/privacy", visibility: "public", sitemap: false },
  {
    source: "kids.family.tsx",
    pattern: "/kids/family",
    visibility: "private",
    sitemap: false,
    robotsPath: "/kids/family",
  },
  {
    source: "kids.$levelId.tsx",
    pattern: "/kids/level-*",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/kids/level-",
  },
  {
    source: "kids.$levelId.index.tsx",
    pattern: "/kids/level-*",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/kids/level-",
  },
  {
    source: "kids.$levelId.$lessonNumber.tsx",
    pattern: "/kids/level-*/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/kids/level-",
  },
  { source: "pricing.tsx", pattern: "/pricing", visibility: "public", sitemap: true },
  { source: "privacy.tsx", pattern: "/privacy", visibility: "public", sitemap: true },
  { source: "terms.tsx", pattern: "/terms", visibility: "public", sitemap: true },
  {
    source: "[index].tsx",
    pattern: "/index",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/index",
  },
  {
    source: "login.tsx",
    pattern: "/login",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/login",
  },
  {
    source: "signup.tsx",
    pattern: "/signup",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/signup",
  },
  {
    source: "forgot-password.tsx",
    pattern: "/forgot-password",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/forgot-password",
  },
  {
    source: "reset-password.tsx",
    pattern: "/reset-password",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/reset-password",
  },
  {
    source: "onboarding.tsx",
    pattern: "/onboarding",
    visibility: "utility",
    sitemap: false,
    robotsPath: "/onboarding",
  },
  {
    source: "account.tsx",
    pattern: "/account",
    visibility: "private",
    sitemap: false,
    robotsPath: "/account",
  },
  {
    source: "payments.tsx",
    pattern: "/payments",
    visibility: "private",
    sitemap: false,
    robotsPath: "/payments",
  },
  {
    source: "invitations.$invitationId.tsx",
    pattern: "/invitations/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/invitations/",
  },
  {
    source: "admin.commerce.tsx",
    pattern: "/admin/commerce",
    visibility: "private",
    sitemap: false,
    robotsPath: "/admin",
  },
  {
    source: "admin.index.tsx",
    pattern: "/admin/",
    visibility: "private",
    sitemap: false,
    robotsPath: "/admin",
  },
  {
    source: "admin.kids-parents.tsx",
    pattern: "/admin/kids-parents",
    visibility: "private",
    sitemap: false,
    robotsPath: "/admin/kids-parents",
  },
  {
    source: "ai-assistant.tsx",
    pattern: "/ai-assistant",
    visibility: "private",
    sitemap: false,
    robotsPath: "/ai-assistant",
  },
  {
    source: "analytics.tsx",
    pattern: "/analytics",
    visibility: "private",
    sitemap: false,
    robotsPath: "/analytics",
  },
  {
    source: "assistant-runtime.tsx",
    pattern: "/assistant-runtime",
    visibility: "private",
    sitemap: false,
    robotsPath: "/assistant-runtime",
  },
  {
    source: "build-logs.tsx",
    pattern: "/build-logs",
    visibility: "private",
    sitemap: false,
    robotsPath: "/build-logs",
  },
  {
    source: "dashboard.tsx",
    pattern: "/dashboard",
    visibility: "private",
    sitemap: false,
    robotsPath: "/dashboard",
  },
  {
    source: "image-gallery.tsx",
    pattern: "/image-gallery",
    visibility: "private",
    sitemap: false,
    robotsPath: "/image-gallery",
  },
  {
    source: "image-gallery.index.tsx",
    pattern: "/image-gallery/",
    visibility: "private",
    sitemap: false,
    robotsPath: "/image-gallery",
  },
  {
    source: "image-gallery.$path.tsx",
    pattern: "/image-gallery/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/image-gallery",
  },
  {
    source: "learn.$pathId.$lessonId.tsx",
    pattern: "/learn/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/learn/",
  },
  {
    source: "roadmap.index.tsx",
    pattern: "/roadmap/",
    visibility: "private",
    sitemap: false,
    robotsPath: "/roadmap",
  },
  {
    source: "roadmap.$id.tsx",
    pattern: "/roadmap/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/roadmap",
  },
  {
    source: "start.tsx",
    pattern: "/start",
    visibility: "private",
    sitemap: false,
    robotsPath: "/start",
  },
  {
    source: "system-state.tsx",
    pattern: "/system-state",
    visibility: "private",
    sitemap: false,
    robotsPath: "/system-state",
  },
  { source: "ai.tsx", pattern: "/ai", visibility: "public", sitemap: true },
  { source: "about.tsx", pattern: "/about", visibility: "public", sitemap: true },
  { source: "kids.pricing.tsx", pattern: "/kids/pricing", visibility: "public", sitemap: true },
  { source: "technical.tsx", pattern: "/technical", visibility: "public", sitemap: false },
  { source: "technical.index.tsx", pattern: "/technical", visibility: "public", sitemap: true },
  {
    source: "technical.pricing.tsx",
    pattern: "/technical/pricing",
    visibility: "public",
    sitemap: true,
  },
  {
    source: "my-learning.tsx",
    pattern: "/my-learning",
    visibility: "private",
    sitemap: false,
    robotsPath: "/my-learning",
  },
  {
    source: "kids.curriculum.tsx",
    pattern: "/kids/curriculum",
    visibility: "public",
    sitemap: true,
  },
  {
    source: "technical.curriculum.tsx",
    pattern: "/technical/curriculum",
    visibility: "public",
    sitemap: true,
  },
  {
    source: "technical.learn.$lessonId.tsx",
    pattern: "/technical/learn/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/technical/learn/",
  },
  {
    source: "academic.tsx",
    pattern: "/academic",
    visibility: "private",
    sitemap: false,
    robotsPath: "/academic",
  },
  {
    source: "academic.index.tsx",
    pattern: "/academic",
    visibility: "private",
    sitemap: false,
    robotsPath: "/academic",
  },
  {
    source: "academic.pricing.tsx",
    pattern: "/academic/pricing",
    visibility: "private",
    sitemap: false,
    robotsPath: "/academic",
  },
  {
    source: "academic.courses.$courseId.tsx",
    pattern: "/academic/courses/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/academic",
  },
  {
    source: "academic.learn.$lessonId.tsx",
    pattern: "/academic/learn/*",
    visibility: "private",
    sitemap: false,
    robotsPath: "/academic",
  },
] as const satisfies readonly RouteCatalogEntry[];

export const PUBLIC_SITEMAP_PATHS = ROUTE_CATALOG.filter((route) => route.sitemap).map(
  (route) => route.pattern,
);
