import type { SupportedLocale } from "@/lib/locale/types";
import type { PaymentMethod } from "./contracts";

export function paymentInstructions(
  method: Pick<PaymentMethod, "instructions" | "instructions_localized">,
  locale: SupportedLocale,
) {
  return method.instructions_localized?.[locale] ?? method.instructions;
}
const en = {
  audit: "Administrator action history",
  delivered: "Delivered",
  delayed: "Delivery delayed",
  bounced: "Bounced",
  complained: "Complaint",
  title: "Payments, groups and offers",
  methods: "Payment method",
  instapay: "InstaPay",
  wallet: "Wallet",
  bank: "Bank transfer",
  stripe: "Stripe",
  paymob: "Paymob — unavailable",
  admin: "Administrator-approved access",
  unavailable: "Unavailable",
  continue: "Continue",
  back: "Back",
  code: "Offer code (optional)",
  quote: "Review price",
  amount: "Agreed amount",
  original: "Original price",
  reference: "Order reference",
  duration: "Duration",
  month: "Monthly",
  year: "Yearly",
  days: "Days",
  receipt: "Payment receipt",
  upload: "Upload receipt",
  receiptNote:
    "A receipt does not confirm payment. Access starts only after funds are verified and an administrator confirms the order.",
  pending: "Pending review",
  orders: "Orders",
  access: "Package access",
  refresh: "Refresh",
  cancel: "Cancel",
  renew: "Renew with a new payment",
  error: "Could not complete the request. Check the information and try again.",
  disabled: "This feature is awaiting release.",
  groups: "Groups and invitations",
  offers: "Offers",
  settings: "Payment instructions",
  payments: "Confirmed payments",
  allocateExisting: "Allocate already confirmed funds",
  grants: "Complimentary grants",
  search: "Search by email, reference or package",
  all: "All",
  groupName: "Group name",
  create: "Create",
  email: "Email",
  name: "Name",
  locale: "Language",
  package: "Package",
  kind: "Access type",
  complimentary: "Complimentary",
  external: "Externally paid",
  start: "Start rule",
  acceptance: "On verified acceptance",
  date: "Selected date",
  after_expiry: "After existing access expires",
  deadline: "Invitation acceptance deadline",
  instructions: "Transfer instructions",
  destination: "Destination account or wallet",
  qr: "QR image URL (HTTPS)",
  enabled: "Available",
  save: "Save",
  template: "Download XLSX template",
  file: "XLSX / CSV file (first worksheet)",
  paste: "Paste email list or CSV",
  preview: "Preview and validate",
  import: "Commit selected recipients",
  exclude: "Exclude",
  mapping: "Column mapping",
  errors: "Errors and warnings",
  errorReport: "Download validation report",
  send: "Queue selected invitations",
  dispatch: "Send next batch",
  pause: "Pause",
  resume: "Resume",
  mailPreview: "Preview invitation",
  funds: "I verified receipt of the funds",
  confirm: "Confirm payment",
  reject: "Reject",
  moreInfo: "Request more information",
  reason: "Reason / review notes",
  received: "Received amount",
  transaction: "Transaction reference",
  receivedAt: "Received date",
  refund: "Record completed refund",
  revoke: "Revoke this access",
  extend: "Extend complimentary access",
  userId: "Existing user ID",
  validFrom: "Offer valid from",
  validUntil: "Offer expires",
  percent: "Percentage discount",
  fixed: "Fixed amount discount (minor units)",
  value: "Discount value",
  limit: "Total redemption limit",
  perEmail: "Limit per email",
  renewals: "Apply to future manual renewals",
  newCustomer: "New customers only",
  export: "Export records",
  viewReceipt: "View receipt",
  downloadReceipt: "Download receipt",
  closeReceipt: "Close preview",
  receiptLoading: "Loading receipt…",
  receiptCloudNote: "The receipt is stored securely online. Download a copy only if you need one.",
  receiptPreviewFallback:
    "If the PDF preview is unavailable in your browser, use Download receipt.",
  paymentAmountUnits:
    "Enter amounts in the displayed currency: 169 means EGP 169. Decimals are allowed.",
  paymentAllocation: "Amount assigned to this order",
  paymentRecorded:
    "Payment recorded. Fully paid orders are confirmed; access follows each order's start date.",
  partialPaymentRecorded:
    "Partial payment recorded. The order remains pending until its full amount is received and assigned.",
  partialPaymentWarning:
    "This is a partial allocation. It will not activate an order until its full amount is covered.",
  allocation: "Allocation amount (minor units)",
  gross: "Received total (minor units)",
  campaign: "Campaign name",
  inviteTitle: "Your Masaarat invitation",
  accept: "Accept invitation",
  verify: "Sign in with the invited email and verify it to accept.",
  kids: "Kids requires the existing guardian consent and family setup.",
  paidWait: "Paid invitation access waits for confirmed payment.",
  noAutopay: "Manual renewal needs another confirmed payment; no automatic collection.",
  sentNote: "Delivery, acceptance, payment and access are tracked separately.",
  configure: "Configure actual destination details before enabling a transfer method.",
  select: "Select",
  remaining: "Unallocated funds",
  refundAccess: "Revoke the access funded by this order",
  optOut: "Marketing opt-out",
  suppressed: "Suppress email",
  preferences: "Email preferences",
  saved: "Saved",
  scheduled: "Scheduled",
  active: "Active",
  expired: "Expired",
  revoked: "Revoked",
  awaiting_receipt: "Awaiting receipt",
  more_info: "More information needed",
  rejected: "Rejected",
  confirmed: "Payment confirmed",
  cancelled: "Cancelled",
  refunded: "Refund recorded",
  accepted: "Accepted",
  not_sent: "Not sent",
  sent: "Sent",
  sending: "Sending",
  failed: "Failed",
  unknown: "Needs manual reconciliation",
  paused: "Paused",
  ready: "Ready",
  currency: "Currency",
  market: "Market",
  interval: "Billing interval",
  overview: "Revenue and access",
  externalRevenue: "External funds received",
  refundTotal: "Recorded refunds",
  complimentaryCount: "Complimentary grants (not revenue)",
  editRows: "Correct rows before committing",
  currencyNotice: "Enter amounts in minor units: EGP piastres / USD cents.",
  existing: "Existing access: review overlap",
  paymentExpiry: "Order expiry",
  inviteRevoked: "Revoke invitation",
  offerEnabled: "Enable / disable offer",
};
const ar: Record<keyof typeof en, string> = {
  audit: "سجل إجراءات المسؤولين",
  delivered: "تم التسليم",
  delayed: "تأخر التسليم",
  bounced: "تعذر تسليم البريد",
  complained: "شكوى بريد",
  title: "المدفوعات والمجموعات والعروض",
  methods: "وسيلة الدفع",
  instapay: "إنستا باي",
  wallet: "محفظة",
  bank: "تحويل بنكي",
  stripe: "Stripe",
  paymob: "Paymob — غير متاح",
  admin: "صلاحية بموافقة المسؤول",
  unavailable: "غير متاح",
  continue: "متابعة",
  back: "رجوع",
  code: "كود العرض (اختياري)",
  quote: "مراجعة السعر",
  amount: "المبلغ المتفق عليه",
  original: "السعر الأصلي",
  reference: "مرجع الطلب",
  duration: "المدة",
  month: "شهري",
  year: "سنوي",
  days: "أيام",
  receipt: "إيصال التحويل",
  upload: "رفع الإيصال",
  receiptNote:
    "الإيصال لا يؤكد الدفع. تبدأ الصلاحية بعد تحقق المسؤول من وصول الأموال وتأكيد الطلب.",
  pending: "بانتظار المراجعة",
  orders: "الطلبات",
  access: "صلاحيات الباقات",
  refresh: "تحديث",
  cancel: "إلغاء",
  renew: "تجديد بدفعة جديدة",
  error: "تعذر إكمال الطلب. راجع البيانات وحاول مجددًا.",
  disabled: "هذه الميزة بانتظار النشر.",
  groups: "المجموعات والدعوات",
  offers: "العروض",
  settings: "تعليمات التحويل",
  payments: "الدفعات المؤكدة",
  allocateExisting: "تخصيص أموال مؤكدة سابقًا",
  grants: "المنح المجانية",
  search: "بحث بالبريد أو المرجع أو الباقة",
  all: "الكل",
  groupName: "اسم المجموعة",
  create: "إنشاء",
  email: "البريد الإلكتروني",
  name: "الاسم",
  locale: "اللغة",
  package: "الباقة",
  kind: "نوع الصلاحية",
  complimentary: "مجانية",
  external: "مدفوعة خارجيًا",
  start: "بداية الصلاحية",
  acceptance: "عند قبول المستلم المؤكد",
  date: "تاريخ محدد",
  after_expiry: "بعد انتهاء الصلاحية الحالية",
  deadline: "آخر موعد لقبول الدعوة",
  instructions: "تعليمات التحويل",
  destination: "الحساب أو المحفظة المستقبلة",
  qr: "رابط صورة QR عبر HTTPS",
  enabled: "متاحة",
  save: "حفظ",
  template: "تحميل نموذج XLSX",
  file: "ملف XLSX أو CSV (الورقة الأولى)",
  paste: "ألصق قائمة بريد أو CSV",
  preview: "معاينة وتحقق",
  import: "حفظ المستلمين المحددين",
  exclude: "استبعاد",
  mapping: "مطابقة الأعمدة",
  errors: "الأخطاء والتنبيهات",
  errorReport: "تحميل تقرير التحقق",
  send: "تجهيز الدعوات المحددة للإرسال",
  dispatch: "إرسال الدفعة التالية",
  pause: "إيقاف",
  resume: "استئناف",
  mailPreview: "معاينة رسالة الدعوة",
  funds: "تحققت من وصول الأموال فعليًا",
  confirm: "تأكيد الدفع",
  reject: "رفض",
  moreInfo: "طلب معلومات إضافية",
  reason: "السبب أو ملاحظات المراجعة",
  received: "المبلغ المستلم",
  transaction: "مرجع التحويل",
  receivedAt: "تاريخ الاستلام",
  refund: "تسجيل استرداد تم بالفعل",
  revoke: "إلغاء هذه الصلاحية",
  extend: "تمديد المنحة المجانية",
  userId: "معرف المستخدم الموجود",
  validFrom: "العرض متاح من",
  validUntil: "انتهاء العرض",
  percent: "خصم بنسبة مئوية",
  fixed: "خصم بمبلغ ثابت (الوحدات الصغرى)",
  value: "قيمة الخصم",
  limit: "الحد الإجمالي للاستخدام",
  perEmail: "الحد لكل بريد",
  renewals: "يسري على التجديدات اليدوية التالية",
  newCustomer: "للعملاء الجدد فقط",
  export: "تصدير السجلات",
  viewReceipt: "عرض الإيصال",
  downloadReceipt: "تنزيل الإيصال",
  closeReceipt: "إغلاق المعاينة",
  receiptLoading: "جارٍ تحميل الإيصال…",
  receiptCloudNote: "الإيصال محفوظ بأمان سحابيًا. يمكنك تنزيل نسخة عند الحاجة.",
  receiptPreviewFallback: "إذا تعذرت معاينة PDF في متصفحك، استخدم زر تنزيل الإيصال.",
  paymentAmountUnits:
    "أدخل المبلغ بالعملة المعروضة: 169 تعني 169 جنيهًا. يمكنك إدخال الكسور العشرية.",
  paymentAllocation: "المبلغ المخصص لهذا الطلب",
  paymentRecorded:
    "سُجّل الدفع وأُكّدت الطلبات المسددة بالكامل. تبدأ الصلاحية وفق موعد بدء كل طلب.",
  partialPaymentRecorded: "سُجّلت دفعة جزئية. يبقى الطلب معلقًا حتى استلام كامل قيمته وتخصيصها له.",
  partialPaymentWarning: "هذا تخصيص جزئي؛ لن يُفعّل الطلب حتى تكتمل قيمته.",
  allocation: "المبلغ المخصص (الوحدات الصغرى)",
  gross: "إجمالي المستلم (الوحدات الصغرى)",
  campaign: "اسم الحملة",
  inviteTitle: "دعوتك إلى مسارات",
  accept: "قبول الدعوة",
  verify: "سجّل الدخول بالبريد المدعو وأكده لقبول الدعوة.",
  kids: "Kids تتطلب موافقة ولي الأمر وإعداد الأسرة بالطريقة الحالية.",
  paidWait: "صلاحية الدعوة المدفوعة تنتظر تأكيد الدفع.",
  noAutopay: "التجديد اليدوي يحتاج دفعة مؤكدة جديدة؛ لا يوجد تحصيل تلقائي.",
  sentNote: "تسليم البريد والقبول والدفع والصلاحية حالات مستقلة.",
  configure: "أدخل بيانات التحويل الفعلية قبل تفعيل الوسيلة.",
  select: "اختيار",
  remaining: "أموال غير مخصصة",
  refundAccess: "إلغاء الصلاحية الممولة من هذا الطلب",
  optOut: "إيقاف البريد التسويقي",
  suppressed: "منع إرسال البريد",
  preferences: "تفضيلات البريد",
  saved: "تم الحفظ",
  scheduled: "مجدولة",
  active: "نشطة",
  expired: "منتهية",
  revoked: "ملغاة",
  awaiting_receipt: "بانتظار الإيصال",
  more_info: "معلومات إضافية مطلوبة",
  rejected: "مرفوضة",
  confirmed: "الدفع مؤكد",
  cancelled: "الطلب ملغى",
  refunded: "استرداد مسجل",
  accepted: "مقبولة",
  not_sent: "لم ترسل",
  sent: "أرسلت",
  sending: "جارٍ الإرسال",
  failed: "فشل الإرسال",
  unknown: "تحتاج مصالحة يدوية",
  paused: "متوقفة",
  ready: "جاهزة",
  currency: "العملة",
  market: "السوق",
  interval: "دورية الدفع",
  overview: "الإيرادات والصلاحيات",
  externalRevenue: "الأموال الخارجية المستلمة",
  refundTotal: "الاستردادات المسجلة",
  complimentaryCount: "المنح المجانية (ليست إيرادًا)",
  editRows: "صحح الصفوف قبل الحفظ",
  currencyNotice: "أدخل المبالغ بالوحدات الصغرى: قرش مصري أو سنت أمريكي.",
  existing: "صلاحية موجودة: راجع التداخل",
  paymentExpiry: "انتهاء طلب الدفع",
  inviteRevoked: "إلغاء الدعوة",
  offerEnabled: "تفعيل أو تعطيل العرض",
};
export type CommerceCopy = typeof en;
export function commerceCopy(locale: SupportedLocale): CommerceCopy {
  if (locale === "en") return en;
  if (locale === "ar-EG")
    return {
      ...ar,
      continue: "كمّل",
      quote: "راجع السعر",
      paymentAmountUnits:
        "اكتب المبلغ بالعملة اللي ظاهرة: 169 يعني 169 جنيه. تقدر تكتب كسور عشرية.",
      paymentAllocation: "المبلغ المخصص للطلب ده",
      paymentRecorded:
        "الدفع اتسجّل والطلبات المسددة بالكامل اتأكدت. الصلاحية بتبدأ في موعد كل طلب.",
      partialPaymentRecorded:
        "اتسجّلت دفعة جزئية. الطلب هيفضل معلّق لحد ما كامل قيمته توصل وتتخصص له.",
      partialPaymentWarning: "ده مبلغ جزئي؛ الطلب مش هيتفعّل إلا لما قيمته تكمل.",
      receipt: "إيصال التحويل",
      downloadReceipt: "نزّل الإيصال",
      closeReceipt: "اقفل المعاينة",
      receiptLoading: "بنحمّل الإيصال…",
      receiptCloudNote: "الإيصال محفوظ بأمان أونلاين. نزّل نسخة بس لو محتاجها.",
      receiptPreviewFallback: "لو ملف PDF مش ظاهر في متصفحك، اضغط على «نزّل الإيصال».",
      error: "تعذر إكمال الطلب. راجع البيانات وحاول تاني.",
    };
  if (locale === "ar-Gulf")
    return {
      ...ar,
      continue: "تابع",
      downloadReceipt: "نزّل الإيصال",
      closeReceipt: "إغلاق المعاينة",
      receiptLoading: "جاري تحميل الإيصال…",
      receiptCloudNote: "الإيصال محفوظ بأمان أونلاين. تقدر تنزّل نسخة إذا احتجتها.",
      receiptPreviewFallback: "إذا ما ظهر ملف PDF في متصفحك، اضغط «نزّل الإيصال».",
      paymentAmountUnits: "اكتب المبلغ بالعملة المعروضة: 169 يعني 169 جنيه. تقدر تدخل كسور عشرية.",
      paymentAllocation: "المبلغ المخصص لهالطلب",
      paymentRecorded:
        "تسجّل الدفع وتأكدت الطلبات المدفوعة بالكامل. الصلاحية تبدأ حسب موعد كل طلب.",
      partialPaymentRecorded: "تسجّلت دفعة جزئية. الطلب يبقى معلّق لين توصل قيمته كاملة وتتخصص له.",
      partialPaymentWarning: "هذا مبلغ جزئي؛ الطلب ما يتفعّل لين تكتمل قيمته.",
      inviteTitle: "دعوتك لمسارات",
      verify: "سجّل دخولك بالإيميل المدعو وأكده لقبول الدعوة.",
    };
  return ar;
}
export function formatAmount(amount: number, currency: string, locale: SupportedLocale) {
  return new Intl.NumberFormat(locale === "en" ? "en-US" : "ar", {
    style: "currency",
    currency,
  }).format(amount / 100);
}
export function accessState(row: {
  starts_at: string;
  ends_at: string;
  revoked_at: string | null;
}) {
  return row.revoked_at
    ? "revoked"
    : new Date(row.ends_at) <= new Date()
      ? "expired"
      : new Date(row.starts_at) > new Date()
        ? "scheduled"
        : "active";
}

export function deliveryLabel(status: string | undefined, w: CommerceCopy) {
  const labels: Record<string, string> = {
    "email.delivered": w.delivered,
    "email.delivery_delayed": w.delayed,
    "email.bounced": w.bounced,
    "email.failed": w.failed,
    "email.complained": w.complained,
    "email.suppressed": w.suppressed,
    accepted: w.sent,
    suppressed: w.suppressed,
  };
  return labels[status ?? ""] ?? w.not_sent;
}
