import type { AdminData } from "./contracts";
import { exportCsv } from "./imports";
import { accessState } from "./copy";

/** Payments are gross receipts; allocations never become additional revenue. */
export function exportCommerce(data: AdminData): string {
  return exportCsv(
    [
      "record",
      "id",
      "email/user",
      "package",
      "status",
      "amount_minor",
      "currency",
      "source_id",
      "group_id",
      "starts_at",
      "ends_at",
      "details",
    ],
    [
      ...data.orders.map((o) => [
        "order",
        o.id,
        o.recipient_email,
        o.package,
        o.review_status,
        o.final_minor,
        o.currency,
        "",
        o.group_id ?? "",
        "",
        "",
        o.reference,
      ]),
      ...data.payments.map((p) => [
        "payment",
        p.id,
        p.user_id ?? "",
        "",
        "confirmed",
        p.amount_minor,
        p.currency,
        "",
        p.group_id ?? "",
        "",
        "",
        p.transaction_reference,
      ]),
      ...data.allocations.map((a) => [
        "allocation",
        a.order_id,
        "",
        "",
        "allocated",
        a.amount_minor,
        "",
        a.payment_id,
        "",
        "",
        "",
        "Included in gross payment, not additional revenue",
      ]),
      ...data.refunds.map((r) => [
        "refund",
        r.id,
        "",
        "",
        "recorded",
        r.amount_minor,
        data.payments.find((p) => p.id === r.payment_id)?.currency ?? "",
        r.payment_id,
        "",
        "",
        "",
        r.order_id ?? "Unallocated funds",
      ]),
      ...data.grants.map((g) => [
        "complimentary_grant",
        g.id,
        g.user_id,
        g.package,
        "",
        0,
        "",
        g.invitation_id ?? "",
        "",
        "",
        "",
        "",
      ]),
      ...data.entitlements.map((e) => [
        "access",
        e.id,
        e.user_id,
        e.package,
        accessState(e),
        "",
        "",
        e.order_id ?? e.grant_id ?? "",
        "",
        e.starts_at,
        e.ends_at,
        "",
      ]),
      ...data.invitations.map((i) => [
        "invitation",
        i.id,
        i.email,
        i.package,
        i.revoked_at ? "revoked" : i.accepted_at ? "accepted" : "pending",
        "",
        "",
        i.order_id ?? "",
        i.group_id,
        "",
        i.deadline,
        JSON.stringify({ send_status: i.send_status, delivery: i.delivery }),
      ]),
      ...data.offers.map((o) => [
        "offer",
        o.id,
        "",
        o.package,
        o.enabled ? "enabled" : "disabled",
        "",
        "",
        "",
        "",
        "",
        o.valid_until,
        JSON.stringify({ code: o.code, kind: o.kind, renewals: o.renewals }),
      ]),
      ...(data.audit ?? []).map((a) => [
        "audit",
        a.id,
        a.actor ?? "",
        "",
        a.action,
        "",
        "",
        a.target_id ?? "",
        "",
        a.created_at,
        "",
        JSON.stringify(a.details),
      ]),
    ],
  );
}
