import type { IntroLessonContent } from "../intro-lesson-types";

/**
 * Dynamic lesson content registry — one async chunk per lesson file.
 * Keys are stable lesson route slugs (same as curriculum lesson ids).
 *
 * Generated by scripts/generate-lesson-registry.ts — re-run after adding lessons.
 */
export const INTRO_LESSON_CONTENT_KEYS = [
  "analyst-m1-l1-from-automation-to-insight",
  "analyst-m2-l1-feeling-to-question",
  "analyst-m2-l2-right-question-rule",
  "analyst-m3-l1-three-sources",
  "analyst-m3-l2-ai-summarization",
  "analyst-m4-automated-dashboard",
  "analyst-m4-l1-pattern-vs-outlier",
  "analyst-m4-l2-decision-rule",
  "analyst-m5-ab-testing",
  "analyst-m5-l1-four-numbers-dashboard",
  "analyst-m5-l2-weekly-review-ritual",
  "analyst-m6-l1-question-mistakes",
  "analyst-m6-l2-interpretation-mistakes",
  "analyst-m7-l1-from-decisions-to-business",
  "automator-m1-l1-where-you-are",
  "automator-m2-l1-systems-view",
  "automator-m2-l2-spot-patterns",
  "automator-m2-l3-decide-what-to-automate",
  "automator-m3-l1-tools-landscape",
  "automator-m3-l2-triggers-actions",
  "automator-m3-l3-filters-routers",
  "automator-m3-testing-automation",
  "automator-m4-l1-connect-database",
  "automator-m4-l2-webhooks-api",
  "automator-m4-l3-error-handling",
  "automator-m5-l1-llm-in-flow",
  "automator-m5-l2-rag-in-n8n",
  "automator-m5-l3-agents",
  "automator-m6-l1-lead-capture",
  "automator-m6-l2-whatsapp-flow",
  "automator-m6-l3-follow-up",
  "automator-m7-l1-closing-loop",
  "builder-m1-l1-what-is-llm",
  "builder-m1-l2-tokens-training",
  "builder-m10-l1-deploy-domain",
  "builder-m10-l2-first-users",
  "builder-m2-l1-prompt-layer",
  "builder-m2-l2-instructions-examples",
  "builder-m2-l3-style-control",
  "builder-m3-l1-context-layer",
  "builder-m3-l2-memory-limits",
  "builder-m4-l1-parameters",
  "builder-m5-l1-transition",
  "builder-m5-l2-frontend",
  "builder-m5-l3-backend-api",
  "builder-m5-l4-database-intro",
  "builder-m5-l5-mini-win",
  "builder-m6-l1-idea-to-page",
  "builder-m6-l2-wireframe",
  "builder-m6-l3-first-prompt-to-lovable",
  "builder-m6-l4-components-routes",
  "builder-m6-l5-iteration",
  "builder-m6-l6-debugging",
  "builder-m7-l1-tables-columns",
  "builder-m7-l2-relations",
  "builder-m7-l3-queries",
  "builder-m8-l1-sessions-jwt",
  "builder-m8-l2-rls",
  "builder-m9-l1-rag",
  "builder-m9-l2-embeddings",
  "builder-m9-l3-agents",
  "business-m1-l1-from-decisions-to-leadership",
  "business-m1-l2-reactive-vs-proactive",
  "business-m1-l3-ai-thinking-partner",
  "business-m2-l1-customer-lifecycle",
  "business-m2-l2-build-your-offer",
  "business-m2-l2-retention-flow",
  "business-m2-l3-readiness-signals",
  "business-m2-l4-pricing-cash-flow",
  "business-m3-l1-delegate-or-automate",
  "business-m3-l2-strategic-operational-admin",
  "business-m3-l3-system-then-people",
  "business-m3-l4-hiring-onboarding",
  "business-m4-l1-premature-scaling",
  "business-m4-l2-reactive-relapse",
  "business-m4-l3-weekly-rhythm",
  "business-m4-l4-full-ecosystem",
  "business-m4-l5-business-os-dashboard",
  "creator-m1-l1-why-content",
  "creator-m1-l2-attention-economy",
  "creator-m2-l1-know-audience",
  "creator-m2-l2-content-pillars",
  "creator-m3-l1-hook",
  "creator-m3-l2-script-structure",
  "creator-m3-l3-cta",
  "creator-m4-l1-reality-check",
  "creator-m4-l2-mobile-shooting",
  "creator-m4-l3-ai-writing",
  "creator-m4-repurposing",
  "creator-m5-l1-editing",
  "creator-m5-l2-thumbnails-captions",
  "creator-m6-l1-platforms",
  "creator-m6-l2-scheduling",
  "creator-m6-l3-analytics",
  "creator-m6-l4-leads",
  "creator-m7-l1-brand-basics",
  "creator-m7-l2-grid-consistency",
  "intro-m1-l1-what-is-ai",
  "intro-m1-l2-first-prompt",
  "intro-m1-l3-setup-your-ai",
  "intro-m1-l4-ai-can-cannot",
  "intro-m1-l5-ai-vs-software",
  "intro-m1-l6-learn-without-fear",
  "intro-m1-l7-choose-your-path",
] as const;

export type IntroLessonContentKey = (typeof INTRO_LESSON_CONTENT_KEYS)[number];

type LessonLoader = () => Promise<IntroLessonContent>;

const LESSON_LOADERS: Record<IntroLessonContentKey, LessonLoader> = {
  "analyst-m1-l1-from-automation-to-insight": () => import("./analyst-m1-l1-from-automation-to-insight").then((m) => m.ANALYST_M1_L1_FROM_AUTOMATION_TO_INSIGHT_BLOCKS),
  "analyst-m2-l1-feeling-to-question": () => import("./analyst-m2-l1-feeling-to-question").then((m) => m.ANALYST_M2_L1_FEELING_TO_QUESTION_BLOCKS),
  "analyst-m2-l2-right-question-rule": () => import("./analyst-m2-l2-right-question-rule").then((m) => m.ANALYST_M2_L2_RIGHT_QUESTION_RULE_BLOCKS),
  "analyst-m3-l1-three-sources": () => import("./analyst-m3-l1-three-sources").then((m) => m.ANALYST_M3_L1_THREE_SOURCES_BLOCKS),
  "analyst-m3-l2-ai-summarization": () => import("./analyst-m3-l2-ai-summarization").then((m) => m.ANALYST_M3_L2_AI_SUMMARIZATION_BLOCKS),
  "analyst-m4-automated-dashboard": () => import("./analyst-m4-automated-dashboard").then((m) => m.ANALYST_M4_AUTOMATED_DASHBOARD_BLOCKS),
  "analyst-m4-l1-pattern-vs-outlier": () => import("./analyst-m4-l1-pattern-vs-outlier").then((m) => m.ANALYST_M4_L1_PATTERN_VS_OUTLIER_BLOCKS),
  "analyst-m4-l2-decision-rule": () => import("./analyst-m4-l2-decision-rule").then((m) => m.ANALYST_M4_L2_DECISION_RULE_BLOCKS),
  "analyst-m5-ab-testing": () => import("./analyst-m5-ab-testing").then((m) => m.ANALYST_M5_AB_TESTING_BLOCKS),
  "analyst-m5-l1-four-numbers-dashboard": () => import("./analyst-m5-l1-four-numbers-dashboard").then((m) => m.ANALYST_M5_L1_FOUR_NUMBERS_DASHBOARD_BLOCKS),
  "analyst-m5-l2-weekly-review-ritual": () => import("./analyst-m5-l2-weekly-review-ritual").then((m) => m.ANALYST_M5_L2_WEEKLY_REVIEW_RITUAL_BLOCKS),
  "analyst-m6-l1-question-mistakes": () => import("./analyst-m6-l1-question-mistakes").then((m) => m.ANALYST_M6_L1_QUESTION_MISTAKES_BLOCKS),
  "analyst-m6-l2-interpretation-mistakes": () => import("./analyst-m6-l2-interpretation-mistakes").then((m) => m.ANALYST_M6_L2_INTERPRETATION_MISTAKES_BLOCKS),
  "analyst-m7-l1-from-decisions-to-business": () => import("./analyst-m7-l1-from-decisions-to-business").then((m) => m.ANALYST_M7_L1_FROM_DECISIONS_TO_BUSINESS_BLOCKS),
  "automator-m1-l1-where-you-are": () => import("./automator-m1-l1-where-you-are").then((m) => m.AUTOMATOR_M1_L1_WHERE_YOU_ARE_BLOCKS),
  "automator-m2-l1-systems-view": () => import("./automator-m2-l1-systems-view").then((m) => m.AUTOMATOR_M2_L1_SYSTEMS_VIEW_BLOCKS),
  "automator-m2-l2-spot-patterns": () => import("./automator-m2-l2-spot-patterns").then((m) => m.AUTOMATOR_M2_L2_SPOT_PATTERNS_BLOCKS),
  "automator-m2-l3-decide-what-to-automate": () => import("./automator-m2-l3-decide-what-to-automate").then((m) => m.AUTOMATOR_M2_L3_DECIDE_WHAT_TO_AUTOMATE_BLOCKS),
  "automator-m3-l1-tools-landscape": () => import("./automator-m3-l1-tools-landscape").then((m) => m.AUTOMATOR_M3_L1_TOOLS_LANDSCAPE_BLOCKS),
  "automator-m3-l2-triggers-actions": () => import("./automator-m3-l2-triggers-actions").then((m) => m.AUTOMATOR_M3_L2_TRIGGERS_ACTIONS_BLOCKS),
  "automator-m3-l3-filters-routers": () => import("./automator-m3-l3-filters-routers").then((m) => m.AUTOMATOR_M3_L3_FILTERS_ROUTERS_BLOCKS),
  "automator-m3-testing-automation": () => import("./automator-m3-testing-automation").then((m) => m.AUTOMATOR_M3_TESTING_AUTOMATION_BLOCKS),
  "automator-m4-l1-connect-database": () => import("./automator-m4-l1-connect-database").then((m) => m.AUTOMATOR_M4_L1_CONNECT_DATABASE_BLOCKS),
  "automator-m4-l2-webhooks-api": () => import("./automator-m4-l2-webhooks-api").then((m) => m.AUTOMATOR_M4_L2_WEBHOOKS_API_BLOCKS),
  "automator-m4-l3-error-handling": () => import("./automator-m4-l3-error-handling").then((m) => m.AUTOMATOR_M4_L3_ERROR_HANDLING_BLOCKS),
  "automator-m5-l1-llm-in-flow": () => import("./automator-m5-l1-llm-in-flow").then((m) => m.AUTOMATOR_M5_L1_LLM_IN_FLOW_BLOCKS),
  "automator-m5-l2-rag-in-n8n": () => import("./automator-m5-l2-rag-in-n8n").then((m) => m.AUTOMATOR_M5_L2_RAG_IN_N8N_BLOCKS),
  "automator-m5-l3-agents": () => import("./automator-m5-l3-agents").then((m) => m.AUTOMATOR_M5_L3_AGENTS_BLOCKS),
  "automator-m6-l1-lead-capture": () => import("./automator-m6-l1-lead-capture").then((m) => m.AUTOMATOR_M6_L1_LEAD_CAPTURE_BLOCKS),
  "automator-m6-l2-whatsapp-flow": () => import("./automator-m6-l2-whatsapp-flow").then((m) => m.AUTOMATOR_M6_L2_WHATSAPP_FLOW_BLOCKS),
  "automator-m6-l3-follow-up": () => import("./automator-m6-l3-follow-up").then((m) => m.AUTOMATOR_M6_L3_FOLLOW_UP_BLOCKS),
  "automator-m7-l1-closing-loop": () => import("./automator-m7-l1-closing-loop").then((m) => m.AUTOMATOR_M7_L1_CLOSING_LOOP_BLOCKS),
  "builder-m1-l1-what-is-llm": () => import("./builder-m1-l1-what-is-llm").then((m) => m.BUILDER_M1_WHAT_IS_LLM_BLOCKS),
  "builder-m1-l2-tokens-training": () => import("./builder-m1-l2-tokens-training").then((m) => m.BUILDER_M1_TOKENS_TRAINING_BLOCKS),
  "builder-m10-l1-deploy-domain": () => import("./builder-m10-l1-deploy-domain").then((m) => m.BUILDER_M10_DEPLOY_DOMAIN_BLOCKS),
  "builder-m10-l2-first-users": () => import("./builder-m10-l2-first-users").then((m) => m.BUILDER_M10_FIRST_USERS_BLOCKS),
  "builder-m2-l1-prompt-layer": () => import("./builder-m2-l1-prompt-layer").then((m) => m.BUILDER_M2_PROMPT_LAYER_BLOCKS),
  "builder-m2-l2-instructions-examples": () => import("./builder-m2-l2-instructions-examples").then((m) => m.BUILDER_M2_INSTRUCTIONS_EXAMPLES_BLOCKS),
  "builder-m2-l3-style-control": () => import("./builder-m2-l3-style-control").then((m) => m.BUILDER_M2_STYLE_CONTROL_BLOCKS),
  "builder-m3-l1-context-layer": () => import("./builder-m3-l1-context-layer").then((m) => m.BUILDER_M3_CONTEXT_LAYER_BLOCKS),
  "builder-m3-l2-memory-limits": () => import("./builder-m3-l2-memory-limits").then((m) => m.BUILDER_M3_MEMORY_LIMITS_BLOCKS),
  "builder-m4-l1-parameters": () => import("./builder-m4-l1-parameters").then((m) => m.BUILDER_M4_TEMPERATURE_BLOCKS),
  "builder-m5-l1-transition": () => import("./builder-m5-l1-transition").then((m) => m.BUILDER_M5_TRANSITION_BLOCKS),
  "builder-m5-l2-frontend": () => import("./builder-m5-l2-frontend").then((m) => m.BUILDER_M5_FRONTEND_BLOCKS),
  "builder-m5-l3-backend-api": () => import("./builder-m5-l3-backend-api").then((m) => m.BUILDER_M5_BACKEND_API_BLOCKS),
  "builder-m5-l4-database-intro": () => import("./builder-m5-l4-database-intro").then((m) => m.BUILDER_M5_DATABASE_INTRO_BLOCKS),
  "builder-m5-l5-mini-win": () => import("./builder-m5-l5-mini-win").then((m) => m.BUILDER_M5_MINI_WIN_BLOCKS),
  "builder-m6-l1-idea-to-page": () => import("./builder-m6-l1-idea-to-page").then((m) => m.BUILDER_M6_IDEA_TO_PAGE_BLOCKS),
  "builder-m6-l2-wireframe": () => import("./builder-m6-l2-wireframe").then((m) => m.BUILDER_M6_WIREFRAME_BLOCKS),
  "builder-m6-l3-first-prompt-to-lovable": () => import("./builder-m6-l3-first-prompt-to-lovable").then((m) => m.BUILDER_M6_FIRST_PROMPT_TO_LOVABLE_BLOCKS),
  "builder-m6-l4-components-routes": () => import("./builder-m6-l4-components-routes").then((m) => m.BUILDER_M6_COMPONENTS_ROUTES_BLOCKS),
  "builder-m6-l5-iteration": () => import("./builder-m6-l5-iteration").then((m) => m.BUILDER_M6_ITERATION_BLOCKS),
  "builder-m6-l6-debugging": () => import("./builder-m6-l6-debugging").then((m) => m.BUILDER_M6_DEBUGGING_BLOCKS),
  "builder-m7-l1-tables-columns": () => import("./builder-m7-l1-tables-columns").then((m) => m.BUILDER_M8_TABLES_COLUMNS_BLOCKS),
  "builder-m7-l2-relations": () => import("./builder-m7-l2-relations").then((m) => m.BUILDER_M8_RELATIONS_BLOCKS),
  "builder-m7-l3-queries": () => import("./builder-m7-l3-queries").then((m) => m.BUILDER_M8_QUERIES_BLOCKS),
  "builder-m8-l1-sessions-jwt": () => import("./builder-m8-l1-sessions-jwt").then((m) => m.BUILDER_M7_SESSIONS_JWT_BLOCKS),
  "builder-m8-l2-rls": () => import("./builder-m8-l2-rls").then((m) => m.BUILDER_M7_RLS_BLOCKS),
  "builder-m9-l1-rag": () => import("./builder-m9-l1-rag").then((m) => m.BUILDER_M9_RAG_BLOCKS),
  "builder-m9-l2-embeddings": () => import("./builder-m9-l2-embeddings").then((m) => m.BUILDER_M9_EMBEDDINGS_BLOCKS),
  "builder-m9-l3-agents": () => import("./builder-m9-l3-agents").then((m) => m.BUILDER_M9_AGENTS_BLOCKS),
  "business-m1-l1-from-decisions-to-leadership": () => import("./business-m1-l1-from-decisions-to-leadership").then((m) => m.BUSINESS_M1_L1_FROM_DECISIONS_TO_LEADERSHIP_BLOCKS),
  "business-m1-l2-reactive-vs-proactive": () => import("./business-m1-l2-reactive-vs-proactive").then((m) => m.BUSINESS_M2_L1_REACTIVE_VS_PROACTIVE_BLOCKS),
  "business-m1-l3-ai-thinking-partner": () => import("./business-m1-l3-ai-thinking-partner").then((m) => m.BUSINESS_M1_L3_AI_THINKING_PARTNER_BLOCKS),
  "business-m2-l1-customer-lifecycle": () => import("./business-m2-l1-customer-lifecycle").then((m) => m.BUSINESS_M3_L1_CUSTOMER_LIFECYCLE_BLOCKS),
  "business-m2-l2-build-your-offer": () => import("./business-m2-l2-build-your-offer").then((m) => m.BUSINESS_M2_BUILD_YOUR_OFFER_BLOCKS),
  "business-m2-l2-retention-flow": () => import("./business-m2-l2-retention-flow").then((m) => m.BUSINESS_M3_L2_RETENTION_FLOW_BLOCKS),
  "business-m2-l3-readiness-signals": () => import("./business-m2-l3-readiness-signals").then((m) => m.BUSINESS_M5_L1_READINESS_SIGNALS_BLOCKS),
  "business-m2-l4-pricing-cash-flow": () => import("./business-m2-l4-pricing-cash-flow").then((m) => m.BUSINESS_M2_L4_PRICING_CASH_FLOW_BLOCKS),
  "business-m3-l1-delegate-or-automate": () => import("./business-m3-l1-delegate-or-automate").then((m) => m.BUSINESS_M4_L2_DELEGATE_OR_AUTOMATE_BLOCKS),
  "business-m3-l2-strategic-operational-admin": () => import("./business-m3-l2-strategic-operational-admin").then((m) => m.BUSINESS_M4_L1_STRATEGIC_OPERATIONAL_ADMIN_BLOCKS),
  "business-m3-l3-system-then-people": () => import("./business-m3-l3-system-then-people").then((m) => m.BUSINESS_M5_L2_SYSTEM_THEN_PEOPLE_BLOCKS),
  "business-m3-l4-hiring-onboarding": () => import("./business-m3-l4-hiring-onboarding").then((m) => m.BUSINESS_M3_L4_HIRING_ONBOARDING_BLOCKS),
  "business-m4-l1-premature-scaling": () => import("./business-m4-l1-premature-scaling").then((m) => m.BUSINESS_M6_L2_PREMATURE_SCALING_BLOCKS),
  "business-m4-l2-reactive-relapse": () => import("./business-m4-l2-reactive-relapse").then((m) => m.BUSINESS_M4_L2_REACTIVE_RELAPSE_BLOCKS),
  "business-m4-l3-weekly-rhythm": () => import("./business-m4-l3-weekly-rhythm").then((m) => m.BUSINESS_M2_L2_WEEKLY_RHYTHM_BLOCKS),
  "business-m4-l4-full-ecosystem": () => import("./business-m4-l4-full-ecosystem").then((m) => m.BUSINESS_M7_L1_FULL_ECOSYSTEM_BLOCKS),
  "business-m4-l5-business-os-dashboard": () => import("./business-m4-l5-business-os-dashboard").then((m) => m.BUSINESS_M4_L5_BUSINESS_OS_DASHBOARD_BLOCKS),
  "creator-m1-l1-why-content": () => import("./creator-m1-l1-why-content").then((m) => m.CREATOR_M1_WHY_CONTENT_BLOCKS),
  "creator-m1-l2-attention-economy": () => import("./creator-m1-l2-attention-economy").then((m) => m.CREATOR_M1_ATTENTION_ECONOMY_BLOCKS),
  "creator-m2-l1-know-audience": () => import("./creator-m2-l1-know-audience").then((m) => m.CREATOR_M3_KNOW_AUDIENCE_BLOCKS),
  "creator-m2-l2-content-pillars": () => import("./creator-m2-l2-content-pillars").then((m) => m.CREATOR_M3_CONTENT_PILLARS_BLOCKS),
  "creator-m3-l1-hook": () => import("./creator-m3-l1-hook").then((m) => m.CREATOR_M2_HOOK_BLOCKS),
  "creator-m3-l2-script-structure": () => import("./creator-m3-l2-script-structure").then((m) => m.CREATOR_M2_SCRIPT_STRUCTURE_BLOCKS),
  "creator-m3-l3-cta": () => import("./creator-m3-l3-cta").then((m) => m.CREATOR_M2_CTA_BLOCKS),
  "creator-m4-l1-reality-check": () => import("./creator-m4-l1-reality-check").then((m) => m.CREATOR_M4_REALITY_CHECK_BLOCKS),
  "creator-m4-l2-mobile-shooting": () => import("./creator-m4-l2-mobile-shooting").then((m) => m.CREATOR_M4_MOBILE_SHOOTING_BLOCKS),
  "creator-m4-l3-ai-writing": () => import("./creator-m4-l3-ai-writing").then((m) => m.CREATOR_M4_AI_WRITING_BLOCKS),
  "creator-m4-repurposing": () => import("./creator-m4-repurposing").then((m) => m.CREATOR_M4_REPURPOSING_BLOCKS),
  "creator-m5-l1-editing": () => import("./creator-m5-l1-editing").then((m) => m.CREATOR_M4_EDITING_BLOCKS),
  "creator-m5-l2-thumbnails-captions": () => import("./creator-m5-l2-thumbnails-captions").then((m) => m.CREATOR_M4_THUMBNAILS_CAPTIONS_BLOCKS),
  "creator-m6-l1-platforms": () => import("./creator-m6-l1-platforms").then((m) => m.CREATOR_M5_PLATFORMS_BLOCKS),
  "creator-m6-l2-scheduling": () => import("./creator-m6-l2-scheduling").then((m) => m.CREATOR_M5_SCHEDULING_BLOCKS),
  "creator-m6-l3-analytics": () => import("./creator-m6-l3-analytics").then((m) => m.CREATOR_M5_ANALYTICS_BLOCKS),
  "creator-m6-l4-leads": () => import("./creator-m6-l4-leads").then((m) => m.CREATOR_M5_LEADS_BLOCKS),
  "creator-m7-l1-brand-basics": () => import("./creator-m7-l1-brand-basics").then((m) => m.CREATOR_M6_BRAND_BASICS_BLOCKS),
  "creator-m7-l2-grid-consistency": () => import("./creator-m7-l2-grid-consistency").then((m) => m.CREATOR_M6_GRID_CONSISTENCY_BLOCKS),
  "intro-m1-l1-what-is-ai": () => import("./intro-m1-l1-what-is-ai").then((m) => m.WHAT_IS_AI_CONTENT),
  "intro-m1-l2-first-prompt": () => import("./intro-m1-l2-first-prompt").then((m) => m.INTRO_FIRST_PROMPT_CONTENT),
  "intro-m1-l3-setup-your-ai": () => import("./intro-m1-l3-setup-your-ai").then((m) => m.INTRO_SETUP_YOUR_AI_CONTENT),
  "intro-m1-l4-ai-can-cannot": () => import("./intro-m1-l4-ai-can-cannot").then((m) => m.AI_CAN_CANNOT_CONTENT),
  "intro-m1-l5-ai-vs-software": () => import("./intro-m1-l5-ai-vs-software").then((m) => m.AI_VS_SOFTWARE_CONTENT),
  "intro-m1-l6-learn-without-fear": () => import("./intro-m1-l6-learn-without-fear").then((m) => m.LEARN_WITHOUT_FEAR_CONTENT),
  "intro-m1-l7-choose-your-path": () => import("./intro-m1-l7-choose-your-path").then((m) => m.INTRO_CHOOSE_YOUR_PATH_CONTENT),
};

const keySet = new Set<string>(INTRO_LESSON_CONTENT_KEYS);

export function hasIntroLessonContent(
  lessonId: string,
): lessonId is IntroLessonContentKey {
  return keySet.has(lessonId);
}

export async function loadIntroLessonContent(
  lessonId: string,
): Promise<IntroLessonContent | null> {
  if (!hasIntroLessonContent(lessonId)) return null;
  return LESSON_LOADERS[lessonId]();
}

const contentCache = new Map<string, IntroLessonContent>();

export async function loadIntroLessonContentCached(
  lessonId: string,
): Promise<IntroLessonContent | null> {
  if (!hasIntroLessonContent(lessonId)) return null;
  const hit = contentCache.get(lessonId);
  if (hit) return hit;
  const loaded = await LESSON_LOADERS[lessonId]();
  contentCache.set(lessonId, loaded);
  return loaded;
}

export async function loadAllIntroLessonContent(): Promise<
  Record<IntroLessonContentKey, IntroLessonContent>
> {
  const pairs = await Promise.all(
    INTRO_LESSON_CONTENT_KEYS.map(async (id) => {
      const content = await loadIntroLessonContentCached(id);
      return [id, content!] as const;
    }),
  );
  return Object.fromEntries(pairs) as Record<
    IntroLessonContentKey,
    IntroLessonContent
  >;
}
