"""Deterministic media preparation. No network, TTS, uploads or release writes.

The existing four pilot videos are never regenerated by this course pipeline.
Narration contains authored teaching content, never formative answer keys.
"""
import argparse
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOCALES = ("ar-EG", "ar-MSA", "ar-Gulf", "en")
PILOT = "AC-BUS-M01-L01"


def canonical(value):
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))


def digest(value):
    return hashlib.sha256(canonical(value).encode()).hexdigest()


def plain(text):
    # Formatting only: preserve quantities, words and mathematical operators.
    text = re.sub(r"\*\*(.*?)\*\*", r"\1", text, flags=re.S)
    text = re.sub(r"(?m)^\s*[*•]\s+", "", text)
    return re.sub(r"\s+", " ", text).strip()


def pieces(text, maximum=420):
    """Keep sentence boundaries where possible; never discard words or numbers."""
    groups, current = [], []
    for sentence in re.split(r"(?<=[.!?؟؛;])\s+", plain(text)):
        if len(sentence) <= maximum:
            if current and len(" ".join(current + [sentence])) > maximum:
                groups.append(" ".join(current))
                current = []
            current.append(sentence)
            continue
        if current:
            groups.append(" ".join(current))
            current = []
        for word in sentence.split():
            if current and len(" ".join(current + [word])) > maximum:
                groups.append(" ".join(current))
                current = []
            current.append(word)
    if current:
        groups.append(" ".join(current))
    return groups


def package(lesson_id, locale):
    if locale not in LOCALES or lesson_id == PILOT:
        raise ValueError("Only exact additional lesson/locale identities are allowed")
    data = json.loads((ROOT / f"experiments/academic/course/expanded/{locale}.json").read_text())
    matches = [item for item in data if item["id"] == lesson_id]
    if len(matches) != 1 or matches[0]["locale"] != locale:
        raise ValueError("Missing, duplicate or wrong-locale source")
    return matches[0]


def make_plan(data):
    en = data["locale"] == "en"
    blocks = [("intro", data["title"], data["intro"], "opening")]
    for section in data["sections"]:
        blocks.append((section["id"], section["title"], section["text"], "concept"))
    case = data["example"]
    blocks.append(("case", case["title"], case["text"], "case"))
    for index, step in enumerate(case.get("steps", []), 1):
        blocks.append((f"case-step-{index}", f"{'Worked step' if en else 'خطوة الحل'} {index}", step, "step"))
    blocks.append(("practice", "Your application" if en else "التطبيق العملي", data["assignment"]["prompt"], "practice"))
    blocks.append(("summary", "Lesson summary" if en else "خلاصة الدرس", " ".join(data["summary"]), "summary"))
    scenes = []
    for block_id, title, text, kind in blocks:
        for index, part in enumerate(pieces(text), 1):
            scenes.append({"id": f"{block_id}-{index}", "blockId": block_id,
                           "title": plain(title), "kind": kind, "spoken": part,
                           "display": part})
    # Reinterpret semantic information as animated field cards. No reading
    # bitmap/SVG/HTML or table component enters the video renderer.
    visual_scenes = []
    for visual in data['readingVisuals']:
        for index, row in enumerate(visual['rows']):
            cells = [{"label": plain(label), "value": plain(value)}
                     for label, value in zip(visual['columns'], row)]
            spoken = '. '.join(f"{cell['label']}: {cell['value']}" for cell in cells)
            visual_scenes.append({"id": f"graphic-{visual['id']}-{index}",
                "blockId": f"graphic-{visual['id']}", "title": plain(visual['title']),
                "kind": visual['kind'], "spoken": spoken, "display": plain(visual['caption']),
                "cells": cells, "rowIndex": index, "rowCount": len(visual['rows'])})
    case_index = next(i for i, scene in enumerate(scenes) if scene['blockId'] == 'case')
    scenes[case_index:case_index] = visual_scenes
    return {"schemaVersion": 1, "lessonId": data["id"], "locale": data["locale"],
            "title": data["title"], "sourceSha256": digest(data), "scenes": scenes,
            "chapters": [{"id": s['id'], "title": plain(s['title'])} for s in data['sections']],
            "visualDirection": data["videoVisualPlan"],
            "visualAcceptance": "pending-render-review",
            "audioAcceptance": "pilot-approved-new-output-review-pending",
            "contentAcceptance": "pending-independent-review",
            "readingAssetsUsed": [], "quizKeysIncluded": False}


def prepare(output):
    curriculum = json.loads((ROOT / "docs/academic/curriculum-proposal.json").read_text())
    order = [lesson["id"] for module in curriculum["modules"] for lesson in module["lessons"] if lesson["id"] != PILOT]
    output.mkdir(parents=True, exist_ok=True)
    entries = []
    for locale in LOCALES:
        for lesson_id in order:
            plan = make_plan(package(lesson_id, locale))
            relative = f"{lesson_id}/{locale}.json"
            target = output / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n")
            entries.append({"lessonId": lesson_id, "locale": locale, "planPath": relative,
                            "sourceSha256": plan["sourceSha256"], "planSha256": digest(plan),
                            "scenes": len(plan["scenes"]),
                            "narrationWords": sum(len(s["spoken"].split()) for s in plan["scenes"])})
    receipt = {"schemaVersion": 1, "courseId": "AC-BUS", "existingPilotPreserved": True,
               "plannedVideos": len(entries), "generatedVideos": 0, "uploadedVideos": 0,
               "mediaProductionStarted": False, "audioAcceptance": "pilot-approved-new-output-review-pending",
               "entries": entries}
    (output / "manifest.json").write_text(json.dumps(receipt, ensure_ascii=False, indent=2) + "\n")
    return receipt


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=ROOT / "tmp/academic-course-media/plans")
    args = parser.parse_args()
    result = prepare(args.output)
    print(json.dumps({k: v for k, v in result.items() if k != "entries"}, indent=2))
