import type { SupportedLocale } from "@/lib/locale/types";

const copy = {
  "ar-EG": {
    title: "رحلة التعليم الفني",
    intro:
      "من فهم احتياج العميل، لملف تصميم وتصنيع وتركيب قابل للمراجعة. هنتعلّم الطريقة المشتركة مرة واحدة، وبعدها نطبّقها على أنواع الأثاث المختلفة.",
    preview: "النجارة وصناعة الأثاث",
    sections: "أقسام",
    modules: "محطات",
    lessons: "خطوات",
    ready: "اقرأ الخطوة",
    planned: "جاري إعداد الخطوة",
    back: "ارجع للرحلة",
    next: "الخطوة اللي بعده",
    previous: "الخطوة اللي قبله",
    search: "دور على خطوة",
    prerequisites: "ابدأ بالمحطات دي",
    goals: "هتقدر تعمل إيه؟",
    reading: "الشرح",
    example: "مثال محلول",
    quiz: "اختبر فهمك",
    assignment: "طبّق بنفسك",
    downloads: "التحميلات",
    assistant: "أسئلة عن الخطوة",
    video: "الفيديو",
    videoPending: "فيديو الخطوة لسه في الإنتاج. الشرح والتطبيق متاحين للقراءة.",
    check: "راجع الإجابات",
    correct: "إجابة صحيحة",
    retry: "راجع الشرح وحاول تاني",
    markRead: "خلصت قراءة الشرح",
    progress: "تقدمك",
    local: "يُحفظ تقدمك في حسابك.",
    save: "احفظ التطبيق",
    saved: "تم حفظ التطبيق في حسابك",
    taskReview: "قيّم تطبيقك باستخدام المعايير. حفظ الملف مش معناه اعتماد فني للمشروع.",
    workbook: "دليل الخطوة",
    worksheet: "ورقة التطبيق",
    zoom: "كبّر الرسم",
    noResults: "مفيش خطوات مطابقة",
    needsApplication: "المشروع الختامي محتاج كمان خطوات التطبيق اللي هتختاره.",
    start: "ابدأ التعلم",
    result: "نتيجة الاختبار",
    downloaded: "ملفات PDF",
    all: "كل الأقسام",
  },
  "ar-MSA": {
    title: "رحلة التعليم الفني",
    intro:
      "من تحليل احتياج العميل إلى حزمة تصميم وتخطيط للتصنيع والتركيب قابلة للمراجعة. تعلّم المنهج المشترك ثم طبّقه على أنواع الأثاث المختلفة.",
    preview: "النجارة وصناعة الأثاث",
    sections: "أقسام",
    modules: "محطات",
    lessons: "خطوات",
    ready: "اقرأ الخطوة",
    planned: "الخطوة قيد الإعداد",
    back: "العودة إلى الرحلة",
    next: "الخطوة التالي",
    previous: "الخطوة السابق",
    search: "ابحث عن خطوة",
    prerequisites: "المتطلبات السابقة",
    goals: "ماذا ستنجز؟",
    reading: "الشرح",
    example: "مثال محلول",
    quiz: "اختبر فهمك",
    assignment: "التطبيق العملي",
    downloads: "التحميلات",
    assistant: "أسئلة عن الخطوة",
    video: "الفيديو",
    videoPending: "فيديو الخطوة قيد الإنتاج. يمكنك الآن قراءة الشرح وتنفيذ التطبيق.",
    check: "تحقق من الإجابات",
    correct: "إجابة صحيحة",
    retry: "راجع الشرح ثم أعد المحاولة",
    markRead: "أتممت قراءة الشرح",
    progress: "تقدمك",
    local: "يُحفظ تقدمك في حسابك.",
    save: "احفظ التطبيق",
    saved: "تم حفظ التطبيق في حسابك",
    taskReview: "راجع تطبيقك وفق المعايير. حفظه لا يُعد اعتمادًا فنيًا للمشروع.",
    workbook: "دليل الخطوة",
    worksheet: "ورقة التطبيق",
    zoom: "تكبير الرسم",
    noResults: "لا توجد خطوات مطابقة",
    needsApplication: "يتطلب المشروع الختامي أيضًا خطوات التطبيق المختار.",
    start: "ابدأ التعلم",
    result: "نتيجة الاختبار",
    downloaded: "ملفات PDF",
    all: "كل الأقسام",
  },
  "ar-Gulf": {
    title: "رحلة التعليم الفني",
    intro:
      "من فهم طلب العميل إلى تجهيز ملف تصميم وتصنيع وتركيب واضح للمراجعة. نتعلّم الأساس المشترك، وبعدها نطبّقه على أنواع الأثاث المختلفة.",
    preview: "النجارة وصناعة الأثاث",
    sections: "أقسام",
    modules: "محطات",
    lessons: "خطوات",
    ready: "اقرأ الخطوة",
    planned: "الخطوة قيد التجهيز",
    back: "ارجع للرحلة",
    next: "الخطوة الجاي",
    previous: "الخطوة السابق",
    search: "ابحث عن خطوة",
    prerequisites: "تحتاج تبدأ بهالوحدات",
    goals: "وش بتنجز؟",
    reading: "الشرح",
    example: "مثال محلول",
    quiz: "اختبر فهمك",
    assignment: "جرّب بنفسك",
    downloads: "التحميلات",
    assistant: "أسئلة عن الخطوة",
    video: "الفيديو",
    videoPending: "فيديو الخطوة قيد الإنتاج. تقدر تقرأ الشرح وتشتغل على التطبيق الحين.",
    check: "راجع الإجابات",
    correct: "إجابة صحيحة",
    retry: "راجع الشرح وجرّب مرة ثانية",
    markRead: "خلصت قراءة الشرح",
    progress: "تقدمك",
    local: "يُحفظ تقدمك في حسابك.",
    save: "احفظ التطبيق",
    saved: "تم حفظ التطبيق في حسابك",
    taskReview: "راجع شغلك على المعايير. حفظ التطبيق ما يعني اعتماد المشروع فنيًا.",
    workbook: "دليل الخطوة",
    worksheet: "ورقة التطبيق",
    zoom: "كبّر الرسم",
    noResults: "ما فيه خطوات مطابقة",
    needsApplication: "المشروع الختامي يحتاج بعد خطوات التطبيق اللي تختاره.",
    start: "ابدأ التعلم",
    result: "نتيجة الاختبار",
    downloaded: "ملفات PDF",
    all: "كل الأقسام",
  },
  en: {
    title: "Technical education journey",
    intro:
      "Take a client need through design, fabrication planning and installation coordination. Learn the shared method once, then apply it across furniture types.",
    preview: "Carpentry and furniture making",
    sections: "Sections",
    modules: "Stations",
    lessons: "Steps",
    ready: "Read step",
    planned: "Step in preparation",
    back: "Back to journey",
    next: "Next step",
    previous: "Previous step",
    search: "Find a step",
    prerequisites: "Start with these stations",
    goals: "What you will accomplish",
    reading: "Explanation",
    example: "Worked example",
    quiz: "Check understanding",
    assignment: "Practice",
    downloads: "Downloads",
    assistant: "Step questions",
    video: "Video",
    videoPending:
      "The step video is in production. Read the explanation and try the practice activity now.",
    check: "Check answers",
    correct: "Correct",
    retry: "Review the explanation and try again",
    markRead: "I have read the explanation",
    progress: "Your progress",
    local:
      "Preview progress is stored on this device. Account sync will be added with main-site integration.",
    save: "Save practice",
    saved: "Practice saved to your account",
    taskReview:
      "Review your work against the criteria. Saving it does not constitute technical project approval.",
    workbook: "Step workbook",
    worksheet: "Practice worksheet",
    zoom: "Enlarge diagram",
    noResults: "No matching steps",
    needsApplication: "The capstone also requires the stations for your selected application.",
    start: "Start learning",
    result: "Quiz result",
    downloaded: "PDF files",
    all: "All sections",
  },
};
export const getTechnicalCopy = (locale: SupportedLocale) => copy[locale];
