import type { SupportedLocale } from "@/lib/locale/types";

const copy = {
  "ar-EG": {
    title: "رحلة التعليم الفني",
    intro:
      "من فهم احتياج العميل، لملف تصميم وتصنيع وتركيب قابل للمراجعة. هنتعلّم الطريقة المشتركة مرة واحدة، وبعدها نطبّقها على أنواع الأثاث المختلفة.",
    preview: "معاينة الرحلة",
    sections: "أقسام",
    modules: "موديولات",
    lessons: "دروس",
    ready: "اقرأ الدرس",
    planned: "جاري إعداد الدرس",
    back: "ارجع للرحلة",
    next: "الدرس اللي بعده",
    previous: "الدرس اللي قبله",
    search: "دور على درس",
    prerequisites: "ابدأ بالموديولات دي",
    goals: "هتقدر تعمل إيه؟",
    reading: "الشرح",
    example: "مثال محلول",
    quiz: "اختبر فهمك",
    assignment: "طبّق بنفسك",
    downloads: "التحميلات",
    assistant: "أسئلة عن الدرس",
    video: "الفيديو",
    videoPending: "فيديو الدرس لسه في الإنتاج. الشرح والتطبيق متاحين للقراءة.",
    check: "راجع الإجابات",
    correct: "إجابة صحيحة",
    retry: "راجع الشرح وحاول تاني",
    markRead: "خلصت قراءة الشرح",
    progress: "تقدمك",
    local: "التقدم هنا بيتحفظ على الجهاز ده. الربط بحسابك هيتم مع الموقع الرئيسي.",
    save: "احفظ التطبيق",
    saved: "التطبيق محفوظ على الجهاز",
    taskReview: "قيّم تطبيقك باستخدام المعايير. حفظ الملف مش معناه اعتماد فني للمشروع.",
    workbook: "دليل الدرس",
    worksheet: "ورقة التطبيق",
    zoom: "كبّر الرسم",
    noResults: "مفيش دروس مطابقة",
    needsApplication: "المشروع الختامي محتاج كمان دروس التطبيق اللي هتختاره.",
    start: "ابدأ التعلم",
    result: "نتيجة الاختبار",
    downloaded: "ملفات PDF",
    all: "كل الأقسام",
  },
  "ar-MSA": {
    title: "رحلة التعليم الفني",
    intro:
      "من تحليل احتياج العميل إلى حزمة تصميم وتخطيط للتصنيع والتركيب قابلة للمراجعة. تعلّم المنهج المشترك ثم طبّقه على أنواع الأثاث المختلفة.",
    preview: "معاينة الرحلة",
    sections: "أقسام",
    modules: "وحدات تعليمية",
    lessons: "دروس",
    ready: "اقرأ الدرس",
    planned: "الدرس قيد الإعداد",
    back: "العودة إلى الرحلة",
    next: "الدرس التالي",
    previous: "الدرس السابق",
    search: "ابحث عن درس",
    prerequisites: "المتطلبات السابقة",
    goals: "ماذا ستنجز؟",
    reading: "الشرح",
    example: "مثال محلول",
    quiz: "اختبر فهمك",
    assignment: "التطبيق العملي",
    downloads: "التحميلات",
    assistant: "أسئلة عن الدرس",
    video: "الفيديو",
    videoPending: "فيديو الدرس قيد الإنتاج. يمكنك الآن قراءة الشرح وتنفيذ التطبيق.",
    check: "تحقق من الإجابات",
    correct: "إجابة صحيحة",
    retry: "راجع الشرح ثم أعد المحاولة",
    markRead: "أتممت قراءة الشرح",
    progress: "تقدمك",
    local: "يُحفظ التقدم على هذا الجهاز في المعاينة. يُربط بحسابك عند التكامل مع الموقع الرئيسي.",
    save: "احفظ التطبيق",
    saved: "حُفظ التطبيق على الجهاز",
    taskReview: "راجع تطبيقك وفق المعايير. حفظه لا يُعد اعتمادًا فنيًا للمشروع.",
    workbook: "دليل الدرس",
    worksheet: "ورقة التطبيق",
    zoom: "تكبير الرسم",
    noResults: "لا توجد دروس مطابقة",
    needsApplication: "يتطلب المشروع الختامي أيضًا دروس التطبيق المختار.",
    start: "ابدأ التعلم",
    result: "نتيجة الاختبار",
    downloaded: "ملفات PDF",
    all: "كل الأقسام",
  },
  "ar-Gulf": {
    title: "رحلة التعليم الفني",
    intro:
      "من فهم طلب العميل إلى تجهيز ملف تصميم وتصنيع وتركيب واضح للمراجعة. نتعلّم الأساس المشترك، وبعدها نطبّقه على أنواع الأثاث المختلفة.",
    preview: "معاينة الرحلة",
    sections: "أقسام",
    modules: "وحدات تعليمية",
    lessons: "دروس",
    ready: "اقرأ الدرس",
    planned: "الدرس قيد التجهيز",
    back: "ارجع للرحلة",
    next: "الدرس الجاي",
    previous: "الدرس السابق",
    search: "ابحث عن درس",
    prerequisites: "تحتاج تبدأ بهالوحدات",
    goals: "وش بتنجز؟",
    reading: "الشرح",
    example: "مثال محلول",
    quiz: "اختبر فهمك",
    assignment: "جرّب بنفسك",
    downloads: "التحميلات",
    assistant: "أسئلة عن الدرس",
    video: "الفيديو",
    videoPending: "فيديو الدرس قيد الإنتاج. تقدر تقرأ الشرح وتشتغل على التطبيق الحين.",
    check: "راجع الإجابات",
    correct: "إجابة صحيحة",
    retry: "راجع الشرح وجرّب مرة ثانية",
    markRead: "خلصت قراءة الشرح",
    progress: "تقدمك",
    local: "التقدم في المعاينة ينحفظ على هالجهاز. ربطه بحسابك بيكون مع الموقع الرئيسي.",
    save: "احفظ التطبيق",
    saved: "انحفظ التطبيق على الجهاز",
    taskReview: "راجع شغلك على المعايير. حفظ التطبيق ما يعني اعتماد المشروع فنيًا.",
    workbook: "دليل الدرس",
    worksheet: "ورقة التطبيق",
    zoom: "كبّر الرسم",
    noResults: "ما فيه دروس مطابقة",
    needsApplication: "المشروع الختامي يحتاج بعد دروس التطبيق اللي تختاره.",
    start: "ابدأ التعلم",
    result: "نتيجة الاختبار",
    downloaded: "ملفات PDF",
    all: "كل الأقسام",
  },
  en: {
    title: "Technical education journey",
    intro:
      "Take a client need through design, fabrication planning and installation coordination. Learn the shared method once, then apply it across furniture types.",
    preview: "Journey preview",
    sections: "Sections",
    modules: "Modules",
    lessons: "Lessons",
    ready: "Read lesson",
    planned: "Lesson in preparation",
    back: "Back to journey",
    next: "Next lesson",
    previous: "Previous lesson",
    search: "Find a lesson",
    prerequisites: "Start with these modules",
    goals: "What you will accomplish",
    reading: "Explanation",
    example: "Worked example",
    quiz: "Check understanding",
    assignment: "Practice",
    downloads: "Downloads",
    assistant: "Lesson questions",
    video: "Video",
    videoPending:
      "The lesson video is in production. Read the explanation and try the practice activity now.",
    check: "Check answers",
    correct: "Correct",
    retry: "Review the explanation and try again",
    markRead: "I have read the explanation",
    progress: "Your progress",
    local:
      "Preview progress is stored on this device. Account sync will be added with main-site integration.",
    save: "Save practice",
    saved: "Practice saved on this device",
    taskReview:
      "Review your work against the criteria. Saving it does not constitute technical project approval.",
    workbook: "Lesson workbook",
    worksheet: "Practice worksheet",
    zoom: "Enlarge diagram",
    noResults: "No matching lessons",
    needsApplication: "The capstone also requires the modules for your selected application.",
    start: "Start learning",
    result: "Quiz result",
    downloaded: "PDF files",
    all: "All sections",
  },
};
export const getTechnicalCopy = (locale: SupportedLocale) => copy[locale];
