// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "نظام فعلي.",
    "title": "Dashboard فيه ٢٠ رقم = مفيش Dashboard.",
    "highlight": "٤ أرقام إنت بتقرأهم كل أسبوع",
    "chip": "٤ أرقام بس"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Dashboard",
    "definition": "شاشة واحدة بتعرض أهم الأرقام عشان تتابع حال شغلك بسرعة.",
    "tag": "متابعة سريعة"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "مؤشر أداء أساسي",
    "term": "KPI (Key Performance Indicator)",
    "definition": "رقم محدد بيعرفك إنت ماشي صح ولا عاكك في الشغل."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "رقم قياس",
    "term": "Metric",
    "definition": "أي رقم تقدر تقيسه في الشغل زي عدد الزوار أو المبيعات."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "ولاء العملاء",
    "term": "Retention",
    "definition": "نسبة الزبائن اللي اشتروا منك قبل كده ورجعوا لك تاني."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Threshold",
    "definition": "الرقم اللي لو زدت أو قليت عنه يبدأ القلق ولازم تتحرك.",
    "tag": "حد الخطر"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "مصمم ومُحدث",
    "term": "Creator vs Automator",
    "definition": "أدوار بتعملها؛ الأول بيصمم اللوحة، والتاني بيخلي الأرقام تتحدث تلقائي."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "الـ ٤ أرقام الأساسية",
    "bullets": [
      "Leads — كام واحد تواصل معاك الأسبوع ده؟ (مصدره: Creator + Automator).",
      "Conversion % — كام منهم اشترى؟",
      "Revenue — كام فلوس دخلت فعلاً؟",
      "Retention — كام عميل قديم رجع؟",
      "كل رقم جنبه: قيمة الأسبوع ده، الأسبوع اللي فات، السهم (↑/↓)."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Leads",
      "Conversion",
      "Revenue",
      "Retention",
      "مع الأسبوع اللي فات والسهم."
    ],
    "title": "Dashboard أسبوع 42 — أرقام حقيقية"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "بتفتحه وبتقفله من غير ما تقرّر حاجة. الكتير = صفر.",
      "label": "FAILURE — Dashboard مليان"
    },
    "title": "٢٠ رقم vs ٤ أرقام",
    "right": {
      "body": "في ثانيتين بتعرف لو فيه مشكلة. القرار جاهز قبل ما تخلص الأرقام.",
      "label": "RIGHT — ٤ أرقام واضحة"
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "eyebrow": "دورك دلوقتي",
    "highlight": "ابني أول Dashboard",
    "tagline": "حل الأسئلة دي عشان تطبق اللي اتعلمته.",
    "title": "ابني أول Dashboard في Sheet"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "Mission",
    "highlight": "ابني Dashboard من ٤ أرقام بس",
    "tagline": "Dashboard فيه ٢٠ رسم = ديكور. اختار ٤ أرقام لو اتحرّكوا، شغلك بيتحرّك معاهم.",
    "title": "ابني Dashboard من ٤ أرقام بس"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "/dashboard فيه ٤ widgets بس",
    "bullets": [
      "Streak: رقم واحد بسيط.",
      "Reviews Due: عدد + CTA واحد.",
      "Welcome Checklist: 4 خطوات بس."
    ]
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "نتقابل في الدرس الجاي: Review أسبوعي = ١٥ دقيقة.",
    "title": "٤ أرقام بس",
    "highlight": "نظام متابعة حقيقي",
    "eyebrow": "الخلاصة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [460, 436, 448, 427, 355, 393, 396, 604, 407, 421, 292, 436, 456, 303];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
