// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "حاجة حصلت مرّة = Outlier",
    "title": "Pattern أم Outlier؟",
    "highlight": "حاجة بتتكرّر = Pattern",
    "chip": "HERO"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "نقطة البداية",
    "term": "Baseline",
    "definition": "نقطة البداية أو \"المتوسط الطبيعي\" اللي بنقيس عليه أي تغيير في الأرقام."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "مقياس الأداء",
    "term": "Metric",
    "definition": "المقياس أو الرقم اللي بتتابعه عشان تعرف أداء شغلك عامل إزاي."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "تكرار منتظم",
    "term": "Pattern",
    "definition": "تكرار أو شكل منتظم في الأرقام بيخليك تتوقع اللي جاي."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "رقم شاذ",
    "term": "Outlier",
    "definition": "رقم \"شاذ\" أو غريب، بعيد جداً عن الأرقام الطبيعية اللي متعود عليها."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "خطوات ثابتة ومكتوبة بنمشي عليها عشان نخلص شغلانة معينة بنفس الطريقة.",
    "tag": "خطوات ثابتة",
    "term": "SOP (Standard Operating Procedure)"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "فن استخراج المعلومة المهمة والمفيدة من وسط زحمة الأرقام والدوشة.",
    "tag": "معلومة مفيدة",
    "term": "Signal vs Noise"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "«ده حصل قبل كده؟»",
      "آه = Pattern → خطّط عليه (Automation/SOP/ ميزانية ثابتة).",
      "لأ = Outlier → افهم سببه (فرصة تكبّرها أو خطر تمنعه).",
      "قاعدة: ٣ مرّات في ٣ فترات مختلفة = Pattern مؤكّد."
    ],
    "title": "أول سؤال قدام أي رقم متغيّر"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "«ده حصل قبل كده؟»",
      "آه = Pattern → خطّط عليه (Automation/SOP/ ميزانية ثابتة).",
      "لأ = Outlier → افهم سببه (فرصة تكبّرها أو خطر تمنعه).",
      "قاعدة: ٣ مرّات في ٣ فترات مختلفة = Pattern مؤكّد."
    ],
    "title": "أول سؤال قدام أي رقم متغيّر"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "Pattern مستقر حوالين ٤٤ lead/أسبوع.",
      "القفزة في الأسبوع ٨ سببها حملة لمرّة واحدة — مش قاعدة."
    ],
    "title": "١٢ أسبوع — نمط واحد و outlier واحد"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "Pattern مستقر حوالين ٤٤ lead/أسبوع.",
      "القفزة في الأسبوع ٨ سببها حملة لمرّة واحدة — مش قاعدة."
    ],
    "title": "١٢ أسبوع — نمط واحد و outlier واحد"
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "right": {
      "body": "بتاخد قرار على Pattern مؤكّد، وبتفهم الـ Outlier من غير ما تتسرّع.",
      "label": "RIGHT — بتشوف الـ trend"
    },
    "title": "ردّ فعل مقابل قراءة",
    "left": {
      "label": "FAILURE — كل رقم بتفزع منه",
      "body": "Outlier واحد = قرار كبير. بعد أسبوع تكتشف إنه كان مصادفة وضيّعت وقت وفلوس."
    }
  },
  {
    "card": "CompareCard",
    "accent": "mint",
    "title": "ردّ فعل مقابل قراءة",
    "left": {
      "label": "FAILURE — كل رقم بتفزع منه",
      "body": "Outlier واحد = قرار كبير. بعد أسبوع تكتشف إنه كان مصادفة وضيّعت وقت وفلوس."
    },
    "right": {
      "body": "بتاخد قرار على Pattern مؤكّد، وبتفهم الـ Outlier من غير ما تتسرّع.",
      "label": "RIGHT — بتشوف الـ trend"
    }
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "left": {
      "body": "Outlier واحد = قرار كبير. بعد أسبوع تكتشف إنه كان مصادفة وضيّعت وقت وفلوس.",
      "label": "FAILURE — كل رقم بتفزع منه"
    },
    "title": "ردّ فعل مقابل قراءة",
    "right": {
      "body": "بتاخد قرار على Pattern مؤكّد، وبتفهم الـ Outlier من غير ما تتسرّع.",
      "label": "RIGHT — بتشوف الـ trend"
    }
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "title": "صنّف ٥ ملاحظات",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حل الأسئلة دي عشان تفرّق بين الـ Pattern والـ Outlier بنفسك.",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "eyebrow": "دورك دلوقتي",
    "title": "صنّف ٥ ملاحظات",
    "tagline": "حل الأسئلة دي عشان تفرّق بين الـ Pattern والـ Outlier بنفسك.",
    "highlight": "اختبر فهمك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [359, 279, 337, 316, 287, 291, 288, 307, 501, 316, 325, 231, 282, 281, 237, 220];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
