// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "Business بيشغّلها",
    "chip": "أهلًا",
    "subtitle": "Analyst بيقولك «خد القرار ده». Business بيحوّله لنظام يومي + علاقات + توسع.",
    "title": "قراراتك جاهزة"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "عملاء محتملين",
    "term": "Leads (العملاء المحتملين)",
    "definition": "ناس عينيها على شغلك وممكن يشتروا بس لسه مطلعوش المحفظة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "طريقة تنظيم شغل بتشوف فيها الحاجة وهي بتتحرك من البداية للنهاية.",
    "tag": "تنظيم الشغل",
    "term": "Kanban Board"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "لوحة تحكم",
    "term": "Dashboard (لوحة تحكم)",
    "definition": "شاشة بتجمع لك أهم الأرقام والمؤشرات عشان تتابع شغلك بلمحة."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "الـ Analyst بيفهم البيانات، والـ Business هو صاحب القرار اللي بيوجه الشغل.",
    "tag": "فرق الأدوار",
    "term": "Analyst vs. Business"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "دراسة نظرية",
    "term": "Academic Exercise (تمرين أكاديمي)",
    "definition": "كلام نظري أو دراسة على الورق بعيد عن واقع السوق والصعوبات."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "تحسين مستمر",
    "term": "Feedback Loop (الدائرة المغلقة)",
    "definition": "عملية متكررة بتبدأ من خطوة وتلف ترجع لنفس النقطة عشان تحسن النتائج."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "definition": "برامج أو أدوات بتنفذ الخطوات اليومية المتكررة بدل ما تعملها بإيدك.",
    "tag": "أتمتة الشغل",
    "term": "Operational System (نظام التشغيل)"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "الـ Loop الكامل",
    "bullets": [
      "Builder بنى المنتج → بيانات.",
      "Creator جاب الـ Reach → leads.",
      "Automator وصّل كل ده → جمعها في مكان واحد.",
      "Analyst سأل وفسّر → قرارات.",
      "Business بياخد القرارات دي ويحوّلها لنظام يومي + علاقات عملاء + خطط توسع.",
      "وبعدين Business بيدّي feedback يرجع Builder/Creator/Automator — وتبدأ الدورة من جديد بمستوى أعلى."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "قرارات الـ Analyst بتدخل في Kanban للتنفيذ.",
      "بتمر بمراحل To Do، Doing، لحد ما تبقى Done."
    ],
    "title": "من قرارات لـ Business System"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "label": "RIGHT — Business بيشغّلها",
      "body": "كل قرار له owner + deadline + مكان في الـ system. التنفيذ بقى تلقائي."
    },
    "title": "قرارات في درج ولا نظام؟",
    "left": {
      "body": "Analyst بيطلّع قرارات أسبوعيًا. مفيش حد بينفّذ. بعد شهرين بقت document ميّت.",
      "label": "FAILURE — قائمة قرارات بتطول"
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "حل الأسئلة عشان تحوّل القرارات لأكشن حقيقي.",
    "title": "جهّز الـ Decision Backlog",
    "eyebrow": "دورك دلوقتي",
    "highlight": "وابدأ التطبيق"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "كل insight له roadmap_item مرتبط بيه.",
      "الـ item بياخد phase حسب أولوية الـ insight.",
      "معدل إنجاز القرارات بنتابعه أول بأول."
    ],
    "title": "الـ Analyst بيحوّل القرار لـ Roadmap Item"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [327, 405, 411, 357, 373, 385, 449, 405, 909, 477, 747, 400, 581];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
