// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أهلًا",
    "title": "كل تفسير ينتهي بـ «إذًا هعمل…»",
    "subtitle": "تفسير من غير قرار = وقت ضايع. كل insight لازم يطلّع action.",
    "highlight": "إذًا هعمل…"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "فهم من الأرقام",
    "term": "Insight",
    "definition": "فهم جديد وواضح طلعته من الأرقام بيعرفك الدنيا ماشية إزاي."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "خطوة فعلية",
    "term": "Action",
    "definition": "القرار أو الخطوة اللي هتاخدها فعلياً بناءً على اللي فهمته."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "مقياس أداء",
    "term": "Metric",
    "definition": "حاجة بنقيس بيها الأداء، زي المسطرة اللي بنقيس بيها الشغل."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "الخط الأحمر",
    "term": "Threshold",
    "definition": "الرقم \"الخط الأحمر\" اللي لو عديناه لازم ناخد تصرف فوراً."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "شكل واستخدام",
    "term": "UI/UX",
    "definition": "شكل الموقع أو التطبيق وإزاي الزبون بيستخدمه بسهولة."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "مقارنة فكرتين",
    "term": "A/B Testing",
    "definition": "تجربة بنقارن فيها بين فكرتين عشان نشوف أنهي واحدة نتيجتها أحسن."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Insight: «٧٠٪ من العملاء بيسألوا عن السعر قبل المنتج».",
      "Action: «أضيف السعر في أول رسالة على WhatsApp».",
      "Owner: «أنا».",
      "Deadline: «الأربعاء».",
      "من غير الـ ٤ عناصر دي = القرار مش هيتنفّذ."
    ],
    "title": "Insight → Action → Owner → Deadline"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "مثال حقيقي بـ ٤ خانات — من غير الـ ٤ القرار مش هيتنفّذ."
    ],
    "title": "Insight → Action → Owner → Deadline"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "البيانات قالتلك حاجة. مفيش حد عمل حاجة. نفس المشكلة الأسبوع الجاي.",
      "label": "FAILURE — «إيه ده مثير للاهتمام»"
    },
    "title": "تفسير ميّت vs قرار حي",
    "right": {
      "body": "كل insight بيتحوّل لـ task لها owner و deadline. الأسبوع الجاي بتقيس الأثر.",
      "label": "RIGHT — «إذًا الأربعاء أنا هعمل…»"
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "title": "حوّل ٣ insights لـ ٣ قرارات",
    "tagline": "حلّ الأسئلة اللي جاية وطبّق اللي اتعلّمته عشان تحوّل الـ insights لقرارات حقيقية.",
    "highlight": "٣ قرارات",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "كل widget له action واحد مقترح على الأقل.",
      "Actions بتظهر كزرار، مش كنص.",
      "بنتابع كم action اتنفّذ vs كم اتعرض."
    ],
    "title": "كل insight في /analytics جنبه action مقترح"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [395, 279, 280, 215, 263, 259, 265, 341, 240, 606, 489, 406];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
