// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "بعد الريفيو والأسئلة والتفسير، محتاج تربط قراراتك باتجاه البيزنس.",
    "highlight": "القرارات الأسبوعية الصغيرة بتتجمّع لهدف أكبر",
    "title": "هتفهم إيه النهاردة؟",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كل أسبوع قرار: «نزود منشورات» — «نخفّض سعر» — «نجرب حملة» — ومفيش صورة للهدف الكبير.",
      "Analyst بيطلّع قرارات. Business بيحوّلها لنظام يومي — بس من غير هدف، القرارات بتتشتت.",
      "الـ AI يساعدك تربط القرار بالهدف وتسأل «ده بيقرّبنا ولا بيشتّتنا؟» — إنت تختار الأولوية."
    ],
    "title": "قرارات كتير — ومفيش اتجاه"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "كل قرار أسبوعي لازم يخدم هدف أكبر — وإلا بيبقى busy work.",
      "Decision Backlog: قائمة قرارات Analyst — Business يحوّلها لـ To Do · Doing · Done.",
      "٣ أرقام progress تربط الأسبوع بالهدف: مثلاً leads، conversion، revenue — أو progress، responses، results.",
      "Feedback loop: Business يرجّع feedback لـ Builder/Creator/Automator — والدورة تبدأ من جديد."
    ],
    "title": "قرارات أسبوعية → هدف ٦ شهور"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "قرارات في الدرج vs قرارات في نظام",
    "left": {
      "label": "قائمة قرارات بتطول",
      "body": "Analyst بيطلّع قرارات أسبوعيًا. مفيش حد بينفّذ. بعد شهرين = document ميّت."
    },
    "right": {
      "label": "قرار → owner → deadline",
      "body": "كل قرار له مكان في النظام. التنفيذ بقى جزء من الشغل اليومي — مش «لما نفضى»."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Decision Backlog (مخزون قرارات)",
    "definition": "قائمة قرارات Analyst جاهزة للتنفيذ — كل واحد له owner وموعد.",
    "tag": "تجربة رد ٢٤ ساعة"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Progress Numbers (أرقام التقدّم)",
    "tag": "leads، conversion، retention",
    "definition": "٣ أرقام تقيس إذا القرارات الأسبوعية بتقرّبك من الهدف الكبير."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "قرارات Analyst بتتحول لـ Kanban.",
      "الـ Kanban ده بيبقى فيه 3 مراحل: To Do · Doing · Done.",
      "كل قرار لازم يكون ليه owner مسؤول عنه."
    ],
    "title": "من القرار للتنفيذ"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "فكّر كويس، وشوف إزاي تحوّل القرارات لنظام يومي وشغل حقيقي.",
    "highlight": "Analyst قرر: «خصم ١٥٪ لأول طلب». إيه أول خطوة Business عشان يحوّله لنظام؟",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "الدرس الجاي هنشوف Business Path، إزاي تحوّل القرارات لنظام يومي وتوسع.",
    "highlight": "فهمت إيه؟ القرارات الأسبوعية بتتجمّع لهدف أكبر",
    "eyebrow": "خلّصت الربط",
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [556, 765, 937, 767, 774, 699, 617, 576, 742];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
