// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "A/B Testing",
    "subtitle": "غيّر حاجة واحدة، قيس نتيجة واحدة — مش تجارب عشوائية.",
    "title": "هتفهم إيه النهاردة؟",
    "chip": "أهلًا، بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "غيّرت العنوان والسعر والصورة في نفس الأسبوع — المبيعات زادت. «يعني كله نفع!»",
      "ده مش A/B test — ده chaos. متغيّرات كتير = مفيش درس.",
      "الـ AI يساعدك تكتب فرضية وتفسّر النتيجة — إنت تحدّد متغيّر واحد ومقياس واحد قبل ما تبدأ."
    ],
    "title": "«جرّبنا حاجات كتير — ومش عارفين إيه نفع»"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "A/B = نسخة A (زي ما هي) vs نسخة B (تغيير واحد بس). الباقي ثابت.",
      "حدّد المقياس قبل ما تبدأ: conversion %، clicks، revenue — مش «نشوف إيه يحصل».",
      "تحذير للمبتدئ: عيّنة صغيرة = نتيجة مش مضمونة. ٢–٤ أسابيع ملاحظة أحسن من ٣ أيام.",
      "الـ AI يساعدك تصيغ الفرضية وتفسّر — بس متبالغش «ثبتنا ١٠٠٪» من ٢٠ زائر."
    ],
    "title": "A vs B — متغيّر واحد — مقياس قبل البداية"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "تجارب عشوائية vs A/B منظّم",
    "left": {
      "label": "«جرّبنا كل حاجة»",
      "body": "٣ تغييرات في أسبوع — مفيش عرفنا إيه نفع. قرار على تخمين."
    },
    "right": {
      "label": "A/B واحد",
      "body": "عنوان A vs عنوان B — نفس الصفحة، نفس السعر — ٢ أسبوع — conversion %."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "مثال: صفحة A vs B",
    "term": "A/B Test (اختبار A/B)",
    "definition": "مقارنة نسختين — فرق واحد بس — لقياس أثر التغيير."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "مثال: ٢٠ زائر vs ٢٠٠+",
    "term": "Sample Size (حجم العيّنة)",
    "definition": "عدد الملاحظات اللي محتاجها قبل ما تثق في النتيجة."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "نتيجة A/B محتاجة pattern — مش outlier يوم واحد.",
      "استخدم الرسم في المهمة."
    ],
    "title": "نمط vs صدفة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "title": "سؤال واحد — مش امتحان",
    "eyebrow": "دورك دلوقتي",
    "tagline": "شوف إجابتك صح ولا لأ.",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "title": "صمّم A/B test بسيط",
    "eyebrow": "مهمتك",
    "tagline": "صمّم الـ A/B test بتاعك بنفسك.",
    "highlight": "جاهز للتطبيق العملي؟"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "فهمت إيه؟ A/B = تغيير واحد، نتيجة واحدة — والـ AI يساعد من غير مبالغة.",
      "تقدر تعمل إيه؟ عندك تصميم A/B test جاهز للتجربة."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [990, 839, 1140, 919, 755, 676, 586, 351, 724, 527];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
