// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أهلًا",
    "title": "السؤال الصح أهم من الإجابة",
    "highlight": "أهم من الإجابة",
    "subtitle": "السؤال هو اللي بيوجّه كل حاجة بعديه."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "لو سألت غلط، هتجمع بيانات غلط.",
      "هتفسّر المعلومات دي غلط.",
      "وفي الآخر هتاخد قرارات غلط تمامًا."
    ],
    "title": "خطأ في السؤال = مشاكل كتير"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "مقياس رقمي",
    "term": "Metric",
    "definition": "رقم أو مقياس بنستخدمه عشان نعرف السهم طالع ولا نازل."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "الفترة الزمنية اللي بنبص فيها على الأرقام (يوم، شهر، سنة).",
    "term": "Window (Timeframe)",
    "tag": "فترة زمنية"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Threshold",
    "definition": "الرقم اللي عنده بنقرر هنعمل إيه بالضبط.",
    "tag": "نقطة قرار"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "AI Assistant (ChatGPT)",
    "definition": "برنامج ذكي بيساعدك تحلل البيانات وتطلع منها ملخص مفيد.",
    "tag": "مساعد ذكي"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "سؤال عملي",
    "definition": "سؤال إجابته بتخليك تحط إيدك على الفعل اللي عليه الدور، مش مجرد معلومة.",
    "term": "Actionable Question/Answer"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "شغل مركز",
    "definition": "فترة شغل مركزة وليها هدف، زي إعلانات العيد أو الشتاء.",
    "term": "Campaign (حملة) / Follow-up"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Specific Question (سؤال محدد)",
    "definition": "سؤال مفصل فيه (مين، فين، وإمتى) عشان يوصلك لرد دقيق.",
    "tag": "سؤال دقيق"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "محدّد: فيه «مين/إيه/إمتى/كام»."
    ],
    "title": "٤ شروط للسؤال الصح"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "قابل للقياس: الإجابة رقم أو نسبة.",
      "متعلّق بقرار: لو الإجابة جت، فيه حاجة هتتغيّر.",
      "في وقت محدّد: «هذا الأسبوع» أو «آخر ٣٠ يوم»."
    ],
    "title": "٤ شروط للسؤال الصح"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "سؤال عام بيفشل في الـ ٤ شروط اللي قلناها.",
      "لكن السؤال المحدّد بينجح فيهم كلهم."
    ],
    "title": "نفس الموضوع · صياغتين · نتيجتين"
  },
  {
    "card": "CompareCard",
    "accent": "mint",
    "left": {
      "body": "إجابة من ١٠ ساعات. مفيش قرار. بتقفل البيانات وتروح.",
      "label": "FAILURE — «إيه أحوال البيع؟»"
    },
    "right": {
      "body": "إجابة في دقيقة. القرار: لو كبير — كرّر الـ campaign. لو صغير — اعمل follow-up.",
      "label": "RIGHT — «كام عميل اشترى مرتين الشهر ده؟»"
    },
    "title": "سؤال عام vs سؤال محدّد"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كل widget بيجاوب على سؤال محدّد.",
      "الأسئلة المبهمة بتولّد dashboards مبهمة.",
      "لو معندكش سؤال للـ widget — اشيله أحسن."
    ],
    "title": "السؤال اللي بنى /analytics"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "title": "حسّن ٣ من أسئلتك",
    "highlight": "حسّن ٣ من أسئلتك",
    "tagline": "طبق اللي اتعلمته وحوّل أسئلتك العادية لأسئلة هتساعدك تاخد قرارات صح.",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [283, 376, 342, 407, 348, 385, 375, 345, 427, 382, 533, 465, 463, 574, 466];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
