// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "بعد ما الريفيو الأسبوعي بقى عادة، محتاج تتجنّب ٤ فخاخ تفسير قبل ما تتسرّع في القرار.",
    "highlight": "البيانات ممكن تكون صح — والقرار غلط لو قرأتها غلط.",
    "chip": "أهلًا | بداية الدرس",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "«المبيعات زادت لما شغّلنا أغاني هادية» — قررت تعتمدها طول الوقت. بعد شهر نزلت.",
      "«الـ retention بقت ٨٠٪!» — فرحت. لما شفت العدد الكلي، اكتشفت إن الناس اللي بتسيب اتشالت.",
      "الـ AI يساعدك تسأل «هل ده سبب ولا صدفة؟» — إنت تقرر قبل ما تبني قرار كبير."
    ],
    "title": "الأرقام واضحة — والقرار طلع غلط"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Correlation ≠ Causation: حاجتين بيتحركوا مع بعض مش معناه واحد سبب التاني. اسأل: في حاجة تالتة؟",
      "عيّنة صغيرة: ٣ عملاء مش «السوق». متاخدش قرار كبير من ٥ حالات.",
      "Vanity metric: لايكات ومشاهدات مش دايمًا = مبيعات. اسأل: الرقم ده بيخدم قرار إيه؟",
      "Recency bias: آخر أسبوع مش كل القصة. قارن بفترة أطول قبل ما تتسرّع.",
      "قرار صغير قابل للتراجع > قرار كبير مبني على «حاسس»."
    ],
    "title": "٤ فخاخ تفسير — وعلاجهم"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "تفسير سريع vs تفسير حذر",
    "right": {
      "body": "تجربة صغيرة: أغاني vs بدون — نفس الوقت — تقيس المبيعات. بيانات جديدة الأسبوع الجاي.",
      "label": "«هجرّب أسبوع واحد»"
    },
    "left": {
      "body": "Correlation اتعاملت كـ Causation. ممكن الصبح = زبائن أكتر — مش الموسيقى.",
      "label": "«الأغاني سبب الزيادة»"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "ارتباط",
    "term": "Correlation (ارتباط)",
    "definition": "حاجتين بيتحركوا مع بعض — من غير ما يكون واحد سبب التاني."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Vanity Metric (رقم شكلي)",
    "definition": "رقم يبان حلو بس مش بيخدم قرار حقيقي.",
    "tag": "رقم شكلي"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "آيس كريم وغرق بيتحرّكوا مع بعض — السبب الحقيقي حاجة تالتة (الحرارة)."
    ],
    "title": "Correlation ≠ Causation"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان",
    "highlight": "هل ده سبب ولا صدفة؟",
    "tagline": "اسأل نفسك قبل ما تاخد قرار كبير. شوفك في الدرس الجاي!"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [411, 499, 672, 591, 444, 444, 460, 406];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
