// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "Automator بيجمع، Analyst بيحوّل لقرار. ورقة أو Google Sheet يكفي.",
    "highlight": "البيانات الجاهزة بداية مش نهاية.",
    "title": "هتفهم إيه النهاردة؟",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Dashboard فيه ٢٠ رسم بياني. بتفتحه يوميًا وتقول «حلو». بس مفيش حاجة اتغيّرت في شغلك بسببه.",
      "البيانات بقت ديكور — مش أداة قرار. Automator خلّى الكومة تكبر، بس من غير سؤال محدّد مش هتعرف تتحرّك.",
      "الـ AI يساعدك تصيغ الأسئلة وتلخّص الأرقام — إنت تقرر إيه السؤال اللي يستاهل وقتك وإيه القرار اللي هتاخده."
    ],
    "title": "بتفتح التقرير كل يوم — ومفيش قرار اتغيّر"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Builder بنى المنتج — كل click وكل order بيتسجّل. Creator جاب الـ Reach — كل view وكل lead بيتحفظ.",
      "Automator وصّل كل ده في مكان واحد: CRM أو Sheet أو قاعدة بيانات.",
      "Analyst بيقف قدام البيانات ويسأل: إيه اللي بيشتغل؟ إيه اللي مش بيشتغل؟ إيه القرار اللي لازم آخده الأسبوع ده؟",
      "الأرقام لوحدها مش insight — الـ insight بيطلع لما السؤال يوصّلك لقرار تقدر تنفّذه."
    ],
    "title": "Automator بيجمع — Analyst بيسأل"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "بتفتح تقرير المبيعات كل صباح. بتشوف الأرقام وتمشي. مفيش سؤال محدّد — ومفيش قرار.",
      "label": "بتتفرّج بس"
    },
    "right": {
      "body": "«ليه الـ Conversion نزل ٥٪ الأسبوع ده؟» — بتفتح التقرير بسؤال واحد، تطلع بقرار محدّد، تنفّذه نفس اليوم.",
      "label": "بتدخل بسؤال"
    },
    "title": "بتتفرّج على الأرقام vs بتدخل بسؤال"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "أرقام وحقائق",
    "definition": "أرقام وحقائق مجمّعة — مبيعات، زيارات، طلبات، شكاوى.",
    "term": "Data (بيانات)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "فهم للعمل",
    "definition": "فهم يخلّيك تعرف إيه اللي تعمله — مش مجرد رقم على الشاشة.",
    "term": "Insight (رؤية)"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Dashboard بدون سؤال = ديكور.",
      "سؤال محدّد → إجابة → قرار → تنفيذ → مراجعة.",
      "ابداً من السؤال في المهمة."
    ],
    "title": "حلقة القرار — ٥ مراحل"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "جاوب على السؤال ده عشان تتأكد إنك فهمت.",
    "highlight": "اختبر فهمك وإزاي تطبق",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "تقدر تطبق اللي اتعلمته. شوفك في الدرس الجاي!",
    "highlight": "فهمت إيه؟ وجود أرقام مش نفس فهمك إيه اللي تعمله",
    "eyebrow": "خلّصت البداية",
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [765, 939, 1051, 862, 666, 546, 754, 412, 523];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
