// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "٣ مصادر",
    "subtitle": "قرار كويس محتاج إيه الناس بتعمله، إيه النتائج، وإيه اللي الناس بتقوله.",
    "chip": "أهلًا، بداية الدرس",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "واتساب في مكان، الفواتير في مكان، ملاحظاتك في دفتر — كل مصدر لوحده.",
      "بتنسى نص الـ context، وبتقرّر من فاتورة بس ومش سامع العملاء.",
      "الـ AI يساعدك تلخّص من المصادر المختلفة، وإنت تقرر إيه الناقص قبل القرار."
    ],
    "title": "بتفتح ٥ تطبيقات عشان تجاوب سؤال واحد"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "٣ مصادر بيكمّلوا بعض",
    "bullets": [
      "سلوك (Behavior) — إيه اللي الناس بتعمله: زيارات، clicks، طلبات، رسائل واتساب.",
      "نتائج (Results) — إيه اللي حصل فعلًا: مبيعات، فواتير، إيرادات، conversions.",
      "كلام (Words) — إيه اللي الناس بتقوله: شكاوى، استفسارات، ملاحظاتك، آراء العملاء.",
      "مصدر واحد بيعطيك جزء من الصورة — التلاتة مع بعض بيدوك قرار أقوى.",
      "لو Automator شغّال، الـ ٣ ممكن يتجمّعوا في Sheet أو CRM واحد."
    ]
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "label": "تلات مصادر",
      "body": "فواتير + واتساب + ملاحظات الفريق — تكتشف إن المشكلة في منتج واحد مش في الإعلان. القرار يتغيّر."
    },
    "title": "مصدر واحد vs تلات مصادر",
    "left": {
      "label": "مصدر واحد",
      "body": "بتقرّر من فواتير المبيعات بس — المبيعات نزلت، فبتقلّل الإعلان. بس العملاء على الواتساب بيسألوا عن منتج تاني."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "المكان اللي بتجيب منه بياناتك — واتساب، فواتير، شيت، CRM.",
    "tag": "رسائل العملاء على واتساب",
    "term": "Source (مصدر)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "SSOT (مكان واحد للحقيقة)",
    "tag": "Sheet فيه ملخص أسبوعي",
    "definition": "مكان واحد يجمع المصادر عشان ما تتوهش — مش لازم يكون معقّد."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "دمج المصادر",
    "bullets": [
      "سلوك + نتائج + كلام في مكان واحد.",
      "سؤال واحد = إجابة أقوى.",
      "استخدمه في المهمة."
    ]
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان",
    "tagline": "جاوب على السؤال عشان تتأكد إنك فهمت.",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "إيه اللي عندك دلوقتي؟",
    "bullets": [
      "فهمت إن القرار الكويس محتاج سلوك + نتائج + كلام — مصدر واحد بيديك جزء بس.",
      "عندك خريطة ٣ مصادر لقرار واحد — تعرف إيه الناقص قبل ما تقرر."
    ]
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "eyebrow": "ختام الدرس",
    "title": "ملخص سريع",
    "tagline": "شوفك في الدرس الجاي عشان نكمل رحلتنا.",
    "highlight": "القرار الصح محتاج أكتر من مصدر"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [773, 917, 1192, 948, 547, 657, 531, 304, 623, 232];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
