// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "ليه دلوقتي؟ الشغل المتكرر بيرجع يدوي",
    "highlight": "الأتمتة أقوى ببيانات منظمة",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الأوتوميشن بيبعت إيميل ترحيب — تمام. بس لما المبيعات تسأل «مين العميل ده؟» — مفيش سجل.",
      "البيانات راحت في الإيميل بس — مش في مكان منظم تقدر ترجعله كل يوم.",
      "العامل الافتراضي محتاج ذاكرة: فين بيحفظ؟ إيه الحقول؟ إمتى بيقرأ؟ — من غير ده الشغل المتكرر بيرجع يدوي."
    ],
    "title": "العميل اتسجّل — ومش لاقيين بياناته"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "كل lead أو طلب محتاج يتسجّل في مكان واحد — جدول أو شيت منظم بحقول ثابتة.",
      "اكتب: إمتى البيانات تتكتب؟ (بعد التسجيل) — إمتى تتقري؟ (تقرير يومي، متابعة).",
      "٣ حقول كفاية للبداية: اسم، تواصل، تاريخ/حالة — مش لازم ٢٠ عمود.",
      "الـ workflow بيقرأ من نفس المكان اللي بيكتب فيه — ده اللي بيخلي الشغل المتكرر يشتغل لوحده."
    ],
    "title": "DB = ذاكرة الأتمتة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "label": "إيميل بس",
      "body": "الأوتوميشن بيبعت إيميل — البيانات في صندوق الوارد. بعد أسبوع: مين سجّل؟ محدش عارف."
    },
    "right": {
      "label": "سجل + إيميل",
      "body": "نفس الأوتوميشن يكتب صف في جدول (اسم، تليفون، تاريخ) + يبعت إيميل. المتابعة تلقائية."
    },
    "title": "رسالة وخلاص vs سجل منظم"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "leads: name, phone, status, created_at.",
    "definition": "الحقول اللي بتحفظها — اسم كل عمود ونوعه.",
    "term": "Schema (شكل الجدول)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تسجيل جديد → Create. تقرير يومي → Read.",
    "definition": "Create = اكتب. Read = اقرأ. Update = حدّث. Delete = امسح.",
    "term": "CRUD (قراءة وكتابة)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/unique/automator-m4-l1-connect-database.jpg",
    "title": "بيانات منظمة ورا الـ workflow",
    "caption": "كل حدث (تسجيل، تقدّم، طلب) بيتسجّل في مكان واحد. الـ workflow يقرأ ويكتب من نفس المصدر — مش ملفات متفرقة.",
    "eyebrow": "شوفها ببساطة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "highlight": "اختبر فهمك",
    "title": "سؤال واحد — مش امتحان",
    "tagline": "هل فهمت ليه الذاكرة مهمة للأتمتة؟",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ الأتمتة أقوى لما عندها ذاكرة منظمة — مكان + حقول + إمتى تكتب وتقرأ.",
      "تقدر تعمل إيه؟ عندك خطة تخزين جاهزة لـ workflow حقيقي.",
      "اللي جاي: Webhooks & APIs — لما تطبيق يقول لتطبيق تاني «حصل حاجة»."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [574, 609, 755, 595, 534, 810, 570, 420, 611];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
