// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "3 أدوات بنفس الفكرة. بس كل واحدة ليها مكانها الصح.",
    "title": "Make vs n8n vs Zapier",
    "highlight": "Make vs n8n vs Zapier",
    "chip": "Workflow"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "سير العمل",
    "term": "Workflow (سير العمل)",
    "definition": "طريق متخطط لخطوات الشغل وبتمشي لوحدها من غير ما تتدخل."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "الشرارة",
    "term": "Trigger (المُشغّل)",
    "definition": "الشرارة أو \"الخبطة\" اللي بتنبه البرنامج إنه يبدأ يشتغل دلوقت."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "توصيل برامج",
    "term": "Integration (الربط)",
    "definition": "توصيل برنامجين ببعض عشان يكلموا بعض ويتبادلوا بيانات."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "من غير كود",
    "term": "No-Code (من غير كود خالص)",
    "definition": "أدوات بتخليك تعمل برامج معقدة من غير ما تلمس الكود."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "سيرفرك الخاص",
    "term": "Self-hosted (استضافة ذاتية)",
    "definition": "إنك تشغل البرنامج على جهازك أو سيرفرك الخاص بدل ما تأجره جاهز."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "كود متاح",
    "term": "Open Source (مصدر مفتوح)",
    "definition": "برامج كودها متاح للكل، تقدر تستخدمها وتعدل فيها ببلاش من غير اشتراك."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Zapier — الأسهل، الأغلى، أكتر integrations جاهزة. خيار مثالي لو لسه بتقول يا هادي في الأتمتة والـ workflows البسيطة.",
      "Make (سابقًا Integromat) — توازن بين السهولة والقوة. visual interface حلو، أرخص من Zapier، فيه scenarios معقّدة.",
      "n8n — الأقوى، open-source، تقدر تستضيفه بنفسك ببلاش. محتاج منك مجهود ووقت أكتر في الأول عشان تفهمه بس مفيش سقف للي تقدر تعمله."
    ],
    "title": "كلهم بيعملوا نفس الحاجة، بس بشكل مختلف"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "eyebrow": "شوف بنفسك",
    "src": "lessons/unique/automator-m3-l1-tools-landscape.jpg",
    "caption": "المنصة بتاعتنا فيها طبقات شغّالة 24/7 — Context، Retrieval، Memory. الـ 3 أدوات اللي بنقارنهم بيعملوا نفس الفكرة بالظبط بس على workflows بتاعتك إنت: كل scenario = طبقة بتسمع لـ trigger وبتنفّذ سلسلة actions.",
    "title": "الطبقات التشغيلية بتاعتنا"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "label": "FAILURE — بتختار الأرخص أو الأشهر",
      "body": "بتفتح Zapier لأنه شهير، وبعد شهر تكتشف إن الـ workflow بتاعك محتاج 50 task في اليوم والاشتراك بقى 80$ شهري. أو بتفتح n8n وبتقعد أسبوع تحاول تشغّله."
    },
    "title": "اختيار الأداة الصح",
    "right": {
      "label": "RIGHT — بتختار حسب الحجم والتعقيد",
      "body": "Workflow بسيط وقليل (>100 task/شهر) → Zapier. متوسط ومحتاج logic → Make. كتير ومعقّد أو محتاج تحكّم كامل → n8n. الأداة معمولة عشان تريحك، مش عشان تدوخك وراها."
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "يلا نطبق ونشوف هتختار أنهي أداة لكل سيناريو.",
    "highlight": "اختار أداة لمشروعك",
    "eyebrow": "دورك دلوقتي",
    "title": "اختار أداة لمشروعك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [273, 286, 235, 243, 223, 245, 269, 245, 340, 289, 253];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
