// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "عشان كل طلب ياخد ردّه الصح، مش كله مسار واحد.",
    "chip": "أهلًا بيك يا صاحبي",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "الأتمتة الذكية"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "أوتوميشن بيرد على رسايل الواتساب بنفس الرد",
      "عميل بيسأل عن سعر، أو بيشتكي — نفس الرد",
      "المشكلة: الـ workflow مفيهوش قرار",
      "العامل الافتراضي محتاج يعرف إمتى يكمّل أو يوقف أو يروح لمسار تاني"
    ],
    "title": "نفس الرد لكل الرسائل"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الفلتر: لو الشرط اتحقّق، البيانات تعدّي. لو لأ، الـ workflow يقف.",
      "الروتر: نفس الـ trigger، بس بيتقسم على مسارات حسب الشرط.",
      "if/then واحد يغيّر تجربة العميل لرد مناسب.",
      "ابدأ بشرط واحد واضح، مش فروع كتير."
    ],
    "title": "الفلتر بوّابة، والروتر مفترق طرق"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "مسار واحد ولا حسب الحالة؟",
    "left": {
      "label": "مسار واحد لكل حاجة",
      "body": "كل lead ياخد نفس الإيميل والنفس الرد — العميل اللي بيشتكي يحس إنك مش سامعه."
    },
    "right": {
      "label": "if/then واحد",
      "body": "لو الرسالة فيها «سعر» → ابعت قائمة أسعار. غير كده → حوّل لدعم. كل حالة ردها مناسب."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Filter (فلتر)",
    "definition": "بوّابة: الشرط اتحقّق → يعدّي. لأ → يقف.",
    "tag": "بيوقف أو يعدّي"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "بيوزّع المسار",
    "definition": "مفترق طرق: نفس الـ trigger، مسارات مختلفة حسب الشرط.",
    "term": "Router (موزّع)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "caption": "نفس الحدث (مستخدم دخل) — بس المسار بيتغيّر حسب الاختيار. نفس الفكرة في شغلك: lead جديد → مسار. شكوى → مسار تاني.",
    "src": "lessons/unique/automator-m3-l3-filters-routers.jpg",
    "eyebrow": "شوفها ببساطة",
    "title": "نفس الـ trigger — مسارات مختلفة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "شوف إيه الأنسب للموقف ده.",
    "highlight": "اختبر فهمك",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "title": "ضيف if/then واحد لـ workflow",
    "tagline": "فكر في workflow متكرر عندك وضيف عليه شرط واحد بس.",
    "highlight": "صمم شرط يغير المسار",
    "eyebrow": "مهمتك"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إن الأتمتة أذكى لما تختار المسار حسب الشرط.",
      "الفلتر بيوقف أو يمرّر، والروتر بيوزّع.",
      "عندك if/then واحد جاهز تضيفه لـ workflow حقيقي."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [577, 651, 607, 616, 508, 545, 577, 345, 639, 581];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
