// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "قبل ما تربط بحاجة حقيقية",
    "highlight": "مفاهيم",
    "subtitle": "٥ مفاهيم لازم تعرفها قبل M3. كل واحد منهم بيظهر في كل درس جاي.",
    "chip": "أهلًا"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "مفتاح صلاحية",
    "term": "Credential",
    "definition": "مفتاح أو توكن بتديه للأداة عشان تقدر تكلم خدمة تانية بدل اسمك."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "خريطة بيانات",
    "term": "Schema",
    "definition": "خريطة الجدول: أسماء الأعمدة وأنواع البيانات اللي بتدخل فيها."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "أمان الصفوف",
    "term": "RLS",
    "definition": "قواعد بتخلي كل مستخدم يشوف صفوفه هو بس في الجدول."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "سؤال ولا بلاغ",
    "term": "Endpoint vs Webhook",
    "definition": "Endpoint: إنت بتسأل الخدمة. Webhook: الخدمة بتبلغك أول ما يحصل حاجة."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "مشكلة طبيعية",
    "term": "Failure",
    "definition": "النت بيقطع، الـ API بيرجع 500، الأداة بترفض. ده طبيعي مش استثناء."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Credential — بدونه أي ربط بأي خدمة هيرفض (401).",
      "Schema — بدونه مش هتعرف تكتب أو تقرا الـ DB صح.",
      "RLS — بدونه ممكن تكتب كود يشوف بيانات مش ليه.",
      "Endpoint vs Webhook — بدونه هتختار الـ trigger الغلط وتقعد تـ poll بدل ما تستنى.",
      "Failure — بدونه أول error هيوقف الـ workflow وأنت مش عارف ليه."
    ],
    "title": "ليه المفاهيم دي مهمة قبل أي درس في M3؟"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "تخلص الدرس ده (٣-٥ دقايق)، وكل كلمة تقابلك في M3 يبقى عندك مرساة ذهنية ليها. الدروس الجاية بقت تطبيق على مفاهيم عارفها، مش مفاهيم جديدة كل ثانيتين.",
      "label": "RIGHT — تقفل الـ ٥ مفاهيم الأول"
    },
    "left": {
      "body": "تفتح أول درس عن وصل الـ DB، تلاقي كلمات Service Role Key، RLS، Connection String. كل كلمة محتاجة تسأل ChatGPT. خلصت الدرس وأنت لسه مش فاهم الفكرة الأم.",
      "label": "FAILURE — تدخل M3 مباشرة بدون أساس"
    },
    "title": "تبدأ M3 بإيه صح؟"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "٥ أسئلة",
    "tagline": "حل الـ ٥ أسئلة دول عشان تتأكد إنك فهمت كل حاجة قبل ما تكمل.",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك للمفاهيم"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [273, 463, 424, 442, 511, 485, 648, 807, 330];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
