// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "المحتوى جاب عين. هنا بنبني الجسر بين Views وشغلك.",
    "chip": "أهلًا",
    "title": "من Views لـ Leads",
    "highlight": "لـ DB"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "صفحة هدف واحد",
    "term": "Landing Page",
    "definition": "صفحة هدفها حاجة واحدة بس، زي إن الزبون يسجل بياناته."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "خانات البيانات",
    "term": "Form (النموذج)",
    "definition": "الخانات اللي الزبون بيملاها ببياناته عشان يتواصل معاك."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Database / DB (قاعدة بيانات)",
    "tag": "مخزن البيانات",
    "definition": "المخزن اللي بتشيل فيه بيانات الزبائن وتكون مترتبة ومنظمة."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "CRM",
    "tag": "متابعة العملاء",
    "definition": "برنامج ذكي بتابع عليه علاقتك بالزبون من أول ما سجل لحد ما اشترى."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "كود صغير بتزوده في آخر اللينك عشان تعرف الزبون جالك منين.",
    "tag": "تتبع المصدر",
    "term": "UTM (علامة تتبع)"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "رسول بياخد البيانات من برنامج يوديها لبرنامج تاني في لحظتها.",
    "term": "Webhook (المخبر)",
    "tag": "ناقل بيانات فوري"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "المسار الكامل: Content → Landing Page → Form → DB → Automation",
    "bullets": [
      "المحتوى بيجيب traffic.",
      "Landing Page بتخلي المشاهد ياخد خطوة فعلية واحدة (بريد/رقم/طلب).",
      "Form Submission بيروح لـ DB أو بيتبعت Webhook للـ automation tool.",
      "Automation بياخد الـ data: يرد فورًا، يصنّف، يسجّل، يبعت تنبيه."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "eyebrow": "شوف بنفسك",
    "caption": "في Creator M5 شفنا إن Views لوحدهم مش هدف — الهدف Leads. هنا هنبني الـ automation اللي بيستقبلهم: trigger = form submission → filter = validate email/phone → router = qualify by intent → actions = CRM + auto-reply + notify sales.",
    "src": "lessons/unique/automator-m6-lead-capture.jpg",
    "title": "من Views لـ Leads"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "كل lead بيتسجّل فورًا في DB بتاعته UTM tagged. الـ automation بيرد على طول بإيميل/رسالة ترحيب. فريق المبيعات بيشوف في الـ CRM تاريخ كل lead ومصدره. مفيش نسخ ولا لصق.",
      "label": "RIGHT — Form → webhook → automation → CRM"
    },
    "title": "Form بيتبعت لـ email وخلاص vs Form بيدخل system",
    "left": {
      "body": "كل lead بيوصلك إيميل. إنت بتفتح وتنسخ الـ data وتلصّقها في Excel. لو نزل 50 lead في يوم، بتقعد تنسخ وتلصّق لغاية ما تنام. فريق المبيعات بيدوخوا ويسألوا 'الـ leads منين؟'.",
      "label": "FAILURE — تستنّى الـ form تيجي في الإيميل"
    }
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "DB trigger handle_new_user() بيتنفّذ تلقائي.",
      "بينشئ profile + user_streaks في same transaction.",
      "Redirect لـ /onboarding بدل صفحة فاضية."
    ],
    "title": "Signup form → user record → onboarding flow"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "highlight": "Lead Capture Flow",
    "eyebrow": "دورك دلوقتي",
    "title": "اعمل Lead Capture Flow",
    "tagline": "يلا بينا نختبر فهمك ونشوف هتعمل إيه. وماتنساش تستعد للدرس الجاي عن WhatsApp Flow ذكي!"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [378, 309, 336, 349, 345, 316, 397, 693, 545, 589, 510, 430];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
