// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "كل automation",
    "subtitle": "وبتخلص بـ Action أو أكتر.",
    "highlight": "بتبدأ بـ Trigger",
    "chip": "Triggers + Actions"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "بيانات الرسالة",
    "term": "Payload / JSON",
    "definition": "دي البيانات اللي بتتنقل بين البرامج، زي علبة بيانات كده."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Input / Output",
    "definition": "الـ Input هو اللي بتدخله، والـ Output هو النتيجة اللي بتطلع.",
    "tag": "مدخلات ومخرجات"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Database / DB",
    "definition": "المكان اللي بتخزن فيه بيانات شغلك بشكل منظم ومحمي.",
    "tag": "تخزين بيانات"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "API / HTTP Request",
    "definition": "الطريقة اللي البرامج بتكلم بيها بعض وتطلب بيانات.",
    "tag": "تواصل برامج"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "سؤال متكرر",
    "term": "Polling",
    "definition": "الأداة بتسأل الموقع \"فيه جديد؟\" كل فترة معينة."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "إشعار فوري",
    "term": "Webhook",
    "definition": "الخدمة بتبعت البيانات للأداة \"فورا\" أول ما حاجة تحصل."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Trigger & Action",
    "definition": "الـ Trigger هو الشرارة اللي بتبدأ الشغل، والـ Action هو التنفيذ.",
    "tag": "شرارة وتنفيذ"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "حاجة بتحصل (Trigger) → خطوة أو أكتر بتتنفّذ كرد فعل (Actions).",
      "Triggers أنواع: Schedule، Webhook، Polling، Manual.",
      "Actions أنواع: HTTP request، إضافة صف في DB، إرسال إيميل/رسالة، استدعاء AI، تحويل بيانات."
    ],
    "title": "كل workflow هيكلها بسيط"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "كل action بياخد output الـ action اللي قبله كـ input. فالـ workflow عاملة زي السير اللي ماشي ورا بعضه."
    ],
    "title": "كل workflow هيكلها بسيط"
  },
  {
    "card": "ScreenshotCard",
    "accent": "pink",
    "src": "lessons/unique/automator-m3-l2-triggers-actions.jpg",
    "eyebrow": "شوف بنفسك",
    "caption": "كل خطوة في صفحة /dashboard دي عبارة عن Trigger → Action. المستخدم خلّص درس (Trigger) → سجّل تقدّمه في الـ DB.",
    "title": "رحلة المستخدم في المنصة"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mintDeep",
    "caption": "فتحله الدرس اللي بعده + بعتله notification (3 Actions). نفس الفكرة هتطبّقها على شغلك.",
    "title": "رحلة المستخدم في المنصة",
    "src": "lessons/unique/automator-m3-l2-triggers-actions.jpg",
    "eyebrow": "شوف بنفسك"
  },
  {
    "card": "CompareCard",
    "accent": "mint",
    "left": {
      "body": "بتخلّي الـ workflow يسأل كل دقيقة 'في رسالة جديدة؟'. بتاكل tasks كتير، وبتدفع فلوس على مشاوير على الفاضي، والـ response بيتأخّر دقيقة كاملة.",
      "label": "FAILURE — Polling لكل حاجة"
    },
    "right": {
      "label": "RIGHT — Webhook لما يكون متاح",
      "body": "بتخلّي الخدمة (WhatsApp، Stripe، Typeform) تبعتلك فورًا لما حاجة تحصل. سرعة فورية، tasks أقل بكتير، تكلفة أقل."
    },
    "title": "Polling vs Webhook"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "title": "Polling vs Webhook",
    "right": {
      "label": "RIGHT — Webhook لما يكون متاح",
      "body": "بتخلّي الخدمة (WhatsApp، Stripe، Typeform) تبعتلك فورًا لما حاجة تحصل. سرعة فورية، tasks أقل بكتير، تكلفة أقل."
    },
    "left": {
      "body": "بتخلّي الـ workflow يسأل كل دقيقة 'في رسالة جديدة؟'. بتاكل tasks كتير، وبتدفع فلوس على مشاوير على الفاضي، والـ response بيتأخّر دقيقة كاملة.",
      "label": "FAILURE — Polling لكل حاجة"
    }
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "ابني أول scenario",
    "eyebrow": "دورك دلوقتي",
    "tagline": "يلا بينا نطبق اللي اتعلمناه ونشوف فهمنا إيه في الكويز ده.",
    "title": "ابني أول scenario في 5 دقائق"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "Trigger: lesson_completed → DB function تتولّى الباقي.",
      "Actions متسلسلة: update streak → schedule review → award badge."
    ],
    "title": "كل learner_event = Trigger في المنصة"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "كله شغّال بـ Postgres functions و triggers."
    ],
    "title": "كل learner_event = Trigger في المنصة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [432, 413, 316, 371, 352, 354, 361, 408, 473, 347, 403, 423, 376, 427, 393, 391, 417];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
