// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "مش رفاهية تقنية.",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "الاختبار بيمنع أخطاء محرجة في الأتمتة"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "شغّلت Workflow جديد على التشغيل الحقيقي من غير اختبار. الرسالة فيها «مرحبًا undefined» — ل٣٠٠ عميل.",
      "العميل فكر إنكم روبوت مش بتحترموه. الثقة راحت في ساعة.",
      "دقيقة اختبار قبل الـ live كانت هتكشف إن حقل الاسم فاضي — مش رفاهية، حماية لسمعتك."
    ],
    "title": "«الأوتوميشن بعت «undefined» لكل العملاء»"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "اختبار خطوة واحدة (Unit test): لو الاسم فاضي، إيه اللي يحصل؟",
      "اختبار المسار كامل (Integration test): شغّل الـ Flow ببيانات تجريبية — مش بيانات عملاء حقيقيين.",
      "حالات غريبة (Edge cases): فاضي، غلط، مكرر — ٣ حالات على الأقل قبل التشغيل الحقيقي.",
      "مراجعة يدوية (Manual review): حد يشوف النتيجة بعينه قبل ما تفتح على الكل — آخر بوابة.",
      "الاختبار بيحمي الثقة — مش بس الكود."
    ],
    "title": "٤ مستويات اختبار — من خطوة لـ flow كامل"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "طلّع live من غير اختبار vs checklist",
    "left": {
      "body": "شغّلت على production — أول خطأ بيوصل لـ ٣٠٠ عميل. اعتذار + ثقة ضايعة.",
      "label": "«نجرب على العملاء»"
    },
    "right": {
      "body": "بيانات تجريبية → ٣ edge cases → مراجعة يدوية → بعدها production. الخطأ يفضل عندك.",
      "label": "Checklist قبل live"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Unit Test (اختبار خطوة)",
    "tag": "اختبار جزء",
    "definition": "تختبر جزء واحد — node أو شرط — من غير الـ flow كله."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "اختبار flow كامل",
    "definition": "تشغّل الـ Workflow (خطوات ماشية ورا بعض بشكل تلقائي) كامل من أوله لآخره ببيانات وهمية.",
    "term": "Integration Test (اختبار التدفق)"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "Testing Checklist",
    "bullets": [
      "Unit → Full flow → Edge cases → Manual review → Live. استخدم الرسم في المهمة."
    ]
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "شوف إجابتك الصح عشان تطبّق اللي اتعلمته.",
    "title": "سؤال واحد — مش امتحان",
    "highlight": "إيه أحسن خطوة قبل production؟",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "اختار أوتوميشن عندك واكتب خطة اختبار كاملة.",
    "eyebrow": "مهمتك",
    "tagline": "ابني خطة اختبار خطوة بخطوة عشان تحمي شغلك.",
    "title": "اعمل test checklist لأوتوميشن واحد"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "تقدر تعمل test checklist جاهز لأي أوتوميشن قبل الـ live. نتقابل في الدرس الجاي.",
    "title": "إيه اللي عندك دلوقتي؟",
    "highlight": "فهمت إن الاختبار بيحمي ثقة العملاء — unit، flow كامل، edge cases، ومراجعة يدوية.",
    "eyebrow": "خلّصت الاختبار"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [383, 510, 568, 489, 345, 349, 432, 364, 453, 305];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
