// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الأوتوميشن بيخليها منتظمة ومش معتمدة على ذاكرتك.",
    "chip": "أهلًا - بداية الدرس",
    "highlight": "المتابعة",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Lead سجّل واستلم رد ترحيب. قلت «هكلمه بكرة». بكرة في شغل تاني. الأسبوع عدى.",
      "العميل فتح إيميل من حد تاني. الصفقة راحت — مش عشان المنتج وحش، عشان المتابعة وقفت.",
      "المشكلة مش نقص اهتمام منك — المشكلة مفيش نظام يكمل المحادثة لو إنت مش فاضي."
    ],
    "title": "ردّيت مرة — وسكتّوا الاتنين"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Follow-up مش رسالة واحدة — تسلسل: يوم ٠ ترحيب، يوم ٢ تذكير، يوم ٥ سؤال واحد.",
      "كل خطوة لها هدف مختلف — مش نفس «تفتكر العرض؟» كل يومين.",
      "الأوتوميشن يوقف لو العميل رد، أو يحوّل لبشري لو بقى مهتم.",
      "المتابعة المنتظمة = فرص أكتر — من غير إزعاج."
    ],
    "title": "تسلسل متابعة = خطوات بوقت وسلوك"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "label": "تسلسل أوتوماتيك",
      "body": "يوم ٠: ترحيب + مورد. يوم ٢: تذكير لطيف. يوم ٥: سؤال واحد. رد؟ يوقف ويحوّل لبشري."
    },
    "title": "متابعة عشوائية vs تسلسل منتظم",
    "left": {
      "label": "حسب المزاج",
      "body": "«هكلمه لما أفضى». ساعات ترد، ساعات تنسى. العميل مش عارف إنت مهتم ولا لأ."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "خطوات رسائل مترتبة بوقت — كل واحدة هدفها مختلف.",
    "tag": "مترتبة بوقت",
    "term": "Follow-up Sequence (تسلسل متابعة)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "إمتى التسلسل يقف — العميل رد، طلب إلغاء، أو اشتري.",
    "tag": "إمتى يقف التسلسل",
    "term": "Stop Condition (شرط التوقف)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/unique/automator-m6-l3-follow-up.jpg",
    "caption": "كل touchpoint هدفه مختلف — مش تكرار نفس الرسالة. الوقت + المحتوى + شرط التوقف.",
    "eyebrow": "لقطة بصرية",
    "title": "جدول المتابعة على ٣ خطوات"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "highlight": "اختبر فهمك",
    "title": "سؤال واحد — مش امتحان",
    "tagline": "حل السؤال عشان تتأكد إنك فهمت كويس.",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "المتابعة بتضيع فيها المبيعات، والأوتوميشن بيخليها منتظمة. شوفك في الدرس الجاي!",
    "eyebrow": "لخص اللي فات",
    "highlight": "وفر وقتك ومبيعاتك",
    "title": "المتابعة أهم حاجة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [637, 747, 796, 723, 376, 465, 486, 401, 445];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
