// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الـ LLM ممكن يبقى node في الـ flow بتاعك.",
    "highlight": "مش لازم تفتح ChatGPT بإيدك.",
    "title": "أهلًا بيك يا صاحبي",
    "chip": "LLM جوه الـ Workflow"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "لو خلصت Builder M1، إنت عارف الـ LLM بياخد نص ويرد بنص. نفس الفكرة هنا بالظبط.",
      "الفرق: في Builder بتستدعيه من كود، هنا من node جوّه n8n/Make. نفس الـ API ورا الكواليس.",
      "لو لسه مكملتش Builder: الـ LLM = AI بتبعتله نص وبيرجعلك نص. ركّز إزاي تستخدمه في الـ flow."
    ],
    "title": "نفس الفكرة، تطبيق مختلف"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "خطوة واحدة جوه سير العمل بتعمل مهمة معينة ومحددة.",
    "tag": "مهمة محددة",
    "term": "Node (خطوة)"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "System Prompt",
    "tag": "أوامر أساسية",
    "definition": "الأوامر الأساسية اللي بتعرف الموديل هو شغال إيه وشخصيته إيه."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "هيكل أو تقسيمة فاضية بتحدد للموديل ينظم بياناته إزاي بالظبط.",
    "tag": "هيكل بيانات",
    "term": "Schema (فورمة)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "JSON Mode / Structured Output",
    "tag": "رد منظم",
    "definition": "طريقة تخلي الموديل يرد بشكل منظم تفهمه البرامج التانية مش كلام رغي."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "وحدة قياس الكلام اللي الموديل بيعالجه، وعليها بتتحسب التكلفة.",
    "tag": "وحدة قياس",
    "term": "Token Cost (التكلفة)"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "في n8n/Make/Zapier فيه nodes جاهزة لـ OpenAI و Anthropic و Gemini.",
      "بتدّيه: system prompt + user message + parameters (temperature، model).",
      "بيرجّعلك: text أو JSON تقدر تستخدمه في الـ step اللي بعده.",
      "أمثلة: تصنيف رسالة، تلخيص مكالمة، استخراج اسم وtelephone، ترجمة، صياغة رد."
    ],
    "title": "الـ LLM بقى زي أي API"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "caption": "المساعد ده عبارة عن LLM node + سياق المتعلم + system prompt محدّد. الـ flow ورا الكواليس فيه نفس الـ nodes اللي هتبنيها في Make/n8n. الفكرة واحدة، بس بتطبّقها على شغلك.",
    "src": "lessons/unique/automator-m4-llm-in-flow.jpg",
    "eyebrow": "شوف بنفسك",
    "title": "مساعد المنصة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "بتقوله: 'رد بـ JSON: { \"type\": \"complaint|inquiry|followup\", \"urgent\": true|false }'. الـ step اللي بعده بياخد الـ JSON على طول ويعمل Route حسب النوع.",
      "label": "RIGHT — JSON محدّد"
    },
    "title": "Free-text vs Structured Output",
    "left": {
      "label": "FAILURE — بترجّع نص حر",
      "body": "بتقول للـ LLM 'صنّف الرسالة دي'. بيرد بفقرة فيها التصنيف وسطها. الـ step اللي بعده مش عارف يقراها، فبتقعد تكتب regex وتتعصّب."
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّ الأسئلة دي عشان تثبت فهمك",
    "highlight": "يلا نطبق اللي اتعلمناه",
    "title": "أول LLM node"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [355, 963, 460, 442, 509, 523, 466, 1033, 613, 761, 327];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
