// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "= نظام",
    "subtitle": "Inputs → Processes → Outputs. لو شفته كده، تقدر تأتمته.",
    "title": "أي شغل بتعمله",
    "chip": "أهلًا"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "System",
    "definition": "مجموعة خطوات ثابتة بتعملها عشان تخلص شغلك وتطلع نتيجة مضمونة.",
    "tag": "خطوات ثابتة"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Input",
    "definition": "أي حاجة بتدخلها للسيستم عشان يبدأ يشتغل.",
    "tag": "مدخلات السيستم"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Process",
    "definition": "الخطوات اللي بتحصل جوه السيستم عشان تحول المدخلات لنتائج.",
    "tag": "الخطوات الفعلية"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Output",
    "definition": "النتيجة النهائية اللي بتطلع من السيستم بعد ما يخلص شغله.",
    "tag": "النتيجة النهائية"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "زبون محتمل",
    "term": "Leads",
    "definition": "الزبون المحتمل اللي لسه بيسأل ومشتراش منك بشكل رسمي."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "CRM",
    "definition": "أي مكان بتجمع فيه بيانات الزباين وتاريخ كلامك معاهم.",
    "tag": "إدارة العملاء"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الـ Inputs: البيانات اللي بتدخل زي Lead form أو رسالة واتساب.",
      "الـ Processes: الخطوات اللي بتتعمل عليها زي Validate وتصنيف.",
      "الـ Outputs: اللي بيطلع في الآخر زي رد أو صف في داتابيز.",
      "مثال: الرد على واتساب = Input (سؤال العميل) → Process (تفهم وتدوّر) → Output (رد وإضافة لـ CRM)."
    ],
    "title": "الـ 3 طبقات"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "caption": "دي صفحة /operational-layers بتاعتنا. المنصة نفسها مبنية كـ system: كل طبقة عندها Input محدّد، Process معروف، وOutput بيتغذّى للطبقة اللي بعدها. ده اللي هتعمله مع شغلك إنت — تكسره لطبقات وتشوف الـ Inputs/Outputs بين كل واحدة.",
    "src": "lessons/unique/automator-m2-systems-view.jpg",
    "eyebrow": "شوف بنفسك",
    "title": "صفحة /operational-layers"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "«أنا عندي نظام رد على الرسائل بيشتغل كده». لما تشوفه نظام، تقدر تحسّنه، تأتمته، أو تسلّمه لحد تاني. الـ tasks بتختفي، النظام بيفضل.",
      "label": "RIGHT — بتفكّر في Systems"
    },
    "left": {
      "body": "«أنا محتاج أرد على الرسالة دي». «محتاج أنزل بوست النهارده». كل حاجة منفصلة، وكل يوم بتبدأ من الصفر. مفيش حاجة بتتراكم.",
      "label": "FAILURE — بتفكّر في Tasks"
    },
    "title": "Tasks vs Systems"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "يلا نطبق اللي اتعلمناه ونشوف إزاي تحوّل مهامك لأنظمة.",
    "title": "حوّل 3 tasks",
    "highlight": "لـ 3 systems",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [381, 439, 336, 367, 333, 353, 315, 1111, 517, 946, 300];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
