// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "إزاي تتجنب تكرار الكود وتبني واجهات منظمة",
    "highlight": "سباجيتي؟",
    "chip": "المشكلة",
    "title": "ليه الكود بتاعك بيتحول لـ "
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "src": "lessons/builder-m6-l16-components-routes.jpg",
    "caption": "الصفحة دي تبان معقدة، بس هي في الحقيقة تكرار لـ ٣-٤ قوالب بسيطة. دي فكرة الـ Components.",
    "title": "بص على أي موقع كبير بعين الـ Developer",
    "eyebrow": "جرّب دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الـ Component قطعة ليجو: زرار، كارت منتج، قايمة جانبية.",
      "تصمم \"قالب الكارت\" مرة واحدة بس."
    ],
    "title": "السر كله: قالب + بيانات = Component"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "الـ Props: بيانات مختلفة لنفس القالب",
    "bullets": [
      "الـ Props هي البيانات اللي بتبعتها للقالب.",
      "قالب `ProductCard` بيعرض منتجات مختلفة بـ `title` و `price`."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "الـ Route vs الـ Component",
    "bullets": [
      "الـ Route: الصفحة الكاملة اللي ليها عنوان في الـ browser (مثال: `/products`).",
      "الـ Component: قطعة جوه الصفحة دي (مثال: `ProductCard` أو `Sidebar`).",
      "الصفحة (الـ Route) هي component كبير بيجمع components أصغر."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "قاعدة مهمة: كل component يعمل حاجة واحدة بس",
    "bullets": [
      "كل component المفروض يعمل حاجة واحدة بس.",
      "لو Component فيه كود كتير، قسمه لقطع أصغر.",
      "ده بيخلي الكود سهل يتفهم ويتصلح."
    ]
  },
  {
    "card": "CompareCard",
    "accent": "mint",
    "right": {
      "label": "صح — قاعدة الـ 3 مرات",
      "body": "أول مرة: اكتب الكود عادي. تاني مرة: ممكن copy-paste. تالت مرة: طلع الكود في Component منفصل واستخدمه في الـ 3 أماكن. كده الكود نضيف ومنظم."
    },
    "left": {
      "body": "هعمل كارت في المنتجات، وكارت شبهه في العروض، وتالت في الداش بورد. النتيجة: 3 نسخ من نفس الكود. أي تغيير لازم يتعمل في الـ 3 أماكن، ولو نسيت واحد، الموقع شكله هيبوظ.",
      "label": "غلط — كل حاجة من الأول"
    },
    "title": "امتى تعمل Component وامتى لأ؟"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "highlight": "حل الـ Quiz ده",
    "eyebrow": "دورك دلوقتي",
    "tagline": "اكتشف إزاي تفكر زي الـ Component Developer",
    "title": "مخك بيفكر كـ Component Developer؟"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "حلل فكرة تطبيقك وطلع خريطة للـ Routes والـ Components.",
      "ارسم شخبطة سريعة للصفحة الرئيسية.",
      "طلع قايمة بالـ Components المتكررة والـ Props اللي محتاجاها.",
      "فكر لو فيه component محتاج \"ذاكرة\" داخلية (state)."
    ],
    "title": "ارسم خريطة الـ Components لتطبيقك"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "صفحة المناهج مبنية بنفس الطريقة",
    "bullets": [
      "صفحة /curriculum فيها route رئيسي وكل مسار (Builder, Creator) هو route ابن.",
      "الـ Component بتاع `LessonLink` مشترك في كل المسارات.",
      "أي تغيير في تصميم `LessonLink` بيظهر فورًا في كل مكان."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [797, 729, 532, 637, 583, 526, 1092, 304, 729, 647];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
