// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "المحادثة كانت في ذاكرة مؤقتة (RAM) واتمسحت!",
    "highlight": "والعميل قفل الـ tab",
    "title": "الـ AI بتاعك جاوب",
    "chip": "الذاكرة الخاينة"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "caption": "كل رقم وعلامة صح (✓) شايفها في حسابك مش متخزنة على جهازك. دي عايشة في مخزن ذكي (Database) مركزي. لو فتحت من الموبايل هتلاقي نفس الأرقام. بالظبط زي ما تطبيقك هيحفظ كل سؤال العميل بيسأله للـ AI وكل إجابة بياخدها.",
    "title": "شايف تقدمك ده؟",
    "src": "lessons/builder-m5-l4-database-intro.jpg",
    "eyebrow": "جرّب دلوقتي"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "المخزن الذكي (Database)",
    "tag": "أرشيف بيانات التطبيق",
    "definition": "الأرشيف اللي بنشيّل فيه كل حاجة مهمة في التطبيق بتاعنا، من بيانات العملاء لحد محادثاتهم مع الـ AI."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "شيت بيانات جوه المخزن",
    "term": "الجدول (Table)",
    "definition": "هو المكان اللي بنرص فيه البيانات جوه المخزن. تخيله بالظبط زي شيت إكسيل منظم."
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "body": "لو المعلومة دي لازم العميل يلاقيها بكرة أو على جهاز تاني، يبقى مكانها المخزن الذكي. محادثات الـ AI، ملفات العميل، الاشتراكات... كل ده لازم يعيش في مكان دائم وآمن.",
      "label": "صح: أي بيانات مهمة مكانها المخزن الذكي"
    },
    "left": {
      "body": "البيانات هتضيع لو فتح من جهاز تاني، أو مسح الـ cache. ده مكان للتفضيلات المؤقتة بس، زي الـ Dark Mode.",
      "label": "غلط: أخزّن في المتصفح (localStorage)"
    },
    "title": "تخزّن فين؟ في ذاكرة المتصفح ولا في المخزن الذكي؟"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "highlight": "بياناتك في أمان",
    "eyebrow": "ملخص",
    "tagline": "إحنا كده فهمنا أهمية الـ Database. شوفك في الدرس الجاي!",
    "title": "المخزن الذكي: أساس أي تطبيق"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [759, 489, 316, 245, 648, 335];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
