// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "Database: المكان اللي البيانات بتعيش فيه فعلاً",
    "highlight": "البيانات بتعيش فيه فعلاً",
    "chip": "HERO",
    "subtitle": "الـ Frontend بيعرض. الـ Backend بيشتغل. طب البيانات نفسها بتتخزّن فين؟"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "خريطة البيانات",
    "term": "Schema",
    "definition": "خريطة أو \"رسمة\" بتحدد شكل الجداول والبيانات هتمشي إزاي."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "كود مميز لكل سطر، مستحيل يتكرر عشان نعرف نوصل للبيان.",
    "tag": "كود فريد",
    "term": "Primary Key"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "مفتاح بيوصل جدول بجدول تاني عشان نربط البيانات ببعض.",
    "tag": "ربط الجداول",
    "term": "Foreign Key"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "يعني الخانة مسموح تكون \"فاضية\" مش مكتوب فيها أي حاجة.",
    "tag": "خانة فاضية",
    "term": "Nullability / Null"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "SQL",
    "tag": "لغة الأوامر",
    "definition": "لغة بسيطة بنطلب بيها من قاعدة البيانات تنفذ أوامر معينة."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "جدول بيانات",
    "term": "Table",
    "definition": "مكان جوه قاعدة البيانات بنرص فيه البيانات في جداول منظمة."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "🛑 وقفة مهمة قبل ما تكمّل — اقراها مرة واحدة وانساها:",
      "الكود ده **مش مطلوب منك تحفظه ولا تكتبه ولا حتى تفهمه سطر سطر**.",
      "وجوده هنا زي ما الدكتور بيريك أشعة عشان تطمن — مش عشان تشخّص بنفسك.",
      "Lovable هي اللي بتكتب الكود ده لك. شغلك إنك تفهم **الفكرة** اللي تحت الكود، مش الـ syntax.",
      "لو الكود رعبك — تخطّاه واقرا الشرح اللي حواليه. هتلاقي نفس المعنى بكلام بشري."
    ],
    "title": "الكود في الدروس الجاية مرجع — مش امتحان"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Database برنامج متخصّص في تخزين بيانات منظّمة بشكل دائم.",
      "بيدير ملايين السطور، بيحمي البيانات لو السيرفر وقع، وبيسمح لكذا مستخدم يقروا/يكتبوا في نفس الوقت.",
      "أشهر نوع هو Relational Database (PostgreSQL، MySQL). البيانات بتتحط في Tables.",
      "كل جدول له Columns (أعمدة بنوع محدّد) و Rows (سطور = سجلات فعلية).",
      "بتكلّمه بلغة اسمها SQL: SELECT (هات)، INSERT (ضيف)، UPDATE (عدّل)، DELETE (امسح).",
      "الـ Backend هو اللي بيكتب الـ SQL — مش الـ Frontend.",
      "نقطة أمان حرجة: مين له حق يقرأ/يكتب إيه؟ ده اسمه Row Level Security."
    ],
    "title": "Database = جدول منظّم بيتقرا بـ SQL"
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "eyebrow": "من المنصة",
    "caption": "كل رقم شايفه على الشاشة دي مش mockup — جاي من Database حقيقي. \"مرحبًا، صديقي\" جاي من جدول profiles (column: display_name). \"4 / 0\" يعني فيه 4 دروس متاحة و0 مكتملة (جدول lesson_completions، WHERE user_id = me). \"0 يوم — السلسلة\" نتيجة query بيحسب الفرق بين تواريخ آخر دروس مكتملة. شريط التقدم \"0/12\" في Builder = COUNT من جدول lessons WHERE module IN builder. لو فتحت الصفحة من جهاز تاني هتلاقي نفس الأرقام بالظبط — لأنها مش متخزّنة في الـ Frontend، متخزّنة في الـ Database.",
    "title": "Case Study — كل رقم في اللوحة جاي من Database",
    "src": "lessons/builder-m5-database-intro.jpg"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "title": "غلطة المبتدئ: تخزّن البيانات في المكان الغلط",
    "left": {
      "label": "FAILURE — تخزّن في الـ Frontend (localStorage / state)",
      "body": "\"خلاص هحفظ تقدّم المستخدم في localStorage بتاع المتصفح.\" المشكلة: لو فتح من جهاز تاني → التقدم اختفى. لو مسح cache → اختفى. لو غيّر متصفح → اختفى. مفيش backup، مفيش analytics، مفيش حماية. localStorage مكانه بيانات مؤقتة فقط (مثلاً تفضيل الـ theme)."
    },
    "right": {
      "label": "RIGHT — أي بيانات لازم تعيش = Database",
      "body": "أي حاجة المفروض المستخدم يلاقيها بكرة، أو على جهاز تاني، أو إنت كصاحب التطبيق محتاج تشوفها → Database. التقدم، الرسائل، الإعدادات، الاشتراكات. القاعدة: \"هل لو السيرفر اتقفل وفتح تاني، البيانات دي لازم تكون لسه موجودة؟\" لو الإجابة آه → Database."
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "دورك دلوقتي",
    "highlight": "الـ Schema وأساسيات الجداول",
    "tagline": "جاوب على الأسئلة عشان تتأكد إنك فهمت أساسيات الـ Database.",
    "title": "اختبر فهمك للـ Database"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [595, 469, 396, 413, 391, 387, 342, 557, 845, 606, 609, 377];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
