// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "بيألّف إجابات؟",
    "chip": "نقطة بتلخبط الكل",
    "title": "ليه الـ AI ساعات بيألّف إجابات؟",
    "subtitle": "الـ AI مش بيعرف، هو بيخمّن."
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "بتستغله في الحاجات اللي هو شاطر فيها (كتابة، تلخيص، ترجمة، كود)، وبتديله انت السياق والمصادر عشان يطلّع ردود دقيقة. التأكد من المعلومة دي شغلتك انت، مش شغلته هو.",
      "label": "صح: بتتعامل معاه كأنه 'مساعد لغوي'"
    },
    "title": "إزاي تفكر فيه صح",
    "left": {
      "body": "بتفترض إن إجاباته حقايق أكيدة ومتحدثة. الحقيقة: هو اتدرب على داتا قديمة، وممكن بمنتهى الثقة يألّف معلومة مش موجودة.",
      "label": "غلط: بتتعامل معاه كأنه Google"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "توقع كلام",
    "term": "بيخمّن، مش بيعرف",
    "definition": "بيتوقع الكلمة اللي جاية بناءً على الداتا اللي اتدرب عليها. مش بيبحث عن إجابة."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "ده المصطلح التقني لما الـ AI يخترع معلومة بثقة. عشان كده لازم تراجع أي أرقام أو تواريخ أو أسماء بيقولها.",
    "term": "ممكن يهلوس (Hallucinate)",
    "tag": "اختراع معلومة"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "برامج AI",
    "term": "ChatGPT / Claude / Gemini",
    "definition": "دي أشهر برامج بتستخدم الموديلات دي. زي ما فيه عربيات تويوتا وهيونداي وكيا، كلهم بيوصلوك."
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "دورك دلوقتي",
    "highlight": "اختبر فهمك",
    "title": "سؤال سريع",
    "tagline": "جاوب على السؤال عشان تتأكد إنك فهمت الدرس."
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "title": "إزاي بنستخدمه في المنصة؟",
    "src": "lessons/builder-m1-l1-what-is-llm.jpg",
    "eyebrow": "مثال من شغلنا",
    "caption": "مساعد المنصة اللي بتستخدمه ده مثال حيّ. هو مش متبرمج بإجابات جاهزة. ده عبارة عن LLM (زي اللي بنشرحه) بياخد سؤالك مع السياق بتاعك (انت في أنهي درس) ويخمّن أنسب رد. عشان كده بيقدر يساعدك في أي حاجة، حتى لو محدش سألها قبل كده."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Large (ضخم): اتدرب على داتا بحجم الإنترنت تقريبًا.",
      "Language (لغوي): متخصص في فهم وتوليد الكلام البشري.",
      "Model (نموذج إحصائي): بيحسب احتمالية الكلمة اللي جاية."
    ],
    "title": "يعني إيه 'LLM'؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [514, 495, 435, 496, 450, 325, 403, 510];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
