// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "Wireframe",
    "subtitle": "رسمة كروكي قبل البناء بتمنع اللخبطة."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "«ابنيلي واجهة» — ويطلع أي كلام",
    "bullets": [
      "بتطلب من AI يبنيلك واجهة — ويطلعلك حاجة عامة مش اللي في دماغك.",
      "تعدّل ٥ مرات. كل مرة تخمين جديد. ٣ ساعات ضاعت.",
      "المشكلة: ما رسمتش الخريطة الأول. AI بيخمّن — إنت اللي لازم توضّح."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Wireframe = مربعات + أسماء — من غير ألوان ولا صور.",
      "هدفه يجاوب: إيه في أول الشاشة؟ فين الزرار الرئيسي؟ إيه ترتيب الأقسام؟",
      "ورقة وقلم في ١٠ دقايق > ٣ ساعات تعديل على واجهة غلط.",
      "لما توصف Wireframe لـ AI — النتيجة قريبة من دماغك من أول مرة."
    ],
    "title": "الرسمة الكروكي بتمنع اللخبطة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "label": "من غير Wireframe",
      "body": "«ابنيلي واجهة AI وصفات» — AI يخمّن. ٥ محاولات. لسه مش مظبوط."
    },
    "right": {
      "label": "مع Wireframe",
      "body": "«هيدر + مربع نص + زرار «اقترح» + ٣ كروت وصفات» — AI يبني اللي وصفته. أقرب من أول مرة."
    },
    "title": "«ابنيلي واجهة» vs «عندي ٧ بوكسات»"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Wireframe",
    "tag": "هيكل الشاشة",
    "definition": "رسم كروكي — بوكسات بأسامي، من غير تصميم."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "أهم زرار — اللي العميل المفروض يدوس عليه.",
    "term": "CTA (Call to Action)",
    "tag": "زرار رئيسي"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/unique/builder-m6-l2-wireframe.jpg",
    "caption": "مربعات + أسماء. «هيدر»، «مربع نص»، «زرار»، «٣ كروت». ده اللغة اللي AI يفهمها.",
    "eyebrow": "شوفها ببساطة",
    "title": "بوكسات — مش ألوان"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "جاوب على سؤال سريع عشان تتأكد إنك فهمت.",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "eyebrow": "خلّصت البداية",
    "title": "إيه اللي عندك دلوقتي؟",
    "tagline": "الـ Wireframe بيمنع اللخبطة، ومجهّزك لأول prompt مع الـ AI. نتقابل في الدرس الجاي.",
    "highlight": "جاهز لأول prompt"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [706, 733, 862, 786, 529, 541, 521, 316, 670];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
