// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "كتير بنشوف أفكار تطبيقات ذكاء اصطناعي عظيمة، لكن بنقف محتارين قدام صفحة فاضية. هل أفتح برنامج تصميم؟ أختار الـ AI model؟ أكتب prompt؟",
    "title": "عندك فكرة AI جامدة...",
    "chip": "البداية",
    "highlight": "بس تبدأ منين؟"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "title": "الغلطة اللي بتضيّع وقتك",
    "left": {
      "body": "تفتح Figma وتصمم شكل الشات وأيقونة طيارة. عندك تصميم حلو، بس مش عارف: العميل هيكتب إيه؟ الـ AI هيسأل على إيه؟ هتضطر تعيد كل ده تاني.",
      "label": "الغلط: تبدأ بشكل الواجهة"
    },
    "right": {
      "body": "العميل عايز يخطط لرحلة: يفتح التطبيق ← يكتب للـ AI ← الـ AI يسأله ← العميل يرد ← الـ AI يعرض خطة متكاملة. الخريطة دي هي الأساس.",
      "label": "الصح: تبدأ برحلة العميل مع الـ AI"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "User Flow",
    "definition": "الخريطة أو الخطوات اللي العميل بيمشيها عشان يوصل لهدفه من الـ AI بتاعك.",
    "tag": "خريطة العميل"
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "eyebrow": "شوف بنفسك",
    "src": "lessons/builder-m6-l13-idea-to-page.jpg",
    "caption": "الصفحة دي مثال حي. هدفها واحد بس: تخليك تعرف كل اللي هتتعلمه وتختار هتبدأ منين. مفيش أي حاجة تشتتك. الـ User Flow بتاعها بسيط: المستخدم يدخل ← يشوف الخريطة كلها ← يضغط على أول درس. بس كده.",
    "title": "إزاي ده بيترجم لواجهة حقيقية؟"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "اختار فكرة تطبيق AI، واكتب الـ User Flow بتاعها في ٣ خطوات بسيطة وواضحة، زي ما شرحنا.",
    "title": "حوّل فكرة الـ AI بتاعتك لخريطة",
    "highlight": "لخريطة",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "أي تطبيق AI هو مجموعة شاشات العميل بيتفاعل معاها.",
      "قبل ما تفكر في شكل الشاشة، فكر في رحلة العميل (User Flow).",
      "كل خطوة في الرحلة دي بتترجم لشاشة، وبكده عندك خريطة واضحة."
    ],
    "title": "الشاشة = خطوة في حوار العميل مع الـ AI"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "صفحة /image-gallery اتبنت بنفس الطريقة دي.",
      "الفكرة: مكان واحد لكل صور الـ AI بتاعتي.",
      "الرحلة (User Flow): يفتح الصفحة ← يلاقي صوره مترتبة ← يضغط على صورة يكبرها.",
      "التنفيذ: شاشة تطلب من الـ Backend صور المستخدم ده بس."
    ],
    "title": "كل ده مش كلام نظري"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "اختبر فهمك لرحلة المستخدم وإزاي تحولها لشاشات تطبيق AI.",
    "title": "سؤال وجواب سريع",
    "highlight": "فهمك",
    "eyebrow": "اختبر فهمك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [460, 474, 457, 568, 477, 479, 409, 400];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
