// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "مش بيضمن الحقيقة.",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "autocomplete ذكي"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "سألت ChatGPT أو Gemini سؤال، وردّ عليك بثقة بمعلومة — وبعد ساعة لقيتها مش صح.",
      "بتحس إنه «بيعرف» — بس الحقيقة إنه بيكمل الكلام الأنسب زي autocomplete متطوّر.",
      "لما تبني منتج فيه AI، المستخدم هيعتمد على الردود. لو إنت مش فاهم الفرق، هتبني ميزة بتضلّل الناس من غير ما تقصد."
    ],
    "title": "ردّ بثقة — وبعدها تكتشف إنه غلط"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "تشبيه بسيط: LLM (نموذج لغوي كبير) = autocomplete ذكي على مستوى جمل كاملة. بيتوقّع الكلام الأنسب — مش بيبحث في Google.",
      "لما يردّ بثقة، ده مش دليل إنه «فاهم» — ده دليل إن الجملة شكلها منطقي.",
      "في Builder: أي مساعد في منتجك هيشتغل بنفس المنطق. التحقّق من الحقائق مسؤوليتك — مش الموديل.",
      "استخدمه في الكتابة والتلخيص والأفكار. راجع أي أرقام أو تواريخ قبل ما تعرضها للمستخدم."
    ],
    "title": "بيخمّن الكلام الأنسب — مش بيتحقّق من الحقيقة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "بتستغله في الحاجات اللي هو شاطر فيها، وبتديّه سياق ومصادر. وبتضيف خطوة تحقّق للحقائق — زي ما أي منتج محترم بيعمل.",
      "label": "صح: بتتعامل معاه كمساعد لغوي"
    },
    "title": "Google vs مساعد لغوي",
    "left": {
      "body": "بتفترض إن كل إجابة حقيقة. لما تبني ميزة «اسأل أي حاجة» من غير تحذير أو تحقّق، المستخدم هيتصدم لما يلاقي معلومة مختلقة.",
      "label": "غلط: بتتعامل معاه كأنه Google"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "مفهوم أساسي",
    "term": "LLM (نموذج لغوي كبير)",
    "definition": "autocomplete ذكي للجمل — بيتوقّع الكلام الأنسب، مش بيبحث في قاعدة بيانات."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Hallucination (هلوسة)",
    "definition": "لما الـ AI يخترع معلومة بثقة — جملة شكلها صح بس المحتوى غلط.",
    "tag": "مصطلح مهم"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "caption": "المساعد مش متبرمج بإجابات جاهزة. بياخد سؤالك + السياق (إنت في أنهي درس) ويخمّن أنسب رد. عشان كده يقدر يساعد في أسئلة جديدة — وعشان كده لازم تتحقّق من أي حقيقة قبل ما تعتمد عليها في منتجك.",
    "title": "مساعد AI — سؤال وسياق ورد",
    "src": "lessons/builder-m1-l1-what-is-llm.jpg",
    "eyebrow": "شوفها ببساطة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "title": "سؤال واحد بس",
    "tagline": "شوف إزاي الـ AI بيشتغل بنفسك.",
    "highlight": "مش امتحان",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "إيه اللي عندك دلوقتي؟",
    "bullets": [
      "فهمت إيه؟ LLM = autocomplete ذكي — مش ضمان للحقيقة. Builder Level 3 اختياري.",
      "تقدر تعمل إيه؟ تستخدمه للكتابة والأفكار، وتتحقّق من الحقائق قبل ما تعرضها.",
      "نتقابل في الدرس الجاي."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [492, 592, 603, 579, 474, 467, 445, 293, 385];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
