// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "إزاي؟",
    "chip": "نقلة جديدة",
    "subtitle": "لحد دلوقتي، كل اللي عملناه كان مجرد \"كلام\" مع الـ AI. بس الأبلكيشن الحقيقي أكبر من مجرد شات. فيه زراير، فيه صفحات، فيه مكان تحفظ فيه بياناتك وتدخل باليوزر نيم والباسورد. إزاي تحوّل \"شات ذكي\" لأبلكيشن كامل الناس تستخدمه؟ ده اللي هنعرفه في الـ 5 دروس الجايين.",
    "title": "الـ AI ذكي، بس مش أبلكيشن."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Frontend (الواجهة)",
    "definition": "الوش بتاع الأبلكيشن. كل حاجة عينك شايفاها وصباعك بيدوس عليها.",
    "tag": "الوش اللي بتشوفه"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "المطبخ اللي بيطبخ",
    "term": "Backend (الكواليس)",
    "definition": "المطبخ أو العقل اللي بيفكر وبينفذ الأوامر اللي مبتتشفش."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Database (المخزن)",
    "definition": "الأرشيف اللي بنشيّل فيه كل حاجة (بيانات المستخدمين، المنتجات، الرسايل) عشان نرجع لها بعدين.",
    "tag": "الأرشيف اللي بيخزن"
  },
  {
    "card": "ScreenshotCard",
    "accent": "pink",
    "title": "الجسر اللي بين الكلام والبناء",
    "src": "lessons/unique/builder-m5-l9-transition.jpg",
    "caption": "إنت دلوقتي واقف على الجسر ده. خلصت مرحلة إزاي \"تكلّم\" الـ AI، وداخل على مرحلة إزاي \"تبني\" له بيت يعيش فيه.",
    "eyebrow": "شوف بنفسك"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "المنصة اللي إنت عليها دي معمولة بنفس الطريقة",
    "bullets": [
      "الـ Frontend: شكل الصفحة دي والزراير اللي فيها.",
      "الـ Backend: الكود اللي بيسجّل تقدمك لما بتخلص الدرس.",
      "الـ Database: المكان اللي متخزّن فيه إنت خلصت كام درس."
    ]
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "highlight": "جرّب دلوقتي",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّل أبلكيشن بتستخدمه كل يوم عشان تفهم مكوناته الأساسية.",
    "title": "حلّل أبلكيشن بتستخدمه كل يوم"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [586, 498, 421, 503, 426, 442, 360];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
