// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "بيفهم أرقام",
    "title": "الـ AI مش بيفهم كلامك",
    "chip": "المشكلة",
    "subtitle": "إزاي نخلي البحث يفهم المعنى؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الداتابيز بتقارن أرقام ونصوص حرفية",
      "مبتعرفش تفهم إيه اللي 'شبه' إيه",
      "الـ Embeddings هي الحل للبحث الذكي"
    ],
    "title": "الداتابيز مبتفهمش المعنى"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "eyebrow": "جرّب تشوف المعنى بعينك",
    "title": "إزاي الكلام بيتحوّل لخريطة معاني",
    "src": "lessons/concepts/embeddings-diagram.jpg",
    "caption": "من نص لـ Vector لخريطة معاني"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Embedding (تمثيل رقمي للمعنى)",
    "tag": "إحداثيات المعنى",
    "definition": "عملية تحويل أي حاجة (كلام، صور، صوت) لـ vector (قايمة أرقام طويلة)، عشان الـ AI يقدر يقيس المعنى والتشابه رياضيًا."
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "الخريطة بتحوّل مكان لإحداثيات (خط طول وعرض)",
      "الـ Embedding بيحوّل كلمة لـ 1536 رقم",
      "الأرقام دي بتوصف معنى الكلمة من كل الزوايا"
    ],
    "title": "الـ Embedding زي الخريطة"
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "title": "البحث بالكلمة vs. البحث بالمعنى",
    "right": {
      "label": "صح — البحث بالـ Embedding",
      "body": "بيحوّل سؤالك لـ embedding، ويجيب أقرب دروس في المعنى. بحث ذكي."
    },
    "left": {
      "label": "غلط — البحث بـ ILIKE",
      "body": "بيدور على الجملة حرفيًا بس. غالبًا النتيجة صفر. بحث غبي."
    }
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّ الأسئلة عشان تعرف تطبّق الـ Embeddings صح.",
    "highlight": "اختبر فهمك",
    "title": "إيه أهم حاجة تحوّلها لـ Embedding؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [300, 535, 513, 413, 472, 529, 385];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
