// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "ترسم واجهة تطبيقك",
    "chip": "بعد الدرس ده هتقدر",
    "subtitle": "خريطة واجهة أي AI app في 10 دقايق.",
    "highlight": "في دقايق"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كأنك بتبني بيت من غير رسم هندسي.",
      "الرسمة الكروكي دي بتوفر عليك ساعات تعديلات."
    ],
    "title": "الـ AI بتاعك عبقري، بس الواجهة بتاعته بتطفّش الناس؟"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "src": "lessons/unique/builder-m6-l14-wireframe.jpg",
    "caption": "دي خريطة واجهة التطبيق (Wireframe). مجرد بوكسات بتقول للـ AI: 'حط هنا كذا وهنا كذا'. دي اللغة اللي الـ AI بيفهمها عشان يبنيلك واجهة مظبوطة من أول مرة.",
    "eyebrow": "جرّب الحل ده",
    "title": "الخريطة اللي بتنقذ مشروعك في دقايق"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "مفيش ألوان أو خطوط شكلها حلو أو صور.",
      "مجرد مربعات ومستطيلات مكتوب جواها: «هيدر»، «صورة رئيسية»، «زرار»."
    ],
    "title": "بوكسات وكلام، مش تصميم وألوان"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "إيه اللي العميل هيشوفه أول ما يفتح التطبيق؟",
      "فين أهم زرار المفروض يدوس عليه؟",
      "إيه ترتيب الأقسام في الصفحة؟"
    ],
    "title": "الـ Wireframe بيجاوب على أسئلة مهمة"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "واجهة التطبيق (Frontend)",
    "definition": "الوش اللي العميل بيشوفه وبيكلم منه الـ AI بتاعك.",
    "tag": "الوش اللي بيشوفه العميل"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "رسم كروكي بسيط بـ \"بوكسات\" بيحدد أماكن كل حاجة في واجهة التطبيق قبل ما تتكتب كود.",
    "tag": "خريطة الواجهة بالبوكسات",
    "term": "Wireframe"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "left": {
      "body": "من غير رسمة، الـ AI بيخمّن. هيطلعلك حاجة عامة، فهترجع تطلب تعديل، وهتضيع ساعات كتير.",
      "label": "غلط: تطلب من الـ AI 'ابنيلي واجهة'"
    },
    "right": {
      "body": "ورقة وقلم في 20 دقيقة هيطلعولك wireframe فيه 7 بوكسات بأساميهم. الـ AI هيطلعلك حاجة قريبة قوي من اللي في دماغك من أول مرة.",
      "label": "صح: ترسم الخريطة الأول، بعدين توصفها للـ AI"
    },
    "title": "إزاي تبني واجهة الـ AI بتاعك صح"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "في اختبار سريع",
    "tagline": "شوف إزاي تقدر تحدد المشاكل وتحلها صح في الـ Wireframe.",
    "eyebrow": "دورك دلوقتي",
    "title": "طبّق اللي فهمته"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [226, 303, 346, 323, 358, 289, 316, 298, 258];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
