// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "هتكتب طلب تعديل جراحي واحد — محدد ومضمون النتيجة.",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "تعديل واحد كل مرة"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الـ AI بنالك واجهة، بس الألوان مش ماشية والزرار مش في مكانه.",
      "أول رد فعل: «همسح كل ده وأبدأ من الأول».",
      "بس ده أبطأ طريق. كل واجهة محترفة بتاخد ٤–٧ لفات تحسين.",
      "السر: تطلب تعديل واحد محدد كل مرة — وتشوف النتيجة قبل ما تطلب التاني."
    ],
    "title": "الواجهة شكلها وحش — تمسح كل حاجة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Iteration Loop = ٤ خطوات: اطلب → شوف النتيجة → راجع → عدّل.",
      "كل لفة بتقربك للشكل المطلوب.",
      "Surgical Edit = تعديل جراحي: «خلي زرار الإرسال برتقالي #FF6B35 — متغيّرش أي حاجة تانية.»",
      "لو طلبت تعديلات كتير، الـ AI بيخمن وممكن يبوظ حاجة كانت شغالة (Regression)."
    ],
    "title": "تعديل واحد كل مرة — لفة التحسين"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "«غيّرها» vs تعديل جراحي",
    "right": {
      "label": "صح — تعديل واحد محدد",
      "body": "«في صفحة الشات، خلي لون زرار «ابعت» برتقالي #FF6B35 والكلام جواه أبيض. متغيّرش أي حاجة تانية.» تعديل محدد = نتيجة مضمونة."
    },
    "left": {
      "label": "غلط — «الواجهة شكلها وحش»",
      "body": "الـ AI مش فاهم يعني إيه «وحش». هيخمن ويغيّر حاجات عشوائية — وممكن يبوّظ حاجة شغالة. بعد ساعة الواجهة أسوأ من الأول."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "زي الترزي: مقاسات → تعديل → مقاسات تاني لحد ما البدلة تبقى مظبوطة.",
    "term": "Iteration (لفة التحسين)",
    "definition": "تجربة → ملاحظة → تصليح → تجربة تاني — لحد ما توصل للهدف."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "عدّلت حجم الخط في الشات — وفجأة الـ Header اتلغبط.",
    "term": "Regression (تراجع)",
    "definition": "لما تصلّح حاجة فتبوّظ حاجة تانية كانت شغالة كويس."
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "caption": "اطلب → شوف النتيجة → راجع → عدّل. متستعجلش — أي واجهة محترفة بتاخد لفات. كل لفة = تعديل واحد بس.",
    "eyebrow": "شوفها ببساطة",
    "src": "lessons/unique/builder-m6-l5-iteration.jpg",
    "title": "٤ خطوات — وكل لفة تقرّبك"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "title": "سؤال واحد — مش امتحان",
    "tagline": "اكتب طلب تعديل جراحي آمن — نتقابل في الدرس الجاي.",
    "highlight": "طبّق اللي فهمته",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [664, 690, 858, 943, 647, 547, 517, 420];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
