// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "بس الواجهة بتاعته بتطفّش الناس؟",
    "title": "الـ AI بتاعك عبقري،",
    "subtitle": "لما الـ AI بتاعك يبقى جاهز، أكبر غلطة ممكن تعملها هي إنك تبدأ تبني الواجهة بتاعته على طول من غير تخطيط. كأنك بتبني بيت من غير رسم هندسي.",
    "chip": "نقطة الألم"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "src": "lessons/unique/builder-m6-l14-wireframe.jpg",
    "eyebrow": "جرّب الحل ده",
    "caption": "دي خريطة واجهة التطبيق (Wireframe). مجرد بوكسات بتقول للـ AI: 'حط هنا كذا وهنا كذا'. دي اللغة اللي الـ AI بيفهمها عشان يبنيلك واجهة مظبوطة من أول مرة.",
    "title": "الخريطة اللي بتنقذ مشروعك في دقايق"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "بوكسات وكلام، مش تصميم وألوان",
    "bullets": [
      "الـ Wireframe مش تصميم: مفيش ألوان، خطوط حلوة، ولا صور.",
      "مجرد مربعات ومستطيلات مكتوب جواها: «هيدر»، «صورة رئيسية»، «زرار»، «3 كروت»."
    ]
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "الواجهة الخارجية",
    "term": "واجهة التطبيق (Frontend)",
    "definition": "الوش اللي العميل بيشوفه وبيكلم منه الـ AI بتاعك. زي واجهة المحل أو الديكور."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Wireframe",
    "definition": "رسم كروكي بسيط بـ \"بوكسات\" بيحدد أماكن كل حاجة في واجهة التطبيق قبل ما تتكتب كود.",
    "tag": "رسم كروكي"
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "left": {
      "body": "من غير رسمة، الـ AI بيخمّن. هيطلعلك حاجة عامة، فهترجع تطلب تعديل، وهتضيّع وقت كتير.",
      "label": "غلط: تطلب من الـ AI 'ابنيلي واجهة'"
    },
    "right": {
      "body": "ورقة وقلم في 20 دقيقة هيطلعولك wireframe واضح. الـ AI هيطلعلك حاجة قريبة قوي من اللي في دماغك من أول مرة.",
      "label": "صح: ترسم الخريطة الأول، بعدين توصفها للـ AI"
    },
    "title": "إزاي تبني واجهة الـ AI بتاعك صح"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "جاوب على الأسئلة عشان تتأكد إنك فهمت الدرس كويس.",
    "highlight": "اختبر معلوماتك",
    "title": "طبّق اللي فهمته",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "كل صفحة هنا كانت مجرد Wireframe",
    "bullets": [
      "الجزء اللي بتتعلم فيه ده اتبنى بنفس الطريقة.",
      "بنرسم Wireframe بسيط على ورقة قبل أي شاشة.",
      "ده بيساعد المعلومة توصلك بسهولة.",
      "الرسمة بتاخد دقايق، تعديل الكود بياخد ساعات.",
      "كل صفحة جديدة كان ليها رسمة كروكي قبل التنفيذ.",
      "افتح /system-state وشوف بنفسك الـ layout."
    ]
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "title": "جاهز للدرس الجاي؟",
    "tagline": "نتقابل في الدرس الجاي عشان نكمل رحلتنا.",
    "highlight": "شوفك هناك!",
    "eyebrow": "يلا بينا"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [491, 497, 715, 407, 340, 685, 227, 811, 205];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
