// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "في M8.1 صمّمت جدول واحد بشكل صح. بس التطبيق الحقيقي = جداول كتير مربوطة ببعض.",
    "title": "كل جدول مربوط بحاجة تانية",
    "highlight": "مربوط بحاجة تانية",
    "chip": "البيانات مش بتعيش لوحدها"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "لما تربط غلط... إيه اللي بيحصل؟",
    "bullets": [
      "لو ربطت غلط، البيانات هتتكرر كتير.",
      "الـ queries هتكون بطيئة قوي.",
      "هتعدّل حاجة تكسر حاجة تانية."
    ]
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "اللغة أو الأوامر اللي بنكتبها عشان نكلم قاعدة البيانات.",
    "term": "SQL",
    "tag": "لغة قاعدة البيانات"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Foreign Key (FK)",
    "definition": "عمود في جدول بنسجل فيه ID جاي من جدول تاني عشان نربطهم.",
    "tag": "ربط الجداول"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "طريقة بتخلي قاعدة البيانات تلاقي المعلومة بسرعة من غير ما تدور في كله.",
    "term": "Index (فهرس)",
    "tag": "تسريع البحث"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تغيير متزامن",
    "definition": "خاصية بتخلي أي تغيير أو مسح في جدول يسمّع لوحده في الباقي.",
    "term": "Cascade"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "ربط Many-to-Many",
    "term": "Junction Table (الوسيط)",
    "definition": "جدول وسيط بنعمله عشان نربط حاجتين ببعض ليهم علاقة \"Many-to-Many\"."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "كود فريد",
    "definition": "كود طويل ومعقد بيستخدم كـ ID فريد عشان البيانات متدخلش في بعض.",
    "term": "UUID (الكود الفريد)"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "تجميع بيانات",
    "definition": "أمر بنستخدمه عشان نجمع بيانات من جدولين أو أكتر ونطلعهم مع بعض.",
    "term": "Join (الربط)"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "One-to-One (1:1)",
      "One-to-Many (1:N)",
      "Many-to-Many (N:M)"
    ],
    "title": "٣ أنواع علاقات أساسية"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "سطر في جدول A بيقابله سطر واحد في جدول B.",
      "مثال: user ↔ profile.",
      "بنستخدمها لتقسيم بيانات حساسة عن بيانات عامة."
    ],
    "title": "1) One-to-One (1:1)"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "2) One-to-Many (1:N)",
    "bullets": [
      "سطر في A بيقابله كذا سطر في B.",
      "ده النوع الأكتر شيوعًا.",
      "مثال: user → tasks.",
      "الـ FK بيتحط في الجدول 'الكتير'."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "3) Many-to-Many (N:M)",
    "bullets": [
      "سطر في A بيقابله كذا سطر في B والعكس.",
      "مثال: tasks ↔ tags.",
      "مفيش FK مباشر — لازم جدول وسيط (junction table)."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "قاعدة الـ ON DELETE",
    "bullets": [
      "Cascade: يتمسح معاه.",
      "Set Null: يبقى null.",
      "Restrict: ارفض المسح.",
      "لكل نوع استخداماته حسب البيانات."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "title": "Foreign Keys: إزاي الجداول بتتربط ببعض",
    "caption": "الـ diagram ده بيوضّح علاقة جدولين أو أكتر. كل جدول له primary key (id فريد لكل سطر)، والـ foreign key في جدول تاني (زي posts.user_id) بيشاور على الـ id بتاع السطر المرتبط.",
    "src": "lessons/concepts/relations-diagram.jpg",
    "eyebrow": "توضيح بصري"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "الـ JOIN والـ Cascade",
    "bullets": [
      "الـ JOIN بيجيب بيانات مرتبطة ببعض.",
      "لو مسحت user، كل الـ posts والـ comments بتاعته تتمسح تلقائي.",
      "ده بيمنع وجود 'سطور يتيمة' ملهاش صاحب."
    ]
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "label": "RIGHT — جداول منفصلة + FKs + junction للـ N:M",
      "body": "users(id, email, name)، tasks(id, user_id references users(id) on delete cascade, title)، tags(id, name unique)، task_tags(task_id, tag_id, PK مركّب). دلوقتي: تغيير اسم المستخدم = سطر واحد. كل tasks اللي عليها tag 'urgent' = JOIN سريع باستخدام index على tag_id. مسح user = مسح كل tasks بتاعته تلقائيًا (cascade). البيانات مش بتتكرر، والـ DB بيضمن التماسك."
    },
    "title": "تكرار البيانات vs ربطها صح",
    "left": {
      "label": "FAILURE — كل حاجة في جدول واحد",
      "body": "جدول tasks(id, user_email, user_name, user_avatar, title, tags). كل task بتعيد إيميل واسم المستخدم. وحقل tags = 'urgent,work,personal' كنص. النتيجة: مستحيل تـ filter بـ tag، ومستحيل تعرف كل الـ tasks اللي عليها tag معيّن. أي تعديل في tag واحد = تحديث آلاف السطور."
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّ الأسئلة عشان تتأكد إنك فهمت كل حاجة.",
    "highlight": "اختبر فهمك للـ Relations",
    "title": "ارسم Relations الـ schema بتاعك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [316, 499, 299, 300, 257, 299, 298, 303, 316, 315, 315, 378, 396, 391, 405, 437, 384, 426];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
