// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أهلًا، بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "subtitle": "من غير «ساعي بريد» بين الواجهة والكواليس — مفيش تطبيق يشتغل.",
    "highlight": "الـ API بتوصّل اللي العميل يشوفه بالشغل اللي بيحصل ورا."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الزرار شغّال، الشاشة بتحمّل، بس الرد مش بيوصل أو بيطلع خطأ.",
      "الواجهة أخدت كلامك ودوس إرسال، بس مفيش حد يربطها بالكواليس.",
      "الـ API عامل زي الجرسون، بينقل الطلب من الترابيزة للمطبخ ويرجّع الأكل."
    ],
    "title": "بتدوس «إرسال» — ومفيش حاجة بتحصل"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "العميل بيكتب في الواجهة ويدوس زرار، ده اللي بيشوفه.",
      "الكواليس بتستقبل الطلب، تكلّم AI، وترجّع الرد، ده اللي مش بيشوفه.",
      "الـ API هي اللغة اللي بتنقل الطلب والرد بين الاتنين.",
      "كل زرار في تطبيقك بيساوي طلب API واحد على الأقل."
    ],
    "title": "الـ API بتوصّل اللي ظاهر بالشغل المخفي"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "العميل بيطلب، الجرسون بياخد الطلب، المطبخ بيطبخ، والجرسون بيرجع الأكل. كل خطوة مربوطة.",
      "label": "مع API"
    },
    "left": {
      "body": "العميل بيكتب على المنيو بس مفيش حد يوصل الطلب للمطبخ. المنيو حلو بس مفيش أكل.",
      "label": "من غير API"
    },
    "title": "منيو بدون جرسون vs مطعم شغّال"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "مخ التطبيق",
    "term": "Backend (الكواليس)",
    "definition": "المكان اللي التطبيق بيفكّر فيه، بيستقبل، يكلّم AI، ويرجّع."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "اللغة اللي بتنقل الطلبات والردود بين الواجهة والكواليس.",
    "tag": "لغة التواصل",
    "term": "API (ساعي البريد)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "caption": "أول ما تكتب رسالة وتدوس إرسال: الواجهة تبعت طلب → الكواليس تكلّم AI → الرد يرجع على الشاشة. ده مسار API.",
    "src": "lessons/builder-m5-l3-backend-api.jpg",
    "eyebrow": "شوفها ببساطة",
    "title": "زرار → طلب → رد"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "جاوب على السؤال ده عشان تتأكد إنك فهمت.",
    "highlight": "أنهي مكون مسؤول عن إنه يكلّم الـ AI؟",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [552, 671, 732, 604, 529, 553, 376, 521];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
