// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "RAG محتاج بحث بالمعنى — مش بالحروف.",
    "chip": "أهلًا",
    "highlight": "الـ Embedding (تحويل الكلام لأرقام تمثّل المعنى) يلاقي المعنى — مش الكلمة الحرفية.",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "البحث التقليدي بيدور على الكلمات حرفيًا. «يرد» مش مكتوبة في المقال — رغم إن المقال بيشرح الموضوع!",
      "المخزن شاطر في مقارنة نصوص — بس مش بيفهم إن «يرد» و«يجاوب» و«يولّد رد» نفس الفكرة.",
      "عشان RAG (AI يجاوب من ملفاتك بدل ما يخمّن) يشتغل صح، محتاج بحث بالمعنى — مش بالحروف."
    ],
    "title": "العميل كتب «إزاي الـ AI بيرد؟» — ومفيش نتائج"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Embedding (تحويل الكلام لأرقام تمثّل المعنى) = تحوّل أي نص لقايمة أرقام بتمثّل «مكانه على خريطة المعاني».",
      "الجمل اللي معناها قريب — الأرقام بتاعتها قريبة. «قطة بتلعب» و«كلب بيجري» أقرب من «البورصة».",
      "لما العميل يسأل، بنحوّل سؤاله لـ Vector (طريقة تخزين المعنى بشكل رقمي) وندوّر على أقرب Chunks (أجزاء صغيرة من المحتوى) — حتى لو الكلمات مختلفة."
    ],
    "title": "Embeddings تلاقي المعنى — مش الكلمات"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "«إزاي الـ AI بيرد؟» — مفيش match حرفي. العميل يحس إن مفيش محتوى — رغم إن عندك دروس عن tokens والـ context.",
      "label": "غلط — بحث بالكلمة"
    },
    "right": {
      "body": "السؤال يتحوّل لـ Vector (طريقة تخزين المعنى بشكل رقمي) — يلاقي Chunks (أجزاء صغيرة من المحتوى) عن «توليد الرد». نفس المعنى، كلمات مختلفة.",
      "label": "صح — embedding"
    },
    "title": "بحث حرفي vs بحث بالمعنى"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "تحوّل النص لـ Vector — أرقام بتوصف المعنى على «خريطة».",
    "term": "Embedding (تحويل الكلام لأرقام تمثّل المعنى)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "البحث عن أقرب Vectors (طريقة تخزين المعنى بشكل رقمي) للسؤال — مش match حرفي.",
    "term": "Vector Search (بحث بالمعنى)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "title": "من نص لـ vector لخريطة",
    "src": "lessons/concepts/embeddings-diagram.jpg",
    "eyebrow": "شوفها ببساطة",
    "caption": "كل جملة ليها «مكان» على الخريطة. المعنى القريب = نقاط قريبة. المعنى البعيد = حتة تانية خالص."
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "title": "سؤال واحد — مش امتحان",
    "tagline": "كل ما السياق أغنى، الـ embedding يفهم «خفيف وسريع» أحسن — يلا نطبّق!",
    "highlight": "مدونة وصفات — العميل بيدور «أكل خفيف وسريع». إيه أحسن حاجة تعملها embedding؟",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ Embeddings = بحث بالمعنى — مش بالكلمة الحرفية.",
      "تقدر تعمل إيه؟ عندك سؤالين باختبار — نفس القصد، كلمات مختلفة.",
      "نتقابل في الدرس الجاي!"
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [306, 71, 365, 408, 490, 462, 391, 505, 390];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
