// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "غلطة في تصميم الجدول بتدفع تمنها",
    "subtitle": "تخيل تطبيقك بعد 6 شهور من الـ launch... شغال تمام، وفجأة كل حاجة بتبطأ وبقت بتضرب أخطاء غريبة. السبب؟ غالبًا قرار غلط خدته في ثانيتين وانت بتعمل أول جدول في المشروع. كلمة زي `text` بدل `numeric` ممكن توقّع سيستم كامل لما الداتا تكبر.",
    "highlight": "شهور",
    "chip": "أهلًا في البداية"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "كل عمود له نوعه المظبوط: `title text not null` (مينفعش يبقى فاضي)، `price numeric` (عشان الفلوس)، `is_published boolean` (عشان أه/لأ)، `created_at timestamptz` (عشان تعرف كل حاجة اتعملت امتى). كده السيستم نفسه بيحميك من الداتا الغلط.",
      "label": "تصميم يستحمل ملايين المستخدمين"
    },
    "left": {
      "body": "كله `text` وخلاص: `name text`, `price text`, `items text`. كل حاجة ممكن تبقى فاضية (nullable) عشان \"يمكن نحتاج\". النتيجة؟ لو حبيت تجيب أغلى منتج، السيستم هيتلخبط بين سعر '100.00' و '99.5' ومش هيعرف يرتبهم صح. كارثة.",
      "label": "تصميم هيقع بعد شهرين"
    },
    "title": "اختيار واحد بيفرق بين مشروع ناجح ومشروع فاشل"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "eyebrow": "مثال حي",
    "src": "lessons/builder-m7-l19-tables-columns.jpg",
    "caption": "بص على صفحة الـ System State دي. كل كارت (زي `currentPath` أو `currentUser`) هو بالظبط column في جدول، والقيمة اللي تحته هي الداتا اللي في الصف بتاعك. التصميم اللي بيحدد شكل الجدول ده هو اللي بنسميه الـ Schema.",
    "title": "كل صفحة بتشوفها أصلها جدول"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "زي ما بتقول: جدول 'المنتجات' فيه عامود 'السعر' وده لازم يكون رقم عشري ومينفعش يبقى فاضي.",
    "term": "Schema",
    "definition": "الرسم الهندسي أو الخريطة اللي بتوصف كل جدول في السيستم: عواميده إيه، نوع البيانات في كل عامود، وإيه القواعد اللي بتحكمه."
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "highlight": "طبّق",
    "eyebrow": "دورك دلوقتي",
    "tagline": "يلا بينا نختبر فهمك ونشوف إزاي بتصمم جداول صح.",
    "title": "طبّق اللي اتعلمته"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "ده schema لجدول 'products' في سيستم e-commerce، بس مليان غلطات هتعمل مشاكل بعدين.",
      "مهمتك تصلحه.",
      "فكّر في أنواع البيانات الصح.",
      "إيه الخانات اللي مينفعش تبقى فاضية (not null).",
      "إيه الأعمدة الأساسية اللي ناقصة عشان الجدول يبقى production-ready (زي الـ id)."
    ],
    "title": "صلّح الـ Schema المضروب ده"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "الـ `user_id` مع الـ `lesson_id` بيعملوا مع بعض مفتاح فريد (unique constraint) عشان نضمن إنك متسجلش نفس الدرس مرتين.",
      "عامود الـ `status` نوعه متحدد (enum) عشان يقبل قيم معينة بس: 'not-started', 'in-progress', 'completed'.",
      "بدأنا بـ 4 عواميد بس، وزوّدنا اتنين لما احتجناهم. ابدأ بسيط وكبّر لما تحتاج، مش العكس."
    ],
    "title": "جدول lesson_progress = أبسط مثال تطبيقي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [665, 969, 558, 731, 222, 646, 1128];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
