// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أكبر كارثة في تطبيقات الـ AI",
    "subtitle": "ركز عشان ده أهم درس ممكن تتعلمه في الـ AI.",
    "title": "لو مفتاح الـ AI اتسرق،",
    "highlight": "هتدفع آلاف"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "left": {
      "body": "لو حطيت مفتاح الـ AI في الـ Frontend، أي يوزر يقدر يشوفه ويسرقه ويستخدمه على حسابك. هتصحي تلاقي فاتورة بآلاف الدولارات!",
      "label": "الغلطة القاتلة"
    },
    "right": {
      "body": "الحل إن كل طلب للـ AI يعدّي على الـ Backend الأول. الـ Backend معاه المفتاح السرّي، يكلم الـ AI ويرجع الرد للـ Frontend من غير ما يكشفه.",
      "label": "الحل الصح"
    },
    "title": "حل الكارثة دي بسيط"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "حل السؤال ده عشان تشوف بنفسك إزاي الـ API بتشتغل في الكواليس!",
    "eyebrow": "دورك دلوقتي",
    "title": "شوف الـ API وهي شغالة",
    "highlight": "إزاي الـ API بتشتغل؟"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "تخيل إنك في مطعم.",
      "الترابيزة، المنيو، الديكور... ده هو الـ Frontend.",
      "دي الواجهة اللي بتتعامل معاها."
    ],
    "title": "الـ Backend هو المطبخ، والـ API هو الجرسون"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "المطبخ اللي بيجهز الأكل ومحدش غريب بيدخله... ده الـ Backend.",
      "بيستخدم مكونات سرّية.",
      "طب إزاي طلبك بيوصل من الترابيزة للمطبخ؟"
    ],
    "title": "الـ Backend هو المطبخ، والـ API هو الجرسون"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "عن طريق الجرسون! الجرسون ده هو الـ API.",
      "هو الوسيط اللي بياخد طلبك ويرجعلك الأكل الجاهز.",
      "من غير ما تحتاج تعرف إيه اللي حصل في المطبخ."
    ],
    "title": "الـ Backend هو المطبخ، والـ API هو الجرسون"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "وسيط التواصل",
    "term": "API",
    "definition": "العقد أو الوسيط اللي بيسمح لجزئين في السيستم (زي الـ Frontend والـ Backend) يكلموا بعض بطريقة منظمة ومفهومة."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "في Lovable، مش محتاج تعمل مشروع Backend منفصل.",
      "الموضوع أبسط من كده بكتير.",
      "بتكتب function عادية، بس بتحط قبلها كلمة معينة."
    ],
    "title": "الـ Backend بتاعك هو مجرد Function"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الـ Frontend بينادي الـ function دي كأنها عادية.",
      "المنصة بتحوّلها لـ API request كامل يروح للـ Backend.",
      "مفتاح الـ AI بتاعك بتحطه في الـ server function، كده بيفضل في أمان."
    ],
    "title": "الـ Backend بتاعك هو مجرد Function"
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "src": "lessons/builder-m5-l11-backend-api.jpg",
    "eyebrow": "مثال حي من المنصة",
    "title": "مساعد Lovable بيكلم الـ Backend",
    "caption": "الصفحة دي مثال حي. أول ما بتفتحها، الـ Frontend بيبعت طلب للـ Backend عشان يعرف إنت مين وفي أنهي درس (ده طلب GET). ولما بتكتب رسالة وتدوس \"إرسال\"، بيبعت طلب تاني فيه رسالتك (ده طلب POST)."
  },
  {
    "card": "ScreenshotCard",
    "accent": "pink",
    "src": "lessons/builder-m5-l11-backend-api.jpg",
    "eyebrow": "مثال حي من المنصة",
    "title": "مساعد Lovable بيكلم الـ Backend",
    "caption": "الـ Backend ياخد الرسالة، يكلم الـ AI بالمفتاح السرّي، ويرجعلك الرد. كل ده والـ Frontend مش شايف أي مفاتيح."
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "في جملة واحدة، جاوب: إيه أهم طلب الـ Frontend هيطلبه من الـ Backend عشان فكرتك تشتغل؟",
    "eyebrow": "مهمتك دلوقتي",
    "title": "صمّم أهم API لتطبيقك",
    "highlight": "كل تطبيق له طلب أساسي واحد هو قلبه."
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [295, 435, 275, 277, 316, 316, 327, 346, 411, 333, 343, 421];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
