// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "هتفهم إيه النهاردة؟",
    "subtitle": "Goal + Users + Pages + Style + Constraints.",
    "chip": "بداية الدرس",
    "highlight": "أول prompt محتاج ٥ أجزاء بس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كتبت «ابنيلي واجهة AI» — طلع ألوان فاقعة وأقسام مش عايزها.",
      "Lovable بيبني اللي بتكتبه حرفيًا — مش اللي بتتمناه. ٣ كلمات = تخمين كامل.",
      "الحل آمن وبسيط: اكتب وصفة ٥ أجزاء — انسخها في Lovable وجرّب."
    ],
    "title": "«اعملي واجهة» — ويطلع مش اللي في بالك"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Goal: نوع الواجهة وهدفها.",
      "Users: مين هيستخدمها.",
      "Pages: أقسام الـ Wireframe.",
      "Style: الألوان والنبرة والمود.",
      "Constraints: إيه اللي مش عايزينه."
    ],
    "title": "أول prompt = ٥ أجزاء أساسية"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "label": "Prompt Spec",
      "body": "Goal: landing page لكافيه + AI باريستا. Users: زباين ٢٠–٣٥. Pages: hero + منيو ٦ مشروبات + تواصل. Style: دافي، بنّي وبيج. Constraints: من غير login."
    },
    "title": "«ابني واجهة» vs Prompt Spec",
    "left": {
      "body": "«ابنيلي واجهة كافيه» — AI يخمّن كل حاجة. ٦ تعديلات. لسه مش مظبوط.",
      "label": "٣ كلمات"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "وصفة كاملة",
    "term": "Prompt Spec (مواصفات الواجهة)",
    "definition": "الوصفة الكاملة — goal, users, pages, style, constraints."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "إيه اللي في النسخة دي — وإيه اللي بعدين.",
    "tag": "النسخة الحالية",
    "term": "Scope (النطاق)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/unique/builder-m6-l3-first-prompt-to-lovable.jpg",
    "title": "Prompt → Preview",
    "caption": "الـ prompt مش «اعملي واجهة» — فيه goal، نشاط، أقسام بالاسم، وستايل. النتيجة أقرب من أول مرة.",
    "eyebrow": "شوفها ببساطة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "شارك في السؤال عشان تتأكد إنك فهمت كويس.",
    "title": "اختبر فهمك",
    "highlight": "اختار أحسن جزء في الـ Prompt Spec",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [420, 591, 511, 540, 360, 387, 454, 406];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
