// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "قبل أي كود.",
    "chip": "أهلًا | بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "أي فكرة AI تقدر تتبني كشاشات + خطوات"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "عندك فكرة AI عظيمة — بس لما تفتح أداة البناء، مش عارف أول خطوة إيه.",
      "تبدأ بالألوان؟ ولا بالـ model؟ ولا بالـ prompt؟ — وتضيع ساعات.",
      "المشكلة مش الأداة. المشكلة إن الفكرة لسه مش مترجمة لرحلة العميل."
    ],
    "title": "فكرة جامدة — وصفحة بيضا"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "أي تطبيق AI = رحلة: العميل يفتح → يعمل حاجة → يوصل لهدف.",
      "كل خطوة = شاشة. ٣ شاشات كفاية للبداية: بداية، وسط، نهاية.",
      "قبل الألوان والكود: ارسم «العميل يمشي إزاي».",
      "User Flow = الخريطة. الشاشات = البيوت على الخريطة."
    ],
    "title": "الفكرة = شاشات + خطوات"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "تصميم شكل vs رحلة العميل",
    "left": {
      "body": "«عايز AI يخطط رحلات» → تصمّم شات حلو. بعد ساعتين: مش عارف العميل يبدأ منين — بلد؟ ميزانية؟",
      "label": "تبدأ بالشكل"
    },
    "right": {
      "body": "«يفتح → يكتب «إيطاليا ٥ أيام» → AI يسأل ميزانية → يعرض خطة» — ٣ خطوات = ٣ شاشات. واضح.",
      "label": "تبدأ بالرحلة"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "٣ خطوات",
    "term": "User Flow (رحلة المستخدم)",
    "definition": "الخطوات اللي العميل بيمشيها عشان يوصل لهدفه."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Screen (شاشة)",
    "definition": "كل خطوة في الرحلة = شاشة واحدة في التطبيق.",
    "tag": "كل خطوة = شاشة"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/builder-m6-l1-idea-to-page.jpg",
    "caption": "أي صفحة = هدف واحد + خطوات واضحة. المستخدم يدخل → يشوف الخريطة → يختار. نفس المنطق لتطبيقك.",
    "eyebrow": "شوفها ببساطة",
    "title": "رحلة بسيطة — ٣ خطوات"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "الرحلة الأول — لما تعرف الخطوات، تعرف الشاشات والأسئلة اللي AI محتاج يسألها.",
    "highlight": "إيه أهم أول خطوة؟",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ الفكرة = شاشات + خطوات. User Flow قبل الألوان.",
      "تقدر تعمل إيه؟ عندك flow من ٣ شاشات — جاهز للـ wireframe.",
      "اللي جاي: Wireframe — ليه الرسمة الكروكي بتمنع اللخبطة."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [756, 660, 927, 946, 558, 594, 634, 682, 643];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
