// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الحل في العلاقات",
    "highlight": "كارثة خصوصية",
    "title": "الـ AI بتاعك بينسى مين بيكلمه",
    "chip": "المشكلة"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "left": {
      "label": "غلط — كله في جدول واحد",
      "body": "جدول واحد فيه: محادثات(اسم_العميل, ايميل_العميل, رسالة_العميل, رد_الAI). فوضى."
    },
    "right": {
      "body": "دولابين نضاف: عملا(id, الاسم, الايميل) ومحادثات(id, عميل_id, الرسالة). منظم.",
      "label": "صح — فصل وربط بذكاء"
    },
    "title": "شوف الفرق: كومة واحدة vs. دواليب مترتبة"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "عمود في دولاب بنحط فيه رقم الـ ID بتاع حاجة من دولاب تاني، عشان نربطهم ببعض.",
    "term": "الوصلة بين دولابين (Foreign Key)",
    "tag": "ربط ذكي"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "أكتر علاقة هتقابلك: واحد لـ كتير (One-to-Many).",
      "فيه واحد لـ واحد (One-to-One): زي كل عميل ليه profile_settings واحدة.",
      "وفيه كتير لـ كتير (Many-to-Many): زي المقالة الواحدة فيها tags كتير.",
      "نصيحة أمان: امسحهم مع بعض (Cascade Delete) لما عميل يمسح حسابه."
    ],
    "title": "أشهر وصلة هتحتاجيها للـ AI بتاعك"
  },
  {
    "card": "ScreenshotCard",
    "accent": "pink",
    "caption": "بص على الرسمة دي. تخيل `users` هما العملا بتوعك، و`posts` هي المحادثات بتاعتهم مع الـ AI. شايف `posts.user_id`؟ دي **الوصلة بين الدولابين** اللي بتقولنا مين صاحب المحادثة دي. من غيرها، الـ AI بتاعك هيبقى أعمى، مش عارف بيكلم مين.",
    "title": "شكل الوصلات دي إيه في الحقيقة؟",
    "src": "lessons/concepts/relations-diagram.jpg",
    "eyebrow": "شوف بنفسك"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "دورك دلوقتي",
    "tagline": "جاوبي على الأسئلة عشان تطبقي صح",
    "highlight": "طبق اللي اتعلمته",
    "title": "اختبر فهمك في دقيقة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [593, 472, 492, 787, 633, 363];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
