// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "هتفهم إيه النهاردة؟",
    "subtitle": "بين الجداول بتجاوب على أسئلة حقيقية",
    "highlight": "العلاقات",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الـ AI بيكلم أحمد وبعدين سارة — وفجأة يبعت لسارة ملخص محادثة أحمد. كارثة خصوصية.",
      "المشكلة: كل المحادثات في كومة واحدة ومفيش وصلة رسمية بين كل محادثة وصاحبها.",
      "الحل: فصل الجداول وربطهم بـ Foreign Key — كل حاجة مربوطة بصاحبها."
    ],
    "title": "الـ AI بينسى مين بيكلمه — أو بيبعت بيانات غلط"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "بدل جدول واحد فيه كل حاجة — جدولين: `users` و `conversations`. كل محادثة فيها `user_id` بيشاور على صاحبها.",
      "One-to-Many (واحد لكتير): عميل واحد → محادثات كتير. كل محادثة ليها صاحب واحد بس.",
      "السؤال «هات محادثات العميل ٥» = علاقة. من غيرها، المخزن مش هيعرف يجاوب."
    ],
    "title": "العلاقات بتجاوب على أسئلة حقيقية"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "كومة واحدة vs فصل وربط",
    "left": {
      "label": "غلط — كل حاجة في جدول واحد",
      "body": "`محادثات(اسم_العميل, ايميل, رسالة)`. العميل غيّر اسمه؟ تلف على كل رسايله. غلط في حرف؟ السيستم يفتكره عميل جديد."
    },
    "right": {
      "body": "`users(id, name)` و `conversations(id, user_id, message)`. غيّر الاسم في مكان واحد. كل محادثة مربوطة بـ `user_id`.",
      "label": "صح — جدولين مربوطين"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "عمود في جدول بيشاور على `id` في جدول تاني — الوصلة بينهم.",
    "tag": "وصلة جداول",
    "term": "Foreign Key (مفتاح أجنبي)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "علاقة جداول",
    "term": "One-to-Many (واحد لكتير)",
    "definition": "صف واحد في جدول أ → صفوف كتير في جدول ب."
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/concepts/relations-diagram.jpg",
    "caption": "تخيّل `users` = العملا و `posts` = المحادثات. `posts.user_id` = الوصلة اللي بتقول مين صاحب المحادثة. من غيرها، التطبيق أعمى.",
    "eyebrow": "شوفها ببساطة",
    "title": "الوصلة بين الجداول"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "جاوب على السؤال ده عشان تثبت فهمك للعلاقات.",
    "highlight": "مش امتحان",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ العلاقات بتجاوب على أسئلة حقيقية. `user_id` = الوصلة اللي بتمنع الفوضى والتلخبط.",
      "تقدر تعمل إيه؟ عندك علاقة user-to-many مصمّمة — جاهزة تسأل المخزن أسئلة محدّدة.",
      "هنتقابل في الدرس الجاي!"
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [784, 717, 1007, 1121, 615, 601, 623, 365, 661];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
