// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "Mini Win قبل الكمال",
    "highlight": "صغير ومنشور",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "عندك ٢٠ feature في دماغك: login، دفع، ٥ لغات، dashboard، notifications...",
      "بعد شهر لسه بتخطّط — ومفيش حاجة شغّالة قدام حد حقيقي.",
      "المشكلة مش الفكرة. المشكلة إنك مستني «الكمال» قبل ما تجرب."
    ],
    "title": "بتخطّط لتطبيق ضخم — ومش بتبدأ"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "صغير ومنشور > كامل ومش متجرب",
    "bullets": [
      "Mini Win = أصغر نسخة من تطبيقك تقدر تنشرها وتجربها مع مستخدم حقيقي.",
      "صفحة واحدة + action واحد + نتيجة واحدة = كفاية للبداية.",
      "Feedback من ٣ مستخدمين أهم من ٣٠ feature مفيش حد جربهم.",
      "Phase 2 خلّصت المفاهيم — Phase 3 هتبني. Mini Win هو جسرك."
    ]
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "تطبيق كامل في دماغك vs Mini Win",
    "right": {
      "body": "صفحة واحدة: اكتب سؤال → AI يرد. ٥ أصدقاء جربوا. عرفت إيه يشتغل وإيه لأ.",
      "label": "Mini Win في أسبوع"
    },
    "left": {
      "body": "٣ شهور تخطيط. login + دفع + ١٠ صفحات. مفيش حد جرب — ومفيش feedback.",
      "label": "«هعمل كل حاجة الأول»"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "مش prototype",
    "term": "Mini Win (انتصار صغير)",
    "definition": "أصغر نسخة منشورة تثبت إن الفكرة تشتغل — مش prototype في دماغك."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "نفس الفكرة بالإنجليزي — أقل منتج يقدر يوصل قيمة حقيقية.",
    "term": "MVP (Minimum Viable Product)",
    "tag": "أقل منتج قيمة"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Frontend: العميل يشوف ويدوس.",
      "Backend: AI يشتغل ورا.",
      "Database: التطبيق يفتكر.",
      "Mini Win = أقل حاجة في كل طبقة — بس تشتغل end-to-end."
    ],
    "title": "٣ طبقات — جاهزة للبناء"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "جاوب على السؤال عشان تتأكد إنك فهمت.",
    "title": "سؤال واحد سريع",
    "eyebrow": "دورك دلوقتي",
    "highlight": "تأكيد فهمك للدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "إيه اللي عندك دلوقتي؟",
    "bullets": [
      "فهمت إيه؟ صغير ومنشور > كامل ومش متجرب. Mini Win = جسرك لـ Phase 3.",
      "تقدر تعمل إيه؟ عندك تعريف Mini Win + حدود + ٣ testers.",
      "اللي جاي: من فكرة لصفحة — إزاي أي idea تبقى شاشات وخطوات."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [383, 430, 784, 529, 427, 540, 435, 306, 672];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
