// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "البداية",
    "subtitle": "عمرك سألت الـ AI نفس السؤال مرتين، وجابلك ردين مختلفين تمامًا؟ ده مش سحر، ده زرار اسمه Temperature. وانت اللي بتتحكم فيه.",
    "highlight": "(أو الملل)",
    "title": "Temperature: زرار الإبداع"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "highlight": "Temperature",
    "title": "امتى تعلّي وامتى توطّي؟",
    "tagline": "شوف إزاي تختار الـ Temperature الصح لكل مهمة.",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "الزرار اللي بتلفّه عشان تقرر الـ AI يكون \"موظف ملتزم\" ولا \"فنان مبدع\".",
    "term": "Temperature (زرار الإبداع)",
    "tag": "تحكم في إبداع الـ AI"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "من الثبات للإبداع برقم واحد",
    "bullets": [
      "كل مرة الـ AI بيكتب كلمة، بيبقى قدامه لستة احتمالات.",
      "الـ Temperature هي اللي بتقوله: خد أول كلمة في اللستة (ثبات)، ولا خُش في اللي بعده وفاجئنا (إبداع)؟"
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "Temperature واطية (0 – 0.3)",
    "bullets": [
      "إجابات متوقعة، دقيقة، وممكن تكون مملة.",
      "ممتازة للمهام اللي عايزة إجابة صح واحدة: أكواد، استخراج بيانات، ترجمة حرفية."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "توازن بين الدقة والإبداع الخفيف.",
      "مناسبة لكتابة الإيميلات، الشرح، والدردشة العادية."
    ],
    "title": "Temperature متوسطة (0.4 – 0.7)"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "إبداع صافي، مفاجآت، وأفكار جديدة.",
      "استخدمها في الـ brainstorming، عناوين مقالات، شعر، أو أي حاجة محتاجة خيال."
    ],
    "title": "Temperature عالية (0.8 – 1.2+)"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "ملحوظة مهمة",
    "bullets": [
      "الأرقام دي بتاعت OpenAI. موديلز تانية ممكن أرقامها تختلف، بس المبدأ واحد.",
      "صفر = ثبات، ورقم عالي = إبداع.",
      "الخلاصة: لو عايز \"الإجابة الصح\" — وطّيها. لو عايز \"١٠ أفكار مختلفة\" — علّيها."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "src": "lessons/builder-m4-l8-parameters.jpg",
    "caption": "بص على كروت الدروس دي: ٤ دروس، نفس الشكل، نفس الترتيب، صفر مفاجآت. ده لأنها معمولة بـ Temperature واطية (حوالي 0.2). دي معلومات منظمة، مش قطعة فنية. لو كنا عملناها بـ Temperature عالية، كان كل كارت هيطلع بترتيب مختلف، وعناوين بأسلوب مختلف، ومكنتش هتعرف تمشي في المنهج. في المقابل، اسم المسار نفسه \"Builder\" والـ tagline بتاعه طلعوا من جلسة brainstorming بـ Temperature عالية عشان كنا محتاجين شخصية، مش مجرد نظام.",
    "eyebrow": "مثال حي",
    "title": "ليه كروت المنهج شكلها متكرر؟"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "الـ AI Assistant بتاعنا متظبط على ٠.٤",
    "bullets": [
      "الـ AI Assistant اللي في المنصة هنا معمول بنفس مسار Builder اللي بتتعلمه.",
      "ظابطين الـ Temperature بتاعته على 0.4 عن قصد.",
      "الرقم ده واطي كفاية عشان إجاباته التعليمية تكون دقيقة وشبه بعض.",
      "وعالي كفاية عشان ميحسسكش إنه بيرد ردود محفوظة ومملة.",
      "لو عليناها لـ 1.2 هتلاقيه بيألّف إجابات غريبة.",
      "أسئلة عن القواعد (زي «إزاي أكتب prompt؟») — Temperature واطية = إجابة موحدة ودقيقة.",
      "جرّب اسأله نفس السؤال مرتين — هتلاقي الردود قريبة قوي من بعض بس مش نسخة طبق الأصل."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [420, 225, 390, 400, 424, 449, 401, 534, 529, 543];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
