// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "في الـ 8 دروس الجايين هتبني تطبيق AI كامل. الدرس ده هيوريك الخريطة.",
    "highlight": "وانت عارف فين رايح",
    "chip": "بعد الدرس ده هتقدر",
    "title": "تبدأ Phase 2"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "خلصنا Phase 1: فهمت الـ AI كويس.",
      "عرفت إزاي بيفكر وإزاي تتحكم في رده."
    ],
    "title": "لحظة انتقال مهمة"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "هنحول الفكرة لتطبيق حقيقي (Phase 2).",
      "العميل محتاج واجهة، مكان لحفظ كلامه، وحاجة تعرفه."
    ],
    "title": "من هنا هنحوّل الفكرة لتطبيق حقيقي."
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "مش كورس Web Development.",
      "بنركّب ٣ طبقات توصل الـ AI للناس.",
      "كل مصطلح هتسمعه، هتلاقي جنبه تشبيه."
    ],
    "title": "مش مطلوب منك تكون مبرمج."
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "هنمشي خطوة بخطوة.",
      "في آخر Phase 2، هتبني أول AI app حقيقي."
    ],
    "title": "مهمتك في Phase 2"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "highlight": "وحدد الـ ٣ طبقات بتاعته",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّ الأسئلة اللي جاية عشان تفهم أكتر",
    "title": "حلّل أبلكيشن بتستخدمه"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "ديكور المطعم",
    "term": "Frontend (الواجهة)",
    "definition": "الوش بتاع الأبلكيشن. كل حاجة عينك شايفاها وصباعك بيدوس عليها."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "الشيف في المطبخ",
    "term": "Backend (الكواليس)",
    "definition": "المطبخ أو العقل اللي بيفكر وبينفذ الأوامر اللي مبتتشفش."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "تلاجة المكونات",
    "term": "Database (المخزن)",
    "definition": "الأرشيف اللي بنشيّل فيه كل حاجة (بيانات المستخدمين، المنتجات، الرسايل) عشان نرجع لها بعدين."
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "title": "الجسر اللي بين الكلام والبناء",
    "src": "lessons/unique/builder-m5-l1-transition.jpg",
    "eyebrow": "شوف بنفسك",
    "caption": "إنت دلوقتي واقف على الجسر ده. خلصت مرحلة إزاي \"تكلّم\" الـ AI، وداخل على مرحلة إزاي \"تبني\" له بيت يعيش فيه."
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "كل حاجة هنا مبنية بالـ ٣ طبقات.",
      "الدروس اللي فاتت كانت كلام مع AI.",
      "دلوقتي بتتعامل مع أبلكيشن حقيقي.",
      "كل صفحة بتفتحها هي تطبيق عملي."
    ],
    "title": "المنصة اللي إنت عليها دي معمولة بنفس الطريقة"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "Frontend: شكل الصفحة والزراير.",
      "Backend: الكود اللي بيسجّل تقدمك.",
      "Database: متخزّن فيه خلصت كام درس."
    ],
    "title": "أمثلة من المنصة اللي إنت عليها:"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [359, 341, 399, 423, 184, 246, 390, 479, 450, 355, 487, 432];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
