// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أول خطوة ليك كـ Builder",
    "title": "الشاشة بيّضت فجأة؟",
    "subtitle": "إزاي تتعامل مع الـ bugs زي المحترفين.",
    "highlight": "مبروك."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "في أي متصفح، دوس F12 هيفتحلك الـ Console.",
      "الـ Console هو الصندوق الأسود لأي ويب سايت.",
      "هتلاقي ٩٩٪ من رسائل الـ Error الحمرا مستنياك هناك.",
      "دي أول حاجة تبص عليها دايماً."
    ],
    "title": "أول رد فعل ليك: دوس F12"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "رسالة الـ Error بالحرف (copy/paste).",
      "مكان الـ Error (اسم الفايل ورقم السطر).",
      "إزاي المشكلة حصلت (خطوات التكرار).",
      "إيه اللي المفروض كان يحصل."
    ],
    "title": "٤ معلومات بتحل ٩٠٪ من الـ bugs"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "ده اللي الـ AI محتاجه، بالحرف",
    "bullets": [
      "الـ prompt فيه رسالة الـ Error بالظبط واسم الفايل ورقم السطر",
      "عشان كده الـ AI رد بتشخيص دقيق وحل مباشر",
      "لما تقوله «الكود بايظ» بس",
      "بيرد باحتمالات عامة"
    ]
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "body": "لما تديله الـ Error والخطوات والمتوقع، الـ AI هيرد بحل دقيق ومباشر في ٣٠ ثانية بس.",
      "label": "صح: Error + خطوات + المتوقع"
    },
    "left": {
      "body": "الـ AI هيرد باحتمالات عامة، زي جرّب refresh أو اتأكد من النت. هتضيع ساعة من وقتك من غير حل.",
      "label": "غلط: «الصفحة مش شغالة»"
    },
    "title": "الفرق بين ساعة ضايعة و٣٠ ثانية"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "رسالة من السيستم بتقولك إن فيه حاجة باظت ومحتاجة تتصلح، وبتوصف نوع المشكلة بالظبط.",
    "tag": "رسالة الخطأ",
    "term": "Error Message"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "اكتب prompt للـ AI يحل بيه bug (حقيقي أو من خيالك).",
      "الـ prompt لازم يكون فيه الـ ٤ معلومات اللي اتعلمناها.",
      "رسالة الـ Error، مكانها، خطوات التكرار، وإيه اللي كان المفروض يحصل."
    ],
    "title": "مهمتك: اكتب prompt يحل bug"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "جاوب على الأسئلة عشان تطبق اللي اتعلمته وتتأكد إنك بقيت محترف في الـ debugging.",
    "title": "اختبر نفسك",
    "highlight": "اتأكد إنك فهمت",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "كل error بيحصل عند أي مستخدم بيتبعت لجدول عندنا.",
      "بنخزن رسالة الـ error كاملة والصفحة اللي حصل فيها.",
      "بنراجع الـ logs دي أسبوعيًا ونصلّح أكتر أخطاء بتتكرر."
    ],
    "title": "/build-logs — كل غلطة بتتحول لدرس"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "نتقابل في الدرس الجاي عشان نفهم إزاي المونتاج بيكمل رسالة الفيديو وبيخليه فعال أكتر.",
    "title": "المونتاج مش رفاهية",
    "highlight": "هو نص الفيديو",
    "eyebrow": "الدرس الجاي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [663, 544, 498, 558, 603, 513, 558, 378, 592, 432];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
