// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "تعمل إيه؟",
    "title": "الـ AI طلعلك حاجة غلط",
    "subtitle": "لما تلاقي الألوان والمسافات مش مظبوطة",
    "chip": "أهلًا، الحقيقة المُرّة"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "label": "صح — تعديل جراحي (Surgical Edit)",
      "body": "اطلب تعديل محدد: 'الزرار أزرق، خليه برتقاني #FF6B35'. نتيجة مضمونة."
    },
    "title": "إزاي تطلب تعديل صح",
    "left": {
      "label": "غلط — «الشكل وحش، صلّحه»",
      "body": "الـ AI مش بيفهم 'وحش'. هيخمن ويغيّر عشوائي، ممكن يبوظ حاجات كانت شغالة (Regression)."
    }
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "شغلك عبارة عن لفّات من 4 خطوات",
    "bullets": [
      "دي لفة التحسين (Iteration Loop)",
      "كل لفة بتقربك للصح",
      "الخطوات: اطلب (Prompt) -> شوف النتيجة (Result) -> راجع (Review) -> عدّل (Refine)"
    ]
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "مفهوم أساسي",
    "term": "Iteration / التكرار والتحسين",
    "definition": "تعمل لفة كاملة: تجربة، ملاحظة الغلط، تصليحه، وتجربة تاني."
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "جاوب على الأسئلة عشان تتأكد إنك فهمت إزاي تعمل تعديل صح.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "هل تقدر تعدّل صح؟",
    "title": "اختبر فهمك للـ Iteration"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [526, 765, 623, 533, 316];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
