// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "السبب غالبًا في الطريقة اللي الـ AI بيشوف بيها كلامك.",
    "title": "ليه الـ AI ساعات بيبطّأ أو بيكلّفك أكتر؟",
    "chip": "السؤال المهم",
    "highlight": "AI"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "جرّب تكتب: 'لخص المقال ده في 3 نقط' على OpenAI Tokenizer.",
      "شوف هيطلعلك كام token.",
      "جرّب نفس الطلب بالإنجليزي: 'Summarize this article in 3 points'.",
      "لاحظت الفرق في عدد الـ tokens؟"
    ],
    "title": "شوف كلامك بيتقطّع كام حتة"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "الـ 'قطمة' اللي الـ AI بيقسم بيها كلامك عشان يفهمه. مش شرط تكون كلمة كاملة، ممكن تبقى نص كلمة أو حتى علامة ترقيم.",
    "tag": "مفهوم أساسي",
    "term": "Token"
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "caption": "الـ Hero ده اتبنى بـ prompt بسيط. لو كتبناه بالإنجليزي، كان هياخد tokens أقل بحوالي 40%، ويدي نفس النتيجة. توفير في الوقت والفلوس.",
    "eyebrow": "مثال حي من شغلنا",
    "title": "الـ Hero بتاع موقعنا ده",
    "src": "lessons/builder-m1-tokens.jpg"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "body": "بتدخل في الموضوع على طول. بتدي سياق واضح وطلب محدد. tokens أقل = رد أسرع، تكلفة أقل، وتركيز أعلى من الـ AI.",
      "label": "صح: كلام مباشر وواضح"
    },
    "title": "إزاي تكتب prompt يوفر عليك",
    "left": {
      "body": "بتكتب مقدمات ملهاش لازمة وتكرر كلامك ('يا صديقي الذكاء الاصطناعي، من فضلك لو سمحت عايزك تساعدني...'). كل ده tokens على الفاضي بتزوّد التكلفة وبتشتت الـ AI.",
      "label": "غلط: حشو وكلام كتير"
    }
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "في صفحة المساعد الشخصي، بنوريك دايمًا عدد الـ tokens لسؤالك ورد الـ AI.",
      "الـ AI مش بيقرأ كلمات، بيقرأ tokens، وكل حاجة ليها تمن.",
      "كل طلب بنحسب الـ tokens اللي داخلة واللي خارجة.",
      "لو المحادثة قربت تملى الذاكرة، بنمسح أقدم رسايل.",
      "التكلفة والسرعة بتتحسب بالـ token. ده قانون اللعبة."
    ],
    "title": "عداد الـ Tokens في Lovable"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "highlight": "فهمك",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك",
    "tagline": "جاوب على الأسئلة عشان تتأكد إنك استوعبت الدرس كويس."
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [358, 558, 491, 454, 699, 717, 198];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
