// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الحل الصح: الكواليس هي الحارس الأمين",
    "highlight": "الغلطة القاتلة: مفتاح الـ AI في واجهة التطبيق",
    "title": "لو مفتاح الـ AI اتسرق، هتصحى على فاتورة بآلاف الدولارات",
    "chip": "أخطر غلطة ممكن تدمر تطبيق الـ AI بتاعك"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "جاوب على السؤال عشان تفهم أكتر",
    "eyebrow": "دورك دلوقتي",
    "highlight": "إزاي الطلبات بتعدي على الكواليس",
    "title": "شوف ساعي البريد وهو شغال"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "الكواليس هي المطبخ، وساعي البريد هو الجرسون",
    "bullets": [
      "تخيل تطبيق الـ AI بتاعك مطعم.",
      "وش التطبيق (Frontend) هو الترابيزة والمنيو.",
      "مخ التطبيق أو الكواليس (Backend) ده المطبخ اللي بيجهز الردود.",
      "ساعي البريد (API) هو الجرسون اللي بينقل الطلبات والردود."
    ]
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "ساعي البريد",
    "term": "API (Application Programming Interface)",
    "definition": "هو العقد أو اللغة المشتركة اللي بتخلي البرامج المختلفة (زي واجهة التطبيق والكواليس) يكلموا بعض وينفذوا طلبات لبعض."
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "في Lovable، الكواليس بتاعتك مجرد function",
    "bullets": [
      "زمان كان بناء الكواليس معقد، لكن في Lovable الموضوع أبسط.",
      "بتكتب function عادية وبتحدد إنها تشتغل في الكواليس بس.",
      "المنصة بتحول نداء الـ function لطلب API كامل يروح للكواليس ويرجع بالرد.",
      "مفتاح الـ AI بتاعك بيفضل أمان قوي في الكواليس جوه الـ function."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "mintDeep",
    "src": "lessons/builder-m5-l11-backend-api.jpg",
    "title": "مساعد Lovable بيكلم الكواليس",
    "eyebrow": "مثال حي من المنصة",
    "caption": "الصفحة دي مثال حي. أول ما بتفتحها، الواجهة بتبعت طلب للكواليس عشان تجيب بياناتك (ده طلب GET). ولما بتكتب رسالة، بتبعت طلب تاني فيه رسالتك (ده طلب POST). الكواليس تاخد الرسالة، تكلم الـ AI بالمفتاح السري، وترجعلك الرد. كل ده بيحصل من غير ما مفتاحك يظهر أبدًا."
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "highlight": "إيه أهم رسالة واجهة التطبيق هتبعتها للكواليس؟",
    "title": "صمّم أهم طلب لـ 'ساعي البريد' بتاع تطبيقك",
    "tagline": "فكر في فكرتك وطبق اللي اتعلمته",
    "eyebrow": "مهمتك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [370, 293, 478, 413, 425, 502, 450];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
