// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "بداية الدرس",
    "subtitle": "عشان أي ميزة في منتجك تردّ «ليك» مش «لأي حد».",
    "highlight": "السياق الصح",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "«اعملي خطة محتوى» — والرد خطة عامة منسوخة مش بتاعت مشروعك.",
      "المشكلة مش السؤال — المشكلة إن الـ AI مش عارف: إنت مين؟ لمين؟ بكام؟ على أنهي منصة؟",
      "في أي تطبيق فيه AI، السياق اللي بتمرّره = فرق بين «مساعد» و«حيطة»."
    ],
    "title": "سؤال واضح — وردّ غبي"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "السياق الصح في الوقت الصح",
    "bullets": [
      "Context = كل المعلومات اللي الـ AI يعرفها قبل ما يرد: من أنت، إيه مشروعك، إيه اللي حصل قبل كده.",
      "تخيّل دكتور معاه ملفك vs دكتور أول مرة. نفس السؤال — رد مختلف.",
      "في Builder: مش لازم المستخدم يكتب السياق كل مرة — أنت تمرّره من التطبيق (صفحة، دور، بيانات).",
      "القاعدة: خلفية قبل الطلب. كل ما السياق أوضح، كل ما المخرج قابل للتنفيذ."
    ]
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "«اعملي خطة محتوى.» — الـ AI يخمّن. خطة عامة — مش لمشروعك.",
      "label": "من غير سياق"
    },
    "title": "سؤال عايم vs سياق كامل",
    "right": {
      "label": "سياق قبل الطلب",
      "body": "«أنا صاحب مخبز في القاهرة، ميزانية ٢٠٠٠/شهر، جمهور ستات ٣٠–٤٥ على انستجرام. خطة ٤ أسابيع.» — خطة تنفّذها."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Context (السياق)",
    "tag": "مهم قوي",
    "definition": "المعلومات اللي الـ AI يشوفها مع السؤال — دورك، مشروعك، المرحلة."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "ملخص ثابت",
    "definition": "ملخّص ثابت تبدأ بيه أي محادثة مهمة — أو التطبيق يمرّره أوتوماتيك.",
    "term": "Context Card (بطاقة سياق)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "eyebrow": "شوفها ببساطة",
    "src": "lessons/builder-m3-l1-context-layer.jpg",
    "caption": "قبل ما تكتب، المساعد عارف إنت في أنهي مسار وأنهي درس. السياق ده بيخلّي الرد يكمّل رحلتك — مش إجابات عامة. نفس الفكرة في أي منتج: مرّر للـ AI اللي المستخدم «فيه» دلوقتي.",
    "title": "سياق يظهر قبل السؤال"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّ السؤال عشان تتأكد إنك فهمت.",
    "highlight": "اختبر فهمك",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "إيه اللي عندك دلوقتي؟",
    "bullets": [
      "فهمت إيه؟ Context = السياق الصح في الوقت الصح — من التطبيق مش من ذاكرة المستخدم.",
      "تقدر تعمل إيه؟ تصمّم ٤ حقول سياق لأي ميزة AI."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [487, 541, 527, 471, 478, 517, 527, 454, 462];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
