// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "التطبيق live — بس الصمت مريب. محتاج ناس حقيقية تجرب وتقولك الحقيقة.",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "أول ١٠ مستخدمين يعلّموك الواقع",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "اللينك شغال. تقنيًا كل حاجة تمام. بس مفيش تسجيلات — مفيش feedback.",
      "بتكتب بوست على فيسبوك وتستنى. ٥٠٠ زائر، ٢٠ يسجّلوا، ومحدش يرجع.",
      "المشكلة مش marketing — المشكلة إنك مش بتسمع من ١٠ ناس تعرفهم بالاسم."
    ],
    "title": "Live — ومفيش حد بيستخدم"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "أول ١٠ مش للأرقام — للتعلّم. هما اللي يقولولك: ده بيحل مشكلة؟ ولا شكل حلو بس؟",
      "٥–١٠ ناس تعرفهم + مكالمة ١٥ دقيقة كل أسبوع > ١٠٠٠ زائر من إعلان.",
      "Iteration: تسمع → تصلّح مشكلة واحدة → ترجعلهم. بعد شهر — منتج الناس محتاجاه."
    ],
    "title": "أول ١٠ مستخدمين يعلّموك الواقع"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "تستنى الزوار vs تسمع ١٠ ناس",
    "right": {
      "body": "١٠ ناس بالاسم. كل أسبوع ٣ مكالمات: «آخر مرة فتحت لِيه؟» «إيه اللي معرفتش تعمله؟». مشكلة واحدة → تصلّح → ترجعلهم.",
      "label": "صح — ١٠ أوائل + استماع"
    },
    "left": {
      "body": "بوست عام → زوار → تسجيل → مفيش رجوع. تضيف features جديدة من غير ما تعرف الناس محتاجة إيه.",
      "label": "غلط — إطلاق وتستنى"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "مستخدمين أوائل",
    "definition": "الناس اللي مستعدة تجرب وهي لسه نص سوا — وبتصبر على المشاكل.",
    "term": "Early Adopters"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Feedback Loop",
    "tag": "تطوير مستمر",
    "definition": "تسمع → تعدّل → ترجّع للمستخدم → تسمع تاني. أسرع طريقة للتطور."
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/builder-m10-l2-first-users.jpg",
    "caption": "لما تبني واجهة تطبيقك — فكّر: إزاي المستخدم يشوف إنه بيتقدم؟ الأرقام دي بتحرّك سلوك — مش للمنظر.",
    "eyebrow": "شوفها ببساطة",
    "title": "قياس التقدّم — مش للمنظر"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "فكّر كويس قبل ما تجاوب وتشوف الشرح.",
    "highlight": "بعد ٤ أسابيع: ٤ من ١٠ لسه بيستخدمون التطبيق. إيه القرار الصح؟",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ أول ١٠ مستخدمين = معلمين — مش أرقام.",
      "تقدر تعمل إيه؟ عندك رسالة دعوة + سؤالين جاهزين.",
      "عمق Builder (اختياري) خلص — Creator و Automator و Business و Analyst لسه مسارات قيمة تكمل رحلتك."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "شوفك في الدرس الجاي عشان نكمل رحلتك.",
    "highlight": "اسمع منهم، صلّح مشكلة واحدة، وكرّر.",
    "eyebrow": "ملخص الدرس",
    "title": "أول ١٠ مستخدمين: مش أرقام، دول معلمين!"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [419, 463, 669, 748, 361, 363, 337, 439, 489, 423];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
