// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "السبب غالبًا في الطريقة اللي الـ AI بيشوف بيها كلامك.",
    "highlight": "بيبطلأ أو بيكلفك أكتر؟",
    "chip": "السؤال المهم",
    "title": "ليه الـ AI ساعات بيبطّأ أو بيكلّفك أكتر؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "روح على أداة OpenAI Tokenizer وجرّب تكتب: 'لخص المقال ده في 3 نقط'. شوف كام token.",
      "دلوقتي جرب نفس الطلب بالإنجليزي: 'Summarize this article in 3 points'.",
      "لاحظت الفرق في عدد الـ tokens؟ الرقم ده هو مفتاح كل حاجة."
    ],
    "title": "شوف كلامك بيتقطّع كام حتة"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Token",
    "tag": "وحدة فهم الـ AI",
    "definition": "الـ 'قطمة' اللي الـ AI بيقسم بيها كلامك عشان يفهمه. مش شرط تكون كلمة كاملة، ممكن تبقى نص كلمة أو حتى علامة ترقيم."
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "caption": "الـ Hero ده اتبنى بـ prompt بسيط. لو كتبناه بالإنجليزي، كان هياخد tokens أقل بحوالي 40%، ويدي نفس النتيجة. توفير في الوقت والفلوس.",
    "eyebrow": "مثال حي من شغلنا",
    "src": "lessons/builder-m1-tokens.jpg",
    "title": "الـ Hero بتاع موقعنا ده"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "label": "صح: كلام مباشر وواضح",
      "body": "ادخل في الموضوع على طول بسياق واضح وطلب محدد. tokens أقل = رد أسرع وتكلفة أقل."
    },
    "title": "إزاي تكتب prompt يوفر عليك",
    "left": {
      "body": "مقدمات ملهاش لازمة وتكرار كلام بيزود التكلفة ويشتت الـ AI.",
      "label": "غلط: حشو وكلام كتير"
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "highlight": "اختبر فهمك",
    "tagline": "جاوب على الأسئلة عشان تتأكد إنك فهمت.",
    "title": "اختبر فهمك",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "اكتب نفس الطلب بطريقتين: مرة طويلة ومرة مختصرة.",
      "قارن عدد الـ tokens لكل واحدة (باستخدام OpenAI Tokenizer).",
      "شوف الفرق في عدد الـ tokens عشان تحس بالفرق عمليًا."
    ],
    "title": "جرّب تقلل الـ Tokens بنفسك"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "عداد الـ Tokens في Lovable",
    "bullets": [
      "الـ AI مش بيقرأ كلمات، بيقرأ tokens (كل حاجة ليها تمن).",
      "بنحسب الـ tokens اللي داخلة واللي خارجة لكل طلب.",
      "لو المحادثة قربت تملى الذاكرة، بنمسح أقدم رسايل.",
      "التكلفة والسرعة بتتحسب بالـ token، ده قانون اللعبة."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [286, 491, 517, 408, 515, 384, 460, 526];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
