// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "البداية",
    "title": "الـ AI بتاعك بيردّ...",
    "subtitle": "الدرس ده هو القفزة من Chatbot بيرد لـ Agent بينفّذ.",
    "highlight": "بس مش بيعمل حاجة"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "العميل: \"عايز ألغي اشتراكي\". الـ Agent: (بيستخدم tool اسمها `getSubscription`) \"لقيت اشتراكك Pro. أكّد الإلغاء؟\" العميل: \"آه\". الـ Agent: (بيستخدم tool اسمها `cancelSubscription`) \"تمام، اتلغى\". النتيجة: المهمة خلصت في ٢٠ ثانية والعميل معملش أي مجهود.",
      "label": "صح: Agent إيده في الشغل"
    },
    "title": "شوف الفرق: Chatbot بيقول vs. Agent بيعمل",
    "left": {
      "label": "فاشل: Chatbot حافظ مش فاهم",
      "body": "العميل: \"عايز ألغي اشتراكي\". الـ AI: \"تمام، عشان تلغي، روح Settings → Billing → Cancel Subscription\". النتيجة: العميل قفل الشات محبط. حس إن الـ AI بتاعك ديكور مش أكتر."
    }
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Agent",
    "definition": "برنامج ذكي عنده (مخ) عشان يفكّر ويقرّر، و(إيدين) عشان ينفّذ.",
    "tag": "مخ وإيدين"
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "src": "lessons/concepts/agents-diagram.jpg",
    "caption": "الـ Agent مش مجرد LLM بيرد وخلاص. هو دايرة تفكير وتنفيذ. لما بيجيله طلب، بيفكّر (Think)، ويقرر يستخدم أنهي أداة (Act)، ويشوف نتيجتها (Observe)، ويكرر الدايرة دي لحد ما يوصل للحل النهائي. ده اللي بيخليه يحل مشاكل معقدة.",
    "eyebrow": "تحت الغطا",
    "title": "الـ Agent بيفكر إزاي: فكّر ← نفّذ ← شوف النتيجة ← كرّر"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "إزاي الـ Agent بيستخدم الـ Tools بتاعته؟",
    "bullets": [
      "الـ Tool هي مجرد function في الكود بتاعك، إنت بتدي للـ LLM قايمة بيها ووصف لكل واحدة، وهو بيقرر إمتى يستخدمها.",
      "الـ Agent بيمشي في دايرة تفكير اسمها ReAct Loop: اليوزر يطلب، الـ LLM يفكّر ويطلب tool، الكود ينفّذ ويرجع النتيجة للـ LLM، الـ LLM يفكّر تاني لحد ما يوصل لرد نهائي.",
      "الأمان الأول: أي tool خطيرة لازم خطوة تأكيد من اليوزر (Human-in-the-loop)، وتحديد أقصى عدد محاولات عشان الـ Agent ميفضلش يلف للأبد."
    ]
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "دورك دلوقتي",
    "title": "هتعرف تتصرف؟",
    "tagline": "حل الأسئلة دي عشان تتأكد إنك فهمت إزاي الـ Agent بيفكر وبيشتغل صح.",
    "highlight": "اختبر فهمك للـ Agents"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [789, 807, 559, 679, 1377, 371];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
