// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "ولا توريه الشكل اللي عايزه؟",
    "highlight": "تعمل إيه؟",
    "title": "Instructions ولا Examples؟",
    "chip": "أهلًا"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Instructions (التعليمات)",
    "definition": "الأوامر المباشرة اللي بتكتبها للذكاء الاصطناعي عشان ينفذ مهمة معينة.",
    "tag": "أوامر مباشرة"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "هي الرسالة الكاملة اللي بتبعتها للـ AI (التعليمات + الأمثلة).",
    "tag": "رسالة الـ AI",
    "term": "Prompt (البرومبت)"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Role (الدور)",
    "tag": "وظيفة الـ AI",
    "definition": "تحديد وظيفة الـ AI (زي \"خبير ضرائب\") عشان يجاوب بدقة."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "شكل الرد اللي عاوزه (نقط، جدول، أو ملف معين).",
    "tag": "شكل الرد",
    "term": "Output Format (شكل الرد)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "أمثلة توضيحية",
    "definition": "إنك تديله شوية أمثلة توضحه يشتغل إزاي قبل ما يجاوب.",
    "term": "Few-shot (أمثلة توضيحية)"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Zero-shot (من غير أمثلة)",
    "definition": "بتطلب الطلب مباشرة من غير ما تدي أي أمثلة للـ AI.",
    "tag": "من غير أمثلة"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Instruction = بتوصف المطلوب بكلامك. زي: \"اكتبلي عنوان قصير وجذاب لمنتج عطر\".",
      "Example = بتوريه نموذج ليه نفس الشكل اللي إنت عايزه. زي: \"على نمط 'رائحة بتفضّل بعدك' — اعملي 5 عناوين زيّه لمنتجات تانية\".",
      "الـ AI شاطر قوي في التقليد. أوقات مثال واحد بيوصّل المعنى أحسن من فقرة شرح كاملة.",
      "القاعدة: لو الشكل أو الأسلوب صعب توصفه بالكلام — وريه مثال. لو السياق واضح ومحتاج خطوات — اكتبلوه instructions.",
      "الأفضل غالبًا = الاتنين مع بعض. تعليمات قصيرة + 1-3 أمثلة. ده اللي بيتسمّى Few-shot prompting.",
      "ولو طلبت من غير أمثلة خالص (تعليمات بس) — ده Zero-shot. مناسب لمهام بسيطة زي «ترجم الجملة دي» أو «لخّص الفقرة».",
      "حدّد كمان شكل الرد (Output Format): «اعمل ٥ عناوين على شكل قائمة مرقّمة» أو «رد بـ JSON فيه title و subtitle». ده بيخلّي الرد جاهز للاستخدام أو الربط ببرنامج تاني."
    ],
    "title": "وصف بالكلام، ولا نموذج جاهز؟"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "caption": "الـ 5 كروت دي (الباني، المُبدع، المُؤتمت، المحلّل، صاحب الأعمال) كلها بنفس الهيكل بالظبط: badge مرحلة + أيقونة + عنوان + role label + وصف. ده مكنش من instructions طويلة — كان كارت واحد كـ مثال + جملة: \"اعمل 4 زيّه للمسارات التانية\". الـ AI قلّد الـ pattern وطلّع الـ 4 الباقيين بنفس الإيقاع.",
    "title": "Case Study — كروت المسارات في الصفحة الرئيسية",
    "src": "lessons/builder-m2-instructions-examples.jpg",
    "eyebrow": "من المنصة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "بتفضل تشرح وتشرح: \"عايز عنوان عاطفي مش مباشر يخلّي القارئ يحس بـ...\". الـ AI بيتلخبط لإن الكلام مفتوح للتفسير، فبيطلّع حاجة جنب اللي إنت متخيّله.",
      "label": "FAILURE — وصف طويل بدون مثال"
    },
    "right": {
      "body": "بتقوله: \"على نمط 'رائحة بتفضّل بعدك' — اعملي 5 زيّه\". الـ AI شاف الشكل والمزاج والطول، فبيقلّد بدقة. مثال واحد = 100 كلمة شرح.",
      "label": "RIGHT — مثال + تعليمة قصيرة"
    },
    "title": "إمتى تستخدم إيه"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "حل الأسئلة عشان تطبق اللي فهمته وتثبت المعلومة.",
    "highlight": "طبق اللي اتعلمته",
    "eyebrow": "دورك دلوقتي",
    "title": "جرّب Few-shot في دقيقتين"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [276, 289, 239, 245, 219, 210, 214, 827, 623, 827, 478];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
