// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "الـ Agent محتاج هدف + أدوات + حدود",
    "title": "هتفهم إيه النهاردة؟",
    "subtitle": "مش بس ردود كلام.",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "العميل: «عايز ألغي اشتراكي». الـ AI: «روح Settings → Billing → Cancel».",
      "العميل قفل الشات متضايق — إنت رميتله تعليمات بدل ما تخلّص له المشكلة.",
      "Chatbot بيرد. Agent بينفّذ — بس لازم أدوات محددة وحدود واضحة."
    ],
    "title": "الـ AI وصف الحل — بس ما نفّذش"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Agent = AI ياخد قرارات ويستخدم tools (functions) عشان ينفّذ في العالم الحقيقي.",
      "Tools زي `cancelSubscription` أو `searchOrders` — الـ Agent يختار إمتى يستخدمهم.",
      "Boundaries (حدود): إيه خارج النطاق — زي «ما تمسحش بيانات من غير تأكيد» أو «ما تدفعش من غير موافقة»."
    ],
    "title": "Agent = هدف + أدوات + حدود"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "Chatbot بيقول vs Agent بيعمل",
    "left": {
      "label": "Chatbot — كلام بس",
      "body": "«عشان تلغي، اعمل كذا وكذا». العميل لسه محتاج يتحرك بنفسه — حس إن الـ AI ديكور."
    },
    "right": {
      "body": "يستخدم `getSubscription` → يسأل «أكّد الإلغاء؟» → `cancelSubscription`. المهمة خلصت في ٢٠ ثانية.",
      "label": "Agent — تنفيذ"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "AI ياخد قرارات وينفّذ — مش بس يرد بكلام.",
    "tag": "يلغي اشتراك، يغيّر ميعاد",
    "term": "Agent"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "زي الشيف بيستخدم سكينة",
    "term": "Tool (أداة)",
    "definition": "function في الكود الـ Agent يقدر يستدعيها — زي `sendEmail` أو `findOrder`."
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/concepts/agents-diagram.jpg",
    "caption": "Think → Act (أداة) → Observe (النتيجة) → كرّر لحد ما المهمة تخلص. ده اللي يخلّيه يحل مشاكل من كذا خطوة.",
    "title": "دايرة تفكير الـ Agent",
    "eyebrow": "شوفها ببساطة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "highlight": "الـ Agent يبدأ بإيه؟",
    "eyebrow": "دورك دلوقتي",
    "tagline": "جمع معلومات قبل ما تنفّذ.",
    "title": "سؤال واحد — مش امتحان"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ Agent = هدف + tools + حدود — مش chatbot بس.",
      "تقدر تعمل إيه؟ عندك تصميم Agent بأداتين وحد واحد."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "highlight": "الـ Agent مش chatbot",
    "eyebrow": "الخلاصة",
    "tagline": "نتقابل في الدرس الجاي!",
    "title": "ملخص الدرس"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [420, 613, 715, 616, 399, 612, 501, 415, 423, 329];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
