// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أهلًا يا صاحبي",
    "highlight": "ليجو الـ Frontend",
    "subtitle": "هتقسّم كل صفحة لقطع صغيرة بتتكرّر.",
    "title": "Components:"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "واجهة المستخدم",
    "term": "Frontend",
    "definition": "وش البرنامج أو الموقع، ده الجزء اللي اليوزر بيشوفه ويتعامل معاه."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "قطعة قابلة لإعادة الاستخدام",
    "term": "Component",
    "definition": "قطعة من واجهة الموقع بتقدر تكرر استخدامها في كذا مكان."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "بيانات الـ Component",
    "term": "Props",
    "definition": "المعلومات اللي بتبعتها للـ Component عشان يغير شكله أو محتواه."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "حالة الـ Component",
    "term": "State/Stateful",
    "definition": "حالة الـ Component الحالية، زي هل الزرار ده مضغوط ولا لأ؟"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تنقل الصفحات",
    "term": "TanStack Router",
    "definition": "الأداة اللي بتتحكم في نقل اليوزر بين صفحات الموقع المختلفة."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Component هو قطعة UI قابلة لإعادة الاستخدام زي زرار أو كرت.",
      "بتكتب الكود مرة واحدة وتستخدمه كذا مرة بقيم مختلفة.",
      "القيم اللي بتدخل للـ component اسمها Props.",
      "الـ Props بتخلي الـ component يطلع أشكال مختلفة بنفس التصميم من غير تكرار.",
      "الـ Route صفحة كاملة لها URL، والـ Component قطعة جوه الصفحة.",
      "الـ Route نفسه component بس مربوط بـ URL في نظام الـ routing.",
      "قاعدة التقسيم (single responsibility): كل component يعمل حاجة واحدة.",
      "لو الـ component بتاعك كبير ومسؤول عن حاجات كتير، قسّمه."
    ],
    "title": "Component = قالب + بيانات (Props)"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "title": "Case Study — نفس الـ Component بـ Props مختلفة",
    "src": "lessons/builder-m6-components-routes.jpg",
    "eyebrow": "من المنصة",
    "caption": "الصورة دي بتشرح هرم الـ components في صفحة واحدة. الـ Route هو /curriculum. جواه PathCard مرة لـ Creator ومرة لـ Automator — نفس الـ component، props مختلفة. جوّه كل PathCard فيه ModuleCard — برضه نفس الـ component، بيتكرّر بـ data مختلفة. وجوّه كل ModuleCard فيه LessonRow. 3 levels من الـ components، كل واحد له شغلة واحدة. لو غيّرت تصميم LessonRow في ملف واحد، كل الدروس في كل الصفحات هتتغيّر تلقائيًا."
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "أول مرة اكتبها عادي، تاني مرة copy-paste، تالت مرة استخرجها لـ component بـ props. كده مفيش over-engineering ولا chaos.",
      "label": "RIGHT — قاعدة \"3 مرات\" (Rule of Three)"
    },
    "left": {
      "body": "هتلاقي عندك 3 نسخ من نفس الكود. لما تيجي تغير حاجة، هتنسى أماكن وهتخلي التطبيق inconsistent. هتقع في bugs بسبب فرق بسيط بين النسخ.",
      "label": "FAILURE — كل صفحة تكتب كل حاجة من الأول"
    },
    "title": "متى تعمل Component جديد ومتى لأ"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "title": "حدّد components تطبيقك",
    "eyebrow": "دورك دلوقتي",
    "tagline": "طبّق اللي اتعلّمته عشان تفهم أكتر، وهنتقابل في الدرس الجاي: إزاي السيرفر بيعرف إن \"ده إنت\"؟",
    "highlight": "في 10 دقايق"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [468, 285, 325, 372, 366, 359, 1074, 904, 1001, 346];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
