// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "في 4 دروس بس فهمت اللي مبرمج محترف بياخد شهور عشان يفهمه: إزاي أي تطبيق في الدنيا بيشتغل من جوه. بريك سريع قبل ما نبدأ نبني فعلاً.",
    "chip": "أهلًا، بعد الدرس ده هتقدر",
    "highlight": "Phase 2",
    "title": "تشوف إنت بنيت إيه فعلاً"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "ديكور المطعم والمنيو",
    "term": "الواجهة (Frontend)",
    "definition": "اللي العميل بيشوفه ويدوس عليه"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "العقل اللي بيستقبل الطلبات وينفّذها",
    "term": "الكواليس (Backend)",
    "tag": "المطبخ اللي بيطبخ"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "المكان اللي التطبيق بيفتكر فيه كل حاجة",
    "term": "المخزن الذكي (Database)",
    "tag": "مخزن المكونات"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "Lovable بيعمل التلاتة بنفسه",
    "bullets": [
      "إنت فاهم الـ 3 طبقات دلوقتي.",
      "مش لازم تكتب الكود بإيدك.",
      "Lovable بيبني الواجهة، وبيجهّز الكواليس، وبيعمل المخزن.",
      "إنت دورك تقوله إنت عايز إيه."
    ]
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "اربط كل طبقة بشغلها",
    "highlight": "في 30 ثانية",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر نفسك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [484, 382, 357, 453, 436, 330];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
