// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "هتفهم إيه النهاردة؟",
    "chip": "أهلًا | بداية الدرس",
    "subtitle": "ليه دلوقتي؟ المستخدم بيحس بالمنتج من نبرة المساعد والنصوص. نفس المعلومة بإحساس مختلف = منتج مختلف. هتعمل إيه بعد الدرس؟ هتكتب Voice Profile قصير لمساعد أو محتوى.",
    "highlight": "إزاي تخلي AI يتكلم بصوتك — مش بصوت «ChatGPT العام»."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "طلبت وصف برفان — وطلع: «اكتشف سحر الرائحة الفاخرة التي تأسر القلوب...»",
      "ده مش صوتك — ده صوت تسويقي محفوظ. كل منتج AI من غير Style Guide هيطلع نفس الكلام.",
      "Personalization = تحدّد النبرة والكلمات اللي تمثّلك — قبل ما المستخدم يشوف أول رد."
    ],
    "title": "«اكتب وصف منتج» — وطلع كليشيه"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Style = الشكل: رسمي ولا كاجوال؟ نقط ولا فقرات؟",
      "Tone = الإحساس: هادي، حماسي، مطمّن؟",
      "Persona = الشخصية الكاملة: «اتكلم كأنك خبير قهوة بيكلم مبتدئ».",
      "في Builder: Voice Profile في الـ System Prompt = كل رد يبان إنه من منتجك — مش من أي شات عام."
    ],
    "title": "AI بصوتك = تجربة مخصّصة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "طلب عايم vs طلب بنبرة",
    "left": {
      "body": "«اكتب وصف برفان.» — نبرة تسويقية مكررة: «فاخر»، «سحر»، «أسر القلوب».",
      "label": "طلب عايم"
    },
    "right": {
      "body": "«اكتب وصف برفان — نبرة شاعر هادي، جملتين، من غير ‚فاخر‘ أو ‚سحر‘، للقرّاء.» — «ريحة بتفضل في الأوضة بعد ما تقفل الكتاب.»",
      "label": "طلب بنبرة"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Tone (النبرة)",
    "definition": "الإحساس اللي بيوصل من الكلام — رسمي، ودود، حماسي، هادي.",
    "tag": "إيميل لعميل (رسمي) ≠ دردشة مع صاحب (ودود)."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "«جمل قصيرة، عامية مصرية، من غير كلمات تسويقية — استبدل ‚فاخر‘ بـ ‚مريح‘.»",
    "term": "Voice Profile (ملف الصوت)",
    "definition": "وصف قصير لأسلوب كلام منتجك — تضيفه في System Prompt."
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "eyebrow": "شوفها ببساطة",
    "src": "lessons/builder-m2-l3-style-control.jpg",
    "caption": "«تنفيذ قبل التنظير»، «نظام مش فوضى» — جمل قصيرة، موقف واضح. ده نتيجة Prompt حدّد النبرة: manifesto، من غير كليشيهات. نفس المعنى بنبرة «تسويقية» كان هيبان منتج تاني.",
    "title": "نبرة واضحة — مش صدفة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "eyebrow": "دورك دلوقتي",
    "highlight": "سؤال واحد — مش امتحان",
    "tagline": "طبّق اللي فهمته في سؤال سريع عشان تثبّت المعلومة.",
    "title": "اختبر فهمك"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "فهمت إيه؟ Style و Tone = هوية المنتج في كل رد AI.",
      "تقدر تعمل إيه؟ Voice Profile جاهز تضيفه في System Prompt."
    ],
    "title": "إيه اللي عندك دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [769, 208, 923, 207, 636, 343, 276, 400, 618];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
