// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "تعمل إيه؟",
    "subtitle": "لو الواجهة معقدة أو مش مريحة، محدش هيثق في الـ AI بتاعك أصلًا.",
    "title": "الـ AI طلعلك واجهة شكلها وحش",
    "chip": "الـ AI مش دايماً بيفهمك من أول مرة"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "«في واجهة الشات، خلي لون زرار 'ابعت' برتقاني #FF6B35. وخلي الكلام اللي جواه لونه أبيض. متغيّرش أي حاجة تانية.» تعديل محدد = نتيجة مضمونة.",
      "label": "صح"
    },
    "title": "إزاي تطلب تعديل يطلّع نتيجة مضمونة",
    "left": {
      "body": "لما تقول للـ AI 'الواجهة شكلها وحش، غيّرها'، هو مش بيفهم يعني إيه وحش. هيخمن وممكن يبوظ حاجات كانت شغالة صح، ودي بنسميها Regression. بعد ساعة تلاقي الواجهة بقت أسوأ من الأول.",
      "label": "غلط"
    }
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "src": "lessons/unique/builder-m6-l17-iteration.jpg",
    "title": "شغلك عبارة عن لفّات من 4 خطوات بسيطة",
    "caption": "دي اسمها لفة التحسين (Iteration Loop). كل لفة بتقربك للواجهة المثالية للـ AI بتاعك. أي واجهة محترفة بتاخد 4-7 لفات عشان تظبط. الخطوات هي: اطلب (Prompt)، شوف النتيجة (Result)، راجع (Review)، وبعدين عدّل (Refine) بطلب تعديل واحد بس ومحدد.",
    "eyebrow": "السيستم الصح"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "تجربة وتصليح",
    "definition": "إنك تعمل لفة كاملة من: التجربة، وملاحظة الغلط، وتصليحه، والتجربة تاني عشان تقرّب من الهدف.",
    "term": "Iteration / لفة التحسين"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Surgical Edit / تعديل جراحي",
    "tag": "تعديل محدد",
    "definition": "إنك تطلب تعديل واحد بس، محدد جدًا، عشان تضمن النتيجة ومتلخبطش الـ AI."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تصليح يبوظ",
    "definition": "لما تصلح حاجة، فتبوظ حاجة تانية كانت شغالة كويس.",
    "term": "Regression / حاجة تبوظ غصب عنك"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "highlight": "طبق اللي اتعلمته",
    "eyebrow": "دورك دلوقتي",
    "tagline": "حلّ الأسئلة عشان تشوف إزاي تطبق مبادئ التحسين دي في شغلك.",
    "title": "اختبر قدرتك على التحسين"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [387, 497, 565, 502, 432, 408, 316];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
