// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "أهلًا بيك يا صاحبي",
    "title": "بنيت نظام، شغل سليم",
    "subtitle": "إزاي أحمد وقع في فخ الـ Reactive Relapse؟",
    "highlight": "وبعدين فجأة رجعت تطفي حرايق"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Reactive Mode",
    "definition": "حالة بتكون فيها بتاكل ردود أفعال على الأحداث طول الوقت بدون خطة.",
    "tag": "أحمد بيرد على واتساب"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Relapse",
    "definition": "الرجوع لعادة قديمة بعد ما اتعلمت أحسن.",
    "tag": "أحمد رجع لـ admin شغل"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "موظف ساب الشغل",
    "term": "Crisis Trigger",
    "definition": "حدث محدد بيخلّيك تنسى النظام وترجع للحرايق."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "كل سبت، أحمد يحط رقم",
    "term": "Reactive Audit",
    "definition": "تشيك أسبوعي بسيط: قضيت كم ساعة strategic vs reactive؟"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "System Anchor",
    "definition": "ميعاد ثابت بيرجعك للنظام مهما حصل — مش قابل للتأجيل.",
    "tag": "أحمد بيراجع الـ Time Audit"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Strategic Block اتلغى أو اتنقل أكتر من ٣ مرات في أسبوع.",
      "بترد على واتساب فوراً — مش في ميعاد محدّد.",
      "بتشرح نفس الحاجة لموظفين بدل ما تحوّلهم للـ SOP.",
      "آخر مرة فكّرت في نمو البيزنس كانت من أسبوعين+."
    ],
    "title": "٤ علامات بتقولّك إنك رجعت Reactive"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "\"كل سبت هكلّمك. هقولك: كم ساعة strategic، كم ساعة admin، كم Strategic Block اتلغى، وأكبر أزمة الأسبوع. إنت تقولي: هل أنا في Reactive Relapse؟ على مقياس ١-١٠، إيه الرقم؟ وإيه الـ ٣ خطوات الأسبوع الجاي عشان أرجّع نفسي للنظام؟\""
    ],
    "title": "Weekly Reactive Audit"
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "أحمد حجز سبت ٧ صباحاً كـ Reactive Audit ثابت. حتى لو في أزمة، بيقعد ٣٠ دقيقة بس. ده بينبّهه قبل ما يتعمّق في الـ relapse.",
      "label": "RIGHT — System Anchor"
    },
    "title": "علاج مؤقت vs قاعدة دائمة",
    "left": {
      "body": "أحمد قال \"الأسبوع ده استثناء\". الاستثناء بقى عادة. النظام اتسحب من تحت رجليه في شهرين بدون ما يحس. لما حس، كان صعب يرجع.",
      "label": "FAILURE — \"مؤقتاً هرجع\""
    }
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "احجز ميعاد ثابت أسبوعي (٣٠ دقيقة) في الكالندر — اسمه \"Reactive Audit\". اختار وقت مفيش فيه أي حاجة (٧ صباحاً، يوم إجازة).",
      "اكتب الـ ٤ علامات اللي فوق في مكان هتشوفه أثناء الـ Audit.",
      "اعمل جدول بسيط في Notion: التاريخ / Strategic Hours / Admin Hours / علامات Relapse / الرقم من ١-١٠.",
      "في أول Audit، الصق الـ Prompt القاتل في AI وادّيله الأرقام بتاعتك.",
      "خد الـ ٣ خطوات اللي AI اقترحها واكتبها كـ \"خطة الأسبوع الجاي\".",
      "في الـ Audit التاني، قارن — تحسّن ولا اتدهور؟"
    ],
    "title": "اعمل System Anchor الأسبوع ده"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "highlight": "حلّ الأسئلة دي",
    "tagline": "عشان تتأكد إنك هتعرف ترجع للنظام بسهولة.",
    "title": "اختبر فهمك للـ Reactive Relapse",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "الخلاصة",
    "tagline": "وعشان تكمل بناء نظامك، شوف الدرس الجاي: أسبوعك مش ٧ أيام عشوائية — هو ٤ مسارات متوازنة",
    "title": "الـ Reactive Relapse مش نهاية العالم",
    "highlight": "بس لازم تكون واعي ليه"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [435, 481, 370, 430, 402, 460, 502, 490, 526, 491, 351, 501];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
