// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "صاحب مطعم خسر ٤٠ ألف جنيه وشهرين عشان وظّف غلط.",
    "highlight": "اسأل: المهمة دي محتاجة إنسان فعلاً؟",
    "chip": "أهلًا",
    "title": "قبل ما توظّف"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "المدير ساب الشغل بعد شهرين.",
      "أحمد رجع ينفّذ كل حاجة بنفسه.",
      "خسر ٤٠ ألف جنيه، وده غير الشهرين اللي ضاعوا."
    ],
    "title": "النتيجة؟ أحمد خسر ٤٠ ألف جنيه وشهرين!"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "أحمد اكتشف إن ٧٠% من مهامه بتتعمل بـ AI",
    "bullets": [
      "جلس مع AI ورسم كل المهام.",
      "اكتشف إن ٧٠% منها مهام متكرّرة.",
      "ممكن تتأتمت بـ AI في يومين بس.",
      "الـ ٣٠% الباقية بس محتاجة إنسان حقيقي."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "النهاردة هتتعلم إزاي تفرّق بين المهام",
    "bullets": [
      "مهمة لازم تتعمل بإنسان.",
      "مهمة لازم تتعمل بـ AI.",
      "قبل ما تصرف جنيه واحد على توظيف."
    ]
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "تدّي مهمة لإنسان — موظف، فريلانسر، شريك.",
    "term": "Delegate",
    "tag": "أحمد يدّي شيف يطوّر منيو جديد."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تقرير المبيعات اليومي يتبعت تلقائياً الساعة ٩ صباحاً.",
    "term": "Automate",
    "definition": "تخلّي المهمة تتعمل لوحدها بأداة أو AI من غير تدخل بشري."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "الرد على \"إنتو فاتحين امتى؟\"",
    "definition": "مهمة بتتكرر بنفس الشكل تقريباً — قابلة للأتمتة.",
    "term": "Repeatable Task"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Judgment Task",
    "definition": "مهمة محتاجة قرار بشري، تعاطف، أو سياق متغيّر.",
    "tag": "عميل غاضب يطلب تعويض — محتاج إنسان."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Automation ROI",
    "definition": "نسبة بين تكلفة الأتمتة (ساعات + أدوات) والوقت اللي بتوفّره.",
    "tag": "لو هتوفّر ٥ ساعات أسبوعياً الـ ROI ممتاز."
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "المهمة بتتكرر بنفس الشكل أكتر من ٥ مرات في الأسبوع؟ ← كانديدت للأتمتة.",
      "المهمة محتاجة حكم بشري على مواقف متغيرة؟ ← محتاج إنسان.",
      "المهمة محتاجة تعاطف، علاقات، أو تفاوض؟ ← محتاج إنسان.",
      "المهمة عبارة عن نقل بيانات أو تنسيق أو إرسال؟ ← AI أرخص وأسرع."
    ],
    "title": "٤ أسئلة قبل أي قرار توظيف"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "title": "٤ أسئلة قبل أي قرار توظيف",
    "bullets": [
      "المهمة محتاجة حكم بشري على مواقف متغيرة؟ ← محتاج إنسان.",
      "المهمة محتاجة تعاطف، علاقات، أو تفاوض؟ ← محتاج إنسان."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "٤ أسئلة قبل أي قرار توظيف",
    "bullets": [
      "المهمة عبارة عن نقل بيانات أو تنسيق أو إرسال؟ ← AI أرخص وأسرع."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "\"دي قايمة بكل المهام اللي بفكر أوظّف حد عشانها: [اكتبهم]. صنّف كل واحدة في عمود من ٣: AUTOMATE / DELEGATE / KEEP MYSELF. في كل صف اكتب السبب في سطر واحد + اقتراح أداة الأتمتة لو AUTOMATE.\""
    ],
    "title": "الـ Prompt القاتل: Delegate vs Automate Auditor"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "أتمت كل اللي يقدر AI يعمله. شوف اللي فاضل. لو ٣٠% بس محتاجة إنسان، ممكن تستعين بـ part-time أو فريلانسر — بدل ٧٢ ألف جنيه في السنة.",
      "label": "RIGHT — أتمت الأول"
    },
    "title": "الفخ اللي وقع فيه أحمد",
    "left": {
      "body": "أحمد افتكر إن الحل = إنسان. وظّف مدير بـ ١٢ ألف. ٧٠% من شغله كان نقل بيانات وإرسال تقارير — AI كان بيعملها في ١٠ دقايق. خسر فلوس ووقت.",
      "label": "FAILURE — وظّف الأول"
    }
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "افتح Google Sheet جديد بـ ٤ أعمدة: المهمة / تكرارها أسبوعياً / AUTOMATE-DELEGATE-KEEP / السبب.",
      "اكتب كل مهمة بتعملها بنفسك أو فكّرت توظّف عشانها (حتى لو ١٠ مهام بس).",
      "افتح AI. الصق الـ Prompt القاتل مع قايمتك."
    ],
    "title": "اعمل Audit للمهام في ٢٠ دقيقة"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "اعمل Audit للمهام في ٢٠ دقيقة",
    "bullets": [
      "خد رد AI، حطّه في الـ Sheet، وراجع كل صف — هل موافق على التصنيف؟",
      "اختار مهمة واحدة بس من عمود AUTOMATE — الأسهل والأكثر تكراراً. ده مشروعك الأسبوع ده."
    ]
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "حل الأسئلة دي عشان تتأكد إنك مستعد للخطوة الجاية.",
    "highlight": "قبل ما نكمل، شوف إنت فهمت الدرس ده كويس ولا لأ.",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [591, 407, 601, 438, 421, 521, 423, 429, 504, 455, 441, 330, 484, 555, 418, 516, 385];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
