// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "هو اللي بيوصّل الـ ٤ مسارات لبعضها",
    "subtitle": "أحمد دلوقتي عنده نظام تشغيل كامل، بس اكتشف إن مسار Business لوحده مش كافي. لازم يربط الـ ٥ مسارات في إيكوسيستم متكامل.",
    "chip": "أهلًا، مسار Business",
    "title": "Business مش مسار لوحده"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "Business بيقرّر، Analyst بيقيس.",
    "term": "Ecosystem",
    "definition": "منظومة متكاملة من المسارات الـ ٥ بتشتغل مع بعض بدل ما تكون منعزلة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Conductor Role",
    "definition": "دور القائد اللي بيحدّد كل مسار يلعب امتى وإزاي.",
    "tag": "أحمد بيقرّر إن Analyst يحلّل."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "Analyst + Creator: بيانات بتتحوّل لقصة.",
    "term": "Cross-Track Synergy",
    "definition": "لما مسارين بيشتغلوا مع بعض بيطلّعوا نتيجة أكبر من جمعهم."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Workflow Stack",
    "definition": "تسلسل واضح: المسار ده بياخد input من فين، وبيدّي output لمين.",
    "tag": "Analyst → Business → Automator → Creator."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Integration Audit",
    "definition": "مراجعة دورية: هل المسارات الـ ٥ بتتكلم مع بعض ولا كل واحد لوحده؟",
    "tag": "أحمد كل شهر يشوف: هل في مسار شغّال في عزلة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Analyst — بيكشف المشكلة بالأرقام (مثلاً: Retention 18%).",
      "Business — بيحدّد القرار (نشتغل على Retention قبل أي حاجة).",
      "Automator — بيبني الـ workflow (رسالة بعد كل أوردر).",
      "Creator — بيكتب الرسالة بصوت البراند.",
      "Builder — بيبني الأداة لو محتاج شيء مخصّص (تطبيق ولاء مثلاً)."
    ],
    "title": "إزاي نربط الـ ٥ مسارات في workflow واحد؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "\"عندي مشكلة في بيزنسي [اوصفها]. صمّم لي workflow بيستخدم الـ ٥ مسارات (Business, Analyst, Automator, Creator, Builder) بالترتيب. لكل مسار: ١) دوره في الحل. ٢) الـ input اللي بياخده. ٣) الـ output اللي بيدّيه. ٤) أداة AI واحدة محدّدة هستخدمها.\""
    ],
    "title": "الـ Prompt القاتل: 5-Track Ecosystem Designer"
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "أحمد يبدأ من Analyst (إيه المشكلة؟)، يقرّر بـ Business، يبني بـ Automator، يوصّل بـ Creator. كل مسار بيدخل في التاني. نتيجة: شغل أقل، أثر أكبر.",
      "label": "RIGHT — ecosystem"
    },
    "left": {
      "body": "أحمد يستخدم Creator لمحتوى عشوائي بدون أرقام من Analyst. يكتب أتمتة بدون قرار من Business. كل مسار شغّال لوحده — نتيجة: شغل كتير، أثر قليل.",
      "label": "FAILURE — منعزل"
    },
    "title": "مسارات منعزلة vs ecosystem متكامل"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "اختار مشكلة حقيقية في بيزنسك دلوقتي (Retention ضعيف، مبيعات ثابتة، فريق مش منتج).",
      "افتح AI. الصق الـ Prompt القاتل مع المشكلة بتاعتك.",
      "خد الـ workflow اللي طلع، وارسمه على ورقة كـ flow chart (مربع لكل مسار + سهم بين كل اتنين).",
      "لكل مسار، حدّد: الأداة اللي هتستخدمها + الوقت المتوقع + المسؤول (إنت، فريق، AI).",
      "نفّذ أول خطوتين فقط (Analyst + Business) الأسبوع ده. مش لازم تنفّذ الـ ٥ مرة واحدة.",
      "وثّق الـ workflow في \"Business OS\" بتاعك — هتعيد استخدامه لمشاكل تانية."
    ],
    "title": "صمّم workflow حقيقي يربط الـ ٥ مسارات"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "title": "اختبر فهمك",
    "eyebrow": "دورك دلوقتي",
    "tagline": "خش دلوقتي وجاوب على الأسئلة عشان تتأكد إنك فهمت",
    "highlight": "شوف إزاي تربط كل حاجة ببعضها"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "title": "صمّم ونفّذ workflow حقيقي يربط ٥ مسارات",
    "eyebrow": "Mission",
    "tagline": "نتقابل في الدرس الجاي: النظام بتاعك الشخصي خلص — دي اللحظة اللي بتغيّر كل حاجة",
    "highlight": "ده الاختبار النهائي للـ Business OS بتاعك. مش درس — هو تخرّج."
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [647, 357, 376, 437, 468, 442, 843, 642, 930, 846, 354, 583];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
