// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "أحمد كان متحمس للتوسع بعد ما ظبط الـ Retention وزاد LTV، بس الـ Readiness Audit كشف مشاكل خطيرة خلّته يأجّل 4 شهور لحد ما ظبط الـ Process والموظفين وبقى System-Independent.",
    "title": "الإحساس بالنجاح",
    "highlight": "≠ الجاهزية للتوسع",
    "chip": "جاهزية التوسع"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "فحص الجاهزية",
    "definition": "فحص دقيق قبل أي توسع: هل النظام جاهز فعلًا؟",
    "term": "Readiness Audit"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Premature Scaling",
    "tag": "توسع مبكر",
    "definition": "تتوسع قبل ما تثبّت — تكبّر المشاكل بدل ما تحلّها."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "SOPs",
    "tag": "دليل التشغيل",
    "definition": "دليل مكتوب لكل خطوة شغل أساسية."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Cashflow Positive",
    "tag": "تدفق نقدي موجب",
    "definition": "بتدخل أكتر مما بتصرف — لمدة محسوبة."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "عنق الزجاجة",
    "definition": "نقطة واحدة بتعطّل كل النظام.",
    "term": "Bottleneck"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "System-Independent",
    "tag": "مستقل عنك",
    "definition": "البيزنس بيشتغل بدونك يومين متتاليين."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Cashflow موجب 6 شهور متواليين — مش شهر أو اتنين.",
      "Retention > 40% — العميل بيرجع لوحده، مش بتدفع إعلانات تجيبه تاني."
    ],
    "title": "الـ 5 علامات اللي لازم تكون موجودة"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "SOPs موثّقة لأهم 5 عمليات — أي حد يقدر يقرأها ويشتغل.",
      "Bottleneck مش إنت — لو غبت يومين، البيزنس بيشتغل عادي."
    ],
    "title": "الـ 5 علامات اللي لازم تكون موجودة"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "في طلب أكتر من قدرتك — السوق بيشدّك، مش إنت بتدفع نفسك."
    ],
    "title": "الـ 5 علامات اللي لازم تكون موجودة"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "عندي بيزنس [النوع، الحجم، عدد الموظفين]. عايز أعرف هل أنا جاهز أتوسع. هسجّلك حقيقتي بدون تجميل: ١) Cashflow آخر 6 شهور: [أرقام]، ٢) Retention rate: [%]، ٣) SOPs موثّقة: [نعم/لا + لأي عمليات]، ٤) لو غبت 3 أيام بيحصل إيه؟ [وصف]، ٥) الطلب الحالي: [أكتر من قدرتي / مساوي / أقل]."
    ],
    "title": "الـ Prompt القاتل: Readiness Auditor"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "قيّم كل علامة من 10، حدّد القرار (اتوسّع / أأجّل / اصلّح أولًا)، واقترح أول حاجة لازم تتعمل."
    ],
    "title": "الـ Prompt القاتل: Readiness Auditor"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "اقعد لوحدك 30 دقيقة بدون مقاطعة. ده قرار مصيري، مش حاجة تعملها في الزحمة.",
      "افتح AI والصق الـ Prompt القاتل. عبّيه ببياناتك الحقيقية — بدون تجميل، بدون \"ممكن\" أو \"تقريباً\"."
    ],
    "title": "اعمل Readiness Audit دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "خد التقييم اللي طلع — كل علامة من 10. اللي تحت 6 = خطر.",
      "اكتب القرار بصوت عالي: \"أنا [اتوسّع / أأجّل / اصلّح] لأن [سبب محدّد].\""
    ],
    "title": "اعمل Readiness Audit دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "لو القرار \"أأجّل\" أو \"اصلّح\": حدّد المدة (شهر، شهرين، 4؟) + أول 3 خطوات هتبدأ بيهم بكرة.",
      "احفظ الـ Audit. كرّره بعد المدة دي. ساعتها بس تاخد قرار التوسع بثقة، مش بحماس."
    ],
    "title": "اعمل Readiness Audit دلوقتي"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "highlight": "قبل أي قرار توسع",
    "tagline": "حلّ الأسئلة دي عشان تتأكد إنك فهمت إزاي تقيّم وضعك صح.",
    "title": "اختبر فهمك للجاهزية",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [438, 316, 339, 384, 370, 421, 400, 359, 336, 316, 468, 394, 334, 352, 412, 343];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
