// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "تمنع البيزنس من الفوضى",
    "highlight": "المراجعة الأسبوعية",
    "chip": "أهلًا | بداية الدرس",
    "title": "هتفهم إيه النهاردة؟"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "شغل كتير، طلبات وردود، وفي الآخر تلاقي الشهر خلص ومراجعتش أرقامك.",
      "الإيقاع اليومي يحمي يومك، والمراجعة الأسبوعية بتحمي اتجاه البيزنس كله.",
      "الـ AI بيجمع: ملخص مبيعات، مهام معلّقة، شكاوى عملاء — وإنت بتاخد قرار واحد."
    ],
    "title": "الأسابيع بتعدي — ومفيش «لحظة توقف»"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "٣٠ دقيقة — ٣ أرقام — ٣ أسئلة — قرار واحد",
    "bullets": [
      "اختار ٣ أرقام مهمة لبيزنسك (مبيعات، هامش، عملاء راجعين).",
      "اسأل الـ AI تلات أسئلة: إيه اللي اتغيّر؟ إيه المهام المعلّقة؟ وإيه نمط شكاوى العملاء؟",
      "خد قرار واحد بس للأسبوع الجاي، واكتبه في سطر واحد."
    ]
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Weekly Review (مراجعة أسبوعية)",
    "tag": "مراجعة للاتجاه",
    "definition": "وقت ثابت تراجع فيه الأرقام والإشارات وتسجّل قرارًا واحدًا."
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "body": "٣٠ دقيقة. ملخص واضح. قرار واحد مكتوب — والأسبوع الجاي بيكون عنده اتجاه.",
      "label": "مراجعة + AI"
    },
    "title": "أسبوع بدون مراجعة vs أسبوع بقرار",
    "left": {
      "body": "نفس المشاكل بتتكرر. القرارات بتفضل مؤجلة «لما يفضى وقت»، وعادةً الوقت ده مبيفضاش.",
      "label": "بدون مراجعة"
    }
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "أرقام → أسئلة AI → قرار.",
      "نفس اليوم كل أسبوع — حتى لو نصف ساعة فقط."
    ],
    "title": "Weekly Review"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "جاوب على السؤال عشان تتأكد إنك فهمت كويس.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "سؤال واحد",
    "title": "طبّق اللي اتعلّمته"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [395, 583, 547, 481, 492, 485, 276];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
