// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "HERO",
    "highlight": "مش محتاج إنت",
    "title": "٨٠٪ مش محتاج إنت",
    "subtitle": "بصّ في يومك. ٨ من ١٠ مهام ممكن حد تاني أو نظام يعملها. السؤال: تفوّض ولا تأتمت؟"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "تكليف بشري",
    "term": "Delegate",
    "definition": "إنك تكلف حد غيرك يعمل المهمة بس بشرفه البشري وتفكيره."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "شغل آلي",
    "term": "Automate",
    "definition": "تخلي برنامج أو سيستم يعمل المهمة لوحده من غير تدخلك خالص."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "خطوات عمل",
    "term": "SOP (Standard Operating Procedure)",
    "definition": "خطوات بسيطة ومكتوبة بتمشي عليها عشان تخلص مهمة معينة بدقة."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "نموذج جاهز",
    "term": "Template",
    "definition": "نموذج جاهز بتملاه عشان يسهل عليك المهمة، بس مش بيشتغل لوحده."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "بداية الأتمتة",
    "term": "Trigger (مُحفز)",
    "definition": "الشرارة أو الزرار اللي لما بيحصل بيخلي الأتمتة تبدأ تشتغل."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "نقطة توقف",
    "term": "Bottleneck (عنق الزجاجة)",
    "definition": "نقطة في الشغل بتخلي الدنيا تقف وتتعطل بسبب زحمة المهام عندها."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "متكرّرة + واضحة + قواعد ثابتة ← Automate (Automator).",
      "متكرّرة + محتاجة حكم بشري ← Delegate (ناس + SOP).",
      "غير متكرّرة + استراتيجية ← إنت بنفسك.",
      "متكرّرة + غامضة ← اكتب SOP الأول، وبعدها قرّر."
    ],
    "title": "قاعدة القرار"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "أربع خانات.",
      "كل مهمة في مكانها.",
      "Bot للقواعد.",
      "شخص للحكم."
    ],
    "title": "Matrix — تكرار × طبيعة المهمة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "Bot للروتيني. شخص للحكم. إنت للقرار الكبير. كل واحد بيحب اللي بيعمله.",
      "label": "RIGHT — كل مهمة في مكانها"
    },
    "left": {
      "body": "Bot بيرد على شكاوى معقّدة. العميل بيتضايق. السمعة بتأذى.",
      "label": "FAILURE — أتمت كل حاجة"
    },
    "title": "أتمت اللي محتاج حكم vs نظام صح"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "AI mission evaluation = 50 ساعة شغل/أسبوع.",
      "Email notifications = postgres triggers بسيطة.",
      "Lesson writing = AI draft + human edit."
    ],
    "title": "وزّعنا شغل بناءً على ROI: نأتمت أو نسيب"
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "eyebrow": "دورك دلوقتي",
    "tagline": "يلا طبق اللي اتعلّمته وجاوب على الأسئلة عشان تشوف فهمت إزاي تفرّق بين التفويض والأتمتة.",
    "highlight": "قرّر لـ ٥ مهام",
    "title": "قرّر لـ ٥ مهام"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "استعد للدرس الجاي عشان تعرف إمتى تكون جاهز إنك توسع شغلك.",
    "highlight": "علامات الجاهزية للتوسع",
    "title": "علامات الجاهزية للتوسع",
    "eyebrow": "الدرس الجاي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [447, 395, 365, 377, 363, 369, 316, 683, 370, 569, 585, 355, 305];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
