// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "وإنت لسه مش جاهز",
    "highlight": "هو إنك توسّع",
    "chip": "أهلًا",
    "title": "أخطر قرار تاخده"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "definition": "التوسّع قبل ما البيزنس الأصلي يكون مستقر وقابل للنسخ.",
    "term": "Premature Scaling",
    "tag": "توسّع قبل الاستقرار"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Product-Market Fit",
    "definition": "إثبات إن المنتج بحقّ بيحلّ مشكلة وعملاء بيرجعوا له بانتظام.",
    "tag": "منتج بيحل مشكلة"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "هل كل وحدة (طلب، عميل، فرع) بتربح فعلاً بعد كل المصاريف؟",
    "term": "Unit Economics",
    "tag": "ربح كل وحدة"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "قدرة الفريق على التوسّع",
    "term": "Operational Capacity",
    "definition": "قدرة الفريق والنظام يتحمّلوا التوسّع بدون انهيار الجودة."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "اختبار البيزنس الصعب",
    "term": "Stress Test",
    "definition": "اختبار البيزنس في موقف صعب قبل التوسّع — مثلاً غيابك أسبوع."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "٥ أسئلة لازم تجاوب عليهم بـ \"آه\" قبل التوسّع",
    "bullets": [
      "Retention أعلى من ٤٠% آخر ٣ شهور؟",
      "هامش الربح في كل وحدة محسوب وموجب فعلاً؟",
      "الـ SOPs مكتوبة وأي موظف جديد بيتدرّب فيها في أسبوع؟",
      "لو غبت أسبوع — البيزنس هيكمّل بدونك؟",
      "عندك cash reserve يكفي ٦ شهور لو التوسّع فشل؟"
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "الـ Prompt القاتل: Scaling Readiness Audit",
    "bullets": [
      "\"عندي بيزنس [اوصفه]. بفكّر أوسّع بـ [الخطة]. اسألني الـ ٥ أسئلة بتاعة Scaling Readiness بالترتيب، وانتظر إجابتي على كل واحدة قبل ما تنتقل للي بعدها. في الآخر، قولي بصراحة: جاهز ولا لأ؟ ولو لأ، إيه أهم سؤالين أركّز عليهم الـ ٣ شهور الجاية؟\""
    ]
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "أحمد بنى SOPs، رفّع الـ Retention لـ ٥٠%، درّب مدير ثاني صف. فتح فرع واحد — ربح من شهر ٢. فتح التاني بعد ٦ شهور — أنجح من الأصلي.",
      "label": "RIGHT — استنى ٤ شهور"
    },
    "title": "وسّع مبكّر vs استنّى وبنى",
    "left": {
      "body": "أحمد لو فتح ٣ فروع — كل فرع بيحتاجه شخصياً. جودة الأكل اختلفت. عملاء الفرع الأصلي اختفوا. بعد ٦ شهور قفل الـ ٣ وخسر مدخراته.",
      "label": "FAILURE — التوسّع المبكّر"
    }
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "اعمل Scaling Readiness Audit الأسبوع ده",
    "bullets": [
      "خد ورقة، اكتب الـ ٥ أسئلة، وجاوب على كل واحدة بـ \"آه\"، \"لأ\"، أو \"مش متأكد\".",
      "لكل \"مش متأكد\" — حدد رقم أو دليل تحتاجه عشان تجاوب بثقة.",
      "لكل \"لأ\" — اكتب الخطوة الأولى اللي محتاجها عشان تتحوّل لـ \"آه\".",
      "افتح AI. الصق الـ Prompt القاتل وخلّيه يسألك الأسئلة بالترتيب.",
      "اكتب التقييم النهائي من AI + خطة الـ ٣ شهور المقترحة.",
      "احفظ التاريخ — راجع الـ Audit بعد ٣ شهور بالظبط."
    ]
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك",
    "highlight": "هل فهمت الدرس كويس؟",
    "tagline": "حلّ الأسئلة عشان تتأكد إنك استوعبت كل حاجة وتطبق اللي اتعلمته صح."
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "اعمل Scaling Audit بصراحة",
    "bullets": [
      "إجاباتك على الـ ٥ أسئلة (\"آه\"، \"لأ\"، \"مش متأكد\") مع رقم/دليل لكل إجابة.",
      "عدد الـ \"آه\" — والتقييم العام (جاهز / مش جاهز).",
      "أول خطوتين هتشتغل عليهم الـ ٣ شهور الجاية.",
      "لو فكرت توسّع، إيه الـ Stress Test اللي هتعمله قبل القرار النهائي؟",
      "تاريخ مراجعة الـ Audit التانية (٣ شهور من النهارده)."
    ]
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "eyebrow": "الدرس الجاي",
    "title": "بنيت نظام، شغل سليم",
    "highlight": "وبعدين فجأة رجعت تطفي حرايق",
    "tagline": "هنشوف إزاي تحافظ على اللي بنيته من غير ما ترجع لنقطة الصفر."
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [316, 358, 331, 329, 331, 363, 303, 366, 399, 358, 309, 387, 383];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
