// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "الـ ٥ مسارات في يومك",
    "highlight": "شخص واحد + AI + System صح = Business كامل.",
    "chip": "أهلًا · الـ ٥ مسارات في يومك",
    "subtitle": "ده اللي كنت بتبنيه على مدار الرحلة."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "شغل متكامل",
    "term": "Ecosystem",
    "definition": "دائرة شغل كاملة، كل حتة فيها بتسلم اللي بعدها عشان المكنة تطلع قماش."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Leads parenting (Leads)Line",
    "definition": "زبون محتمل أبدى اهتمام، لسه مشتراش بس \"خيط\" ممكن يوصلك لبيعة.",
    "tag": "زبون محتمل"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Builder & Creator Roles",
    "definition": "الأدوار اللي بتقوم بيها؛ يا بتبني السيستم (Builder) يا بتعمل محتوى يشد الناس (Creator).",
    "tag": "باني ومُنشئ"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Automator",
    "definition": "برامج بتربط الشغل ببعضه عشان يشتغل \"أوتوماتيك\" من غير ما تدوس على زراير.",
    "tag": "شغل تلقائي"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Output to Input",
    "definition": "شغل بيخلص بيبقى هو البنزين اللي بيشغل الخطوة اللي بعدها علطول.",
    "tag": "مخرجات لمدخلات"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "روتين العمل",
    "term": "Operating Cadence index (Cadence)Index",
    "definition": "الروتين أو الجدول اللي بيمشي عليه الـ Ecosystem عشان ميفصلش منك."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Compounding",
    "definition": "مكاسب بسيطة فوق بعضها، مع الوقت بتعمل خبطة كبيرة ومفاجأة.",
    "tag": "مكاسب متراكمة"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "خبرتك + مشكلة حقيقية = نقطة البداية.",
      "Builder: System بيشتغل لوحده (المنتج).",
      "Creator: Leads بيجيبها المحتوى.",
      "Automator: كل حاجة تلقائية (الجمع + المتابعة).",
      "Analyst: الأرقام بتقولّك إيه اللي اشتغل.",
      "Business: إنت بتاخد القرارات الاستراتيجية بس — وبتديها للـ ٤ مسارات تنفّذ.",
      "النتيجة: شغل ينمو، وإنت بتشتغل أقل ساعات بقرار أكبر."
    ],
    "title": "الـ Loop الكامل"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "كل مسار بيغذّي اللي بعديه.",
      "إنت و الـ AI و السيستم في المركز."
    ],
    "title": "الـ ٥ مسارات — Ecosystem واحد"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "كل مسار لوحده vs ecosystem",
    "right": {
      "body": "كل مسار بيغذّي اللي بعديه. القرار الواحد بيلمس كل المنظومة. الشغل بقى نظام عضوي.",
      "label": "RIGHT — Ecosystem واحد"
    },
    "left": {
      "body": "Builder منفصل عن Creator. Creator منفصل عن Analyst. كل واحد شغّال بس مفيش loop.",
      "label": "FAILURE — مسارات منفصلة"
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "title": "ارسم Ecosystem-ك",
    "tagline": "وطبق اللي اتعلمته في الدرس ده",
    "highlight": "اختبر فهمك للـ ٥ مسارات",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الجزء ده من المنصة اتبنى بمسار Business، زي اللي بتتعلمه بالظبط.",
      "/journey بيوريك تقدّم المتعلم.",
      "/system-state بيوريك صحة الـ system.",
      "/roadmap بيوريك المستقبل.",
      "٣ صفحات بس بتدير Ecosystem كامل بشخص واحد و AI."
    ],
    "title": "/journey + /system-state + /roadmap = الـ ecosystem كامل"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [316, 301, 330, 335, 241, 271, 286, 257, 748, 333, 677, 297, 589];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
