// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "HERO",
    "subtitle": "أحمد عيّن أول Operations Manager، خد قرار في يومين ومشي بعد ٣ شهور. رجع تاني بالـ AI، وعيّن صح.",
    "highlight": "لو غلط، البيزنس بيتأخّر سنة",
    "title": "أول موظف بتعيّنه"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "مش مجرد اسم وظيفة",
    "term": "Job Description (JD)",
    "definition": "وصف مفصّل للوظيفة: المسؤوليات، النتايج المطلوبة، المعايير، الـ red flags."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "بتوظف على أساس النتايج اللي محتاجها مش على الـ titles.",
    "tag": "ركز على النتايج",
    "term": "Outcome-Based Hiring"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "كارت تقييم بمعايير ثابتة لكل candidate — يمنعك تختار بالـ \"feeling\".",
    "tag": "أرقام مش إحساس",
    "term": "Interview Scorecard"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "خطة أول شهر",
    "term": "Onboarding Plan",
    "definition": "خطة الـ 30 يوم الأول للموظف الجديد — مكتوبة قبل أول يوم."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "AI بيساعدك توظف",
    "term": "AI-Augmented Hiring",
    "definition": "استخدام AI في كل خطوة: كتابة JD، فحص CVs، interview questions، evaluating answers."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "اكتب الـ JD بمساعدة AI من الـ Outcomes اللي محتاجها — مش من الـ Title."
    ],
    "title": "٤ خطوات توظيف بالـ AI"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "وَلّد Interview Questions موجّهة لكل outcome — كل سؤال بيختبر معيار محدد.",
      "اعمل Scorecard ثابت — كل candidate يتقيّم بنفس المعايير."
    ],
    "title": "٤ خطوات توظيف بالـ AI"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "حضّر Onboarding Plan كامل قبل أول يوم — لازم الموظف يعرف بالظبط هيتعلّم إيه في كل أسبوع."
    ],
    "title": "٤ خطوات توظيف بالـ AI"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "\"عايز أعيّن [الوظيفة] في [نوع البيزنس]. النتايج المطلوبة في أول 90 يوم: [اذكرهم]. حجم البيزنس: [اذكره]. اكتبلي JD فيه: ١) ٥ مسؤوليات يومية، ٢) ٣ KPIs قابلة للقياس، ٣) ٥ مهارات لازمة + ٣ مفضّلة، ٤) ٣ red flags لازم أشوفهم في الـ interview، ٥) Onboarding Plan لأول 30 يوم.\""
    ],
    "title": "JD Generator Prompt"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "label": "RIGHT — توظيف بالـ AI",
      "body": "JD مبني على outcomes. Interview بـ scorecard. Onboarding plan جاهز. الموظف منتج من أول أسبوع. الـ retention أعلى 3 أضعاف."
    },
    "title": "توظيف عشوائي vs توظيف بالـ AI",
    "left": {
      "label": "FAILURE — توظيف بالـ feeling",
      "body": "JD نصف صفحة. Interview أسئلة عامة. اختيار بالانطباع. أول شهر فوضى — الموظف مش عارف ينفّذ إيه. بعد 3 شهور إما يمشي أو يطرد."
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "ابني نظام التوظيف بتاعك دلوقتي!",
    "eyebrow": "Build Along — قطعتك في الـ Business OS",
    "highlight": "هتطلع النهارده بـ 3 templates جاهزين تستخدمهم لأي وظيفة جاية.",
    "title": "اعمل JD + Onboarding Generator بتاعك"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "جاوب على الأسئلة عشان تطبق اللي اتعلمته!",
    "eyebrow": "دورك دلوقتي",
    "highlight": "يلا بينا على الكويز!",
    "title": "اختبر فهمك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [427, 346, 394, 375, 405, 485, 427, 443, 379, 402, 364, 343, 461];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
