// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "دي اللحظة اللي بتغيّر كل حاجة",
    "chip": "النظام بتاعك الشخصي خلص",
    "subtitle": "10 دقايق وبقى عارف يعمل إيه في يومه كله.",
    "highlight": "نظام تشغيل كامل"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Business OS",
    "definition": "نظام تشغيل شخصي للبيزنس — مكان واحد بيجمع كل قراراتك وأرقامك وأنظمتك.",
    "tag": "بدل 10 ملفات متفرقة، صفحة واحدة فيها كل حاجة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "لوحة بصرية بتعرض أهم الأرقام والمؤشرات بشكل فوري.",
    "tag": "أحمد بيفتح Notion صباحاً يلاقي: المبيعات أمبارح، أعلى منتج، عدد الـ leads، أحدث شكوى.",
    "term": "Dashboard"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Single Source of Truth",
    "definition": "مرجع وحيد لكل المعلومات — لا تكرار ولا تضارب.",
    "tag": "السعر مكتوب في مكان واحد. لو تغيّر، يتغيّر في مكان واحد. باقي النظام يأخذ منه."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "إيقاع ثابت لاتخاذ القرارات — يومي، أسبوعي، شهري.",
    "tag": "كل يوم: 10 دقايق صباحاً. كل أسبوع: ساعة جمعة. كل شهر: نص يوم آخر شهر.",
    "term": "Decision Cadence"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Compound System",
    "tag": "الـ feedback من العملاء يغذّي الـ SOPs. الـ SOPs تغذّي الـ hiring. الـ hiring يغذّي الـ scaling.",
    "definition": "نظام بيكبر قيمته مع الوقت لأن كل جزء بيغذّي الباقي."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Numbers Today: أهم 4 أرقام بتاريخ اليوم.",
      "Decisions Pending: القرارات اللي محتاجة تتاخد.",
      "Systems & SOPs: لينكات لكل الـ SOPs والـ templates.",
      "Customer Pulse: آخر 5 feedback وحالة الـ retention flow.",
      "Team & Hiring: حالة الـ team والـ JDs الجاهزة للتوظيف."
    ],
    "title": "5 Sections لازم تكون في الـ Dashboard بتاعك"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "عندي بيزنس [النوع، الحجم، عدد الموظفين]. عندي الأنظمة دي جاهزة: [list من اللي بنيته].",
      "عايز Notion Dashboard مفرد. اقترحلي: Layout بـ 5 sections، إيه يدخل لكل section، إيه التحديث المطلوب يومي/أسبوعي/شهري، إزاي أربط الأنظمة مع بعض عشان مكررش بيانات."
    ],
    "title": "Dashboard Architect Prompt"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "اعمل صفحة جديدة في Notion اسمها 'My Business OS'.",
      "ضيف 4 boxes لـ 'Numbers Today' و list لـ 'Decisions Pending'.",
      "اعمل toggle list لـ 'Systems & SOPs' و اربط بـ 'Customer Pulse'.",
      "ضيف لينكات لـ 'Team & Hiring' و 'Decision Cadence' في آخر الصفحة."
    ],
    "title": "اجمع كل اللي بنيته في Dashboard واحد"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "يلا نطبّق اللي اتعلّمناه ونشوف فهمك وصل لفين.",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك",
    "highlight": "اختبر فهمك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [421, 423, 375, 399, 438, 456, 783, 803, 845, 279];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
