// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "هتفهم إيه النهاردة؟",
    "subtitle": "الـ AI يحسّن كل محطة.",
    "chip": "أهلًا",
    "highlight": "العميل رحلة مش صفقة."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كتير بيشوفوا العميل = «حد اشترى وخلاص».",
      "نسبة الرجوع ضعيفة — والتكلفة تزيد كل شهر.",
      "المشكلة غالبًا في محطة ضعيفة في الرحلة.",
      "الـ AI يساعدك بس لازم تعرف فين التسريب."
    ],
    "title": "بتصرف على إعلانات — والعملاء مش بيرجعوا"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Awareness (وعي): العميل عرف إنك موجود.",
      "Consideration (تفكير): بيقارن بينك وبين غيرك.",
      "Purchase (شراء): أول صفقة فعلية.",
      "Retention (احتفاظ): يرجع تاني.",
      "Advocacy (ترشيح): يقول لغيره.",
      "الـ AI يساعد في الرسائل، بس التشخيص يبدأ من رسم الرحلة."
    ],
    "title": "٥ محطات — وكل محطة فرصة"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "كل المحطات من أول سماع عنك لحد الترشيح — مش لحظة الشراء بس.",
    "tag": "من السماع للترشيح",
    "term": "Customer Journey (رحلة العميل)"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "فين التسريب؟",
    "term": "Weakest Stage (أضعف محطة)",
    "definition": "المحطة اللي أكتر ناس بتقع عندها — تحسينها أغلبًا أرخص من جلب عملاء جداد."
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "right": {
      "body": "ترسم الرحلة، تكتشف إن المتابعة بعد الشراء ضعيفة. رسالة بسيطة + متابعة بالـ AI — نفس العملاء يرجعوا أكتر.",
      "label": "تصلّح أضعف محطة"
    },
    "left": {
      "body": "تزود الإعلانات. العملاء الجداد ييجوا — بس نفس النسبة ما بترجعش. التكلفة تطلع والربح يثبت.",
      "label": "تركّز على جلب جداد بس"
    },
    "title": "إعلانات أكتر vs إصلاح محطة ضعيفة"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "خريطة الـ ٥ محطات",
    "bullets": [
      "فكّرها قمع: كل محطة فيها ناس بتكمل وناس بتوقف.",
      "الهدف تعرف فين التسريب.",
      "مش بس تملى القمع من فوق."
    ]
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد — مش امتحان",
    "tagline": "جاوب السؤال عشان تتأكد إنك فهمت الدرس.",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "طبق اللي اتعلمته",
    "tagline": "المهمة دي تطبيق على بيزنسك — مش نظرية.",
    "eyebrow": "مهمتك",
    "title": "ارسم رحلة عميل — وحدّد الضعف"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "eyebrow": "خلّصت بداية النمو",
    "title": "إيه اللي عندك دلوقتي؟",
    "tagline": "شوفك في الدرس الجاي.",
    "highlight": "ملخص الدرس"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [623, 775, 1063, 370, 379, 793, 414, 274, 283, 439];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
