// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الـ AI يحوّل شرحك لـ SOP بسيط.",
    "chip": "بداية الدرس",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "النظام واضح الأول"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "وظّفت حد — وبقيت تشرح نفس الحاجة كل يوم",
    "bullets": [
      "موظف جديد يسأل «أعمل إيه لو العميل قال كذا؟» — وإنت ترد من الذاكرة. كل يوم نفس الشرح.",
      "ده مش فشل الموظف — ده غياب نظام. من غير SOP، كل توظيف يضيف شغل إدارة على رأسك.",
      "الـ AI ياخد شرحك العادي ويرتّبه: خطوات، متى، مثال، استثناء — إنت تراجع وتختبر قبل التوسّع."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الخطوة ١: اكتب العملية زي ما بتشرحها لصاحبك — حتى لو فوضوي.",
      "الخطوة ٢: الـ AI يرتّبها SOP: هدف، خطوات مرقّمة، مثال، «لو حصل كذا».",
      "الخطوة ٣: جرّب الـ SOP بنفسك أو بمساعد مؤقت — عدّل اللي مش واضح.",
      "الخطوة ٤: بعد ما يشتغل مرتين بنفس الجودة — فكّر في توظيف أو تفويض."
    ],
    "title": "نظام → SOP → اختبار → ناس"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "طريقة ثابتة",
    "term": "SOP (إجراء قياسي)",
    "definition": "طريقة ثابتة لتنفيذ مهمة متكررة — أي حد يقدر يتبعها."
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "left": {
      "label": "ناس قبل نظام",
      "body": "كل موظف يعمل بطريقته. إنت وسط — بتوحّد، بتراجع، بترجع Reactive."
    },
    "right": {
      "body": "AI يساعدك توثّق. الموظف يتبع الخطوات — إنت تراجع الاستثناءات بس.",
      "label": "SOP ثم ناس"
    },
    "title": "توظيف بدون نظام vs SOP أولًا"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "الترتيب: نظام ثم ناس",
    "bullets": [
      "SOP واحد واضح أقوى من موظفين اتنين بلا دليل.",
      "اختبر العملية قبل ما تكبّر الفريق."
    ]
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "eyebrow": "دورك دلوقتي",
    "title": "تأكيد سريع",
    "tagline": "حل سؤال واحد بس عشان تتأكد إنك فهمت الدرس ده كويس.",
    "highlight": "مش امتحان"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "إيه اللي عندك دلوقتي؟",
    "bullets": [
      "فهمت إيه؟ التوظيف بدون SOP يزود شغلك — والـ AI يسرّع توثيق النظام.",
      "تقدر تعمل إيه؟ عندك مخطط SOP لعملية واحدة جاهز للاختبار.",
      "اللي جاي: التوسّع — ومتى يكون مبكرًا يكسر الأنظمة الضعيفة."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [433, 736, 837, 623, 657, 478, 341, 707];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
