// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "مش هو الجاهزية للنمو",
    "title": "الشعور بالنمو",
    "subtitle": "4 علامات لازم تشوفها قبل ما تكبر البيزنس بتاعك.",
    "chip": "أهلًا بيك"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Retention (الاستبقاء)",
    "definition": "قدرتك إنك تحافظ على الزبون وما يروحش لغيرك.",
    "tag": "إزاي تحافظ على زباينك"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "SOPs / Playbooks (دليل الشغل)",
    "definition": "كتالوج فيه خطوات عمل كل حاجة عشان الشغل يمشي صح.",
    "tag": "كتالوج خطوات الشغل"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "نقطة بتعطل الشغل",
    "term": "Bottleneck (عنق الزجاجة)",
    "definition": "نقطة الاختناق اللي بتعطل الدنيا لما الشغل يزيد."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Strategic Thinking (التفكير الاستراتيجي)",
    "definition": "إنك تبص لقدام وتخطط لبعيد مش تحت رجلك بس.",
    "tag": "تخطيط للمستقبل"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Premature Scaling (التوسع المبكر)",
    "definition": "إنك تكبر المشروع قبل ما يكون أساسك وقواعدك ثابتة.",
    "tag": "تكبر بدري قوي"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "إيه هي الـ ٤ علامات دي؟",
    "bullets": [
      "النظام بتاعك بيشتغل لوحده، حتى لو غبت أسبوع الشغل ماشي.",
      "النتائج بتاعتك ثابتة ومستقرة شهر بشهر، مفيش طلوع ونزول كتير.",
      "فيه طلب على منتجك أو خدمتك أكتر من قدرتك الحالية، السوق بيشدّك.",
      "عندك وقت كافي للتفكير الاستراتيجي، مش بس بتطفي حرائق يومية.",
      "لو علامة واحدة بس ناقصة، لازم تثبتها الأول وبعدين تفكر في التوسع."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "إفحص نفسك: علامات الجاهزية",
    "bullets": [
      "الحد الأدنى اللي لازم تحققه هو ٦٠٪ في كل علامة من الأربعة.",
      "لو محققتش النسبة دي، يبقى لسه مش جاهز للتوسع.",
      "راجع كل نقطة وشوف فين محتاج تشتغل أكتر."
    ]
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "label": "صح — توسع بجاهزية",
      "body": "النظام بتاعك ثابت، والطلب موجود، وكل موظف جديد بيضيف قيمة من أول يوم."
    },
    "left": {
      "label": "فشل — توسع بحماس",
      "body": "وظّفت ٣ موظفين قبل ما النظام يثبت، وقضيت ٦ شهور بتدربهم وبتحل مشاكلهم."
    },
    "title": "الفرق بين الحماس والجاهزية"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "حلّ الأسئلة عشان تشوف مدى جاهزيتك للتوسع.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "اختبر فهمك للعلامات الأربعة!",
    "title": "إنت جاهز للتوسع؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [405, 417, 463, 400, 427, 455, 970, 598, 712, 375];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
