// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "أهلًا، معظم أصحاب البيزنس بيستخدموا الـ AI زي جوجل بس، وده 10% من قيمته. الـ 90% الباقيين لما تستخدمه شريك تفكير.",
    "chip": "HERO",
    "highlight": "مش بس منفّذ",
    "title": "AI شريكك في التفكير"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Thinking Partner",
    "definition": "الـ AI بيساعدك تفكّر مش بس ينفّذ، يعني بيسألك ويتحداك ويشوف من زاوية تانية.",
    "tag": "بيفكّر معاك"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "هيكل ثابت للقرارات",
    "definition": "هيكل ثابت بتستخدمه مع الـ AI عشان تاخد أي قرار: السياق + الخيارات + المعايير + المخاطر.",
    "term": "Decision Framework"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Devil's Advocate",
    "tag": "بيختبر قرارك",
    "definition": "إنك تطلب من الـ AI إنه يقنعك إن قرارك غلط، وده عشان تختبر قوة حجتك وتشوف لو فيه نقط ضعف."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "ده تحيّز في تفكيرك بيخليك تشوف اللي إنت عايز تشوفه — والـ AI بيساعدك تكشف التحيّز ده.",
    "tag": "تحيّز في التفكير",
    "term": "Cognitive Bias"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تغيير زاوية النظر",
    "definition": "إنك تغيّر زاوية نظرك للمشكلة عشان تظهرلك حلول مكنتش بتشوفها قبل كده.",
    "term": "Reframing"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "الـ Analyst: خليه يحلّل الموقف من ٣ زوايا مختلفة قبل ما يقترح أي حاجة.",
      "الـ Devil's Advocate: اطلب منه يحاول يقنعك إن قرارك ده غلط بأقوى ٣ حجج.",
      "الـ Strategist: اسأله إيه الـ trade-offs، وإيه اللي هتكسبه وإيه اللي هتسيبه في كل خيار.",
      "الـ Coach: خليه يسألك ٥ أسئلة قبل ما تقرر، مش يقترح هو عليك."
    ],
    "title": "أدوار الـ AI كشريك تفكير"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "عندي قرار: [اوصف القرار بتاعك].",
      "السياق: [اكتب ٣ أسطر عن الموقف].",
      "الخيارات اللي بفكر فيها: [اذكر كل الخيارات].",
      "قبل ما تقترح، اسألني ٥ أسئلة هتساعدك تفهم الموقف أكتر. مش تقترح دلوقتي."
    ],
    "title": "الـ Prompt بتاع الـ Decision Framework"
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "بتقوله \"العميل اشتكى من كذا. قبل ما أرد، اسألني ٣ أسئلة تساعدني أفهم الموقف الحقيقي.\" الـ AI ممكن يكتشف إنك بتحل العرض مش السبب. القرار بيطلع أعمق وأحسن.",
      "label": "صح: AI كشريك"
    },
    "left": {
      "body": "بتقوله \"اكتبلي إيميل للعميل اللي اشتكى\". بتاخد الإيميل وخلاص. القرار بيتاخد بعقلك إنت بس، والـ AI بينفّذ. النتيجة هي نفس قراراتك العادية بس بسرعة أعلى.",
      "label": "غلط: AI كمنفّذ"
    },
    "title": "استخدام الـ AI: غلط ولا صح؟"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "افتح ملف جديد (Notion أو Google Doc) وسمّيه \"My Decision Framework\".",
      "انسخ الـ prompt اللي قولناه وعدّله بكلماتك إنت.",
      "ضيف عليه ٣ أسئلة شخصية بتحب الـ AI يسألهالك دايماً.",
      "احفظ الملف ده عشان تستخدمه في أي قرار كبير من النهارده."
    ],
    "title": "اعمل الـ Decision Prompt Template بتاعك"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "eyebrow": "دورك دلوقتي",
    "tagline": "يلا نختبر فهمك ونشوف إزاي ممكن تطبق اللي اتعلمته في الدرس ده.",
    "highlight": "واطبق اللي اتعلمته",
    "title": "اختبر فهمك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [1224, 366, 409, 349, 316, 306, 1045, 811, 1132, 982, 394];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
