// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "الخلاصة",
    "subtitle": "وظّف \"مساعد شخصي\" قبل ما يبني نظام؟ الموظف شاطر بس كل أسبوع بيسأل: \"أعمل ده إزاي؟\"، \"المفروض أرد إزاي؟\". أحمد كان بيشرح نفس الحاجات ١٠ مرات في الأسبوع.",
    "title": "أي توظيف بدون نظام = موظف هيعمل اللي براسه",
    "highlight": "موظف هيعمل اللي براسه"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "خطوات موثّقة",
    "term": "System",
    "definition": "خطوات موثّقة لمهمة متكررة — أي حد يقدر ينفّذها ويطلع نفس النتيجة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "إجراء تشغيلي",
    "term": "SOP",
    "definition": "Standard Operating Procedure — وثيقة مفصّلة لطريقة تنفيذ مهمة محددة."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "رسم بصري لكل خطوات عملية معينة من البداية للنهاية.",
    "term": "Process Map",
    "tag": "خريطة سير العمل"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "معرفة غير موثّقة",
    "definition": "معرفة موجودة بس في عقول الموظفين، مش موثّقة — كارثة لو حد ساب.",
    "term": "Tribal Knowledge"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "SOP مكتوب بمساعدة AI من حوار، أسرع ١٠ مرات من الكتابة من الصفر.",
    "term": "AI-Assisted SOP",
    "tag": "SOP بمساعدة AI"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "وثّق نفسك — اكتب إزاي بتعمل كل مهمة هتفوّضها (حتى لو سطر سطر).",
      "حوّل التوثيق لـ SOP منظّم بمساعدة AI.",
      "اختبر الـ SOP بنفسك مرتين — هل أي حد يقدر يتبعه ويطلع نفس النتيجة؟",
      "بعد ما الـ SOP شغّال، دلوقتي وظّف اللي هينفّذه — مع التدريب على الـ SOP."
    ],
    "title": "الترتيب الصح: ٤ خطوات قبل أول توظيف"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "\"عايز SOP لمهمة [اكتبها].",
      "هسرحلك إزاي بعملها بكلامي العادي، إنت حوّلها لـ SOP منظّم بصيغة:",
      "١) النتيجة المتوقّعة. ٢) الأدوات المطلوبة. ٣) خطوات بالترتيب (كل خطوة جملة قصيرة). ٤) الأخطاء الشائعة وإزاي نتجنبها. ٥) معايير النجاح.",
      "اسألني أسئلة لو ناقص معلومات.\""
    ],
    "title": "الـ Prompt القاتل: SOP Builder"
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "أحمد كتب ٥ SOPs قبل التوظيف. الموظف الأول اتدرّب في يومين. ساب بعد ٦ شهور — الموظف الجديد بدأ شغل في ٣ أيام. النظام بقى أصل، الموظف متغيّر.",
      "label": "RIGHT — نظام الأول"
    },
    "title": "وظّف قبل النظام vs بنى النظام الأول",
    "left": {
      "body": "أحمد وظّف، صرف شهر تدريب شفهي، الموظف ساب. كل المعرفة راحت معاه. الموظف الجديد بدأ من الصفر — نفس التدريب، نفس المصاريف.",
      "label": "FAILURE — وظّف بدون نظام"
    }
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "حلّ الأسئلة عشان تتأكد إنك فهمت الدرس كويس وتعرف تطبّق!",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك",
    "highlight": "طبق اللي اتعلّمته"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [708, 448, 456, 413, 400, 480, 609, 451, 719, 517];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
