// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "Reactive vs Proactive",
    "highlight": "إزاي تتحكم في يومك؟",
    "chip": "أهلًا بيك يا صاحبي",
    "subtitle": "بتبدأ يومك بالرسائل = Reactive. الناس بتحدد يومك. بتبدأ بأهم مهمة = Proactive. إنت بتحدد يومك."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Deep Work",
    "tag": "تركيز عالي",
    "definition": "شغل بتركيز عالي من غير تشتيت ولا موبايل عشان تنجز المهمة الصعبة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "AI (Claude/GPT)",
    "tag": "برامج ذكية",
    "definition": "برامج ذكية زي شات جي بي تي، بتفهمك وتنفذ طلباتك كأنها بني آدم."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "أمر للـ AI",
    "definition": "الطلب أو الأمر اللي بتكتبه للذكاء الاصطناعي عشان يطلعلك النتيجة اللي عاوزها.",
    "term": "Prompt Tag / Prompt"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Ritual",
    "tag": "روتين يومي",
    "definition": "عادتك الثابتة أو \"الروتين\" اللي بتبدأ بيه يومك عشان تجهز للشغل."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "رد فعل",
    "definition": "إنك تكون رد فعل للي بيحصل ومستني الشغل هو اللي يسوقك.",
    "term": "Reactive Mode"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Proactive Mode",
    "tag": "تخطيط وتحكم",
    "definition": "إنك تاخد الخطوة وتخطط ليومك وتتحكم في وقتك قبل ما أي حاجة تشغلك."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "افتح AI (Claude/GPT) قبل WhatsApp.",
      "Prompt: «عندي المهام دي: [اكتبهم]. رتّبلي الأولويات وقولي ابدأ بإيه».",
      "ابدأ بأهم مهمة — ساعة كاملة من غير رسائل.",
      "افتح الرسائل بعد ما تخلّص أول مهمة مهمة.",
      "قاعدة: أهم مهمة الأول — الرسائل بتستنى مش الفرصة."
    ],
    "title": "روتين الصبح مع AI — ٥ دقائق"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Reactive: ٨ ساعات ردود.",
      "Proactive: Deep Work الأول، الرسائل بعدين."
    ],
    "title": "نفس اليوم — توزيعين مختلفين"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "ساعة Deep Work الأول. باقي اليوم في الرسائل والاجتماعات. في الآخر = إنجاز فعلي.",
      "label": "RIGHT — يوم Proactive"
    },
    "title": "يوم Reactive vs Proactive",
    "left": {
      "body": "في المساء تعبان ومش خلّصت حاجة مهمة. ٨ ساعات في الردود.",
      "label": "FAILURE — يوم Reactive"
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "شوف إزاي ممكن تطبق اللي اتعلمته وتصمم يومك بنفسك.",
    "highlight": "اختبر فهمك",
    "eyebrow": "دورك دلوقتي",
    "title": "صمّم يومك بكرة"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "Phase A = urgent, Phase D = deferred.",
      "أسبوعنا 70% planned + 30% reactive slack.",
      "كل reactive issue بيتحوّل لـ proactive entry بعد الحل."
    ],
    "title": "/roadmap = proactive planning، مش reactive"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "eyebrow": "ملخص الدرس",
    "title": "تحكم في يومك",
    "tagline": "شوفك في الدرس الجاي عشان نتكلم عن أسبوعك = ٤ مسارات.",
    "highlight": "ابدأ بأهم مهمة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [305, 304, 353, 269, 264, 299, 297, 301, 439, 609, 261, 576, 370];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
