// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "المحاولات المفيدة المتكررة أهم من لقطة نجاح عشوائية.",
    "highlight": "الاستمرارية",
    "chip": "بداية الدرس",
    "title": "الاستمرارية بتكسب مش الضربة الواحدة"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "أول فترة الأرقام بتكون صغيرة، وده طبيعي قوي حتى للحسابات الجيدة.",
      "اللي بيوقفك مش الواقع، اللي بيوقفك إنك مفسر الأرقام على إنها حكم نهائي."
    ],
    "title": "أرقام قليلة في البداية بتخوف"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "بدل ما تقول الفيديو فشل، اسأل: إيه اللي اتعلمته من أول ٥ ثواني؟",
      "ركز على مؤشرات سهلة: نسبة إكمال، حفظ، رسائل خاصة، أو تعليق له معنى.",
      "التقدم الحقيقي بيبان لما تكرر المحاولة بنفس الفكرة مع تعديل واحد كل مرة.",
      "هدفك في المرحلة دي بناء نظام شغل ثابت، مش ملاحقة رقم كبير بسرعة."
    ],
    "title": "اشتغل بتجارب صغيرة وبيانات بسيطة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "حكم سريع vs اختبار ذكي",
    "right": {
      "body": "«أعيد نفس الفكرة بزاوية مختلفة وأقيس الفرق». كده بتبني معرفة حقيقية عن جمهورك.",
      "label": "الأسلوب العملي"
    },
    "left": {
      "body": "«الفيديو ما جابش رقم كبير، يبقى الفكرة ماتت». كده بتقفل الباب قبل ما تتعلم.",
      "label": "الأسلوب المرهق"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "نفس الموضوع لكن Hook مختلف",
    "term": "Iteration",
    "definition": "إعادة تنفيذ نفس الفكرة مع تعديل محدد للتعلم."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تعليق بيقول جربتها ونجحت",
    "term": "Signal",
    "definition": "إشارة صغيرة بتقول إن المحتوى مفيد فعلا."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "أفضل ٢ من ٥ أفكار من حيث الإكمال",
    "term": "Small Data",
    "definition": "بيانات قليلة لكنها كفاية لاتخاذ قرار بسيط."
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "caption": "بدل العشوائية، شوف كل فكرة على مقياس واضح: هل بتحل مشكلة حقيقية لجمهور واضح؟",
    "eyebrow": "مثال بصري",
    "title": "شكل مراجعة بسيط للأفكار",
    "src": "lessons/creator-m4-l1-reality-check.jpg"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "أي صانع محتوى شاطر بيعدي بمرحلة أرقام صغيرة، واللي بيفرق هو طريقة التفكير.",
      "كمل بالمهمة النهاردة، ومع كل محاولة هتبقى قراراتك أسرع وأوضح."
    ],
    "title": "إنت بقيت بتقيس بعقل مش بانفعال"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "eyebrow": "دورك دلوقتي",
    "title": "اختيار الفكرة القابلة للتجربة",
    "highlight": "اختيار الفكرة",
    "tagline": "يلا بينا نطبق اللي اتعلمناه ونشوف إزاي تختار فكرة قابلة للتجربة صح!"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [478, 424, 703, 529, 365, 347, 403, 400, 427, 221];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
