// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "أول 3 ثواني",
    "subtitle": "المتفرّج بيقرّر يكمّل أو يـ Scroll في أقل من 3 ثواني.",
    "chip": "أهلًا بيك",
    "highlight": "بتقرّر كل حاجة"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Feed/Scroll",
    "tag": "قلّب في المحتوى",
    "definition": "الصفحة اللي بتقعد تقلب فيها في فيسبوك وتشوف منشورات الناس."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "يصطاد المشاهد",
    "definition": "أول جملة أو لقطة بتصطاد المشاهد وتخليه يفرمل وما يقلبش.",
    "term": "Hook"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "يكسر الملل",
    "definition": "حاجة مفاجئة تكسر الملل وتخلي العين تركز غصب عنها.",
    "term": "Pattern Interrupt"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Curiosity Gap",
    "definition": "سؤال أو معلومة ناقصة تخلي الواحد عاوز يكمل عشان يعرف الإجابة.",
    "tag": "سؤال ناقص"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Reel",
    "tag": "فيديو قصير",
    "definition": "فيديو طولي قصير (زي تيك توك) معمول عشان ينتشر بسرعة."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "النسبة اللي بتقولك قد إيه من الناس كملوا الفيديو للآخر.",
    "tag": "إكمال المشاهدة",
    "term": "Retention"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "ليه أول 3 ثواني = البوابة؟",
    "bullets": [
      "الـ Feed بيتحرك بسرعة جنونية.",
      "الـ Hook بيكسر التوقع أو بيفتح فضول.",
      "أقوى Hooks: رقم صادم، سؤال مباشر، نتيجة قبل الشرح.",
      "الـ Hook: أول جملة + لقطة + صوت."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "src": "lessons/creator-m3-l1-hook.jpg",
    "caption": "فيديو واحد بيوقّف العين في الـ Feed.",
    "eyebrow": "شوف بنفسك",
    "title": "Hook الصفحة الرئيسية"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "title": "إزاي تكتب Hook حقيقي؟",
    "right": {
      "label": "RIGHT",
      "body": "بتبتدي بالنتيجة: '3 أخطاء بتضيّع 90%'."
    },
    "left": {
      "body": "بتعرّف نفسك أو تشكر المتابعين.",
      "label": "FAILURE"
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "جاوب على الأسئلة عشان تشوف استوعبت إيه.",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك للـ Hook",
    "highlight": "طبق اللي اتعلمته"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "صمّم 3 Hooks لفيديو/Reel",
    "bullets": [
      "اختار فكرة فيديو واكتب 3 Hooks.",
      "Hook 1: سؤال يخاطب ألم/فضول.",
      "Hook 2: رقم/حقيقة صادمة.",
      "Hook 3: وعد أو تناقض.",
      "اختار Hook واحد وقول ليه اخترته."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كل hero قصير: 5-10 كلمات.",
      "بيستخدم تباين (زي «المبيعات وحشة مش سؤال»).",
      "بيخليك تكمل قراءة تلقائي."
    ],
    "title": "أول جملة في كل درس = Hook"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "title": "الـ Hook هو مفتاح الفيديو",
    "tagline": "نتقابل في الدرس الجاي: كل فيديو ناجح بيمشي على نفس البنية.",
    "eyebrow": "ملخص سريع",
    "highlight": "اخطف العين في 3 ثواني"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [397, 285, 273, 292, 294, 273, 247, 819, 423, 528, 304, 478, 496, 467];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
