// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "بداية الدرس",
    "highlight": "باب الدخول",
    "subtitle": "بعد ما عرفت تطلع من فكرة واحدة أكتر من شكل محتوى، السؤال دلوقتي: إزاي تخلي كل نسخة منهم تتشاف وتتفتح؟ الـ Thumbnail والكابشن أول قرار للمشاهد: يدوس أو يعدي.",
    "title": "الـ Thumbnail والكابشن هم باب الدخول"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "لو الصورة باهتة أو النص طويل ومش واضح، المشاهد مش هيدي فرصة للفيديو.",
      "كمان لو أول سطر في الكابشن ممل، القارئ مش هيكمل للنقطة المهمة."
    ],
    "title": "باب ضعيف بيخسر محتوى ممتاز"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "Thumbnail جيد: نص قليل، تباين قوي، وفكرة واضحة من أول نظرة.",
      "الكابشن الجيد: أول سطر Hook، وبعده جملة توضح الفايدة بسرعة.",
      "اختبر ٢ أو ٣ بدايات للكابشن، واختار اللي يوصل المعنى أسرع.",
      "متخلطش الرسائل: كل Thumbnail له وعد واحد واضح."
    ],
    "title": "خلي الباب واضح وسريع الفهم"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "Thumbnail مركز بكلمات قليلة وكابشن يبدأ بجملة مشوقة مرتبطة بالفائدة.",
      "label": "الأسلوب الأقوى"
    },
    "title": "نص مزحوم vs رسالة تفتح الباب",
    "left": {
      "body": "Thumbnail فيه كلام كتير وكابشن يبدأ بمقدمة طويلة، فالمشاهد يزهق قبل ما يفهم.",
      "label": "الأسلوب الضعيف"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Hook Line",
    "definition": "أول سطر يشد الانتباه بسرعة.",
    "tag": "شد الانتباه"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Thumbnail Text",
    "definition": "الكلمات القليلة الظاهرة على صورة الغلاف.",
    "tag": "نص الصورة"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "نسبة الضغط",
    "term": "CTR",
    "definition": "نسبة الناس اللي ضغطت بعد ما شافت العنوان والصورة."
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "caption": "المهم في المثال إن الرسالة واضحة من أول ثانية: نص قليل، قراءة سهلة، ووعد مفهوم.",
    "title": "نماذج Thumbnail وكابشن",
    "src": "lessons/unique/creator-m5-l2-thumbnails-captions.jpg",
    "eyebrow": "مثال بصري"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "الكابشن",
    "eyebrow": "دورك دلوقتي",
    "title": "أفضل بداية للكابشن",
    "tagline": "شوف إزاي تختار أفضل باب دخول لمحتواك دلوقتي!"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "highlight": "أقوى",
    "eyebrow": "قفلة واثقة",
    "tagline": "ابدأ طبق اللي اتعلمته وشوف الفرق في تفاعل جمهورك!",
    "title": "دلوقتي باب المحتوى عندك أقوى"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [443, 432, 556, 485, 247, 211, 205, 371, 264, 384];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
