// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الحل مش إلهام. الحل نظام.",
    "highlight": "مش ٣٠.",
    "chip": "أهلًا",
    "title": "٣ محاور بس."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Niche (نِيش)",
    "definition": "التخصص الضيق قوي اللي بتحدده لنفسك عشان تتعرف بيه.",
    "tag": "تخصص دقيق"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Content Pillar (كونتنت بيلر)",
    "definition": "العواميد الأساسية أو الأقسام الثابتة اللي فيديوهاتك بتلف وتدور حولها.",
    "tag": "محور أساسي"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "تصنيف أو \"خزنة\" بتحط فيها الأفكار اللي شبه بعض عشان متنساهاش.",
    "tag": "خزنة أفكار",
    "term": "Bucket (باكيت)"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Algorithm (ألجوريزم)",
    "definition": "نظام ذكي بيقرر يوري الفيديوهات لمين على حسب اهتماماتهم.",
    "tag": "نظام ذكي"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "Topic (توبيك)",
    "tag": "فكرة محددة",
    "definition": "فكرة واحدة صغيرة ومحددة بتشرحها جوه المحور الكبير بتاعك."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "Pillar: موضوع كبير إنت مرجع فيه، مش هاشتاج أو نيش.",
      "3 محاور بس: أقل ممل، أكتر الجمهور يتوه.",
      "المحاور المثالية: إنت بتفهم، جمهورك بيتألم، منتجك بيحل مشكلة.",
      "الاستمرارية أهم: 3 فيديوهات أسبوعيًا، واحد من كل Pillar."
    ],
    "title": "إيه هو الـ Pillar؟"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "دي بنية الـ 3 Pillars اللي محتواك كله هيتبني عليها.",
      "عمود التعليم (Educate)، عمود الترفيه (Entertain)، عمود الإلهام (Inspire).",
      "مش 30 موضوع متشتت — 3 Pillars واضحين بيخلوا الجمهور يفهم إنت بتقدم إيه بالظبط.",
      "أي فيديو لازم ينتمي لواحد منهم."
    ],
    "title": "Content Pillars — ٣ أعمدة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "4 محاور فضفاضة وبعيدة عن بعض. الجمهور مش هيفهم إنت مين، والـ Algorithm كمان مش هيعرف يوصّلك للناس المناسبة.",
      "label": "FAILURE — «هتكلّم في AI و Marketing و Productivity و Mindset»"
    },
    "right": {
      "body": "3 محاور متقاطعين حوالين شخصية واحدة (PM). كل فيديو بيقوّي اللي قبله، والجمهور بيعرف يوصّيك لصحابه.",
      "label": "RIGHT — «AI Workflows لـ PMs / قصص PMs / Tools رخيصة»"
    },
    "title": "اختار الـ Pillars الصح"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "eyebrow": "دورك دلوقتي",
    "highlight": "وطبّق اللي اتعلمته",
    "tagline": "جاوب على الأسئلة عشان تحدد محاور المحتوى بتاعك.",
    "title": "اكتب 3 Pillars نهائيين"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "هتختار 3 محاور بس يكون كل محتواك راجع ليها.",
      "أي حاجة برّاهم = مش بتاعتك.",
      "اكتب المجال العام في سطر.",
      "لكل Pillar: اسم، جملة وصف، و2 أفكار محتوى.",
      "وأخيرًا: إيه قاعدة الرفض لأي فكرة محتوى مش طالعة من الـ 3 دول؟"
    ],
    "title": "حدّد ٣ Pillars + ٢ أفكار محتوى لكل واحدة"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كل pillar فيه 6-10 modules + outcome واحد واضح.",
      "Cross-references بين الـ pillars (Builder يربط بـ Automator).",
      "الـ /journey بيوريك الـ pillar المناسب لك حسب هدفك."
    ],
    "title": "5 مسارات = 5 pillars"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [433, 309, 295, 348, 274, 247, 683, 616, 581, 520, 555, 438];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
