// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "بداية الدرس",
    "title": "لو بتكلم الكل",
    "subtitle": "كل ما جمهورك يبقى أوضح، رسالتك تبقى أدق وفرصة التفاعل أعلى.",
    "highlight": "يبقى ولا حد"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "المتلقي مش بيحس إن المحتوى معمول له.",
      "مجهود كبير، تأثير ضعيف ومتقطع."
    ],
    "title": "العمومية بتضيع الرسالة"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "تحديد الجمهور تركيز يخليك توصل بوضوح أسرع.",
      "الـ AI يساعدك ترتب أفكار البيرسونا، لكن قرارك من خبرتك."
    ],
    "title": "جمهور واحد واضح أحسن"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "مبني لشخص واضح بمشكلاته، فيبقى أقرب للفهم والتفاعل.",
      "label": "محتوى موجه"
    },
    "left": {
      "body": "بيحاول يناسب الجميع فغالبًا ما يلمسش حد بشكل عميق.",
      "label": "محتوى عام"
    },
    "title": "رسالة عامة ولا موجهة؟"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "وصف عملي لشخص تمثيلي من جمهورك الأساسي.",
    "tag": "شخصية الجمهور",
    "term": "Persona (پيرسونا)"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "مشكلة متكررة بتتعب الجمهور وبتدور على حل.",
    "tag": "مشكلة الجمهور",
    "term": "Pain Point (پاين پوينت)"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "تعريف الجمهور",
    "term": "Audience Sentence (أودينس سينتنس)",
    "definition": "جملة واحدة دقيقة تعرف مين بتخاطب."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "بيساعدك تجمع الصورة كاملة: الشخص،",
      "مشاكله، وهدفه اللي بيدور عليه."
    ],
    "title": "خريطة شخصية الجمهور"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "جاوب على السؤال عشان تثبت فهمك للدرس.",
    "highlight": "إيه أفضل تعديل؟",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد للتطبيق"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "eyebrow": "إقفال الدرس",
    "title": "كده جمهورك بدأ يوضح",
    "tagline": "نتقابل في الدرس الجاي عشان نبني أعمدة المحتوى.",
    "highlight": "الخطوة الجاية"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [237, 390, 465, 343, 281, 268, 300, 364, 445, 447];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
