// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "أكتر سبب بيخلّي صنّاع المحتوى يقفوا بعد ٣ فيديوهات: متوقعات غلط من البداية.",
    "highlight": "اتفق مع نفسك",
    "chip": "أهلًا HERO",
    "title": "قبل ما تصوّر أول فيديو،"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Watch Time",
    "tag": "لما الناس تكمل الفيديو",
    "definition": "إجمالي الوقت اللي الناس قضته وهي بتتفرج على فيديوهاتك."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "أول ثواني في الفيديو اللي بتخطف عين المشاهد وتخليه يكمل.",
    "tag": "بداية الفيديو اللي بتشد",
    "term": "Hook"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Algorithm",
    "definition": "ده نظام المنصة الذكي اللي بيقرر يظهر فيديوهاتك لمين وإمتى.",
    "tag": "نظام بيظهر فيديوهاتك"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "رقم أو مستوى ثابت بتقيس عليه نجاحك وتقارن بيه أداءك.",
    "tag": "مقياس للنجاح",
    "term": "Benchmark"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "قصة نجاح حقيقية",
    "definition": "دراسة حالة حقيقية بتشرح إزاي مشكلة اتحلت أو نجاح حصل.",
    "term": "Case Study"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Vanity Metrics",
    "tag": "أرقام شكلية",
    "definition": "أرقام منظرة بس (لايكات وفولو) مش بتفيدك ولا بتجيب لك فلوس."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "إرهاق من الشغل",
    "definition": "لما طاقتك تخلص خالص وتكره الشغل بسبب الضغط وتوقف تصوير.",
    "term": "Burnout"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الفيديو رقم ١ مش هيتفرّج عليه حد. ولا الـ ٥. ولا غالبًا الـ ١٠. ده طبيعي، مش فشل.",
      "إنت في أول ٣٠ فيديو بتدفع تمن تعلّم: الكاميرا، الصوت، الإيقاع، وإنك تشوف نفسك من غير ما تكرهها.",
      "النتيجة الحقيقية بتيجي بين فيديو ٣٠ و ٦٠ — لما الـ Algorithm يفهمك، وإنت تفهم جمهورك.",
      "متوسط Views على أول ١٠ فيديوهات لأي حساب جديد: بين ٥٠ و ٥٠٠ View. ده الـ Benchmark الحقيقي.",
      "اللي بيخلّي ٩٠٪ من الناس يقفوا: مش ضعف الـ Views، إنهم متوقعين Views أعلى من الواقع."
    ],
    "title": "أول ٣٠ فيديو = استثمار، مش نتيجة"
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "src": "lessons/creator-m4-reality-check.jpg",
    "caption": "استثناء — مش من المنصة. ده تقرير إحصائي خارجي من Hootsuite عشان نوريك الأرقام الحقيقية مش مزاج. باقي الدروس Case Study بيبقى من منصتنا.",
    "eyebrow": "استثناء — إحصائية",
    "title": "Hootsuite — Posting Frequency (2025)"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "body": "بتقيس بالتطوّر، مش بالـ Views. ده اللي بيخلّيك تكمل لحد فيديو ٣٠ — اللي عنده الـ Algorithm بيبدأ يدفعك فعلًا.",
      "label": "RIGHT — «خلّصت ١٠ فيديوهات، أنا أحسن في الـ Hook عن أول واحد»"
    },
    "title": "إزاي تقيس النجاح في البداية",
    "left": {
      "body": "إنت بتقيس بمقياس غلط. ٨٠ View على فيديو رقم ٤ ده Benchmark طبيعي. لو وقفت هنا، إنت بتدفع تمن التعلّم من غير ما تاخد العائد.",
      "label": "FAILURE — «الفيديو جاب ٨٠ View بس، أنا فاشل»"
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "يلا نطبق اللي اتعلمناه ونشوف مدى فهمك للدرس.",
    "highlight": "٣٠ فيديو",
    "eyebrow": "دورك دلوقتي",
    "title": "وقّع عقد الـ ٣٠ فيديو مع نفسك"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "هتلتزم بالتنفيذ: ٣٠ فيديو على مدى محدّد.",
      "النتيجة تيجي بعد الـ ٣٠، مش قبل.",
      "اختر منصة واحدة ومعدّل نشر يوصلك لـ ٣٠ فيديو في ٣ شهور.",
      "حدّد عناوين أول ٣ فيديوهات ليك.",
      "ركّز على مؤشر واحد بس قبل فيديو ٣٠ (زي Watch Time).",
      "تجاهل تمامًا أي حاجة تانية (زي اللايكات أو التعليقات السلبية).",
      "اعمل جملة التزام واضحة."
    ],
    "title": "اكتب خطة الـ ٣٠ فيديو الأولانيين"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الجزء ده من المنصة اتبنى بمسار Creator، نفس اللي بتتعلمه.",
      "الـ /roadmap بيعرض كل feature خلصت، والأخطاء اللي اتصلّحت، واللي لسه planned.",
      "مفيش تجميل، ده reality check دائم بيخلينا متوازنين بين الـ vision والتنفيذ.",
      "كل item ليه status: todo / doing / done / deferred.",
      "Items فيها notes من user vs AI، وفيه filter للنوعين.",
      "حتى الأخطاء بتظهر، مش بنخفي حاجة."
    ],
    "title": "Roadmap بيوريك إيه شُغل وإيه لسه"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "هنشوف إزاي تستغل موبايلك لأقصى درجة في تصوير فيديوهات احترافية.",
    "highlight": "الكاميرا مش اللي بتبيع.",
    "eyebrow": "الدرس الجاي",
    "title": "موبايلك كافي."
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [336, 189, 169, 186, 193, 209, 173, 229, 898, 304, 922, 255, 859, 952, 288];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
