// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "دي أصعب جملة في صناعة المحتوى.",
    "title": "لو بتكلّم الكل،",
    "highlight": "مش بتكلّم حد",
    "chip": "أهلًا"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "definition": "يعني الناس اللي شافت الحاجة اللي نشرتها، سواء متابعينك أو لأ.",
    "tag": "عدد المشاهدين",
    "term": "Reach (الوصول)"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "الزبون المثالي",
    "term": "Persona (البيرسونا)",
    "definition": "شخصية وهمية بترسمها لزبونك المثالي عشان تعرف تفكر زيه وتكلمه صح."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "دي الجملة أو الحركة اللي بتخطف عين اللي بيشوفك عشان يكمل معاك.",
    "tag": "جذب الانتباه",
    "term": "Hook (الخطفة)"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "الطلب المباشر اللي بتطلبه من الناس يعمله بعد ما يشوفوا كلامك.",
    "tag": "دعوة للفعل",
    "term": "CTA (طلب الفعل)"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "الـ Demographics دي إحصائية، زي شباب من 25 لـ 35 سنة، وبيشتغلوا في مصر.",
      "لكن الـ Persona هو شخص واحد بالاسم، زي أحمد، 28 سنة، Product Manager، وبيحلم يبدأ شركة SaaS.",
      "لما تكتب لأحمد ده، كل واحد شبهه هيحس إن المحتوى موجه ليه هو شخصيًا.",
      "أهم 3 حاجات تعرفها عن جمهورك هي: الألم اللي بيحرقهم، والحلم اللي بيشدّهم، واللغة اللي بيتكلموا بيها.",
      "اللغة دي بتلاقيها في الكومنتات والرسايل ومجموعات الفيسبوك، مش في دماغك أنت."
    ],
    "title": "الـ Persona مش Demographics"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "الـ Persona هي شخص واحد محدد في النص.",
      "وحواليه ٤ معلومات أساسية: السن والاهتمام.",
      "وكمان المشكلة اللي بتحلها.",
      "والهدف اللي بتوصله ليه."
    ],
    "title": "الـ Persona — ٤ معلومات أساسية"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "left": {
      "body": "وصف فضفاض. مش هتعرف تكتب Hook، ولا تختار CTA، ولا حتى تختار لغة. النتيجة: محتوى عام، Reach ضعيف.",
      "label": "FAILURE — «جمهوري الشباب اللي بيحب AI»"
    },
    "title": "إزاي تعرف جمهورك",
    "right": {
      "body": "شخص واحد بالاسم. كل سكريبت بتكتبه، بتسأل نفسك: هل أحمد هيهتم بده؟ النتيجة: محتوى دقيق، تفاعل قوي.",
      "label": "RIGHT — «أحمد، Product Manager، بيخاف من Code»"
    }
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "title": "اكتب Persona كاملة لجمهورك الأساسي",
    "tagline": "اختبر فهمك للدرس وجاوب على الأسئلة عشان تطبق اللي اتعلمته وتثبت المعلومة. نتقابل في الدرس الجاي: ٣ محاور بس. مش ٣٠.",
    "highlight": "وابدأ طبق اللي اتعلمته",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [387, 281, 310, 293, 363, 1036, 426, 826, 475];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
