// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "لما تحدد أعمدة محتواك، قرار النشر يبقى أسهل وأسرع. الهدف هنا إنك تبني ٣ أعمدة واضحة تمشي عليهم بثبات.",
    "highlight": "بتوقف التخمين",
    "title": "الأعمدة",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "كل يوم سؤال: أنشر عن إيه؟",
    "bullets": [
      "من غير أعمدة، الأفكار بتبقى عشوائية ومجهدة.",
      "وده بيخلي حضورك ضعيف حتى لو عندك شغل كويس."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الأعمدة هي مواضيع رئيسية ثابتة، وكل فكرة محتوى لازم تتبع واحد منها.",
      "الـ AI يساعدك يطلع اقتراحات أفكار تحت كل عمود، لكن اختيار اللي يخدم جمهورك وأهدافك قرارك أنت."
    ],
    "title": "٣ أعمدة كفاية قوي"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "كل فكرة بتخدم صورة واحدة متماسكة، فالمتابع يعرف أنت بتميز في إيه.",
      "label": "مع أعمدة"
    },
    "title": "تنوع عشوائي ولا أعمدة واضحة؟",
    "left": {
      "body": "أفكار متقطعة، والرسالة النهائية مش واضحة للجمهور.",
      "label": "من غير أعمدة"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "تعليم، تجارب، أدوات.",
    "definition": "موضوع رئيسي ثابت بيتكرر منه محتوى كتير.",
    "term": "Content Pillar"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "أداة تنظم كتابة السكربت.",
    "definition": "فكرة صغيرة تابعة لعمود معين.",
    "term": "Topic Idea"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Content Mix",
    "tag": "كل أسبوع بوست من كل عمود.",
    "definition": "توزيع المحتوى بين الأعمدة بشكل متوازن."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "شكل توزيع الأعمدة",
    "bullets": [
      "الرسم يوضح إزاي العمود الواحد يتفرع لأفكار متعددة من غير ما تضيع هوية المحتوى."
    ]
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "جاوب على السؤال عشان تثبت فهمك للموضوع وتشوف إزاي تطبق اللي اتعلمته.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "اختبر فهمك",
    "title": "سؤال واحد للتطبيق"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "eyebrow": "إقفال الدرس",
    "tagline": "دلوقتي تقدر تدخل أي أسبوع وعندك اتجاه واضح بدل الحيرة اليومية. شوفك في الدرس الجاي!",
    "highlight": "جاهز تبدأ",
    "title": "كده عندك خريطة محتوى"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [431, 351, 483, 534, 396, 378, 293, 281, 300, 315];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
