// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "السكربت الواضح يوفر وقتك",
    "subtitle": "خطاف ثم قيمة ثم دليل ثم طلب واضح.",
    "highlight": "ترتيب يمنع اللخبطة",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "من غير بنية، الفيديو يطول ويضيع منه الهدف.",
      "المشاهد غالبًا يخرج قبل ما توصل لرسالتك الأساسية."
    ],
    "title": "الارتجال بيضيع الفكرة"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "ابدأ بجملة توقف المشاهد، بعدها قدم القيمة الأساسية بوضوح.",
      "ادعم الكلام بدليل أو مثال واقعي، وفي النهاية اطلب خطوة واحدة فقط.",
      "الـ AI يقدر يساعدك ترتب المسودة بسرعة، لكن القرار النهائي لنبرة السكربت ودقته لازم يكون منك."
    ],
    "title": "خطاف ثم قيمة ثم دليل ثم CTA"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "سكربت مرتب ولا كلام مشتت؟",
    "right": {
      "body": "كل جزء له وظيفة، فالمشاهد يفهم بسرعة ويعرف يعمل إيه بعد الفيديو.",
      "label": "ببنية واضحة"
    },
    "left": {
      "body": "أفكار متداخلة وطلبات متعددة في الآخر، فالتأثير يضعف.",
      "label": "بدون بنية"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "طريقة مختصرة تنفذها فورًا.",
    "definition": "الجزء اللي يقدم الفكرة أو الخطوة الأساسية مباشرة.",
    "term": "Value Block"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "نتيجة رقمية أو مثال عملي.",
    "definition": "دليل بسيط يثبت إن الكلام قابل للتطبيق.",
    "term": "Proof"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "جرب الخطوة دي النهاردة وابعتلي النتيجة.",
    "definition": "طلب واحد واضح بعد انتهاء السكربت.",
    "term": "CTA"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "title": "شكل السكربت المتوازن",
    "caption": "التوزيع الواضح على أجزاء قصيرة بيخلي السكربت مركز وسهل التنفيذ.",
    "src": "lessons/creator-m3-l2-script-structure.jpg",
    "eyebrow": "لقطة بصرية"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "جاوب على السؤال عشان تتأكد إنك فهمت كل حاجة.",
    "highlight": "اختبر فهمك للدرس",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد للتطبيق"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "دلوقتي تقدر ترتب أفكارك بسرعة وتنتج محتوى أوضح بثقة أعلى.",
      "كمّل بنفس المنهج: طبّق المخطط على أكتر من فكرة وراقب التحسن في التفاعل."
    ],
    "title": "بقى عندك قالب تنفيذ واضح"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [414, 421, 738, 562, 445, 315, 377, 382, 337, 579];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
