// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "موبايلك كافي",
    "subtitle": "الفرق مش في الجهاز. الفرق في 3 حاجات: الإضاءة، الزاوية، والمونتاج البسيط.",
    "highlight": "محتواك هو اللي بيبيع.",
    "title": "الكاميرا مش اللي بتبيع."
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "إعدادات أصلية",
    "term": "Default",
    "definition": "الإعدادات الأصلية للجهاز قبل ما إنت تعدل فيها أي حاجة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Front/Back Light",
    "definition": "الإضاءة الأمامية (نور جاي في وشك) أو الخلفية (نور وراك بيظلمك).",
    "tag": "نور وشك/وراك"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "دراسة حالة",
    "term": "Case Study",
    "definition": "دراسة حالة حقيقية بنتعلم منها إزاي المشكلة اتحلت بخطوات عملية."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "1.2x Speed Scaling",
    "definition": "تسرع الفيديو شوية عشان الكلام يبقى نشيط ومش ممل للمشاهد.",
    "tag": "تسريع الفيديو"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "خطوط الكاميرا",
    "term": "Grid",
    "definition": "خطوط بتظهر على شاشة الموبايل بتخليك تظبط الكادر والمنتج صح."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "تثبيت الصورة",
    "term": "Stabilization",
    "definition": "تثبيت الصورة عشان الفيديو ميبقاش مرجح ويوجع عين اللي بيشوفه."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "إضاءة طبيعية قدام شباك = أحسن من أي Ring Light بـ ١٠٠٠ جنيه.",
      "الزاوية: الكاميرا في مستوى العين أو أعلى بشوية."
    ],
    "title": "سيطر على الإضاءة والزاوية، والباقي يجي لوحده"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "التسجيل: AirPods أو أي سماعة فيها Mic بتكون أحسن من Mic الموبايل المدمج بمراحل.",
      "الصوت النظيف = ٥٠٪ من الاحترافية.",
      "المونتاج: CapCut مجاني وبيخلّص الشغل في ١٠ دقايق."
    ],
    "title": "التسجيل والمونتاج"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "الـ Setup الكامل: موبايل + حامل بـ ٣٠ جنيه + شباك + AirPods.",
      "ده كل اللي محتاجه. كل حاجة تانية رفاهية."
    ],
    "title": "الـ Setup الكامل"
  },
  {
    "card": "ScreenshotCard",
    "accent": "pink",
    "eyebrow": "استثناء — هاردوير",
    "title": "إعدادات الكاميرا — iPhone & Android",
    "src": "lessons/creator-m4-mobile-shooting.jpg",
    "caption": "استثناء — مش من المنصة. الإعدادات دي على موبايلك إنت، فلازم تشوف الواجهة الحقيقية. نفس الفكرة موجودة على iPhone و Android بنفس الأسماء تقريبًا. باقي الدروس بنوريك Case Study من منصتنا."
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "left": {
      "label": "FAILURE — «هاجيب كاميرا DSLR و Ring Light و Green Screen»",
      "body": "بتنفق فلوس قبل ما تعرف إنت بتحب التصوير ولا لأ. أغلب الناس اللي عملت كده وقفوا بعد فيديو ٣ لإن الـ Setup بقى عبء مش أداة."
    },
    "right": {
      "body": "أقل عائق = أكتر استمرارية. لما تخلّص ٣٠ فيديو وتعرف إنت بتحب ده فعلًا، وقتها ممكن تفكّر تطوّر الـ Setup.",
      "label": "RIGHT — «موبايل + AirPods + شباك + CapCut»"
    },
    "title": "إزاي تختار Setup التصوير بتاعك"
  },
  {
    "card": "CTACard",
    "accent": "mint",
    "tagline": "يلا نطبّق اللي اتعلمناه ونشوف لو فهمنا صح.",
    "highlight": "صوّر أول فيديو",
    "title": "صوّر أول فيديو — حتى لو مش أحسن حاجة",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "بموبايلك، صوّر ٣ Clips قصيرة.",
      "الفرق بينهم هيكون في الإضاءة والزاوية بس.",
      "جرّب تصوّر ضد الشباك (Backlit) وشوف إيه اللي بيحصل.",
      "وبعدين صوّر والشباك في وشّك (Front light) وقارن الفرق.",
      "وأخيرًا، غيّر زاوية الكاميرا (تحت/فوق وش العين) وشوف الإحساس بيتغيّر إزاي.",
      "بعد كده، اكتب في سطرين تلاتة إيه التركيبة اللي هتستخدمها كـ Default وليه."
    ],
    "title": "صوّر ٣ Clips تتحكّم فيهم في الإضاءة + الزاوية"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الجزء ده من المنصة اتبنى بمسار Creator — نفس اللي بتتعلمه.",
      "60%+ من المتعلمين بيفتحوا المنصة من mobile.",
      "كل layout اتصمّم mobile-first ثم expanded للـ desktop. مش العكس.",
      "Default viewport في الـ design = 375px (iPhone SE).",
      "كل grid بيتحوّل لـ single column أقل من 640px.",
      "Touch targets كلها 44x44px على الأقل."
    ],
    "title": "كل صفحة شُغلت لـ mobile الأول"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [467, 390, 349, 343, 360, 358, 358, 419, 491, 411, 439, 383, 383, 521, 562];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
