// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "الـ Profile هو الـ Landing Page بتاعك",
    "subtitle": "زائر جديد بيشوف Bio + ٩ بوستات قبل ما يقرّر يـFollow ولا لأ. ٣ ثواني فقط. لازم الـ Grid يدّيله إحساس واحد واضح.",
    "highlight": "Landing Page",
    "chip": "HERO"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Landing Page",
    "tag": "زي البياع اللي بيفرد فرشته",
    "definition": "صفحة الهبوط، أول صفحة بيوصلها الزبون وتاخد عينه."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Grid/Layout/Pattern",
    "tag": "تاجر القماش اللي بيرص تاتوابه",
    "definition": "رصة البوستات جنب بعضها في بروفايلك وشكلها العام."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "term": "Primary/Accent colors",
    "tag": "المحاسب اللي بيستخدم قلم أحمر للهوامش",
    "definition": "اللون الأساسي للبراند، واللون الفرعي اللي بينطق التصميم."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Audit",
    "tag": "صاحب محل بيجرد البضاعة",
    "definition": "مراجعة وجرد لبروفايلك عشان تشوف إيه اللي محتاج يتصلح."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "براند ملابس بيحط طبقة ظل",
    "definition": "طبقة لون خفيفة بتتحط فوق الصورة عشان توضح الكلام.",
    "term": "Overlay/Filters"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Hero post/Pinned post",
    "tag": "صاحب مطعم بيثبت بوست المنيو",
    "definition": "البوست اللي بتثبته في أول البروفايل عشان يعرّف الناس بيك."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "لون واحد مهيمن على الـ Grid (٧٠٪ Primary، ٣٠٪ Accents).",
      "Covers موحدة لكل الـ Reels (نفس الـ template، الخط، الـ layout)."
    ],
    "title": "Grid Consistency — ٤ مبادئ"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "باقي المبادئ",
    "bullets": [
      "رتم في الـ Layout (صورة - Reel - صورة - Reel).",
      "Hero Posts متثبتة (أهم ٣ بوستات).",
      "استخدم Preview app للتخطيط."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "src": "lessons/unique/creator-m6-grid-consistency.jpg",
    "caption": "لاحظ كل التايل بـ نفس مدى الألوان (cream + terracotta + black). نفس الخط في العناوين. الزائر بيشوف الـ profile ده ويعرف فوراً: «ده Creator في الـ lifestyle بـ هوية واضحة». الثقة بتبني نفسها.",
    "eyebrow": "شوف بنفسك",
    "title": "Grid متّسق = ثقة فورية"
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "title": "زائر جديد — رد فعل مختلف",
    "left": {
      "body": "كل بوست بلون مختلف، خط مختلف، style مختلف. الزائر يـscroll، يحس بـ chaos، مش بيفهم إنت بتعمل إيه، يرجع. مفيش Follow.",
      "label": "FAILURE — Grid عشوائي"
    },
    "right": {
      "body": "نفس الـ palette، نفس الخط، Covers مصمّمة لكل Reel. الزائر يشوف الـ Grid ٣ ثواني، يفهم القيمة، يضغط Follow. الـ Brand بيشتغل قبل ما يقرا حتى Caption واحد.",
      "label": "RIGHT — Grid موحّد"
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "tagline": "يلا نطبّق ونشوف إزاي تعمل Grid احترافي يجذب الزوار! وقابلني في \"بياناتك جاهزة — دلوقتي بتسأل\".",
    "highlight": "Grid موحّد",
    "eyebrow": "دورك دلوقتي",
    "title": "خطّط أول ٩ بوستات بـ Grid موحّد"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "Container max-width: 1280px ثابت.",
      "Gutter: 24px على desktop، 16px على mobile.",
      "Cards بنفس aspect ratio لكل الـ grids."
    ],
    "title": "Grid system واحد في كل صفحات المنصة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [483, 360, 358, 414, 297, 391, 387, 514, 478, 465, 479, 377, 456];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
