// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "المشاهدات",
    "chip": "أهلًا، بداية الدرس",
    "subtitle": "رقم الـ views ممكن يفرحك، بس ما يقولش الحقيقة كاملة. في بوستات مشاهداتها أقل لكن تأثيرها أعلى بكتير.",
    "title": "المشاهدات لوحدها مش كفاية"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "التركيز على رقم واحد بيضللك",
    "bullets": [
      "لما كل قرارك مبني على views، ممكن تكرر نوع محتوى بيجيب زحمة من غير ثقة ولا تحويل.",
      "ده يخليك تحس إنك شغال كتير بس النمو الحقيقي بطيء، لأنك بتقيس حاجة مش مرتبطة بهدفك الأساسي."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "خليك ثابت على 3 مؤشرات: Watch Time، Save Rate، Follow/Action Rate. دول اللي يوضحوا جودة المحتوى.",
      "Watch Time يقول هل البداية شدت، Save Rate يقول هل القيمة تستحق الرجوع، وFollow/Action يقول هل الثقة زادت.",
      "كل أسبوع راجع آخر 3 بوستات، واكتب قرار تحسين واحد فقط. التحسين الصغير المنتظم أحسن من تغييرات عشوائية كبيرة."
    ],
    "title": "اقرأ البوست بثلاث إشارات"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "قراءة سطحية مقابل قراءة ذكية",
    "left": {
      "body": "بوست جاب مشاهدات عالية إذن ممتاز. بدون فهم للوقت المشاهدة والحفظ، ممكن تعيد نفس الغلط.",
      "label": "قراءة سطحية"
    },
    "right": {
      "body": "أراجع 3 مؤشرات أساسية قبل الحكم. كده أعرف أكرر اللي فعلا بيبني علاقة طويلة مع الجمهور.",
      "label": "قراءة ذكية"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "متوسط الوقت اللي الناس كملت فيه المحتوى.",
    "term": "Watch Time",
    "tag": "لو البداية ضعيفة هتلاقي الرقم نازل بسرعة."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "كل ما القيمة عملية، نسبة الحفظ غالبا تعلى.",
    "definition": "نسبة الحفظ مقارنة بعدد المشاهدات.",
    "term": "Save Rate"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Action Metric",
    "definition": "مؤشر يدل على خطوة فعلية بعد المشاهدة زي متابعة أو رسالة.",
    "tag": "بوست أقل views لكن جاب رسائل جدية = مؤشر أقوى."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "وازن بين التلات إشارات بدل ما تعتمد على views بس، عشان الحكم يبقى أدق."
    ],
    "title": "Analytics Triangle"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "حل السؤال ده عشان تثبت فهمك وتعرف تطبق صح.",
    "highlight": "سؤال واحد",
    "eyebrow": "دورك دلوقتي",
    "title": "سؤال واحد للتثبيت"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "title": "دلوقتي بتقود بالمؤشرات مش بالانطباع",
    "bullets": [
      "بقي عندك عدسة واضحة تفصل بين ضوضاء الأرقام والإشارات المهمة فعلا."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [381, 533, 881, 641, 286, 291, 407, 247, 199, 310];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
