// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "الـ Thumbnail",
    "subtitle": "محتوى ٥٠٪ + Thumbnail قوي = آلاف المشاهدات.",
    "highlight": "نص نجاح اليوتيوب",
    "chip": "أهلًا بيك"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "definition": "ده بطل الصورة أو الحاجة الأساسية اللي عينك بتروح لها أول ما بتشوف التصميم.",
    "tag": "بطل الصورة",
    "term": "Subject (العنصر الأساسي)"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "فرق الألوان",
    "term": "Contrast (التباين)",
    "definition": "فرق الألوان ووضوحها اللي بيخلي الصورة \"تنطق\" وتتشاف بسهولة وسط زحمة الصور."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "صورة الغلاف",
    "term": "Thumbnail (صورة الغلاف)",
    "definition": "الصورة الصغيرة اللي بتعمل \"واجهة\" للفيديو وتحمس الناس تدوس وتتفرج."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "حسبة بسيطة بتعرفنا كام واحد داس من كل 100 شافوا الصورة قدامهم.",
    "term": "CTR (نسبة الضغط)",
    "tag": "نسبة الضغط"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "وصف الفيديو",
    "term": "Caption (وصف الفيديو)",
    "definition": "الكلام اللي بيتكتب تحت الفيديو أو البوست عشان يشرح تفاصيل زيادة."
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "bullets": [
      "١. Subject واضح: وش، منتج، أو Object كبير في النص، ومفيش زحمة.",
      "عين المتفرج بتقرّر في ٠.٣ ثانية."
    ],
    "title": "عشان تعمل Thumbnail قوي، ركّز في ٣ عناصر"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "٢. ٢-٤ كلمات بخط ضخم، مش جملة كاملة.",
      "أمثلة: «STOP DOING THIS»، «I WAS WRONG».",
      "الـ Thumbnail بـ ١٠ كلمات = مفيش حد بيقراها."
    ],
    "title": "٢-٤ كلمات بخط ضخم، مش جملة كاملة"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "٣. Contrast عالي: ألوان متضادة (أصفر مع أسود، أبيض مع أحمر).",
      "لو الـ Thumbnail اختفى في خلفية رمادية = ضعيف."
    ],
    "title": "٣. Contrast عالي بألوان متضادة"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "للـ Caption: أول سطر هو الـ hook، ابدأ بسؤال أو جملة مفاجئة.",
      "استخدم ٣ Templates بس في كل فيديوهاتك.",
      "الـ Consistency (الاتساق) أهم من التنوّع."
    ],
    "title": "نصايح مهمة للـ Caption والـ Templates"
  },
  {
    "card": "ScreenshotCard",
    "accent": "pink",
    "eyebrow": "شوف بنفسك",
    "src": "lessons/unique/creator-m4-thumbnails.jpg",
    "caption": "كل thumbnail هنا فيه ٢-٤ كلمات بس، ألوان مضادة، والكلمات قابلة للقراءة من بعيد.",
    "title": "Thumbnails قوية = ٣ كلمات + ألوان مضادة"
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "title": "إزاي تختار Thumbnail",
    "left": {
      "body": "بتاخد screenshot عشوائي من الفيديو، تكتب عليه عنوان الفيديو كامل. الـ thumbnail باهت، الكلام كتير، مفيش حاجة بتجذب. CTR تحت ٢٪.",
      "label": "FAILURE — Screenshot من الفيديو"
    },
    "right": {
      "body": "صورة وش بتعبير قوي (دهشة، إيجابية)، ٣ كلمات بـ خط ضخم («I WAS WRONG»)، خلفية بلون متضاد. CTR ٨-١٢٪. نفس الفيديو، ٥× مشاهدات.",
      "label": "RIGHT — صورة مخصّصة + ٣ كلمات"
    }
  },
  {
    "card": "CompareCard",
    "accent": "mint",
    "right": {
      "label": "RIGHT — صورة مخصّصة + ٣ كلمات",
      "body": "صورة وش بتعبير قوي (دهشة، إيجابية)، ٣ كلمات بـ خط ضخم («I WAS WRONG»)، خلفية بلون متضاد. CTR ٨-١٢٪. نفس الفيديو، ٥× مشاهدات."
    },
    "title": "إزاي تختار Thumbnail",
    "left": {
      "label": "FAILURE — Screenshot من الفيديو",
      "body": "بتاخد screenshot عشوائي من الفيديو، تكتب عليه عنوان الفيديو كامل. الـ thumbnail باهت، الكلام كتير، مفيش حاجة بتجذب. CTR تحت ٢٪."
    }
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "هتلاقي أسئلة تطبيق هتساعدك تفهم أكتر إزاي تختار Thumbnail صح.",
    "title": "طبّق اللي اتعلمته في أسئلة تطبيق",
    "eyebrow": "دورك دلوقتي",
    "highlight": "صمّم Thumbnails لفيديوهاتك"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [553, 436, 417, 504, 453, 443, 427, 442, 383, 491, 537, 479, 573, 399];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
