// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "Hook → Problem → Proof → CTA",
    "highlight": "بيمشي على نفس البنية",
    "chip": "HERO",
    "title": "كل فيديو ناجح"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "نص الفيديو",
    "term": "Script (سكريبت)",
    "definition": "الكلام اللي بتكتبه وتجهزه قبل ما تبدأ تصوير الفيديو."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "أول كام ثانية في الفيديو اللي بتخطف بيهم عين اللي بيتفرج.",
    "term": "Hook (خُطّاف)",
    "tag": "جاذب الانتباه"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "دي الوعود اللي بتقولها أو التحدي اللي هتحله للمشاهد في الفيديو.",
    "term": "Problem/Promise",
    "tag": "تحدي / وعد"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "إثبات إن كلامك صح، سواء بأرقام أو تجربة حقيقية أو نتيحة.",
    "term": "Proof (دليل)",
    "tag": "دليل الإثبات"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "term": "CTA (اطلب فعل)",
    "tag": "دعوة للفعل",
    "definition": "طلب صريح بتطلبه من الناس يعملوه في آخر الفيديو."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "الهيكل أو الترتيب اللي بيمشي عليه الفيديو بتاعك.",
    "term": "Structure (البنية)",
    "tag": "ترتيب الفيديو"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الـ Hook بيخطف العين ويقول للمتفرج: «استنى، ده ليك»."
    ],
    "title": "دور كل جزء في البنية"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الـ Problem بيسمّي الألم بدقّة، ولو المتفرج حسّ بيه، هيكمل معاك."
    ],
    "title": "دور كل جزء في البنية"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "الـ Proof بيدّي دليل: نتيجة، تجربة شخصية، مثال محسوس."
    ],
    "title": "دور كل جزء في البنية"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "الـ CTA بيقول للمتفرج يعمل إيه دلوقتي، طلب واحد ومحدّد."
    ],
    "title": "دور كل جزء في البنية"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "البنية دي إيقاع، مش قالب جامد، كل جملة في السكريبت تحت جزء من الأربعة."
    ],
    "title": "دور كل جزء في البنية"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/creator-m3-l2-script-structure.jpg",
    "caption": "ده شكل سكريبت 60 ثانية. الـ Proof بياخد أكبر مساحة زمنية — ده اللي بيقنع. الـ Hook الأقصر — بس أهم.",
    "title": "بنية السكريبت — 4 أجزاء بثواني محدّدة",
    "eyebrow": "شوف بنفسك"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "label": "RIGHT — بتكتب 4 سطور قبل التصوير",
      "body": "بتكتب: Hook، Problem، Proof، CTA. النتيجة: فيديو محكوم في 60 ثانية بفكرة واحدة قوية."
    },
    "title": "إزاي تكتب سكريبت حقيقي",
    "left": {
      "label": "FAILURE — بترتجل قدام الكاميرا",
      "body": "بتفتح الكاميرا وبتحاول تفتكر فكرة. النتيجة: فيديو 3 دقايق فيه فكرة واحدة ضايعة وسط الكلام."
    }
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "بالبنية الأربعة",
    "eyebrow": "دورك دلوقتي",
    "title": "اختبر فهمك للبنية",
    "tagline": "حل الأسئلة عشان تطبق اللي اتعلمته"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [276, 232, 255, 253, 294, 295, 255, 295, 316, 316, 300, 300, 307, 294, 419];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
