// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "المحتوى مش بوستات عشوائية",
    "chip": "أهلًا، بداية واضحة",
    "highlight": "نظام يخلي كل قطعة محتوى ليها هدف",
    "subtitle": "لمّين بتتكلم، إيه المشكلة، وإيه نوع المحتوى اللي تقدر تكرره بثبات."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "ليه التعب كبير والنتيجة ضعيفة؟",
    "bullets": [
      "ناس كتير بتنشر يوميًا، بس مفيش تفاعل حقيقي ولا رسايل جدية.",
      "المشكلة غالبًا مش في الجهد، المشكلة إن النشر بيحصل من غير اتجاه ثابت."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "لما المحتوى يبقى سيستم، كل بوست بيخدم وعد واضح لجمهور محدد.",
      "الـ AI يساعدك تطلع أفكار وتعيد صياغة بسرعة، لكن الحكم على المناسب ليك لازم يكون قرارك أنت."
    ],
    "title": "سيستم محتوى = قرارات ثابتة"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "title": "بوست عابر ولا نظام متكرر؟",
    "right": {
      "body": "رسالة ثابتة ونوع محتوى متكرر، فالجمهور يفهمك أسرع ويثق فيك أكتر.",
      "label": "نظام محتوى"
    },
    "left": {
      "body": "فكرة كل يوم من الصفر، فتعب أعلى ونتائج متذبذبة.",
      "label": "نشر عابر"
    }
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "نظام متكامل",
    "term": "Content System",
    "definition": "طريقة شغل فيها جمهور محدد + مشكلة واضحة + نوع محتوى متكرر."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "وعد ثابت",
    "term": "Content Promise",
    "definition": "الوعد اللي الناس بتتوقعه منك كل مرة."
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "definition": "شكل محتوى تقدر تعيده بسهولة من غير ما تحس إنك بتبدأ من الصفر.",
    "term": "Repeatable Format",
    "tag": "شكل متكرر"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "src": "lessons/creator-m1-l1-why-content.jpg",
    "eyebrow": "لقطة بصرية",
    "caption": "الترتيب ده بيوضح إن كل جزء ليه دور، وده بالظبط معنى إن المحتوى يبقى نظام.",
    "title": "شكل السيستم وهو مرتب"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "جاوب على السؤال عشان تثبت فهمك للدرس.",
    "title": "سؤال واحد للتطبيق",
    "highlight": "اختبر فهمك",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "title": "اكتب وعد المحتوى بتاعك",
    "tagline": "المهمة دي هتساعدك تطبق اللي اتعلمته وتحدد وعد محتواك.",
    "highlight": "حدد جمهورك ومشكلتهم ونوع المحتوى",
    "eyebrow": "تدريب عملي"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "أنت دلوقتي شايف الفرق بين نشر عشوائي ونظام محتوى حقيقي.",
      "بالأساس ده، أنت جاهز للخطوة الجاية!"
    ],
    "title": "دلوقتي عندك أساس قوي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [666, 487, 509, 569, 457, 433, 471, 451, 324, 532, 403];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
