// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "المتابعين مهمين، بس لازم يكون فيه طريق واضح للـ Leads.",
    "highlight": "من غير كوبري",
    "title": "المتابع مش عميل",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "ناس كتير بتتابعك وتستفيد، لكن لحظة القرار تضيع لأن الخطوة الجاية مش واضحة لهم.",
      "لو ما فيش CTA بسيط وقيمة أولية، المتابع يفضل متابع لفترة طويلة من غير ما يتحول لعميل محتمل."
    ],
    "title": "فجوة بين الانتباه والشراء"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "المحتوى يبني ثقة، والـ CTA ينقل الشخص لخطوة محددة: تحميل هدية بسيطة، أو رسالة بكلمة مفتاحية، أو تسجيل قصير.",
      "الهدف في المرحلة دي مش البيع الفوري، الهدف تجمع ليدز جادة تقدر تتابع معها بشكل محترم.",
      "كل ما الكوبري بسيط وواضح، التحويل يزيد بدون ضغط أو إلحاح."
    ],
    "title": "اعمل كوبري صغير وواضح"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "right": {
      "body": "قيمة مجانية بسيطة + CTA محدد + متابعة. النتيجة: ليدز أكثر جودة حتى لو المشاهدات أقل.",
      "label": "بكوبري واضح"
    },
    "left": {
      "label": "من غير كوبري",
      "body": "محتوى جميل وتفاعل كويس، لكن مفيش خطوة انتقال واضحة. النتيجة: جمهور واسع وتحويل ضعيف."
    },
    "title": "متابعين بس ولا نظام تحويل؟"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "عميل محتمل",
    "term": "Lead",
    "definition": "شخص مهتم فعلا ومستعد ياخد خطوة للتواصل أو التسجيل."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "هدية مجانية",
    "definition": "قيمة مجانية بسيطة مقابل وسيلة تواصل.",
    "term": "Lead Magnet"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "tag": "دعوة للعمل",
    "term": "CTA",
    "definition": "دعوة واضحة لخطوة واحدة بعد المحتوى."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "كل مرحلة تقلل العدد لكن تزود الجودة.",
      "المهم يكون الانتقال من مرحلة لمرحلة واضح."
    ],
    "title": "قمع الـ Leads من المحتوى"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "highlight": "بسؤال سريع",
    "title": "اختبر فهمك",
    "tagline": "شاركنا إجابتك في التعليقات عشان نشوف فهمك للدرس.",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "yellow",
    "bullets": [
      "دلوقتي مش هتعتمد على الصدفة. عندك خطوة تحويل واضحة تشتغل عليها وتتطور بالأرقام.",
      "كذا تبني Creator business متوازن: محتوى يوصل، ونظام يحول."
    ],
    "title": "دلوقتي عندك كوبري للـ Leads"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "نتقابل في الدرس الجاي عشان نكمل رحلة بناء البيزنس بتاعك.",
    "highlight": "ودخل ثابت",
    "title": "ابني كوبري لـ Leads أكتر",
    "eyebrow": "الخلاصة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [486, 450, 556, 603, 335, 388, 339, 330, 299, 400, 291];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
