// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "title": "هتفهم إيه",
    "subtitle": "المستخدم الذكي يعرف إمتى يثق وإمتى يراجع.",
    "highlight": "النهاردة؟",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "ده بيحصل، مش معناه إن الأداة وحشة.",
      "الأخطر إنه يغلط بثقة فتصدّق من غير مراجعة.",
      "الخبر الحلو: في مهام كتير الـ AI بيوفر وقت رهيب."
    ],
    "title": "الـ AI رد بثقة — وبعدين طلع فيه حاجة غلط؟"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الـ AI شغال كويس في: صياغة، تلخيص، ترتيب أفكار.",
      "محتاج حذر في: أرقام دقيقة، أخبار النهاردة، قانون وطب ومال.",
      "المراجعة جزء طبيعي من استخدام الـ AI."
    ],
    "title": "الـ AI قوي في اللغة — محتاج حذر في الحقائق"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "هلوسة",
    "definition": "لما الـ AI يقول معلومة بثقة — والمعلومة مش صحيحة.",
    "term": "Hallucination"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Verification",
    "tag": "مراجعة",
    "definition": "تتأكد من المعلومة المهمة من مصدر موثوق قبل ما تعتمد عليها."
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "right": {
      "body": "سعر خامة النهارده، نصيحة قانونية، رقم مالي في تقرير — استخدم AI كبداية، وتحقق من مصدر موثوق.",
      "label": "راجع قبل الاعتماد"
    },
    "title": "نفس الأداة — استخدام مريح واستخدام محتاج حذر",
    "left": {
      "body": "تلخيص اجتماع، كتابة مسودة إيميل، ترتيب أفكار لبوست — خذ الرد وعدّل بصوتك.",
      "label": "استخدم بسرعة"
    }
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "eyebrow": "شوفها ببساطة",
    "src": "lessons/intro-m1-l4-ai-can-cannot.jpg",
    "caption": "على الشمال: كتابة وتلخيص وأفكار — استخدم بثقة. على اليمين: أرقام وحقائق متغيرة — راجع قبل ما تعتمد. الصورة توضّح الفكرة — مش قاعدة خوف.",
    "title": "خريطة بسيطة: قوة و حذر"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "eyebrow": "دورك دلوقتي",
    "highlight": "مش امتحان",
    "tagline": "اختبر فهمك: إمتى تثق وإمتى تراجع.",
    "title": "سؤال واحد"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "راجع اللي فات واستعد للدرس الجاي!",
    "title": "إيه اللي عندك",
    "eyebrow": "خلّصت الخطوة الرابعة",
    "highlight": "دلوقتي؟"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [293, 396, 378, 343, 367, 384, 421, 364, 412];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
