// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الحماس في البداية بيخليك عايز Builder و Creator و Automator وكل حاجة مرة واحدة. بس التشتت هنا خطر: ٥ بدايات مفتوحة = صفر نتيجة ملموسة. الدرس ده هيخليك تختار مسار واحد بناءً على مشكلتك الحالية، مش على اللي شكله أمتع.",
    "highlight": "٥ مسارات",
    "chip": "TENSION",
    "title": "لو بدأت الـ ٥ مسارات مع بعض… غالبًا مش هتخلص ولا واحد"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "نسخة شغالة",
    "term": "Builder",
    "definition": "تبني منتج أو تطبيق أو MVP بفكرة واضحة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "محتوى وجماهير",
    "term": "Creator",
    "definition": "تحوّل خبرتك لمحتوى يجذب جمهور وعملاء."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "تخلّي المهام المتكررة تشتغل لوحدها بتدفقات واضحة.",
    "tag": "مهام آلية",
    "term": "Automator"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "بيانات وقرارات",
    "term": "Analyst",
    "definition": "تحوّل البيانات والأسئلة لأرقام وقرارات أوضح."
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "definition": "تستخدم AI لتقليل تكلفة التشغيل وتحسين النمو والربح.",
    "tag": "نمو وربح",
    "term": "Business"
  },
  {
    "card": "BulletsCard",
    "accent": "mint",
    "title": "Decision Tree في سؤال واحد",
    "bullets": [
      "اسأل نفسك: إيه أكبر مشكلة محتاج أحلها الشهرين الجايين؟",
      "لو المشكلة: «عندي فكرة ومش عارف أبنيها» → Builder.",
      "لو المشكلة: «عندي خبرة ومفيش جمهور» → Creator.",
      "لو المشكلة: «وقتي بيتاكل في تكرار» → Automator.",
      "لو المشكلة: «عندي بيانات ومش شايف القرار» → Analyst.",
      "لو المشكلة: «البزنس محتاج يكبر بتكلفة أقل» → Business."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "caption": "كل المسارات منشورة ومفتوحة. الاختيار مش قفل باب — الاختيار تركيز عشان تطلع بنتيجة أولى.",
    "title": "الخمسة متاحين — بس ابدأ بواحد",
    "eyebrow": "شوف بنفسك",
    "src": "lessons/intro-m1-l7-choose-your-path.jpg"
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "right": {
      "body": "تختار مسار واحد، تخلص أول موديول، وتطلع بنتيجة ملموسة قبل ما تضيف مسار تاني.",
      "label": "RIGHT — مسار واحد لنتيجة واحدة"
    },
    "left": {
      "body": "تفتح ٥ مسارات، تاخد أول درس من كل واحد، وبعد شهر تلاقي مفيش مشروع ولا محتوى ولا automation.",
      "label": "FAILURE — كل حاجة مرة واحدة"
    },
    "title": "التركيز هو الاختصار الحقيقي"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "tagline": "حل الأسئلة دي عشان تتأكد إنك فهمت كل مسار بيعمل إيه بالظبط.",
    "title": "مين يناسبه أنهي مسار؟",
    "eyebrow": "دورك دلوقتي",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "highlight": "ركز في اللي جاي",
    "eyebrow": "الدرس الجاي",
    "tagline": "في الدرس الجاي هنفهم ليه المحتوى أهم بكتير من مجرد Posting عشوائي.",
    "title": "المحتوى مش Posting"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [1023, 527, 417, 514, 474, 445, 886, 583, 798, 393, 419];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
