// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "الدرس ده هيفهمك الفرق العملي: تستخدم برنامج عادي إمتى، وتستخدم AI إمتى.",
    "title": "لو بتتعامل مع الـ AI كأنه Google…",
    "highlight": "هتطلع بنتيجة ضعيفة",
    "chip": "أهلًا"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "قواعد ثابتة",
    "term": "Rule-based Software",
    "definition": "برنامج شغال بقواعد ثابتة: نفس المدخل يطلع نفس النتيجة."
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "definition": "نظام بيتعامل مع اللغة والأنماط ويطلع رد مناسب للسياق.",
    "tag": "مرن ومتغير",
    "term": "AI Model"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "نتيجة ثابتة ومتوقعة.",
    "tag": "إجابة واحدة",
    "term": "Deterministic"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "نتيجة مبنية على احتمالات، فممكن تختلف شوية كل مرة.",
    "tag": "نتائج متعددة",
    "term": "Probabilistic"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "لو المهمة لها إجابة واحدة دقيقة: استخدم برنامج عادي أو مصدر موثوق.",
      "لو المهمة محتاجة صياغة، تلخيص، أفكار، مقارنة، شرح: استخدم AI.",
      "لو المهمة فيها الاتنين: خلّي البرنامج يحسب، والـ AI يشرح أو يرتب النتيجة.",
      "مثال: Excel يحسب المبيعات، والـ AI يكتب ملخص تنفيذي من الأرقام."
    ],
    "title": "قاعدة الاختيار السريع"
  },
  {
    "card": "ScreenshotCard",
    "accent": "lavender",
    "caption": "حفظ التقدم والتنقل بين الدروس = Software ثابت. تقييم النصوص والمساعد الذكي = AI مرن.",
    "eyebrow": "شوف بنفسك",
    "title": "المنصة نفسها مزيج من الاتنين",
    "src": "lessons/intro-m1-l5-ai-vs-software.jpg"
  },
  {
    "card": "CompareCard",
    "accent": "peach",
    "left": {
      "body": "تخليه يحسب فاتورة أو يطلع رقم دقيق، وبعدين تستغرب لما تلاقي فرق في الحساب.",
      "label": "FAILURE — AI لكل حاجة"
    },
    "title": "اختيار الأداة أهم من قوة الأداة",
    "right": {
      "label": "RIGHT — كل أداة في مكانها",
      "body": "استخدم Excel للحساب، Google للمصادر، والـ AI للشرح والصياغة والترتيب."
    }
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "title": "اختار الأداة الصح",
    "tagline": "طبّق دلوقتي عشان تفرّق صح بين الـ AI والبرامج العادية.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "اختبر فهمك"
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "title": "Mission — قارن نفس المهمة بأداتين",
    "tagline": "اختار مهمة صغيرة واعملها مرة بأداة تقليدية ومرة بالـ AI، وشوف الفرق بنفسك.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "جرّب بنفسك"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "title": "الـ pipeline هنا مبني على نفس القاعدة",
    "bullets": [
      "Software: يحفظ، يرتب، ويتأكد من القواعد.",
      "AI: يقرأ النص ويشرح ويوجه.",
      "النتيجة: نظام أدق وأذكى في نفس الوقت."
    ]
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [672, 385, 401, 366, 383, 732, 417, 520, 336, 483, 549];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
