// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "ناس كتير بتقول: أكيد محتاج برمجة، أكيد هبوّظ حاجة، أكيد ده مش ليا. الحقيقة أبسط: إنت بتكتب كلام عادي، وتشوف الرد، وتعدّل السؤال لو الرد مش مناسب. الدرس ده مش عن التكنولوجيا. ده عن عقلية التجربة من غير رهبة.",
    "title": "الخوف من الـ AI بيأخر ناس كتير",
    "highlight": "أكتر من صعوبة الـ AI نفسه",
    "chip": "أهلًا - TENSION"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "tag": "تفكيرك",
    "definition": "طريقة تفكيرك تجاه التعلم والتجربة.",
    "term": "Mindset"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "tag": "تحسين خطوة خطوة",
    "term": "Iteration",
    "definition": "تحسين الطلب خطوة خطوة بدل ما تستنى نتيجة مثالية من أول مرة."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "tag": "تجارب آمنة",
    "term": "Safe Practice",
    "definition": "تجارب صغيرة مفيهاش مخاطرة على شغل مهم أو قرار حساس."
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "Feedback Loop",
    "definition": "تشوف النتيجة، تقول إيه اللي ناقص، وتطلب تعديل.",
    "tag": "تقييم وتعديل"
  },
  {
    "card": "BulletsCard",
    "accent": "mintDeep",
    "bullets": [
      "١. ابدأ بحاجة صغيرة قوي: رسالة، تلخيص، فكرة بوست.",
      "٢. متطلبش نتيجة مثالية من أول مرة. اطلب تعديل واحد كل مرة.",
      "٣. استخدمه الأول في حاجات آمنة، وبعد ما تفهمه استخدمه في الشغل الأهم.",
      "الذكاء هنا مش إنك تعرف مصطلحات كتير. الذكاء إنك تجرب وتلاحظ وتعدّل."
    ],
    "title": "٣ قواعد تكسر الرهبة فورًا"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "caption": "كل درس خطوة صغيرة. مفيش حاجة هتتكسر لو prompt طلع ضعيف — هتعدله وتتعلم.",
    "eyebrow": "شوف بنفسك",
    "src": "lessons/intro-m1-l6-learn-without-fear.jpg",
    "title": "من رهبة لتجربة صغيرة"
  },
  {
    "card": "CompareCard",
    "accent": "lavender",
    "right": {
      "body": "Prompt واحد آمن كل يوم. تشوف الرد، تطلب تعديل، وتتعلم من النتيجة.",
      "label": "RIGHT — تجربة صغيرة يوميًا"
    },
    "title": "الخوف بيتحل بالفعل مش بالمشاهدة",
    "left": {
      "body": "تتفرج على شروحات كتير وتفضل خايف تجرب، فالمعرفة تزيد والمهارة تفضل صفر.",
      "label": "FAILURE — تستنى تفهم كل حاجة الأول"
    }
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "حلّ الأسئلة عشان تطبق اللي اتعلمته وتثبت فهمك.",
    "eyebrow": "اختبر فهمك",
    "title": "إيه التصرف الصح؟",
    "highlight": "حان وقت التطبيق"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "highlight": "ابدأ بتجربة صغيرة آمنة",
    "title": "Mission — حوّل خوفك لتجربة",
    "tagline": "اكتب خوفك، واعمل تجربة تكسره. انسخ التعليمات وجرّب.",
    "eyebrow": "دورك دلوقتي"
  },
  {
    "card": "BulletsCard",
    "accent": "pink",
    "bullets": [
      "درس قصير → تطبيق صغير → Feedback واضح.",
      "مفيش قفزة ضخمة مرة واحدة.",
      "التقدم بيتبني من تكرار خطوات صغيرة."
    ],
    "title": "تصميم المنصة معمول لتجارب صغيرة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [635, 334, 369, 413, 324, 652, 348, 505, 257, 411, 493];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
