// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "أداة بتساعدك تفكّر وتنتج أسرع.",
    "subtitle": "مش سحر، ومش وحش جاي ياخد مكانك.",
    "chip": "HERO",
    "title": "AI يعني إيه فعلًا؟"
  },
  {
    "card": "ConceptCard",
    "accent": "lavender",
    "term": "Data (بيانات)",
    "definition": "المعلومات اللي بنستخدمها عشان نفهم حاجة حصلت.",
    "tag": "فهم اللي فات"
  },
  {
    "card": "ConceptCard",
    "accent": "peach",
    "term": "Algorithm (خوارزمية)",
    "tag": "خطوات بسيطة",
    "definition": "خطوات بسيطة ومحددة بنمشي عليها عشان نخلص مأمورية."
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "ده \"المُخ\" اللي اتعلم وخلص تدريب وجاهز يشتغل.",
    "tag": "المخ المدرب",
    "term": "Model (موديل)"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "term": "AI (الذكاء الاصطناعي)",
    "definition": "المجال الكبير اللي بنخلي فيه الآلة تقلد ذكاء البشر.",
    "tag": "تقليد ذكاء البشر"
  },
  {
    "card": "ConceptCard",
    "accent": "mintDeep",
    "tag": "تتعلم من البيانات",
    "definition": "فرع من الـ AI بيخلي الآلة تتعلم لوحدها من البيانات.",
    "term": "Machine Learning (تعلم الآلة)"
  },
  {
    "card": "ConceptCard",
    "accent": "mint",
    "term": "Generative AI (الذكاء الاصطناعي التوليدي)",
    "definition": "نوع ذكاء اصطناعي شاطر في الكلام والكتابة وصناعة المحتوى.",
    "tag": "شاطر في المحتوى"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "الـ AI شاف كمية ضخمة جدًا من الأمثلة والنصوص.",
      "لما تطلب منه حاجة، بيستخدم الأمثلة دي عشان يطلعلك نتيجة قريبة من اللي إنت محتاجه.",
      "اللي بيخلّيه مهم: بقى ممكن تستخدم أدوات قوية بكلامك العادي، من غير ما تكون مبرمج.",
      "وأحسن طريقة تفهمه إنك تجرّبه في حاجة بسيطة من حياتك — وده اللي هتعمله النهارده."
    ],
    "title": "أداة بتاخد طلب وتطلع نتيجة"
  },
  {
    "card": "ScreenshotCard",
    "accent": "peach",
    "title": "مساعد الـ AI شغّال جوّه المنصة",
    "caption": "ده /ai-assistant بتاعنا. AI شغّال فعلًا في المنصة — بيقرأ الدرس قبل ما يرد، ويرد بنفس أسلوبنا. مثال على إن الـ AI أداة عملية مش سحر.",
    "src": "lessons/intro-m1-l1-what-is-ai-assistant.jpg",
    "eyebrow": "شوف بنفسك"
  },
  {
    "card": "CompareCard",
    "accent": "yellow",
    "left": {
      "body": "تتعامل معاه كأنه عقل بشري بيفهم نيّتك من غير ما توضّح.",
      "label": "غلط ✗"
    },
    "title": "السلوك الصح × الغلطة الشائعة",
    "right": {
      "body": "تستخدمه كأداة بتساعدك تفكّر وتنتج أسرع.",
      "label": "صح ✓"
    }
  },
  {
    "card": "CTACard",
    "accent": "pink",
    "tagline": "جاوب على كام سؤال عشان تطبق اللي اتعلمته في حياتك.",
    "title": "اختار أول استخدام عملي ليك",
    "highlight": "اختبر فهمك",
    "eyebrow": "دورك دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [331, 328, 391, 349, 315, 414, 336, 634, 357, 399, 306];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
