// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "subtitle": "مش سباق شعبية — كل واحد يحل نوع مشكلة مختلف.",
    "title": "هتفهم إيه النهاردة؟",
    "highlight": "المسارات الخمسة",
    "chip": "أهلًا"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "عايز تبدأ الـ ٥ مسارات مع بعض؟",
    "bullets": [
      "الحماس بيخليك عايز Business و Creator و Builder وكل حاجة مرة واحدة.",
      "بس ٥ بدايات مفتوحة غالبًا = صفر نتيجة ملموسة. التشتت أخطر من البطء.",
      "القرار الصح: مسار واحد الأول — نتيجة واحدة — وبعدين تضيف مسار تاني لو محتاج."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "المنصة مرتبة على ٣ مستويات. Intro (اللي خلّصته) = البداية لكل الناس.",
      "المستوى ١ — AI User: Business (تشغّل شغلك أحسن بالـ AI)، Creator (محتوى وجمهور بالـ AI)، Analyst (قرارات أذكى بالأرقام والـ AI).",
      "المستوى ٢ — AI Operator: Automator (شغل متكرر يشتغل لوحده — Leads، متابعة، تقارير).",
      "المستوى ٣ — AI Builder: Builder (تبني أدوات وتطبيقات بالـ AI) — اختياري وعميق. مش الوعد الأساسي للمنصة؛ للي عايز يبني منتج بنفسه.",
      "اسأل نفسك: أكبر مشكلة عايز أحلها الشهرين الجايين؟ المسار اللي يطابقها هو اختيارك."
    ],
    "title": "اختار المسار اللي يحل مشكلتك — مش اللي يبان أجمل"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "مجموعة دروس مركّزة على نوع مهارة واحد — مش لازم تخلص كل المسارات.",
    "tag": "نوع مهارة واحد",
    "term": "Path (مسار)"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "tag": "لبناء تطبيقات",
    "term": "Builder (باني)",
    "definition": "مسار تقني اختياري لبناء تطبيقات وأدوات — للي عايز يغوص أعمق."
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "left": {
      "label": "كل المسارات مرة واحدة",
      "body": "أول درس من كل مسار — وبعد شهر مفيش مشروع ولا محتوى ولا أتمتة واضحة."
    },
    "right": {
      "body": "تختار مسار، تخلص أول موديول، وتطلع بحاجة ملموسة — وبعدين تفكر في التاني.",
      "label": "مسار واحد لنتيجة واحدة"
    },
    "title": "تركيز واحد أسرع من حماس خمسة"
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "caption": "فكّرها كخريطة: فوق Intro، تحتها مسارات المستوى ١ (Business، Creator، Analyst)، بعدين Automator، وآخر حاجة Builder للعمق الاختياري. اختيارك = تركيز — مش قفل باقي المسارات.",
    "title": "خريطة المستويات — مش سباق",
    "src": "lessons/intro-m1-l7-choose-your-path.jpg",
    "eyebrow": "شوفها ببساطة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "title": "تطبيق عملي",
    "tagline": "حلّ السؤال عشان تتأكد إنك فهمت صح.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "اختبر فهمك للمسارات"
  },
  {
    "card": "CTACard",
    "accent": "peach",
    "tagline": "ده ختام الـ Intro — اختار مسارك بناءً على هدف حقيقي عندك.",
    "eyebrow": "مهمتك",
    "title": "اختار مسار واحد",
    "highlight": "ووضّح ليه اخترته"
  },
  {
    "card": "CTACard",
    "accent": "yellow",
    "highlight": "اختار مسارك وابدأ أول درس",
    "tagline": "فهمت الـ AI، عرفت أدواته، دلوقتي وقت التطبيق العملي.",
    "eyebrow": "خلّصت Intro",
    "title": "رحلتك الحقيقية تبدأ دلوقتي"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [509, 509, 497, 463, 521, 439, 619, 193, 364, 349];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
