// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "highlight": "الـ AI أداة",
    "title": "هتفهم إيه النهاردة؟",
    "subtitle": "مش سحر، زي مساعد ذكي على الموبايل.",
    "chip": "بداية الدرس"
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "bullets": [
      "طبيعي. في ناس بتقولك «استخدم ChatGPT» من غير ما تشرحلك هو إيه أصلًا.",
      "مش مطلوب منك تبقى خبير النهاردة. المطلوب بس تفهم الفكرة الأساسية وتجرّبها مرة واحدة بإيدك.",
      "لو حسّيت إن الكلام كتير، خُدها خطوة خطوة — كل قسم صغير ولوحده."
    ],
    "title": "بتسمع عن AI كتير ومش واضح تبدأ منين؟"
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "bullets": [
      "الـ AI برنامج اتعلّم من أمثلة كتير، وبيطلّعلك رد قريب من اللي طلبته. زي الآلة الحاسبة: بتوفر وقت، بس القرار في إيدك.",
      "مش بيفكّر زي الإنسان — بيحسب أنسب رد من اللي شافه قبل كده. عشان كده أحيانًا بيغلط، وده طبيعي.",
      "التجربة هتفهمك أسرع من أي شرح طويل."
    ],
    "title": "الـ AI أداة مساعدة — مش سحر ولا بديل عنك"
  },
  {
    "card": "ConceptCard",
    "accent": "yellow",
    "definition": "برنامج بيساعدك في حاجة محددة — كتابة، تلخيص، تنظيم أفكار.",
    "tag": "مساعد رقمي",
    "term": "AI (ذكاء اصطناعي)"
  },
  {
    "card": "ConceptCard",
    "accent": "pink",
    "definition": "اسم البرنامج الجاهز اللي بتتكلم معاه.",
    "tag": "برنامج جاهز",
    "term": "Model (موديل)"
  },
  {
    "card": "CompareCard",
    "accent": "mintDeep",
    "right": {
      "label": "لو فهمته صح",
      "body": "تكتب طلب واضح، تشوف الرد، وتعدّل سؤالك. كل محاولة بتعلّمك إزاي تتعامل معاه كأداة — مش كإنسان."
    },
    "title": "نفس الأداة — فهمين مختلفين",
    "left": {
      "label": "لو فهمته غلط",
      "body": "تتوقع إنه فاهم نيّتك من أول مرة، وتزعل لما الرد يطلع مش مظبوط. فتسيبه وتقول «مش شغال معايا»."
    }
  },
  {
    "card": "ScreenshotCard",
    "accent": "mint",
    "src": "lessons/intro-m1-l1-what-is-ai-assistant.jpg",
    "title": "حلقة واحدة: سؤال → رد → تعديل",
    "caption": "الفكرة كلها في حلقة بسيطة: إنت تسأل → الـ AI يرد → إنت تستخدم الرد أو تعدّله. الصورة توضّح الشكل — مش محتاج تفهم برمجة ولا إعدادات.",
    "eyebrow": "شوفها ببساطة"
  },
  {
    "card": "CTACard",
    "accent": "lavender",
    "tagline": "اختبر فهمك للدرس بسؤال واحد سريع. وبعدها جرّب الـ AI بنفسك.",
    "eyebrow": "دورك دلوقتي",
    "highlight": "الـ AI أداة مساعدة",
    "title": "سؤال واحد — مش امتحان"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [461, 501, 498, 385, 370, 483, 383, 384];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
