// AUTO-GENERATED by remotion/scripts/build-lesson.py — do NOT edit.
import type { SceneData } from "../lesson-cards";

export const SCENES: SceneData[] = [
  {
    "card": "TitleCard",
    "accent": "mint",
    "chip": "ابدأ من هنا",
    "subtitle": "بس تفتح صفحة، تكتب أول سؤال، وتشوف الرد. دقيقتين دلوقتي بيوفّروا عليك ساعات حيرة في كل درس جاي.",
    "title": "افتح أول AI ليك في دقيقتين",
    "highlight": "مفيش تنزيل. مفيش إعدادات. مفيش فلوس."
  },
  {
    "card": "BulletsCard",
    "accent": "lavender",
    "title": "ليه تفتح الحساب دلوقتي بالظبط",
    "bullets": [
      "الحساب مجاني تمامًا. الـ Free Tier بيدّيك شغل بيكلف ١٥ لـ ٣٠ دولار في الشهر.",
      "أول ٤٨ ساعة بعد فتح الحساب الناس بتوفّر متوسط ٣ لـ ٥ ساعات شغل.",
      "أحمد (Freelancer): وفّرت أول ٢٠٠ دولار في أول أسبوعين على الـ Free Tier."
    ]
  },
  {
    "card": "BulletsCard",
    "accent": "peach",
    "title": "٣ خيارات مجانًا — اختار واحد",
    "bullets": [
      "ChatGPT: الأشهر، أسهل واجهة للمبتدئ.",
      "Claude: جودة كتابة طويلة، أسلوب مهذّب.",
      "Gemini: مدمج مع Google، Free Tier سخي.",
      "كلهم Chatbots، اختار واحد وجرّب. الـ Free Tier كافي."
    ]
  },
  {
    "card": "ScreenshotCard",
    "accent": "yellow",
    "eyebrow": "شوف بنفسك",
    "src": "lessons/unique/intro-setup-your-ai.jpg",
    "title": "كده هتلاقي نفسك",
    "caption": "الثلاث واجهات تقريبًا واحدة: مربّع كتابة تحت، والمحادثة بتظهر فوق. لو فتحت أي واحد منهم، هتلاقي نفسك على طول. مفيش حاجة معقّدة."
  },
  {
    "card": "CompareCard",
    "accent": "pink",
    "right": {
      "body": "تفتح واحد بس النهارده وتتعوّد عليه. تقدر تجرّب التانيين بعدين لما تكون فاهم الأساسيات.",
      "label": "RIGHT ✓"
    },
    "title": "السلوك الصح × الغلطة الشائعة",
    "left": {
      "body": "تفتح الـ٣ مرة واحدة وتقارن بينهم من غير ما تستخدم ولا واحد فعلًا. ده بيأخّر بدايتك أسبوع.",
      "label": "FAILURE ✗"
    }
  },
  {
    "card": "CTACard",
    "accent": "mintDeep",
    "highlight": "جاوب على الأسئلة",
    "tagline": "وطبّق اللي اتعلّمته في دقيقة!",
    "eyebrow": "دورك دلوقتي",
    "title": "افتح حساب، اكتب أول رسالة"
  }
] as SceneData[];

export const SCENE_FRAMES: number[] = [460, 581, 477, 459, 487, 258];
export const TOTAL_FRAMES = SCENE_FRAMES.reduce((a, b) => a + b, 0);
