/** Pure PostgreSQL output for the configured lesson-reference tables. */
const LESSON_TABLES = [
  "lesson_progress",
  "lesson_feedback",
  "lesson_notes",
  "lesson_quiz_attempts",
  "lesson_review_schedule",
  "user_lesson_status",
  "user_mission_state",
  "mission_submissions",
  "learner_events",
] as const;

type LessonRename = { oldId: string; newId: string };

function sqlLiteral(value: string): string {
  if (value.includes("\0")) {
    throw new Error("Lesson IDs cannot contain NUL characters.");
  }
  // E literals preserve backslashes independently of standard_conforming_strings.
  return "E'" + value.replace(/\\/g, "\\\\").replace(/'/g, "''") + "'";
}

export function buildLessonRenumberMigration(renames: readonly LessonRename[]): string {
  const values = renames.map(({ oldId, newId }) => ({
    oldId: sqlLiteral(oldId),
    newId: sqlLiteral(newId),
  }));
  const lines = [
    "-- Auto-generated by scripts/lessons-renumber.ts",
    "-- Renames lesson_id values across the configured learner-data tables.",
    "BEGIN;",
  ];
  for (const table of LESSON_TABLES) {
    lines.push("-- Table: " + table);
    for (const { oldId, newId } of values) {
      // Identifiers come exclusively from the fixed table list, never lesson IDs.
      lines.push(
        'UPDATE public."' +
          table +
          '" SET lesson_id = ' +
          newId +
          " WHERE lesson_id = " +
          oldId +
          ";",
      );
    }
  }
  lines.push("COMMIT;");
  return lines.join("\n") + "\n";
}
