import type { SupportedLocale } from "@/lib/locale/types";

const ar = {
  parentTitle: "مساحة وليّ الأمر",
  familyIntro:
    "من هنا تدير ملفات الأطفال وخطواتهم من حساب مسارات نفسه. تجد سجل الموافقة في بيانات الحساب.",
  manageFamily: "الانتقال إلى مساحة وليّ الأمر",
  viewLevel: "عرض خطوات المسار",
  levelStartNotice:
    "هذه أسماء الخطوات. لفتح أي خطوة، ادخل بحساب مسارات، ووافق على سياسة الأطفال وأنشئ ملفًا مناسبًا للمسار.",
  signIn: "تسجيل الدخول",
  signUp: "إنشاء حساب مسارات",
  signInNotice:
    "استخدم حساب مسارات الحالي، أو أنشئ حسابًا واحدًا للمنصة. بعد الدخول توافق على سياسة الأطفال وتنشئ ملفاتهم؛ لا يوجد تسجيل منفصل لكيدز.",
  waiting: "التحقق من جاهزية الحساب...",
  pending: "اقرأ سياسة خصوصية الأطفال ووافق عليها من حساب وليّ الأمر لفتح الملفات والخطوات.",
  unavailable: "تعذّر التحقق من جاهزية كيدز الآن. حاول لاحقًا.",
  setupPending: "خدمة كيدز قيد التجهيز. إنشاء ملفات الأطفال والخطوات غير متاح الآن.",
  retryCheck: "إعادة المحاولة",
  request: "وافق على سياسة الأطفال",
  requestNote: "تواصل ببريد حسابك فقط، دون بيانات الطفل.",
  noProfile: "بعد الموافقة، أنشئ ملفًا لكل طفل واختر مستواه.",
  create: "إنشاء ملف طفل",
  name: "اسم مختصر للملف (دون اسم العائلة)",
  chooseLevel: "اختر المسار",
  submit: "حفظ الملف",
  profileError: "لم يُحفظ الملف. حاول لاحقًا.",
  profiles: "ملفات الأطفال",
  profileLimit: "وصلت إلى الحد الأقصى: 3 ملفات أطفال لكل أسرة.",
  chooseProfile: "اختر ملفًا لهذا المسار",
  activeProfile: "ملف الطفل النشط",
  otherLevelProfile: "هذا الملف لمسار آخر. اخرج منه لاختيار ملف لهذا المسار.",
  exitProfile: "الخروج من ملف الطفل",
  noLevelProfile: "لا يوجد ملف لهذا المسار.",
  level: "المسار",
  lesson: "الخطوة",
  free: "مجاني بعد موافقة وليّ الأمر",
  requiresPlan: "يتطلب اشتراك كيدز مستقلًا",
  openLesson: "عرض حالة الخطوة",
  back: "العودة إلى كيدز",
  backLevel: "العودة إلى المسار",
  locked: "الخطوة غير متاح حاليًا",
  loading: "جارٍ فتح الخطوة...",
  unavailableLesson: "لم تكتمل جاهزية الخطوة. لم يُحمّل الفيديو أو المحتوى.",
  watch: "شاهد الخطوة",
  objectives: "ماذا سنتعلم؟",
  scenes: "فكرة الخطوة",
  reading: "اقرأ وتعلّم",
  practice: "تطبيق عملي",
  quiz: "تحدٍ سريع",
  checkAnswer: "تحقق من الإجابة",
  correct: "إجابة صحيحة",
  retry: "راجع الفكرة ثم حاول مجددًا",
  mission: "مهمتك",
  hint: "مساعدة من الخطوة",
  loadHint: "عرض التلميح",
  privacy: "استخدم تفاصيل خيالية فقط، ولا تشارك اسمك الكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الخطوة",
  videoUnavailable: "الفيديو غير جاهز حاليًا.",
} as const;
type Copy = { [K in keyof typeof ar]: string };
const egyptian: Copy = {
  parentTitle: "مساحة وليّ الأمر",
  familyIntro:
    "من هنا تدير ملفات الأطفال وخطواتهم من نفس حساب مسارات. سجل موافقتك موجود في بيانات الحساب.",
  manageFamily: "روح لمساحة وليّ الأمر",
  viewLevel: "شوف خطوات المسار",
  levelStartNotice:
    "دي أسماء الخطوات. عشان تفتح خطوة، ادخل بحساب مسارات ووافق على سياسة الأطفال واعمل ملف للمسار ده.",
  signIn: "دخول",
  signUp: "اعمل حساب مسارات",
  signInNotice:
    "لو عندك حساب مسارات ادخل بيه، ولو جديد اعمل حساب واحد للمنصة. بعدها توافق على سياسة الأطفال وتعمل ملفاتهم؛ مفيش تسجيل تاني لكيدز.",
  waiting: "بنتأكد إن الحساب جاهز...",
  pending: "اقرأ سياسة خصوصية الأطفال ووافق عليها من حساب وليّ الأمر عشان تفتح الملفات والخطوات.",
  unavailable: "مش قادرين نتأكد من جاهزية كيدز دلوقتي. حاول بعد شوية.",
  setupPending: "خدمة كيدز لسه بتتجهز. ملفات الأطفال والخطوات مش متاحة دلوقتي.",
  retryCheck: "حاول تاني",
  request: "وافق على سياسة الأطفال",
  requestNote: "تواصل ببريد حسابك بس، من غير بيانات الطفل.",
  noProfile: "بعد الموافقة، اعمل ملف لكل طفل واختار مستواه.",
  create: "اعمل ملف طفل",
  name: "اسم مختصر للملف (من غير اسم العيلة)",
  chooseLevel: "اختار المسار",
  submit: "احفظ الملف",
  profileError: "الملف ما اتحفظش. حاول تاني.",
  profiles: "ملفات الأطفال",
  profileLimit: "وصلت للحد الأقصى: ٣ ملفات أطفال لكل أسرة.",
  chooseProfile: "اختار ملف للمسار ده",
  activeProfile: "بروفايل الطفل النشط",
  otherLevelProfile: "البروفايل ده لمسار تاني. اخرج منه عشان تختار بروفايل للمسار ده.",
  exitProfile: "الخروج من بروفايل الطفل",
  noLevelProfile: "ما فيش ملف للمسار ده.",
  level: "المسار",
  lesson: "الخطوة",
  free: "مجاني بعد موافقة وليّ الأمر",
  requiresPlan: "محتاج اشتراك كيدز منفصل",
  openLesson: "شوف حالة الخطوة",
  back: "ارجع لكيدز",
  backLevel: "ارجع للمسار",
  locked: "الخطوة مش متاح دلوقتي",
  loading: "بنفتح الخطوة...",
  unavailableLesson: "الخطوة لسه مش جاهز. الفيديو والمحتوى ما اتحملوش.",
  watch: "اتفرج على الخطوة",
  objectives: "هنتعلم إيه؟",
  scenes: "فكرة الخطوة",
  reading: "اقرأ واتعلّم",
  practice: "جرّب بنفسك",
  quiz: "تحدّي سريع",
  checkAnswer: "راجع إجابتك",
  correct: "إجابة صح",
  retry: "راجع الفكرة وجرّب تاني",
  mission: "مهمتك",
  hint: "مساعدة من الخطوة",
  loadHint: "ورّيني التلميح",
  privacy: "استخدم تفاصيل من خيالك بس، وما تشاركش اسمك بالكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الخطوة",
  videoUnavailable: "الفيديو مش متاح دلوقتي.",
};
const gulf: Copy = {
  parentTitle: "مساحة وليّ الأمر",
  familyIntro:
    "من هنا تدير ملفات الأطفال وخطواتهم من حساب مسارات نفسه. سجل الموافقة تلقاه في بيانات الحساب.",
  manageFamily: "روح لمساحة وليّ الأمر",
  viewLevel: "شوف خطوات المسار",
  levelStartNotice:
    "هذي أسماء الخطوات. عشان تفتح خطوة، ادخل بحساب مسارات ووافق على سياسة الأطفال وسوّ ملفًا لهالمسار.",
  signIn: "تسجيل الدخول",
  signUp: "سوّ حساب مسارات",
  signInNotice:
    "إذا عندك حساب مسارات ادخل به، أو سوّ حسابًا واحدًا للمنصة. بعد الدخول توافق على سياسة الأطفال وتنشئ ملفاتهم؛ ما فيه تسجيل ثاني لكيدز.",
  waiting: "نتأكد من جاهزية الحساب...",
  pending: "اقرأ سياسة خصوصية الأطفال ووافق عليها من حساب وليّ الأمر عشان تفتح الملفات والخطوات.",
  unavailable: "ما قدرنا نتأكد من جاهزية كيدز الحين. جرّب بعدين.",
  setupPending: "خدمة كيدز قيد التجهيز. ملفات الأطفال والخطوات مب متاحة الحين.",
  retryCheck: "جرّب مرة ثانية",
  request: "وافق على سياسة الأطفال",
  requestNote: "تواصل ببريد حسابك بس، من دون بيانات الطفل.",
  noProfile: "بعد الموافقة، سوّ ملف لكل طفل واختر مستواه.",
  create: "سوّ ملف طفل",
  name: "اسم مختصر للملف (من دون اسم العائلة)",
  chooseLevel: "اختر المسار",
  submit: "احفظ الملف",
  profileError: "ما انحفظ الملف. جرّب مرة ثانية.",
  profiles: "ملفات الأطفال",
  profileLimit: "وصلت الحد الأقصى: ٣ ملفات أطفال لكل أسرة.",
  chooseProfile: "اختر ملف لهالمسار",
  activeProfile: "ملف الطفل النشط",
  otherLevelProfile: "هالملف لمسار ثاني. اخرج منه عشان تختار ملف لهالمسار.",
  exitProfile: "الخروج من ملف الطفل",
  noLevelProfile: "ما فيه ملف لهالمسار.",
  level: "المسار",
  lesson: "الخطوة",
  free: "مجاني بعد موافقة وليّ الأمر",
  requiresPlan: "يحتاج اشتراك كيدز مستقل",
  openLesson: "اعرض حالة الخطوة",
  back: "ارجع لكيدز",
  backLevel: "ارجع للمسار",
  locked: "الخطوة مب متاح الحين",
  loading: "نفتح الخطوة...",
  unavailableLesson: "الخطوة ما اكتملت جاهزيته. الفيديو والمحتوى ما تحمّلوا.",
  watch: "شاهد الخطوة",
  objectives: "وش بنتعلّم؟",
  scenes: "فكرة الخطوة",
  reading: "اقرأ وتعلّم",
  practice: "جرّب بنفسك",
  quiz: "تحدّي سريع",
  checkAnswer: "تحقق من إجابتك",
  correct: "إجابة صحيحة",
  retry: "راجع الفكرة وجرّب مرة ثانية",
  mission: "مهمتك",
  hint: "مساعدة من الخطوة",
  loadHint: "اعرض التلميح",
  privacy: "استخدم تفاصيل خيالية بس، ولا تشارك اسمك الكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الخطوة",
  videoUnavailable: "الفيديو مب متاح الحين.",
};
const en: Copy = {
  parentTitle: "Parent space",
  familyIntro:
    "Manage child profiles and steps here with your Masaarat account. Your consent record is in account details.",
  manageFamily: "Go to parent space",
  viewLevel: "View path steps",
  levelStartNotice:
    "These are the step titles. To open a step, use your Masaarat account, accept the children's policy, and create a profile for this path.",
  signIn: "Sign in",
  signUp: "Create Masaarat account",
  signInNotice:
    "Use your existing Masaarat account or create one platform account. Then accept the children's policy and add child profiles. Kids does not need a second registration.",
  waiting: "Checking account readiness...",
  pending:
    "Read and accept the children’s privacy policy from your parent account to open profiles and steps.",
  unavailable: "Kids readiness could not be checked. Try later.",
  setupPending: "Kids is being prepared. Child profiles and steps are not available yet.",
  retryCheck: "Try again",
  request: "Accept children’s privacy policy",
  requestNote: "Contact us with your account email only; no child details.",
  noProfile: "After consenting, create a profile for each child and choose an age path.",
  create: "Create child profile",
  name: "Short profile name (no family name)",
  chooseLevel: "Choose path",
  submit: "Save profile",
  profileError: "Profile could not be saved.",
  profiles: "Child profiles",
  profileLimit: "You have reached the limit of 3 child profiles per family.",
  chooseProfile: "Choose a profile for this path",
  activeProfile: "Active child profile",
  otherLevelProfile: "This profile is for another path. Exit it to choose a profile for this path.",
  exitProfile: "Exit child profile",
  noLevelProfile: "No profile for this path.",
  level: "Path",
  lesson: "Step",
  free: "Free after parent consent",
  requiresPlan: "Separate Kids subscription required",
  openLesson: "View step status",
  back: "Back to Kids",
  backLevel: "Back to path",
  locked: "Step currently unavailable",
  loading: "Opening step...",
  unavailableLesson: "This step is not ready. Video and content were not loaded.",
  watch: "Watch step",
  objectives: "What you will learn",
  scenes: "Step ideas",
  reading: "Read and explore",
  practice: "Try it",
  quiz: "Quick challenge",
  checkAnswer: "Check answer",
  correct: "Correct answer",
  retry: "Review and try again",
  mission: "Your mission",
  hint: "Step hint",
  loadHint: "Show hint",
  privacy: "Use invented details only. Do not share your full name, address or private photos.",
  genericLesson: "Step",
  videoUnavailable: "The video is not available yet.",
};
export function getKidsJourneyCopy(locale: SupportedLocale): Copy {
  if (locale === "en") return en;
  if (locale === "ar-EG") return egyptian;
  if (locale === "ar-Gulf") return gulf;
  return ar;
}
