import type { SupportedLocale } from "@/lib/locale/types";

const ar = {
  parentTitle: "مساحة وليّ الأمر",
  signIn: "تسجيل الدخول",
  signUp: "إنشاء حساب وليّ أمر",
  signInNotice: "سجّل الدخول بحسابك لإدارة ملف طفلك. لا يلزم إدخال بيانات الطفل الآن.",
  waiting: "التحقق من جاهزية الحساب...",
  pending: "إنشاء ملفات الأطفال والدروس مغلق حتى يكتمل تحقق وليّ الأمر واعتماد الخصوصية.",
  unavailable: "تعذّر التحقق من جاهزية كيدز الآن. حاول لاحقًا.",
  setupPending: "خدمة كيدز قيد التجهيز. إنشاء ملفات الأطفال والدروس غير متاح الآن.",
  retryCheck: "إعادة المحاولة",
  request: "اطلب تحقق وليّ الأمر",
  requestNote: "تواصل ببريد حسابك فقط، دون بيانات الطفل.",
  noProfile: "بعد اعتماد الحساب، أنشئ ملفًا لكل طفل واختر مستواه.",
  create: "إنشاء ملف طفل",
  name: "اسم مختصر للملف (دون اسم العائلة)",
  chooseLevel: "اختر المستوى",
  submit: "حفظ الملف",
  profileError: "لم يُحفظ الملف. حاول لاحقًا.",
  profiles: "ملفات الأطفال",
  chooseProfile: "اختر ملفًا لهذا المستوى",
  noLevelProfile: "لا يوجد ملف لهذا المستوى.",
  level: "المستوى",
  lesson: "الدرس",
  free: "مجاني بعد تحقق وليّ الأمر",
  requiresPlan: "يتطلب اشتراك كيدز مستقلًا",
  openLesson: "عرض حالة الدرس",
  back: "العودة إلى كيدز",
  backLevel: "العودة إلى المستوى",
  locked: "الدرس غير متاح حاليًا",
  lockedDetail: "يتطلب الدرس اعتماد وليّ الأمر والمحتوى والتحقق من صلاحية الملف عبر الخادم.",
  loading: "التحقق من صلاحية الوصول...",
  unavailableLesson: "لم تكتمل جاهزية الدرس. لم يُحمّل الفيديو أو المحتوى.",
  watch: "شاهد الدرس",
  objectives: "ماذا سنتعلم؟",
  scenes: "فكرة الدرس",
  reading: "اقرأ وتعلّم",
  practice: "تطبيق عملي",
  quiz: "تحدٍ سريع",
  checkAnswer: "تحقق من الإجابة",
  correct: "إجابة صحيحة",
  retry: "راجع الفكرة ثم حاول مجددًا",
  mission: "مهمتك",
  hint: "مساعدة من الدرس",
  loadHint: "عرض التلميح",
  privacy: "استخدم تفاصيل خيالية فقط، ولا تشارك اسمك الكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الدرس",
  videoUnavailable: "الفيديو غير جاهز حاليًا.",
} as const;
type Copy = { [K in keyof typeof ar]: string };
const en: Copy = {
  parentTitle: "Parent space",
  signIn: "Sign in",
  signUp: "Create parent account",
  signInNotice: "Sign in as a parent. No child details are needed yet.",
  waiting: "Checking account readiness...",
  pending:
    "Child profiles and lessons remain closed until parental verification and privacy approval.",
  unavailable: "Kids readiness could not be checked. Try later.",
  setupPending: "Kids is being prepared. Child profiles and lessons are not available yet.",
  retryCheck: "Try again",
  request: "Request parental verification",
  requestNote: "Contact us with your account email only; no child details.",
  noProfile: "Once approved, create a profile for each child and choose an age level.",
  create: "Create child profile",
  name: "Short profile name (no family name)",
  chooseLevel: "Choose level",
  submit: "Save profile",
  profileError: "Profile could not be saved.",
  profiles: "Child profiles",
  chooseProfile: "Choose a profile for this level",
  noLevelProfile: "No profile for this level.",
  level: "Level",
  lesson: "Lesson",
  free: "Free after parental verification",
  requiresPlan: "Separate Kids subscription required",
  openLesson: "View lesson status",
  back: "Back to Kids",
  backLevel: "Back to level",
  locked: "Lesson currently unavailable",
  lockedDetail:
    "A lesson requires parent and content approvals, then a server grant for this profile.",
  loading: "Checking access...",
  unavailableLesson: "This lesson is not ready. Video and content were not loaded.",
  watch: "Watch lesson",
  objectives: "What you will learn",
  scenes: "Lesson ideas",
  reading: "Read and explore",
  practice: "Try it",
  quiz: "Quick challenge",
  checkAnswer: "Check answer",
  correct: "Correct answer",
  retry: "Review and try again",
  mission: "Your mission",
  hint: "Lesson hint",
  loadHint: "Show hint",
  privacy: "Use invented details only. Do not share your full name, address or private photos.",
  genericLesson: "Lesson",
  videoUnavailable: "The video is not available yet.",
};
export function getKidsJourneyCopy(locale: SupportedLocale): Copy {
  return locale === "en" ? en : ar;
}
