import type { SupportedLocale } from "@/lib/locale/types";

const ar = {
  parentTitle: "مساحة وليّ الأمر",
  familyIntro:
    "من هنا توافق على سياسة الأطفال مرة واحدة، وتدير ملفاتهم من حسابك نفسه. تُحفظ اختياراتك عند العودة.",
  manageFamily: "الانتقال إلى مساحة وليّ الأمر",
  viewLevel: "عرض دروس المستوى",
  levelStartNotice:
    "هذه أسماء الدروس. لفتح أي درس، ادخل بحساب مسارات، ووافق على سياسة الأطفال وأنشئ ملفًا مناسبًا للمستوى.",
  signIn: "تسجيل الدخول",
  signUp: "إنشاء حساب مسارات",
  signInNotice:
    "استخدم حساب مسارات الحالي، أو أنشئ حسابًا واحدًا للمنصة. بعد الدخول توافق على سياسة الأطفال وتنشئ ملفاتهم؛ لا يوجد تسجيل منفصل لكيدز.",
  waiting: "التحقق من جاهزية الحساب...",
  pending: "اقرأ سياسة خصوصية الأطفال ووافق عليها من حساب وليّ الأمر لفتح الملفات والدروس.",
  unavailable: "تعذّر التحقق من جاهزية كيدز الآن. حاول لاحقًا.",
  setupPending: "خدمة كيدز قيد التجهيز. إنشاء ملفات الأطفال والدروس غير متاح الآن.",
  retryCheck: "إعادة المحاولة",
  request: "وافق على سياسة الأطفال",
  requestNote: "تواصل ببريد حسابك فقط، دون بيانات الطفل.",
  noProfile: "بعد الموافقة، أنشئ ملفًا لكل طفل واختر مستواه.",
  create: "إنشاء ملف طفل",
  name: "اسم مختصر للملف (دون اسم العائلة)",
  chooseLevel: "اختر المستوى",
  submit: "حفظ الملف",
  profileError: "لم يُحفظ الملف. حاول لاحقًا.",
  profiles: "ملفات الأطفال",
  profileLimit: "وصلت إلى الحد الأقصى: 3 ملفات أطفال لكل أسرة.",
  chooseProfile: "اختر ملفًا لهذا المستوى",
  noLevelProfile: "لا يوجد ملف لهذا المستوى.",
  level: "المستوى",
  lesson: "الدرس",
  free: "مجاني بعد موافقة وليّ الأمر",
  requiresPlan: "يتطلب اشتراك كيدز مستقلًا",
  openLesson: "عرض حالة الدرس",
  back: "العودة إلى كيدز",
  backLevel: "العودة إلى المستوى",
  locked: "الدرس غير متاح حاليًا",
  lockedDetail: "يتطلب الدرس موافقة وليّ الأمر والمحتوى والتحقق من صلاحية الملف عبر الخادم.",
  loading: "التحقق من صلاحية الوصول...",
  unavailableLesson: "لم تكتمل جاهزية الدرس. لم يُحمّل الفيديو أو المحتوى.",
  watch: "شاهد الدرس",
  objectives: "ماذا سنتعلم؟",
  scenes: "فكرة الدرس",
  reading: "اقرأ وتعلّم",
  practice: "تطبيق عملي",
  quiz: "تحدٍ سريع",
  checkAnswer: "تحقق من الإجابة",
  correct: "إجابة صحيحة",
  retry: "راجع الفكرة ثم حاول مجددًا",
  mission: "مهمتك",
  hint: "مساعدة من الدرس",
  loadHint: "عرض التلميح",
  privacy: "استخدم تفاصيل خيالية فقط، ولا تشارك اسمك الكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الدرس",
  videoUnavailable: "الفيديو غير جاهز حاليًا.",
} as const;
type Copy = { [K in keyof typeof ar]: string };
const egyptian: Copy = {
  parentTitle: "مساحة وليّ الأمر",
  familyIntro:
    "هنا توافق على سياسة الأطفال مرة واحدة، وتدير ملفاتهم من نفس حسابك. اختياراتك بتفضل محفوظة.",
  manageFamily: "روح لمساحة وليّ الأمر",
  viewLevel: "شوف دروس المستوى",
  levelStartNotice:
    "دي أسماء الدروس. عشان تفتح درس، ادخل بحساب مسارات ووافق على سياسة الأطفال واعمل ملف للمستوى ده.",
  signIn: "دخول",
  signUp: "اعمل حساب مسارات",
  signInNotice:
    "لو عندك حساب مسارات ادخل بيه، ولو جديد اعمل حساب واحد للمنصة. بعدها توافق على سياسة الأطفال وتعمل ملفاتهم؛ مفيش تسجيل تاني لكيدز.",
  waiting: "بنتأكد إن الحساب جاهز...",
  pending: "اقرأ سياسة خصوصية الأطفال ووافق عليها من حساب وليّ الأمر عشان تفتح الملفات والدروس.",
  unavailable: "مش قادرين نتأكد من جاهزية كيدز دلوقتي. حاول بعد شوية.",
  setupPending: "خدمة كيدز لسه بتتجهز. ملفات الأطفال والدروس مش متاحة دلوقتي.",
  retryCheck: "حاول تاني",
  request: "وافق على سياسة الأطفال",
  requestNote: "تواصل ببريد حسابك بس، من غير بيانات الطفل.",
  noProfile: "بعد الموافقة، اعمل ملف لكل طفل واختار مستواه.",
  create: "اعمل ملف طفل",
  name: "اسم مختصر للملف (من غير اسم العيلة)",
  chooseLevel: "اختار المستوى",
  submit: "احفظ الملف",
  profileError: "الملف ما اتحفظش. حاول تاني.",
  profiles: "ملفات الأطفال",
  profileLimit: "وصلت للحد الأقصى: ٣ ملفات أطفال لكل أسرة.",
  chooseProfile: "اختار ملف للمستوى ده",
  noLevelProfile: "ما فيش ملف للمستوى ده.",
  level: "المستوى",
  lesson: "الدرس",
  free: "مجاني بعد موافقة وليّ الأمر",
  requiresPlan: "محتاج اشتراك كيدز منفصل",
  openLesson: "شوف حالة الدرس",
  back: "ارجع لكيدز",
  backLevel: "ارجع للمستوى",
  locked: "الدرس مش متاح دلوقتي",
  lockedDetail: "فتح الدرس محتاج موافقة وليّ الأمر والمحتوى والتحقق من صلاحية الملف على الخادم.",
  loading: "بنتأكد من صلاحية الوصول...",
  unavailableLesson: "الدرس لسه مش جاهز. الفيديو والمحتوى ما اتحملوش.",
  watch: "اتفرج على الدرس",
  objectives: "هنتعلم إيه؟",
  scenes: "فكرة الدرس",
  reading: "اقرأ واتعلّم",
  practice: "جرّب بنفسك",
  quiz: "تحدّي سريع",
  checkAnswer: "راجع إجابتك",
  correct: "إجابة صح",
  retry: "راجع الفكرة وجرّب تاني",
  mission: "مهمتك",
  hint: "مساعدة من الدرس",
  loadHint: "ورّيني التلميح",
  privacy: "استخدم تفاصيل من خيالك بس، وما تشاركش اسمك بالكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الدرس",
  videoUnavailable: "الفيديو مش متاح دلوقتي.",
};
const gulf: Copy = {
  parentTitle: "مساحة وليّ الأمر",
  familyIntro:
    "من هنا توافق على سياسة الأطفال مرة واحدة، وتدير ملفاتهم من حسابك نفسه. تظل اختياراتك محفوظة.",
  manageFamily: "روح لمساحة وليّ الأمر",
  viewLevel: "شوف دروس المستوى",
  levelStartNotice:
    "هذي أسماء الدروس. عشان تفتح درس، ادخل بحساب مسارات ووافق على سياسة الأطفال وسوّ ملفًا لهالمستوى.",
  signIn: "تسجيل الدخول",
  signUp: "سوّ حساب مسارات",
  signInNotice:
    "إذا عندك حساب مسارات ادخل به، أو سوّ حسابًا واحدًا للمنصة. بعد الدخول توافق على سياسة الأطفال وتنشئ ملفاتهم؛ ما فيه تسجيل ثاني لكيدز.",
  waiting: "نتأكد من جاهزية الحساب...",
  pending: "اقرأ سياسة خصوصية الأطفال ووافق عليها من حساب وليّ الأمر عشان تفتح الملفات والدروس.",
  unavailable: "ما قدرنا نتأكد من جاهزية كيدز الحين. جرّب بعدين.",
  setupPending: "خدمة كيدز قيد التجهيز. ملفات الأطفال والدروس مب متاحة الحين.",
  retryCheck: "جرّب مرة ثانية",
  request: "وافق على سياسة الأطفال",
  requestNote: "تواصل ببريد حسابك بس، من دون بيانات الطفل.",
  noProfile: "بعد الموافقة، سوّ ملف لكل طفل واختر مستواه.",
  create: "سوّ ملف طفل",
  name: "اسم مختصر للملف (من دون اسم العائلة)",
  chooseLevel: "اختر المستوى",
  submit: "احفظ الملف",
  profileError: "ما انحفظ الملف. جرّب مرة ثانية.",
  profiles: "ملفات الأطفال",
  profileLimit: "وصلت الحد الأقصى: ٣ ملفات أطفال لكل أسرة.",
  chooseProfile: "اختر ملف لهالمستوى",
  noLevelProfile: "ما فيه ملف لهالمستوى.",
  level: "المستوى",
  lesson: "الدرس",
  free: "مجاني بعد موافقة وليّ الأمر",
  requiresPlan: "يحتاج اشتراك كيدز مستقل",
  openLesson: "اعرض حالة الدرس",
  back: "ارجع لكيدز",
  backLevel: "ارجع للمستوى",
  locked: "الدرس مب متاح الحين",
  lockedDetail: "فتح الدرس يحتاج موافقة وليّ الأمر والمحتوى والتحقق من صلاحية الملف على الخادم.",
  loading: "نتأكد من صلاحية الوصول...",
  unavailableLesson: "الدرس ما اكتملت جاهزيته. الفيديو والمحتوى ما تحمّلوا.",
  watch: "شاهد الدرس",
  objectives: "وش بنتعلّم؟",
  scenes: "فكرة الدرس",
  reading: "اقرأ وتعلّم",
  practice: "جرّب بنفسك",
  quiz: "تحدّي سريع",
  checkAnswer: "تحقق من إجابتك",
  correct: "إجابة صحيحة",
  retry: "راجع الفكرة وجرّب مرة ثانية",
  mission: "مهمتك",
  hint: "مساعدة من الدرس",
  loadHint: "اعرض التلميح",
  privacy: "استخدم تفاصيل خيالية بس، ولا تشارك اسمك الكامل أو عنوانك أو صورك الخاصة.",
  genericLesson: "الدرس",
  videoUnavailable: "الفيديو مب متاح الحين.",
};
const en: Copy = {
  parentTitle: "Parent space",
  familyIntro:
    "Accept the children's policy once and manage child profiles with your existing account. Your choices are saved when you return.",
  manageFamily: "Go to parent space",
  viewLevel: "View level lessons",
  levelStartNotice:
    "These are the lesson titles. To open a lesson, use your Masaarat account, accept the children's policy, and create a profile for this level.",
  signIn: "Sign in",
  signUp: "Create Masaarat account",
  signInNotice:
    "Use your existing Masaarat account or create one platform account. Then accept the children's policy and add child profiles. Kids does not need a second registration.",
  waiting: "Checking account readiness...",
  pending:
    "Read and accept the children’s privacy policy from your parent account to open profiles and lessons.",
  unavailable: "Kids readiness could not be checked. Try later.",
  setupPending: "Kids is being prepared. Child profiles and lessons are not available yet.",
  retryCheck: "Try again",
  request: "Accept children’s privacy policy",
  requestNote: "Contact us with your account email only; no child details.",
  noProfile: "After consenting, create a profile for each child and choose an age level.",
  create: "Create child profile",
  name: "Short profile name (no family name)",
  chooseLevel: "Choose level",
  submit: "Save profile",
  profileError: "Profile could not be saved.",
  profiles: "Child profiles",
  profileLimit: "You have reached the limit of 3 child profiles per family.",
  chooseProfile: "Choose a profile for this level",
  noLevelProfile: "No profile for this level.",
  level: "Level",
  lesson: "Lesson",
  free: "Free after parent consent",
  requiresPlan: "Separate Kids subscription required",
  openLesson: "View lesson status",
  back: "Back to Kids",
  backLevel: "Back to level",
  locked: "Lesson currently unavailable",
  lockedDetail:
    "A lesson requires parent consent and approved content, then a server grant for this profile.",
  loading: "Checking access...",
  unavailableLesson: "This lesson is not ready. Video and content were not loaded.",
  watch: "Watch lesson",
  objectives: "What you will learn",
  scenes: "Lesson ideas",
  reading: "Read and explore",
  practice: "Try it",
  quiz: "Quick challenge",
  checkAnswer: "Check answer",
  correct: "Correct answer",
  retry: "Review and try again",
  mission: "Your mission",
  hint: "Lesson hint",
  loadHint: "Show hint",
  privacy: "Use invented details only. Do not share your full name, address or private photos.",
  genericLesson: "Lesson",
  videoUnavailable: "The video is not available yet.",
};
export function getKidsJourneyCopy(locale: SupportedLocale): Copy {
  if (locale === "en") return en;
  if (locale === "ar-EG") return egyptian;
  if (locale === "ar-Gulf") return gulf;
  return ar;
}
