import type { SupportedLocale } from "@/lib/locale/types";
const msa = {
  reviewOnly: "نسخة للمراجعة الإدارية — لم تُتح للمتعلمين بعد.",
  catalogue: "مقررات مسارات أكاديمي",
  intro: "اختر المسار، ثم استعرض محطاته وخطواته وتعلّم بالتطبيق.",
  open: "افتح المنهج",
  back: "العودة إلى المسارات",
  lesson: "افتح الخطوة",
  unit: "المحطة",
  loading: "جارٍ التحميل…",
  unavailable: "تعذر تحميل المحتوى. حاول مجددًا.",
  empty: "سيظهر المسار هنا عند إتاحته.",
  reading: "الشرح",
  example: "مثال محلول",
  video: "الفيديو",
  quiz: "اختبر فهمك",
  practice: "التطبيق العملي",
  faq: "أسئلة شائعة",
  downloads: "التحميلات",
  assistant: "المساعد الذكي",
  progress: "تقدم الأنشطة",
  progressNote: "يُحفظ تقدم القراءة والاختبار وتسليم التطبيق في حسابك.",
  markRead: "أتممت قراءة الشرح",
  submit: "تسليم الإجابات",
  save: "احفظ التطبيق",
  restore: "استعادة الإجابة المحفوظة",
  saved: "تم الحفظ في حسابك.",
  backToCurriculum: "العودة إلى المنهج",
  sections: "أقسام الخطوة",
};
const copy: Record<SupportedLocale, typeof msa> = {
  "ar-MSA": msa,
  "ar-EG": {
    ...msa,
    reviewOnly: "نسخة لمراجعة الإدارة — لسه مش متاحة للطلاب.",
    intro: "اختار المسار، وشوف محطاته وخطواته واتعلّم بالتطبيق.",
    open: "افتح المنهج",
    back: "ارجع للمقررات",
    unavailable: "المحتوى مش متاح دلوقتي. جرّب تاني.",
    empty: "المسار هيظهر هنا لما يتاح.",
    practice: "طبّق بنفسك",
    markRead: "خلصت قراءة الشرح",
    submit: "راجع الإجابات",
    restore: "رجّع الإجابة المحفوظة",
    progressNote: "تقدم القراءة والاختبار وتسليم التطبيق بيتحفظ في حسابك.",
    backToCurriculum: "ارجع للمنهج",
  },
  "ar-Gulf": {
    ...msa,
    reviewOnly: "نسخة لمراجعة الإدارة — ما أُتيحت للطلاب بعد.",
    intro: "اختر المسار، وشوف محطاته وخطواته وتعلّم بالتطبيق.",
    back: "ارجع للمقررات",
    unavailable: "المحتوى مو متاح الحين. جرّب مرة ثانية.",
    empty: "المسار بيظهر هنا وقت إتاحته.",
    practice: "جرّب بنفسك",
    markRead: "خلصت قراءة الشرح",
    submit: "راجع الإجابات",
    restore: "استرجع الإجابة المحفوظة",
    progressNote: "تقدم القراءة والاختبار وتسليم التطبيق ينحفظ في حسابك.",
    backToCurriculum: "ارجع للمنهج",
  },
  en: {
    reviewOnly: "Administrator review — not yet released to learners.",
    catalogue: "Academic paths",
    intro: "Choose a path, explore its stations and steps, and learn through practice.",
    open: "Open curriculum",
    back: "All paths",
    lesson: "Open step",
    unit: "Station",
    loading: "Loading…",
    unavailable: "Content could not be loaded. Please retry.",
    empty: "Paths will appear here when available.",
    reading: "Reading",
    example: "Worked example",
    video: "Video",
    quiz: "Check understanding",
    practice: "Practice",
    faq: "FAQ",
    downloads: "Downloads",
    assistant: "AI assistant",
    progress: "Activity progress",
    progressNote: "Reading, quiz and practice submission progress is saved to your account.",
    markRead: "Mark reading complete",
    submit: "Submit answers",
    save: "Save practice submission",
    restore: "Restore saved response",
    saved: "Saved to your account.",
    backToCurriculum: "Back to curriculum",
    sections: "Step sections",
  },
};
export const getAcademicCopy = (locale: SupportedLocale) => copy[locale];
