/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SystemStateRouteImport } from './routes/system-state'
import { Route as StartRouteImport } from './routes/start'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as ImageGalleryRouteImport } from './routes/image-gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BuildLogsRouteImport } from './routes/build-logs'
import { Route as AssistantRuntimeRouteImport } from './routes/assistant-runtime'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoadmapIndexRouteImport } from './routes/roadmap.index'
import { Route as KidsIndexRouteImport } from './routes/kids.index'
import { Route as ImageGalleryIndexRouteImport } from './routes/image-gallery.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RoadmapIdRouteImport } from './routes/roadmap.$id'
import { Route as KidsLevelIdRouteImport } from './routes/kids.$levelId'
import { Route as ImageGalleryPathRouteImport } from './routes/image-gallery.$path'
import { Route as AdminKidsParentsRouteImport } from './routes/admin.kids-parents'
import { Route as KidsLevelIdIndexRouteImport } from './routes/kids.$levelId.index'
import { Route as LearnPathIdLessonIdRouteImport } from './routes/learn.$pathId.$lessonId'
import { Route as KidsLevelIdLessonNumberRouteImport } from './routes/kids.$levelId.$lessonNumber'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemStateRoute = SystemStateRouteImport.update({
  id: '/system-state',
  path: '/system-state',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageGalleryRoute = ImageGalleryRouteImport.update({
  id: '/image-gallery',
  path: '/image-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildLogsRoute = BuildLogsRouteImport.update({
  id: '/build-logs',
  path: '/build-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRuntimeRoute = AssistantRuntimeRouteImport.update({
  id: '/assistant-runtime',
  path: '/assistant-runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIndexRoute = RoadmapIndexRouteImport.update({
  id: '/roadmap/',
  path: '/roadmap/',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsIndexRoute = KidsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KidsRoute,
} as any)
const ImageGalleryIndexRoute = ImageGalleryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImageGalleryRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapIdRoute = RoadmapIdRouteImport.update({
  id: '/roadmap/$id',
  path: '/roadmap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsLevelIdRoute = KidsLevelIdRouteImport.update({
  id: '/$levelId',
  path: '/$levelId',
  getParentRoute: () => KidsRoute,
} as any)
const ImageGalleryPathRoute = ImageGalleryPathRouteImport.update({
  id: '/$path',
  path: '/$path',
  getParentRoute: () => ImageGalleryRoute,
} as any)
const AdminKidsParentsRoute = AdminKidsParentsRouteImport.update({
  id: '/admin/kids-parents',
  path: '/admin/kids-parents',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsLevelIdIndexRoute = KidsLevelIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KidsLevelIdRoute,
} as any)
const LearnPathIdLessonIdRoute = LearnPathIdLessonIdRouteImport.update({
  id: '/learn/$pathId/$lessonId',
  path: '/learn/$pathId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsLevelIdLessonNumberRoute = KidsLevelIdLessonNumberRouteImport.update({
  id: '/$lessonNumber',
  path: '/$lessonNumber',
  getParentRoute: () => KidsLevelIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant-runtime': typeof AssistantRuntimeRoute
  '/build-logs': typeof BuildLogsRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/image-gallery': typeof ImageGalleryRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/kids': typeof KidsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/system-state': typeof SystemStateRoute
  '/terms': typeof TermsRoute
  '/admin/kids-parents': typeof AdminKidsParentsRoute
  '/image-gallery/$path': typeof ImageGalleryPathRoute
  '/kids/$levelId': typeof KidsLevelIdRouteWithChildren
  '/roadmap/$id': typeof RoadmapIdRoute
  '/admin/': typeof AdminIndexRoute
  '/image-gallery/': typeof ImageGalleryIndexRoute
  '/kids/': typeof KidsIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/kids/$levelId/$lessonNumber': typeof KidsLevelIdLessonNumberRoute
  '/learn/$pathId/$lessonId': typeof LearnPathIdLessonIdRoute
  '/kids/$levelId/': typeof KidsLevelIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant-runtime': typeof AssistantRuntimeRoute
  '/build-logs': typeof BuildLogsRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/index': typeof Char91indexChar93Route
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/system-state': typeof SystemStateRoute
  '/terms': typeof TermsRoute
  '/admin/kids-parents': typeof AdminKidsParentsRoute
  '/image-gallery/$path': typeof ImageGalleryPathRoute
  '/roadmap/$id': typeof RoadmapIdRoute
  '/admin': typeof AdminIndexRoute
  '/image-gallery': typeof ImageGalleryIndexRoute
  '/kids': typeof KidsIndexRoute
  '/roadmap': typeof RoadmapIndexRoute
  '/kids/$levelId/$lessonNumber': typeof KidsLevelIdLessonNumberRoute
  '/learn/$pathId/$lessonId': typeof LearnPathIdLessonIdRoute
  '/kids/$levelId': typeof KidsLevelIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant-runtime': typeof AssistantRuntimeRoute
  '/build-logs': typeof BuildLogsRoute
  '/contact': typeof ContactRoute
  '/curriculum': typeof CurriculumRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/image-gallery': typeof ImageGalleryRouteWithChildren
  '/index': typeof Char91indexChar93Route
  '/kids': typeof KidsRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/start': typeof StartRoute
  '/system-state': typeof SystemStateRoute
  '/terms': typeof TermsRoute
  '/admin/kids-parents': typeof AdminKidsParentsRoute
  '/image-gallery/$path': typeof ImageGalleryPathRoute
  '/kids/$levelId': typeof KidsLevelIdRouteWithChildren
  '/roadmap/$id': typeof RoadmapIdRoute
  '/admin/': typeof AdminIndexRoute
  '/image-gallery/': typeof ImageGalleryIndexRoute
  '/kids/': typeof KidsIndexRoute
  '/roadmap/': typeof RoadmapIndexRoute
  '/kids/$levelId/$lessonNumber': typeof KidsLevelIdLessonNumberRoute
  '/learn/$pathId/$lessonId': typeof LearnPathIdLessonIdRoute
  '/kids/$levelId/': typeof KidsLevelIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/ai-assistant'
    | '/analytics'
    | '/assistant-runtime'
    | '/build-logs'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/forgot-password'
    | '/image-gallery'
    | '/index'
    | '/kids'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/start'
    | '/system-state'
    | '/terms'
    | '/admin/kids-parents'
    | '/image-gallery/$path'
    | '/kids/$levelId'
    | '/roadmap/$id'
    | '/admin/'
    | '/image-gallery/'
    | '/kids/'
    | '/roadmap/'
    | '/kids/$levelId/$lessonNumber'
    | '/learn/$pathId/$lessonId'
    | '/kids/$levelId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/ai-assistant'
    | '/analytics'
    | '/assistant-runtime'
    | '/build-logs'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/forgot-password'
    | '/index'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/start'
    | '/system-state'
    | '/terms'
    | '/admin/kids-parents'
    | '/image-gallery/$path'
    | '/roadmap/$id'
    | '/admin'
    | '/image-gallery'
    | '/kids'
    | '/roadmap'
    | '/kids/$levelId/$lessonNumber'
    | '/learn/$pathId/$lessonId'
    | '/kids/$levelId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/ai-assistant'
    | '/analytics'
    | '/assistant-runtime'
    | '/build-logs'
    | '/contact'
    | '/curriculum'
    | '/dashboard'
    | '/forgot-password'
    | '/image-gallery'
    | '/index'
    | '/kids'
    | '/login'
    | '/onboarding'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/start'
    | '/system-state'
    | '/terms'
    | '/admin/kids-parents'
    | '/image-gallery/$path'
    | '/kids/$levelId'
    | '/roadmap/$id'
    | '/admin/'
    | '/image-gallery/'
    | '/kids/'
    | '/roadmap/'
    | '/kids/$levelId/$lessonNumber'
    | '/learn/$pathId/$lessonId'
    | '/kids/$levelId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRuntimeRoute: typeof AssistantRuntimeRoute
  BuildLogsRoute: typeof BuildLogsRoute
  ContactRoute: typeof ContactRoute
  CurriculumRoute: typeof CurriculumRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImageGalleryRoute: typeof ImageGalleryRouteWithChildren
  Char91indexChar93Route: typeof Char91indexChar93Route
  KidsRoute: typeof KidsRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  StartRoute: typeof StartRoute
  SystemStateRoute: typeof SystemStateRoute
  TermsRoute: typeof TermsRoute
  AdminKidsParentsRoute: typeof AdminKidsParentsRoute
  RoadmapIdRoute: typeof RoadmapIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  RoadmapIndexRoute: typeof RoadmapIndexRoute
  LearnPathIdLessonIdRoute: typeof LearnPathIdLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-state': {
      id: '/system-state'
      path: '/system-state'
      fullPath: '/system-state'
      preLoaderRoute: typeof SystemStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-gallery': {
      id: '/image-gallery'
      path: '/image-gallery'
      fullPath: '/image-gallery'
      preLoaderRoute: typeof ImageGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-logs': {
      id: '/build-logs'
      path: '/build-logs'
      fullPath: '/build-logs'
      preLoaderRoute: typeof BuildLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant-runtime': {
      id: '/assistant-runtime'
      path: '/assistant-runtime'
      fullPath: '/assistant-runtime'
      preLoaderRoute: typeof AssistantRuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/': {
      id: '/roadmap/'
      path: '/roadmap'
      fullPath: '/roadmap/'
      preLoaderRoute: typeof RoadmapIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/': {
      id: '/kids/'
      path: '/'
      fullPath: '/kids/'
      preLoaderRoute: typeof KidsIndexRouteImport
      parentRoute: typeof KidsRoute
    }
    '/image-gallery/': {
      id: '/image-gallery/'
      path: '/'
      fullPath: '/image-gallery/'
      preLoaderRoute: typeof ImageGalleryIndexRouteImport
      parentRoute: typeof ImageGalleryRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap/$id': {
      id: '/roadmap/$id'
      path: '/roadmap/$id'
      fullPath: '/roadmap/$id'
      preLoaderRoute: typeof RoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$levelId': {
      id: '/kids/$levelId'
      path: '/$levelId'
      fullPath: '/kids/$levelId'
      preLoaderRoute: typeof KidsLevelIdRouteImport
      parentRoute: typeof KidsRoute
    }
    '/image-gallery/$path': {
      id: '/image-gallery/$path'
      path: '/$path'
      fullPath: '/image-gallery/$path'
      preLoaderRoute: typeof ImageGalleryPathRouteImport
      parentRoute: typeof ImageGalleryRoute
    }
    '/admin/kids-parents': {
      id: '/admin/kids-parents'
      path: '/admin/kids-parents'
      fullPath: '/admin/kids-parents'
      preLoaderRoute: typeof AdminKidsParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$levelId/': {
      id: '/kids/$levelId/'
      path: '/'
      fullPath: '/kids/$levelId/'
      preLoaderRoute: typeof KidsLevelIdIndexRouteImport
      parentRoute: typeof KidsLevelIdRoute
    }
    '/learn/$pathId/$lessonId': {
      id: '/learn/$pathId/$lessonId'
      path: '/learn/$pathId/$lessonId'
      fullPath: '/learn/$pathId/$lessonId'
      preLoaderRoute: typeof LearnPathIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids/$levelId/$lessonNumber': {
      id: '/kids/$levelId/$lessonNumber'
      path: '/$lessonNumber'
      fullPath: '/kids/$levelId/$lessonNumber'
      preLoaderRoute: typeof KidsLevelIdLessonNumberRouteImport
      parentRoute: typeof KidsLevelIdRoute
    }
  }
}

interface ImageGalleryRouteChildren {
  ImageGalleryPathRoute: typeof ImageGalleryPathRoute
  ImageGalleryIndexRoute: typeof ImageGalleryIndexRoute
}

const ImageGalleryRouteChildren: ImageGalleryRouteChildren = {
  ImageGalleryPathRoute: ImageGalleryPathRoute,
  ImageGalleryIndexRoute: ImageGalleryIndexRoute,
}

const ImageGalleryRouteWithChildren = ImageGalleryRoute._addFileChildren(
  ImageGalleryRouteChildren,
)

interface KidsLevelIdRouteChildren {
  KidsLevelIdLessonNumberRoute: typeof KidsLevelIdLessonNumberRoute
  KidsLevelIdIndexRoute: typeof KidsLevelIdIndexRoute
}

const KidsLevelIdRouteChildren: KidsLevelIdRouteChildren = {
  KidsLevelIdLessonNumberRoute: KidsLevelIdLessonNumberRoute,
  KidsLevelIdIndexRoute: KidsLevelIdIndexRoute,
}

const KidsLevelIdRouteWithChildren = KidsLevelIdRoute._addFileChildren(
  KidsLevelIdRouteChildren,
)

interface KidsRouteChildren {
  KidsLevelIdRoute: typeof KidsLevelIdRouteWithChildren
  KidsIndexRoute: typeof KidsIndexRoute
}

const KidsRouteChildren: KidsRouteChildren = {
  KidsLevelIdRoute: KidsLevelIdRouteWithChildren,
  KidsIndexRoute: KidsIndexRoute,
}

const KidsRouteWithChildren = KidsRoute._addFileChildren(KidsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRuntimeRoute: AssistantRuntimeRoute,
  BuildLogsRoute: BuildLogsRoute,
  ContactRoute: ContactRoute,
  CurriculumRoute: CurriculumRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImageGalleryRoute: ImageGalleryRouteWithChildren,
  Char91indexChar93Route: Char91indexChar93Route,
  KidsRoute: KidsRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  StartRoute: StartRoute,
  SystemStateRoute: SystemStateRoute,
  TermsRoute: TermsRoute,
  AdminKidsParentsRoute: AdminKidsParentsRoute,
  RoadmapIdRoute: RoadmapIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  RoadmapIndexRoute: RoadmapIndexRoute,
  LearnPathIdLessonIdRoute: LearnPathIdLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
