-- One versioned children’s privacy notice across supported Arabic markets.
-- The product owner approved the common policy and a parent-account checkbox.
-- Country rows are storage keys for the existing residency and access model;
-- they all share the same policy text and version.
WITH notices(locale,notice_text,consent_text) AS (
  VALUES
  ('ar-EG',
   'مسارات كيدز خدمة تعليمية للأطفال يديرها وليّ الأمر من حسابه ذي البريد المؤكد. أقرّ صاحب الحساب بصفته وليّ أمر قبل إنشاء ملفات الأطفال. نحفظ بلد إقامة وليّ الأمر ونسخة موافقته وتاريخها، واسم عرض مختصر لكل طفل ومستواه وتقدمه في الدروس. لا نطلب بريد الطفل أو هاتفه أو وثيقة هويته. نستخدم هذه البيانات لتقديم الدروس وحفظ التقدم وحماية الحساب. تقدم Supabase التخزين وتسجيل الدخول، وتعرض Bunny الفيديو، وقد تُستخدم Resend لإرسال إشعارات تشغيلية لوليّ الأمر دون اسم الطفل أو تقدمه. قد تتلقى هذه الخدمات بيانات تقنية مثل عنوان الاتصال وقد تتم المعالجة خارج بلد الأسرة. لا نبيع بيانات الأطفال ولا نستخدمها للإعلانات الموجهة. يستطيع وليّ الأمر سحب موافقة أي ملف من لوحة كيدز فيتوقف وصوله للدروس، وطلب الاطلاع أو التصحيح أو الحذف عبر info@masaarat.ai. الحذف من النسخ الاحتياطية أو خدمات المزودين ليس فوريًا. نحتفظ بالبيانات طوال الحاجة للخدمة والحقوق المرتبطة بها؛ سياسة الاحتفاظ عند انتهاء اشتراك كيدز المدفوع معدة لتسعين يومًا مع إشعار مسبق، ولا يبدأ الحذف الآلي قبل تفعيل الإجراء والتحقق منه. وليّ الأمر مسؤول عن صحة إقراره وإدارة حساب أسرته، ومسارات مسؤولة عن حماية البيانات وتشغيل الخدمة والرد على الطلبات. الموافقة مستقلة عن التسويق واشتراكات الكبار. نعرض نسخة جديدة ونطلب موافقة جديدة عند تغيير جوهري.',
   'قرأت سياسة خصوصية الأطفال وأوافق على معالجة بيانات ملفات أطفالي لتقديم خدمة مسارات كيدز، وأقرّ أنني وليّ أمرهم.'),
  ('ar-MSA',
   'مسارات كيدز خدمة تعليمية للأطفال يديرها وليّ الأمر من حسابه ذي البريد المؤكد. يقر صاحب الحساب بصفته وليّ أمر قبل إنشاء ملفات الأطفال. نحفظ بلد إقامة وليّ الأمر ونسخة موافقته وتاريخها، واسم عرض مختصر لكل طفل ومستواه وتقدمه في الدروس. لا نطلب بريد الطفل أو هاتفه أو وثيقة هويته. نستخدم هذه البيانات لتقديم الدروس وحفظ التقدم وحماية الحساب. تقدم Supabase التخزين وتسجيل الدخول، وتعرض Bunny الفيديو، وقد تُستخدم Resend لإرسال إشعارات تشغيلية لوليّ الأمر دون اسم الطفل أو تقدمه. قد تتلقى هذه الخدمات بيانات تقنية مثل عنوان الاتصال وقد تتم المعالجة خارج بلد الأسرة. لا نبيع بيانات الأطفال ولا نستخدمها للإعلانات الموجهة. يستطيع وليّ الأمر سحب موافقة أي ملف من لوحة كيدز فيتوقف وصوله للدروس، وطلب الاطلاع أو التصحيح أو الحذف عبر info@masaarat.ai. الحذف من النسخ الاحتياطية أو خدمات المزودين ليس فوريًا. نحتفظ بالبيانات طوال الحاجة للخدمة والحقوق المرتبطة بها؛ سياسة الاحتفاظ عند انتهاء اشتراك كيدز المدفوع معدة لتسعين يومًا مع إشعار مسبق، ولا يبدأ الحذف الآلي قبل تفعيل الإجراء والتحقق منه. وليّ الأمر مسؤول عن صحة إقراره وإدارة حساب أسرته، ومسارات مسؤولة عن حماية البيانات وتشغيل الخدمة والرد على الطلبات. الموافقة مستقلة عن التسويق واشتراكات الكبار. نعرض نسخة جديدة ونطلب موافقة جديدة عند تغيير جوهري.',
   'قرأت سياسة خصوصية الأطفال وأوافق على معالجة بيانات ملفات أطفالي لتقديم خدمة مسارات كيدز، وأقرّ أنني وليّ أمرهم.'),
  ('ar-Gulf',
   'مسارات كيدز خدمة تعليمية للأطفال يديرها وليّ الأمر من حسابه ذي البريد المؤكد. يقر صاحب الحساب بصفته وليّ أمر قبل إنشاء ملفات الأطفال. نحفظ بلد إقامة وليّ الأمر ونسخة موافقته وتاريخها، واسم عرض مختصر لكل طفل ومستواه وتقدمه في الدروس. لا نطلب بريد الطفل أو هاتفه أو وثيقة هويته. نستخدم هذه البيانات لتقديم الدروس وحفظ التقدم وحماية الحساب. تقدم Supabase التخزين وتسجيل الدخول، وتعرض Bunny الفيديو، وقد تُستخدم Resend لإرسال إشعارات تشغيلية لوليّ الأمر دون اسم الطفل أو تقدمه. قد تتلقى هذه الخدمات بيانات تقنية مثل عنوان الاتصال وقد تتم المعالجة خارج بلد الأسرة. لا نبيع بيانات الأطفال ولا نستخدمها للإعلانات الموجهة. يستطيع وليّ الأمر سحب موافقة أي ملف من لوحة كيدز فيتوقف وصوله للدروس، وطلب الاطلاع أو التصحيح أو الحذف عبر info@masaarat.ai. الحذف من النسخ الاحتياطية أو خدمات المزودين ليس فوريًا. نحتفظ بالبيانات طوال الحاجة للخدمة والحقوق المرتبطة بها؛ سياسة الاحتفاظ عند انتهاء اشتراك كيدز المدفوع معدة لتسعين يومًا مع إشعار مسبق، ولا يبدأ الحذف الآلي قبل تفعيل الإجراء والتحقق منه. وليّ الأمر مسؤول عن صحة إقراره وإدارة حساب أسرته، ومسارات مسؤولة عن حماية البيانات وتشغيل الخدمة والرد على الطلبات. الموافقة مستقلة عن التسويق واشتراكات الكبار. نعرض نسخة جديدة ونطلب موافقة جديدة عند تغيير جوهري.',
   'قرأت سياسة خصوصية الأطفال وأوافق على معالجة بيانات ملفات أطفالي لتقديم خدمة مسارات كيدز، وأقرّ أنني وليّ أمرهم.'),
  ('en',
   'Masaarat Kids is an educational service managed by a parent through a confirmed-email account. The account holder declares that they are the parent or guardian before creating child profiles. We store the parent’s country, policy version and acceptance time, and each child’s short display name, level and lesson progress. We do not request the child’s email, phone or identity document. We use this data to provide lessons, save progress and protect the account. Supabase handles sign-in and storage, Bunny delivers videos, and Resend may send operational notices to the parent without a child’s name or progress. These providers may receive connection information such as IP address and may process data outside the family’s country. We do not sell children’s data or use it for targeted advertising. Parents can withdraw consent for any profile in Kids, stopping its lesson access, and request access, correction or erasure at info@masaarat.ai. Erasure from backups or providers is not immediate. We retain data while needed for the service and related rights; a 90-day retention policy after the last paid Kids plan expires is prepared with advance notice, and automatic deletion does not begin until the procedure is enabled and verified. Parents are responsible for their declaration and family account; Masaarat remains responsible for data protection, service operation and responding to requests. This consent is separate from marketing and adult plans. Material changes will have a new version and renewed consent.',
   'I have read the children’s privacy policy and consent to processing my children’s profile data to provide Masaarat Kids. I declare that I am their parent or guardian.')
)
INSERT INTO public.kids_consent_policies
  (country_code,version,locale,notice_text,consent_text,review_reference,enabled)
SELECT market.country_code,'kids-shared-2026-09-27-v1',
  notices.locale,notices.notice_text,notices.consent_text,
  'owner-shared-policy-2026-09-27',true
FROM public.kids_market_release market CROSS JOIN notices
ON CONFLICT (country_code,version,locale) DO NOTHING;

-- Activation is explicit, auditable and common to the current supported markets.
UPDATE public.kids_market_release SET accepts_child_data=true,
  reviewed_at=now(), review_reference='owner-shared-policy-2026-09-27';
UPDATE public.kids_release_control SET accepts_child_data=true,
  lesson_access_enabled=true WHERE singleton;
