-- Auto-generated by scripts/lessons-renumber.ts
-- Renames lesson_id values across all learner-data tables.
BEGIN;
-- Table: lesson_progress
UPDATE public.lesson_progress SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.lesson_progress SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.lesson_progress SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.lesson_progress SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.lesson_progress SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.lesson_progress SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.lesson_progress SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.lesson_progress SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.lesson_progress SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.lesson_progress SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.lesson_progress SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: lesson_feedback
UPDATE public.lesson_feedback SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.lesson_feedback SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.lesson_feedback SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.lesson_feedback SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.lesson_feedback SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.lesson_feedback SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.lesson_feedback SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.lesson_feedback SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.lesson_feedback SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.lesson_feedback SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.lesson_feedback SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: lesson_notes
UPDATE public.lesson_notes SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.lesson_notes SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.lesson_notes SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.lesson_notes SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.lesson_notes SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.lesson_notes SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.lesson_notes SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.lesson_notes SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.lesson_notes SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.lesson_notes SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.lesson_notes SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: lesson_quiz_attempts
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.lesson_quiz_attempts SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: lesson_review_schedule
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.lesson_review_schedule SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: user_lesson_status
UPDATE public.user_lesson_status SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.user_lesson_status SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.user_lesson_status SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.user_lesson_status SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.user_lesson_status SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.user_lesson_status SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.user_lesson_status SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.user_lesson_status SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.user_lesson_status SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.user_lesson_status SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.user_lesson_status SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: user_mission_state
UPDATE public.user_mission_state SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.user_mission_state SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.user_mission_state SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.user_mission_state SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.user_mission_state SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.user_mission_state SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.user_mission_state SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.user_mission_state SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.user_mission_state SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.user_mission_state SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.user_mission_state SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: mission_submissions
UPDATE public.mission_submissions SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.mission_submissions SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.mission_submissions SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.mission_submissions SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.mission_submissions SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.mission_submissions SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.mission_submissions SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.mission_submissions SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.mission_submissions SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.mission_submissions SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.mission_submissions SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
-- Table: learner_events
UPDATE public.learner_events SET lesson_id = 'business-m1-l2-reactive-vs-proactive' WHERE lesson_id = 'business-m2-l1-reactive-vs-proactive';
UPDATE public.learner_events SET lesson_id = 'business-m2-l1-customer-lifecycle' WHERE lesson_id = 'business-m3-l1-customer-lifecycle';
UPDATE public.learner_events SET lesson_id = 'business-m2-l2-retention-flow' WHERE lesson_id = 'business-m3-l2-retention-flow';
UPDATE public.learner_events SET lesson_id = 'business-m2-l3-readiness-signals' WHERE lesson_id = 'business-m5-l1-readiness-signals';
UPDATE public.learner_events SET lesson_id = 'business-m3-l1-delegate-or-automate' WHERE lesson_id = 'business-m4-l2-delegate-or-automate';
UPDATE public.learner_events SET lesson_id = 'business-m3-l2-strategic-operational-admin' WHERE lesson_id = 'business-m4-l1-strategic-operational-admin';
UPDATE public.learner_events SET lesson_id = 'business-m3-l3-system-then-people' WHERE lesson_id = 'business-m5-l2-system-then-people';
UPDATE public.learner_events SET lesson_id = 'business-m4-l1-premature-scaling' WHERE lesson_id = 'business-m6-l2-premature-scaling';
UPDATE public.learner_events SET lesson_id = 'business-m4-l2-reactive-relapse' WHERE lesson_id = 'business-m6-l1-reactive-relapse';
UPDATE public.learner_events SET lesson_id = 'business-m4-l3-weekly-rhythm' WHERE lesson_id = 'business-m2-l2-weekly-rhythm';
UPDATE public.learner_events SET lesson_id = 'business-m4-l4-full-ecosystem' WHERE lesson_id = 'business-m7-l1-full-ecosystem';
COMMIT;
