import { describe, expect, it } from "vitest";
import { buildLessonRenumberMigration } from "../../../scripts/lessons-renumber-sql";

const TABLES = [
  "lesson_progress",
  "lesson_feedback",
  "lesson_notes",
  "lesson_quiz_attempts",
  "lesson_review_schedule",
  "user_lesson_status",
  "user_mission_state",
  "mission_submissions",
  "learner_events",
];

// Recognize the supported PostgreSQL E-string syntax independently of the builder.
// An unmatched quote, escape or extra statement makes the remaining SQL fail below.
function readUpdates(sql: string) {
  const literal = String.raw`E'(?:[^'\\]|''|\\\\)*'`;
  const update = new RegExp(
    'UPDATE public."([a-z_]+)" SET lesson_id = (' +
      literal +
      ") WHERE lesson_id = (" +
      literal +
      ");\n",
    "g",
  );
  const decode = (value: string) =>
    value.slice(2, -1).replace(/''|\\\\/g, (pair) => (pair === "''" ? "'" : "\\"));
  const updates = [...sql.matchAll(update)].map((match) => ({
    table: match[1],
    newId: decode(match[2]),
    oldId: decode(match[3]),
  }));
  const remainder = sql.replace(update, "").replace(/^-- Table: [a-z_]+\n/gm, "");
  expect(remainder).toBe(
    "-- Auto-generated by scripts/lessons-renumber.ts\n" +
      "-- Renames lesson_id values across the configured learner-data tables.\n" +
      "BEGIN;\nCOMMIT;\n",
  );
  return updates;
}

describe("lesson renumber SQL generation", () => {
  it("updates only the nine configured tables with quoted table identifiers", () => {
    const mapping = { oldId: "intro-m1-l1-old", newId: "intro-m1-l2-new" };
    const updates = readUpdates(buildLessonRenumberMigration([mapping]));
    expect(updates).toEqual(TABLES.map((table) => ({ table, ...mapping })));
  });

  it("keeps apostrophes, backslashes, newlines and SQL text inside each ID literal", () => {
    const mapping = {
      oldId: "learner's\\n'; DROP TABLE public.lesson_notes; --\n",
      newId: "new\\\n'; COMMIT; UPDATE public.lesson_notes SET lesson_id = 'x'; --",
    };
    const updates = readUpdates(buildLessonRenumberMigration([mapping]));
    expect(updates).toEqual(TABLES.map((table) => ({ table, ...mapping })));
  });

  it("preserves Unicode and empty IDs without adding SQL statements", () => {
    const mapping = { oldId: "", newId: "مقدمة-درس-١" };
    const updates = readUpdates(buildLessonRenumberMigration([mapping]));
    expect(updates).toEqual(TABLES.map((table) => ({ table, ...mapping })));
  });

  it("preserves every mapping in table order", () => {
    const mappings = [
      { oldId: "intro-m1-l1-a", newId: "intro-m1-l2-a" },
      { oldId: "builder-m2-l1-b", newId: "builder-m2-l2-b" },
    ];
    const updates = readUpdates(buildLessonRenumberMigration(mappings));
    expect(updates).toEqual(
      TABLES.flatMap((table) => mappings.map((mapping) => ({ table, ...mapping }))),
    );
  });

  it("emits no update for an empty rename list", () => {
    expect(readUpdates(buildLessonRenumberMigration([]))).toEqual([]);
  });

  it.each(["oldId", "newId"] as const)("rejects NUL in %s", (key) => {
    const mapping = { oldId: "old", newId: "new", [key]: "invalid\0id" };
    expect(() => buildLessonRenumberMigration([mapping])).toThrow("NUL");
  });
});
